### ISSUE TITLE
unable to set any download location apart from drive root

### ISSUE THREAD

**Issue by Dasumianco81** [wabbajack-tools/wabbajack#1020]
**Describe the bug**
I am unable to set any download location eg. g:\downloads and can only set it to the root of the drive e.g. G:\

when trying to set to a new folder (Downloads) I get a warning to choose another location

**Additional context**
win10 2004 FO4

**Logs**
Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. Refere to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) page if you do not know how to post the stack trace in a code block.

**Comment by halgari** [comment]
this has been reworked and improved in recent builds
