### ISSUE TITLE
Make the Nexus Premium soft requirement more visible to users

### ISSUE THREAD

**Issue by LivelyDismay** [wabbajack-tools/wabbajack#1030]
**Is your feature request related to a problem? Please describe.**

Getting a lot of new users lately that aren't aware automated downloading comes courtesy of Nexus Premium.

**Describe the solution you'd like**

Make that information more visible, either on the website or on the UI itself. Or both.

**Describe alternatives you've considered**

I am not smart enough to come up with alternatives.

**Additional context**

**Comment by halgari** [comment]
Fixed in master
