### ISSUE TITLE
Feature to see how far into the modlist we are

### ISSUE THREAD

**Issue by neuroghast** [wabbajack-tools/wabbajack#1033]
**Is your feature request related to a problem? Please describe.**

Not exactly a problem, but for no-premium users would be handy to know how far into the modlist we are.

**Describe the solution you'd like**

Any kind of display showing how many mods have been downloaded and how many are left. It would be useful to have it shown all the time, since we change pages often.

**Describe alternatives you've considered**

Maybe a bar that would visually and/or % show how far into the modlist. Also, showing how many GB have been downloaded and how many are left. I think the number of mods itself is more relevant to know how much clicking you still have left, but files sizes could be useful too.

**Additional context**

Nothing else I recall by now.

**Comment by tr4wzified** [comment]
Has been added since, issue should be closed
