### ISSUE TITLE
Easy and simple way to chose a modlist based of defined mods.

### ISSUE THREAD

**Issue by Trollmen** [wabbajack-tools/wabbajack#1049]
**Is your feature request related to a problem? Please describe.**
Its really hard to pinpoint and find modlist that feature a list of certain mods before download and searching manually in mod manager / other program. 

**Describe the solution you'd like**
It would be great to include a search function in wabbajack, that would work like this:
User defines one or more mod names and writes it down in list form. 
Wabbajack uses a search function on modlist manifest and  proposes modlist based on a number of mods that fit user list.
It could display modlist name and a list of mods it positively recognised.

**Describe alternatives you've considered**
Expand archive search to look across all modlist, and search by list. Or search mods one by one and make an option to save results in some way. (Like checkbox/checklist).

**Comment by erri120** [comment]
Added global archive search to the website: 
https://www.wabbajack.org/#/modlists/search/all 
(https://github.com/wabbajack-tools/wabbajack-tools.github.io/commit/9c67e7f777d8327b2e85475e3175a0fc184d7987)

**Comment by tr4wzified** [comment]
Issue should be closed now
