### ISSUE TITLE
Wabbajack gets stuck while downloading mods manually

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#1055]
**Describe the bug**

A person in the Discord (technoblade#7774) is having issues manually downloading mods - after a few tries the page will pop to the 'Choose Download Type' page and freeze the entire application, from my understanding of it. Nothing is clickable anymore, the download does continue. Link to conversation: https://discord.com/channels/605449136870916175/666599178788536331/747899308023742614

**Additional Context**

Windows 10, version unknown

**Wabbajack Version**

2.2.1.5

**Logs**

Asked for, should arrive tomorrow

**Comment by KNGLogan** [comment]
i have also had this issue before
