### ISSUE TITLE
Plugins ESL-ified through Wrye Bash do not keep their ESL state after the compile.

### ISSUE THREAD

**Issue by SovnSkyrim** [wabbajack-tools/wabbajack#1056]
**Describe the bug**

I ESL-ify some plugins through Wrye Bash, when my user install the list, it has over 255 plugins because it doesn't keep the ESL tag during compile.
Before
http://prntscr.com/u5uod6
After 
https://prnt.sc/u5unrm

**Additional Context**

Windows 10 - Skyrim SE, Wrye Bash Version is 307.202002061758

**Wabbajack Version**

2.2.1.6

**Logs**

Log used to compile the list:
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/5126599/Wabbajack.current.log)

**Comment by halgari** [comment]
Haven't seen this since, so I'm closing for now, re-open if it happens again.
