### ISSUE TITLE
Error: Exiting due to no way to compile these files

### ISSUE THREAD

**Issue by Vladabdf** [wabbajack-tools/wabbajack#107]
Wabbajack hashed every file just fine, no errors. Upon opening it a second time and clicking "Begin" after installing new mods using MO2, it cycles through the MO2 folder, eventually giving the error, "Exiting due to no way to compile these files".

Running Windows 10, game is Fallout 4.

[Log file pastebin](https://pastebin.com/fVtXECjT)

I verified I have the latest version of Python installed, .NET runtimes up to date, etc.

**Comment by halgari** [comment]
It's a little out-of-date, but this video goes into the process of how Wabbajack works, and the core systems are the same : https://www.youtube.com/watch?v=5Fwr0Chtcuc

You need to copy the MO2 archive into the MO2 download folder, and then tell WJ where you got the archive by updating the .meta information on the file.
