### ISSUE TITLE
Program breaches it's license agreement.

### ISSUE THREAD

**Issue by GamerGoddessDin** [wabbajack-tools/wabbajack#1071]
**Describe the bug**

The license agreement does not allow for the prevention of the use of any modlists for any purpose other than having been sold. (Which itself is legally questionable based on the actual license, GPL3 doesn't allow for forcing users into a particular license for things created with the GPL3 license software.) The prevention of use of the program for modlists including mods which the program's creators dislike is a violation of the license agreement.

**Comment by LostDragonist** [comment]
>The prevention of use of the program for modlists including mods which the program's creators dislike is a violation of the license agreement.

Could you give an example of what you believe has been violated here?

**Comment by GamerGoddessDin** [comment]
A modlist which was distributed for free on ATF was prevented from functioning and those who used it prevented from using the program.

**Comment by LivelyDismay** [comment]
Good.

**Comment by LostDragonist** [comment]
Okay.  None of that is covered by any of the applicable licenses.  You and your kin are free to modify and redistribute WJ and any applicable GPLv3 code according to the licenses.  The operations of WJ and the respective WJ servers are not covered by licensing and the owners/operators of WJ and the respective WJ servers are free to do what they wish.

**Comment by tr4wzified** [comment]
Issue should be closed now
