### ISSUE TITLE
add the line `installed=true` to .meta files that get generated during installation.

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#1072]
**Is your feature request related to a problem? Please describe.**

When you install a list or want to build a list based on [SME](https://github.com/EzioTheDeadPoet/SME-FT-#smeft---skyrim-modding-essentials-fixes--tools) the mods in the side panel show as downloaded and not as installed which can be confusing and or annoying depending on who u ask. 

**Describe the solution you'd like**

If there was a way WJ could add the line `installed=true` to a mod after installation this could be solved.

**Describe alternatives you've considered**

An alternative I am considering right now is to upload my currently used .meta files to my GitHub page, but that mean one other thing to maintain in addition to the list itself which, if WJ could add this line to the metas would be completely unnecessary.

**Comment by erri120** [comment]
Simple change, just add it to https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/Downloaders/AbstractDownloadState.cs#L103

**Comment by EzioTheDeadPoet** [comment]
Will do, if I did it wrong or it could have bee written cleaner just correct me in my pull request.
