### ISSUE TITLE
Very Minor UI bug.

### ISSUE THREAD

**Issue by Eggypapa** [wabbajack-tools/wabbajack#1075]
**Describe the bug**

Hovering over the version number in the top right hand corner of the screen shows a blank context box, and appears to be a button that doesn't function.

I vaguely remember the button used to link to the most recent release on github, however if it ever did that it doesn't anymore.

Example image:
![image](https://user-images.githubusercontent.com/56150254/92391349-d7077a00-f15f-11ea-83af-5a00e09b8e1f.png)

Obviously this is very minor, but I imagine it's a very easy fix as well.

**Wabbajack Version**
v2.2.2.0

**Comment by tr4wzified** [comment]
Issue should be closed now
