### ISSUE TITLE
Request: Print Install and Download locations to log file

### ISSUE THREAD

**Issue by LivelyDismay** [wabbajack-tools/wabbajack#1091]
**Is your feature request related to a problem? Please describe.**

Not exactly, just a small support optimization. I'd like to get as much information as possible solely from the logs.

**Describe the solution you'd like**

If possible, I'd like for Wabbajack to print the Installation and Download Locations set by the user in the log. For example:

1.00 - Cleaning VFS, this may take a bit of time
1.00 - Starting Installer Task
1.00 - Installation has Started
1.00 - Installation Set to: "D:\New Modlist"
1.00 - Download Set to "D:\New Modlist\downloads"

**Describe alternatives you've considered**

Don't have any alternatives but I do wonder if it would invade people's privacy. For example, if they have it set to C:\Users\Their Name, then I'd know their name. Probably not a big deal, but...meh.

**Additional context**

I'm just trying to eliminate the need to ask for screenshots since a lot of people are bad at providing relevant screenshots.

**Comment by halgari** [comment]
in master
