### ISSUE TITLE
Crashes when trying to unpack an unsupported archive

### ISSUE THREAD

**Issue by Albeoris** [wabbajack-tools/wabbajack#1105]
**Describe the bug**
Trying to install this list: https://www.wabbajack.org/#/modlists/info?machineURL=fallout_4_enhanced_edition
Getting AccessViolationException at **Realistic bullets DLC Horizon patch-29596-v1.zip**
Repacking the archive helps to work around the issue.
Apparently, the provided 7z.dll does not support the specified archive format.

**Additional Context**
Windows 7 x64
Fallout 4

**Wabbajack Version**
2.3.0.0

**Logs**
```
var th = new Thread(() =>
            {
                try
                {
                    _archive = ArchiveFile.Open(_stream, _sig).Result;
                    ulong checkPos = 1024 * 32;
                    _archive._archive.Open(_archive._archiveStream, ref checkPos, null); // Access Violation
```

**Comment by EzioTheDeadPoet** [comment]
Windows 7 is not supported by Microsoft and Wabbajack for that reason anymore.
If you could run WJ previously try the previous Wabbajack version. If that doesn't help you will most likely need to upgrade to Windows 10 to use it.

**Comment by halgari** [comment]
Pretty sure this is now fixed
