### ISSUE TITLE
Bevilex download issue. 

### ISSUE THREAD

**Issue by Gaetys** [wabbajack-tools/wabbajack#1114]
Trying to download and install Bevilex for Oblivion through Wabbajack and each time it gets to a certain point and says 

Unable to download OR7.0.0.zip (Google drive downloader+State | 1INQXFEkvZHzM_UKtIMgTTIVeLqsvIYpt) 
Cannot Continue, was unable to download one or more archives
Encountered error, can't continue - Cannot continue, was unable to download one or more archives

Like I said above this is for Oblivion on a windows 10 computer. 

Wabbajack 2.2.2.0

**Comment by erri120** [comment]
Issues on this repository are for Wabbajack, the program, not for modlists. If you need help for a modlist go to the support channel on our discord https://www.discord.gg/wabbajack
