### ISSUE TITLE
Mod Organizer 2 losing settings/pathfinding since 2.3.0.1

### ISSUE THREAD

**Issue by Patchier** [wabbajack-tools/wabbajack#1121]
**Describe the bug**

After successful installation of a modlist, the Mod Organizer 2 instance that is installed will lose the ability to find the game on it's own. For Living Skyrim 2, it ALWAYS looks in C:, causing you to have to choose the actual path yourself, whereas Stardew Valley will do a first-time setup for Portable Mode, forcing you to choose Stardew Valley from the list yourself. Issue confirmed to start with 2.3.0.1.

**Additional Context**

Windows 10 - Both Stardew Valley and Skyrim Special Edition

**Wabbajack Version**

2.3.0.1/2.3.0.2

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/5344889/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
is this still happening ?
