### ISSUE TITLE
Fallout 4 VR Failing 

### ISSUE THREAD

**Issue by GingasVRFO** [wabbajack-tools/wabbajack#1122]
[**Failing to complie a new version of a list for Fallout 4 VR, Wabbajack cannot find DLC files on new version**

**When trying to complie a new version of my list, Wabbajack is failing to find all the DLC files, worked fine on version 2.2.2.0 of Wabbajack**

**2.3.02**

**[Wabbajack.current (1).log](https://github.com/wabbajack-tools/wabbajack/files/5351619/Wabbajack.current.1.log)**

**Comment by LostDragonist** [comment]
From the 2.3.0.0 change log: 
> * Profiles can now contain an (optional) file `compiler_settings.json` that includes options for other games to be used during install.
This is now the only way to include extra games in the install process, implicit inclusion has been removed. 

Do you have this file in your MO profile?  I've attached an example that might work...?  IDK.

[compiler_settings.zip](https://github.com/wabbajack-tools/wabbajack/files/5355805/compiler_settings.zip)

**Comment by tr4wzified** [comment]
Working again, should be closed
