### ISSUE TITLE
MO2 does not have the correct path to SKSE

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#1134]
**Describe the bug**

After finishing installation, opening MO2 and attempting to launch SKSE results in a "file not found" error. This is caused by MO2 having the "Start In" path be incorrect. The Start In path should either be blank or match the path the user has Skyrim SE installed to.

**Additional Context**

Windows 10, Skyrim Special Edition, Living Skyrim modlist v2.5.1.1 compiled 10/21/2020

**Wabbajack Version**

2.3.0.4

**Logs**

No log, but a screenshot of the error in question:

![](https://cdn.discordapp.com/attachments/623292774229213185/768596888207097916/unknown.png)

And a screenshot of the same screen from the copy of MO2 used to compile the list: 

![](https://cdn.discordapp.com/attachments/623292774229213185/768604935494696970/unknown.png)

**Comment by halgari** [comment]
@ForgottenGlory can you attach the original ModOrganizer.ini file? That will help with debugging this

**Comment by ForgottenGlory** [comment]
Had to put it in a ZIP so I could upload it, thanks halgari!

[ModOrganizer.zip](https://github.com/wabbajack-tools/wabbajack/files/5419056/ModOrganizer.zip)

**Comment by halgari** [comment]
fixed in master
