### ISSUE TITLE
Wabbajack deleting downloads when overwriting

### ISSUE THREAD

**Issue by LostDragonist** [wabbajack-tools/wabbajack#1137]
Reported by CrunchityFrog#7189 on discord.

[Wabbajack_2020-10-22_15_45_39.log](https://github.com/wabbajack-tools/wabbajack/files/5431991/Wabbajack_2020-10-22_15_45_39.log)

User chose to overwrite Living Skyrim 2.  WJ proceeded to delete everything in the downloads folder.  If I had to guess, WJ is doing a case-sensitive compare on the downloads folder path as the WJ setting is "downloads" and the Windows reported folder is "Downloads".

**Comment by LostDragonist** [comment]
I'm unable to reproduce it myself as the validation on the mod list install settings page sees "D:\Elysium\downloads" as being different than "D:\Elysium\DOWNLOADS" which...  Well, it means there is indeed some case-sensitive compares happening but the user also shouldn't have been able to progress that far.... /shrug.

**Comment by halgari** [comment]
Pretty sure we fixed this in master with some changes to AbsolutePath
