### ISSUE TITLE
Wabbajack does not configure MO2 to use the chosen download folder

### ISSUE THREAD

**Issue by tstavrianos** [wabbajack-tools/wabbajack#114]
**Describe the bug**
When installing a modlist, if you choose a download folder that is not the default one (ie: mo2/downloads), then WJ will place all the embedded .meta files in the default download folder, ignoring the folder that chosen. Also WJ does not update mo2 to point to the actual downloads.
As a result mo2 will delete all meta that were added to the mo2/downloads folder, because it can't find the corresponding archives.

**Additional context**
N/A

**Logs**
N/A

**Solution**

**Comment by halgari** [comment]
I think this was a transient problem in one of our beta builds. Appears to be fixed in master
