### ISSUE TITLE
Ignore build failing if the broken mods are already downloaded

### ISSUE THREAD

**Issue by Deliphin** [wabbajack-tools/wabbajack#1145]
**Is your feature request related to a problem? Please describe.**

When builds fail while installing a pack, most of the downloads may finish, however there seems to always be at least one mod that will stop downloading at some point. It's not even the mod that broke the pack, the mod that updated/hidden/whatever, is already downloaded.

**Describe the solution you'd like**

When a build fails, wabbajack should, instead of just giving up and force me to wait until the update is taken care of, should detect if the mod(s) that updated/hidden are already downloaded. Then, it should do one of two things:  
1. If all broken mods are already downloaded, just keep going according to the downloaded manifest.  
2. If one or more is not downloaded, then still continue and download the rest, but at the end give an error to the user stating that some failed. This means the rest of the pack is already downloaded, so when the modpack is repaired, the user's wabbajack only has to download the remaining mods.

Also, wabbajack files should not be updated automatically. There should be the main button, which will update the wabbajack file then install the pack like normal, and a secondary button, which installs the pack based on the current wabbajack file. I believe this is why I couldn't use the Install from Disk method.

**Describe alternatives you've considered**

I currently see no other possible alternative solution, and see my proposed solution as reasonable. The only other solution I can think of that you could do, which is store mods off of nexus, is something that would really piss off a lot of people and I fully understand why you don't do it.

**Additional context**

I tried using Install From Disk and using my wabbajack file, however, even though the mod that was updated was downloaded and hashed already, it wanted to download it again, for the update I assume.

I know this will result in modpacks that are not up to date, but that's inevitable. Personally, I probably will never update a modpack after starting playing it, for fear of a mod update or addition unknowingly breaking my save.

**Comment by EzioTheDeadPoet** [comment]
1. WJ already does that.
2. same as 2.

We already store backups of mods that are with their permission rules set to allow to be hosted somewhere else and WJ auto detects issues and redirects to the backup. 

But if a mod without these permissions goes down we can't have another solution.

**Comment by EzioTheDeadPoet** [comment]
the installers are put into a locked status and are unable to download when in that state, since sadly a lot of people ignored the fact that it said the list is currently broken and still tried to install them and then complained why it isn't working which is why the decision was made to not allow the download of broken modlist files, since it buried actual support questions for the list pretty fast.

**Comment by Deliphin** [comment]
Ah, I see. I guess that makes sense why you don't do it.
