### ISSUE TITLE
Manifest search/filter not working

### ISSUE THREAD

**Issue by CrazieIvan** [wabbajack-tools/wabbajack#1164]
**Describe the bug**
Typing a string in the manifest search box often returns no results, even though there are multiple entries that contain the string.

**Additional Context**
Win 10 x64, SSE

**Wabbajack Version**
2.3.2.0

Some screenshots.  
1st one shows that typing "patch" in the search box returns nothing.  
https://imgur.com/43xs5KR
2nd one shows that there are multiple entries that contain the word 'patch' in the name.  
https://imgur.com/Uwooqhv
3rd screen shows the results in the web archive list, which returns a bunch of results. 
https://imgur.com/rHNJsmr

**Comment by LostDragonist** [comment]
If you try "Patch" instead of "patch" do the patches show up then?

**Comment by erri120** [comment]
Should prob just remove the internal manifest viewer at this point. The website has way more manifest features, actually works and is not sluggish as hell.

**Comment by CrazieIvan** [comment]
> 
> 
> If you try "Patch" instead of "patch" do the patches show up then?

So if I capitalize it does find the entries that start with "Patch", but it still doesn't search inside the names, because there are many entries that contain "patch" somewhere other than the beginning that don't get found.

**Comment by EzioTheDeadPoet** [comment]
the internal manifest viewer is still useful for unofficial lists. 🤔

**Comment by erri120** [comment]
> 
> 
> the internal manifest viewer is still useful for unofficial lists. 🤔

you can also do that on the website now

**Comment by EzioTheDeadPoet** [comment]
but only for the ones in unlisted healing right ?

**Comment by erri120** [comment]
> 
> 
> but only for the ones in unlisted healing right ?

https://www.wabbajack.org/#/modlists/manifest you can upload any manifest here

**Comment by EzioTheDeadPoet** [comment]
oh nice then it really isn't needed anymore.

**Comment by erri120** [comment]
Removed with #1173
