### ISSUE TITLE
Couldn't locate skyrim legendary edition

### ISSUE THREAD

**Issue by ghost** [wabbajack-tools/wabbajack#1166]
**Describe the bug**
When I try to install Ultimate Skyrim error this error appears. I have a clean version of the game installed (I ran it once) and have tried reinstalling wabbajack and editing registers.
**Additional Context**
Win 8.1 x64
**Wabbajack Version**
2.3.2.0

**Comment by LostDragonist** [comment]
Which game do you have installed, Skyrim or Skyrim Special Edition?
Do you have the Steam version or the GOG version?

**Comment by JDJDJDJDD** [comment]
I have the steam version, legendary edition

**Comment by LostDragonist** [comment]
Legendary edition wasn't one of the choices but I'll assume you meant "Skyrim".  

Can you upload the WJ log?  It's in the logs directory, named wabbajack.current.log.

Also, can you upload appmanifest_72850.acf?  You can find this in the steamapps folder where the game is installed.  (That is, if the game is installed in "C:\Games\Steam\steamapps\common\Skyrim" then the file would be "C:\Games\Steam\steamapps\appmanifest_72850.acf".)

**Comment by EzioTheDeadPoet** [comment]
My guess is it is related to you running Win 8.1 since WJ is designed with Win 10 in mind and the only Official supported OS so it very well could be that Win 8.1 is missing a feature/dependency only found in Win 10. But try what LostDragonist just mentioned.

**Comment by JDJDJDJDD** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/5487934/Wabbajack.current.log)

**Comment by JDJDJDJDD** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/5487955/Wabbajack.current.log)

**Comment by LostDragonist** [comment]
Given the path from your first log, `D:\Mr DJ\The Elder Scrolls V Skyrim Legendary Edition\`, and the fact that you're trying to hide that fact, I'm going to assume you're a pirate.  WJ doesn't support pirated games.

**Comment by LostDragonist** [comment]
[Wabbajack.current (16).log](https://github.com/wabbajack-tools/wabbajack/files/5487962/Wabbajack.current.16.log)
 Original log posted

**Comment by pedropinto0** [comment]
what a f@gs
