### ISSUE TITLE
Request: Download Times

### ISSUE THREAD

**Issue by NettlesFYS** [wabbajack-tools/wabbajack#1169]
I live in a country where we're still heavily metered re: downloads and when it can be done, so would it be possible to add download times to the settings in Wabbajack? For instance: download between midnight and 6AM.

I've tried scheduling this with task manager but I only succeeded in making a hash of it -- even when the program starts up, it doesn't automatically kick in the correct modlist that you were busy with, it waits on you to select a modlist to work on.

Thanks!

**Comment by halgari** [comment]
Could be done after we implement #681
