### ISSUE TITLE
Add update methods so the end user does not have to reinstall the whole thing

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#117]

**Comment by erri120** [comment]
For gathering ideas and stuff:
The idea is that the end user does not have to reinstall the whole modlist when the modlist author changes something.
When compiling we currently let the modlist author point to their MO2 profile and maybe we load some cache if this was already done. Updating would mean having the current MO2 profile and the existing `.modlist_vx` file.
The first idea I had would be to semi-compile the current MO2 profile to get all `Directives` and compare that `List<Directive>` with the List inside the modlist file.
I guess for a first pass you could just compare `List<Archive> Archives` but that would also mean we'd have to recompile the MO2 profile...

**Comment by halgari** [comment]
Done in master, we now only install the files required based on diffing the contents of the install to directory and the modlist.
