### ISSUE TITLE
Modlist File Extension

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#119]
I think it would be good to find a file extension that we like and want to keep for the long term.  If it's stable, we can then take advantage of registering the file extension into the system to open WJ on double click, and other features like that.  This would only work with a stable file extension that doesn't change `_v2` `_v3`.

Since we're still in flux on how we want modlists to look, and where their versioning info goes (#112), I still feel like we have time to lock this in before it causes too much disruption.

As @erri120 suggested, maybe 
`.wabbajack`
`.wj`
`.wjmodlist`
`.wjlist`

**Comment by halgari** [comment]
.wabbajack is fine with me

**Comment by erri120** [comment]
+ extension registry edits to allow `.wabbajack` files being opened by WJ
