### ISSUE TITLE
Different behavior between utility and NSFW lists

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#1196]
**Describe the bug**

Maybe not necessarily a bug, but when 'Show Utility Lists' is checked ONLY utility lists will show up (SMEFT). However, when the 'Show NSFW Lists' checkbox is checked, regular lists wlil show up plus the NSFW ones.

**Additional Context**
-

**Wabbajack Version**
2.3.4.1

**Logs**
-

**Comment by EzioTheDeadPoet** [comment]
I would consider this a good distinction, since utility lists aren't intended to be "played" at least not all of them. So listing them separately makes sense in my eyes.
