### ISSUE TITLE
Request Game Support for "Kingdom Come: Deliverance"

### ISSUE THREAD

**Issue by Silencer711** [wabbajack-tools/wabbajack#1198]
// Feature request related to a problem.

After attempting to create a Wabbajack modlist from scratch, an error is given: "Steam Game "Kingdom Come: Deliverance" (379430) is not supported, skipping"

// Describe the solution you'd like.

Respectfully Requesting official Wabbajack Game Support for "Kingdom Come: Deliverance".

// Describe alternatives you've considered.

Nothing else considered.

// Additional context.

Per your request on Discord, I am submitting this issue ticket for Official Implementation of Game Support for: "Kingdom Come: Deliverance"

Thanks a bunch for everything you guys have done :)

- Chris (Silencer711)

**Comment by halgari** [comment]
@Silencer711 can you send me (attach it here) the ModOrganizer.ini file you're using? There's some config info in that file that will help me implement this, thanks

**Comment by Silencer711** [comment]
Here it is (just change the extension .txt, to ".ini".)
[ModOrganizer.txt](https://github.com/wabbajack-tools/wabbajack/files/5591651/ModOrganizer.txt)

Thanks, Halgari!

**Comment by halgari** [comment]
@Silencer711 added support for this in the release today, give it a try again.
