### ISSUE TITLE
Usage of spluff or something similar to condense installs down in size

### ISSUE THREAD

**Issue by ixanza** [wabbajack-tools/wabbajack#1219]
https://forum.step-project.com/topic/11199-spluff/

Had a discussion on maybe having an option for wabbajack to copy only the winning override and then delete all the overwritten files as this can save a significant amount of space by deleting redundant overwritten files on installation. Maybe an option users can tick that says it can reduce file size footprint at the cost of not being able to modify the list without majorly screwing something up

**Comment by erri120** [comment]
That repository doesn't exist anymore

**Comment by tr4wzified** [comment]
You mean the link is dead? Works fine for me

**Comment by ixanza** [comment]
> That repository doesn't exist anymore

The actual file is in the misc file of relinker

https://www.nexusmods.com/skyrim/mods/77959/?tab=files
