### ISSUE TITLE
Give authors the option to remove the clients's default modlist title

### ISSUE THREAD

**Issue by PierreDespereaux** [wabbajack-tools/wabbajack#1221]
**Is your feature request related to a problem? Please describe.**

Wabbajack gives each modlist an overlayed title over the splash image. This is nice for lists that don't have custom splashes, but become redundant for lists that do.

![image](https://user-images.githubusercontent.com/60482452/102106358-780c6d80-3dfe-11eb-8b1c-4ccf7577b347.png)

**Describe the solution you'd like**

A new option to configure in modlists,json. Perhaps it could also remove the title on the website, however that is a lot less intrusive.

![image](https://user-images.githubusercontent.com/60482452/102106514-ac802980-3dfe-11eb-8a2d-d1342c403ddb.png)

![image](https://user-images.githubusercontent.com/60482452/102106833-0da7fd00-3dff-11eb-9b19-839691fde907.png)

**Comment by EzioTheDeadPoet** [comment]
Yeah didn't think of it but it would be very nice.

**Comment by EzioTheDeadPoet** [comment]
is implemented in the latest versions
