### ISSUE TITLE
"wizard" progress for installer for idiots like me

### ISSUE THREAD

**Issue by isaacimholt** [wabbajack-tools/wabbajack#123]
When I open the current build of Wabbajack (2019-10-27) I get to a screen with 4 sections: 
![image](https://user-images.githubusercontent.com/12482837/67636539-f6900e00-f8d1-11e9-9276-ff272a4f3cfd.png)
Please don't do this. There are too many user actions on the screen. I am an idiot, and I need a single clearly marked action button per screen (plus a cancel). It should progress screen by screen i.e. Select a mod pack -> select an install location -> installation screen with slideshow. I don't want to see anything else. I want to see a single progress bar, I want to see a cancel button, and all the details I want them to be hidden on some "advanced" page, maybe a tab at the top, where all the console logs and individual download progress bars are. To be clear, I am not at all suggesting that any functionality be removed, just that the user experience is more "guided". I opened up the program and audibly said "what the fuck..."

**Comment by halgari** [comment]
Thanks for the feedback, we'll consider it when we have time.
