### ISSUE TITLE
System.OutOfMemoryException when installing Serenity

### ISSUE THREAD

**Issue by stefan-agache** [wabbajack-tools/wabbajack#1235]
I'm using version 2.3.6.0, the installation fails with an out of memory exception when I'm trying to install serenity for Skyrim SE. Looking at the task manager, the RAM is nowhere near being full. Maybe there's an infinite loop somewhere, I'm not sure. I have a Ryzen 3600 and I'm using Win10 Enterprise version number 2004. I'm attaching the log file.

[Wabbajack 2020-12-31 13_46_10.log](https://github.com/wabbajack-tools/wabbajack/files/5757178/Wabbajack.2020-12-31.13_46_10.log)

**Comment by Unnoen** [comment]
It could be pagefile related, please make sure your pagefile is manually set to a size of 12000MB or more (We recommend at least 20000MB for larger lists).

**Comment by EzioTheDeadPoet** [comment]
> **Page files and memory crashes**
> Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.
> 
> A pagefile is a file on your disk Windows will use when there is not enough RAM available.
> 
> **Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.**
> 
> If you've never touched the pagefile, try performing the following steps:
> 1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
> 2. Under the Performance section, press 'Settings'
> 3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
> 4. Disable 'Automatically manage paging file size for all drives'
> 5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
> Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

this is from the Disorcd it is written for crashes during gameplay, but it applies for the installation as well, also make sure that your main windows drive has enough free space for the page file and the TEMP files that come up during the installation. 
If nothing of that helps try reducing the `Disk Threads` in the Wabbajack settings.

**Comment by stefan-agache** [comment]
Setting the Virtual Memory to System managed on all drives fixed the issue. Thanks for the fast responses. 
This issue can be closed now.
