### ISSUE TITLE
Better tools to determine files in .wabbajacks

### ISSUE THREAD

**Issue by NotTotal** [wabbajack-tools/wabbajack#1264]
Currently the only ways to figure out what ends up in a .wabbajack that we didn't intentionally flag to do so is to decipher it from a log or to open up the file in 7zip and try to figure it out from there. Some functionality to properly determine the files that WJ decides to inline/patch would be greatly appreciated to help control large wj file sizes.

**Comment by halgari** [comment]
The CLI command `inlined-file-report` should do the trick. 

```
wabbajack-cli inlined-file-report -i c:\Wabbajack\2.4.1.0\downloaded_mod_lists\tvo.wabbajack > c:\tmp\out.txt

```

Creates this report in `c:\tmp\out.txt` 
[out.txt](https://github.com/wabbajack-tools/wabbajack/files/5817618/out.txt)
