### ISSUE TITLE
METAS EVERYWHERE

### ISSUE THREAD

**Issue by cacophony-wj** [wabbajack-tools/wabbajack#1275]
**Describe the bug**

Wabbajack, during the installation of a Dragon Age: Origins modlist, creates META files for every file in the game directory. This results in over 17,000 duplicated files.

**Additional Context**

Windows 10, Dragon Age Origins

**Wabbajack Version**

2.4.1.1

**Logs**

Log attached.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/5857441/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
wasn't this fixed with the latest release ?

**Comment by halgari** [comment]
Fixed in 2.4.2.0
