### ISSUE TITLE
Arrow button disabled with no error or indication on what's going on

### ISSUE THREAD

**Issue by mihaifm** [wabbajack-tools/wabbajack#1293]
![image](https://user-images.githubusercontent.com/981184/106640161-60e03580-658e-11eb-8856-f9db7d9ac5bc.png)

Hi

I'm new to Wabbajack, I'm trying to build a modlist, but for some reason the arrow button remains disabled no matter what I do. I am basically stuck at the above screen.

I'm probably doing something wrong, but regardless of what's happening here I think an error message would be nice.

**Comment by LostDragonist** [comment]
In this case, you're missing a version (0.0.1, 1.0, etc.).  I think all the other info on the left is optional but you always need a version.

**Comment by mihaifm** [comment]
Ah, life saver, thanks. I had entered 1 but it seems like it needs 1.0

**Comment by EzioTheDeadPoet** [comment]
guess this can be closed :thinking:

**Comment by EzioTheDeadPoet** [comment]
UI could get an indicator similar to the indicator during Installing a list.
