### ISSUE TITLE
Vortex support re-institution

### ISSUE THREAD

**Issue by Patchier** [wabbajack-tools/wabbajack#1301]
**Is your feature request related to a problem? Please describe.**

It's not a problem, merely a request to bring back Vortex support. 

**Describe the solution you'd like**

Support for Vortex.

**Describe alternatives you've considered**

I've attempt to use MO2 specifically with Dragon Age 2, but the Origin backend DRM makes the VFS fail, thus rendering the only usable Mod Manager to be Vortex.

**Additional context**

I appreciate that this was discontinued a while ago, and I'm probably the only person who cares at the moment. Thank you for your time in reading this.

**Comment by EzioTheDeadPoet** [comment]
Won't happen as mentioned in #1389.
