### ISSUE TITLE
Optional "delete unused downloads" button

### ISSUE THREAD

**Issue by TateTaylorUSA** [wabbajack-tools/wabbajack#1328]
**Is your feature request related to a problem? Please describe.**

When switching from individual Project Clarity modules to Project Clarity AIO I noticed that a lot of users were running out of space on their drives. This is because they hadn't been deleting unused downloads that had been removed in previous updates.

**Describe the solution you'd like**

After Wabbajack installs a modlist it will prompt the user, asking if you would like to delete download files that aren't being used in the modlist. This is best used for people not using a unified downloads folder or primarily uses one modlist and updates it often.

**Describe alternatives you've considered**

I'm not sure about any alternatives, but I'm open to hearing them.

**Additional context**

You don't wanna end up like this madlad

![image](https://user-images.githubusercontent.com/60482452/108742847-2e2eba80-7506-11eb-802a-59c72bd7d60a.png)

**Comment by EzioTheDeadPoet** [comment]
there is a CLI command for that, that people can use. I am thinking about creating a GUI for it, seperate from Wabbajack (since I would have to write it in Java), since this is something a lot of people are uncomfortable with .

In my internship work break rn, but since the network blocks discord and the building appears to be a fraday cage I can only adress this here. LOL

**Comment by PierreDespereaux** [comment]
It seems like this should be something that is prompted of the user. As you said, a very small number of users are going to use the CLI commands. A GUI separate from Wabbajack is better, but it runs into the issues of visibility.

**Comment by EzioTheDeadPoet** [comment]
I agree with the visibility argument. But I guess this would be part of the big UI rework, which is why a small CLI GUI could fill the spot for the time being.

**Comment by PierreDespereaux** [comment]
Ah I see where you are coming from.

**Comment by EzioTheDeadPoet** [comment]
![grafik](https://user-images.githubusercontent.com/52624146/109939565-7b164c00-7cd1-11eb-8802-c0e226cf9d34.png)

I have this so far. (currently it does nothing) how would you say it looks ? (besides the colors and stuff, just funtionality wise.)

And yes I am working on a few more functions as well.

Currently I am putting together all the UI windows.

**Comment by slayer621** [comment]
I want to document this here before I forget: 

If the functionality @PierreDespereaux is describing makes it into the main Wabbajack client, and assuming Wabbajack has expanded to act as sort of a launcher for mod lists as proposed elsewhere, I think the original idea could be expanded to account for multiple mod list installations even with a single mod download folder. As proposed, removing a mod that is no longer needed by Modlist A doesn't take into account if it's used by Modlist B (see https://discord.com/channels/605449136870916175/605449136883499140/817692604710912013). 

One clunky idea to get the ball rolling could possibly be done by Wabbajack maintaining a list of all mods needed for all installed modlists. When Modlist A removes a mod in an update, Wabbajack would first verify it's not needed by installed Modlists B and C before removing the mod's archive. This list could possibly be created and maintained from data pulled from the .wabbajack files themselves (and stored along with the client's data so as to allow users to delete old modlist Wabbajack files). Or possibly something as simple as creating a log during the modlist installation process consisting of mods installed and adding it to a centralized list.

Apologies if this doesn't make sense or isn't relavent, I'm still learning.

**Comment by EzioTheDeadPoet** [comment]
[Wabbajack Scrolls: Easy Access to The Wabbajack-CLI](https://github.com/EzioTheDeadPoet/Wabbajack-Scrolls/releases/tag/1.0)
