### ISSUE TITLE
Ability to "WABBAJACK_ALWAYS_DISABLE" separators in Mod Organizer 2

### ISSUE THREAD

**Issue by foreverphoenix** [wabbajack-tools/wabbajack#1336]
So one thing that's always bothered me about Wabbajack is that there is no way to exclude specific separators. I typically have a few dozen mods installed in addition to the setup (for testing purposes) and typically sort them below extra separators. For TPF I now also have sections for "Addons" which are basically extensions for manual guide users.

But the separators for both of these additional sections will also appear in the WJ setup and likely confuse users: "Why are there a dozen weirdly named additional separators at the bottom of my mod order? Should there be more mods that weren't installed properly? WHAT DID YOU DO WITH ALL THOSE EXTRA MODS, PHOENIX?!"

The only alternative I see for myself is keeping separate MO2 instances (one for actually working on the setup, one for WJ compiling) but the amount of extra work and disc space required is pretty disconcerting.

If any solution to this could be found, I'd be very happy. ❤️

**Comment by EzioTheDeadPoet** [comment]
Have you already tried to tag the notes of the separator with `WABBAJACK_ALWAYS_DISABLE` ?
I think Pierre or FG did that before, can't recall if it worked.

**Comment by foreverphoenix** [comment]
I'm pretty sure I asked about this a long time ago and was told it wasn't implemented. I haven't kept up with the changelogs though to be fair.

**Comment by EzioTheDeadPoet** [comment]
Did you try it ? I haven't gotten around to try my theory yet.

**Comment by PierreDespereaux** [comment]
I am guarantee it works like Luca said.

**Comment by foreverphoenix** [comment]
It works!
