### ISSUE TITLE
[Enhancement] Replace README button on installation failiure screen with button to logs folder

### ISSUE THREAD

**Issue by phinocio** [wabbajack-tools/wabbajack#1337]
**Is your feature request related to a problem? Please describe.**

When a list fails to install and someone is asked to send their log, it's slightly tedious/annoying to manually go to the log folder.

**Describe the solution you'd like**

When the install failes, instead of the readme button on 
![this page](https://cdn.discordapp.com/attachments/783306335675875329/814362124306350120/unknown.png)

 have it be a button to open the logs folder.

**Comment by halgari** [comment]
Added in the master branch, will be in the next release
