### ISSUE TITLE
Compression.BSA Crossplatform support

### ISSUE THREAD

**Issue by monyarm** [wabbajack-tools/wabbajack#1338]
**Is your feature request related to a problem? Please describe.**

A number of apps (mainly synthesis and mutagen) make use of Compression.BSA. Compression.BSA being the only thing keeping them from running on Linux/OSX. Due to it's use of Alphaleonis.Win32.Filesystem.File

**Describe the solution you'd like**

using conditional compilation, or runtime conditions, have Alphaleonis.Win32.Filesystem.File only used under windows, with the native filesystem functions being used under all other OS.

**Additional context**

**Comment by erri120** [comment]
#1240

**Comment by halgari** [comment]
None of the Bethesda games WJ was written to support run natively on Linux, opening up support for other OSes will just introduce a lot of headaches with no payoff.
