### ISSUE TITLE
Mod order of a mod is reset when a single capital letter is changed to lower case

### ISSUE THREAD

**Issue by foreverphoenix** [wabbajack-tools/wabbajack#1357]
This is a weird one.

I had two mods in my mod order where I fatfingered the names. However, upon renaming "WInterhold" to "Winterhold", literally only changing the uppercase I to a lowercase i, users now have the mod unchecked and at the bottom of their load order. With the uppercase letter.

The workaround for users was to delete the two mods which I renamed and overwrite the WJ installation. I tried to delete and reinstall the mod on my end, then recompiling but the issue still happens for users since _they_ still have the uppercase letter.

This issue will persist for every single user until they rename and move the mods manually, or delete and overwrite with WJ after they were instructed to do so on Discord.

Needless to say, I'd be thrilled if this was something that could be handled by Wabbajack. =)

**Comment by LostDragonist** [comment]
This specific behavior is fixed with MO 2.4.0.

**Comment by foreverphoenix** [comment]
Ohh excellent. Thanks! Wanted to update TPF to 2.4.0 today anyway.
