### ISSUE TITLE
Download and Output folders no longer automatically update when changing modlist.txt

### ISSUE THREAD

**Issue by foreverphoenix** [wabbajack-tools/wabbajack#1358]
Apparently the Download and Output folder locations are no longer saved along with the modlist.txt when swapping between mod lists.

When I change from TPF to WTP to recompile that, it will automatically update the picture, description, version, etc. In the past it used to also update the Download and Output folders - it doesn't anymore. I'm not sure if this is a bug or a feature but it makes maintaining more than one WJ list quite annoying.

Would be lovely if something could be done about that. =)

**Comment by EzioTheDeadPoet** [comment]
Still works for me, did you move the whole modlist to a different folder, or renamed a parent folder  ?
Cause that will load the modlist.txt as if it is a new modlist.

**Comment by foreverphoenix** [comment]
I know that it happens when the folder structure changed because that's what happened to me recently with WTP. I changed everything back including Downloads and Output folder. Then I swapped to TPF (which I hadn't changed anything about) but lo and behold, while everything else was updated for TPF, the Downloads and Output folder were still the ones for WTP.

**Comment by EzioTheDeadPoet** [comment]
Just realized I was wrong I always have to move downloads folder(beacuse of that I have them all in the same parent folder named after the list they are for`c:\.Downloads\List_Name` cause that way I can switch teh DL folders faster) and just use the same output folder. :facepalm: But yeah it is either a bug or the lack of a neat feature.
