### ISSUE TITLE
Download Speed Throttle Suggestion/Enhancement

### ISSUE THREAD

**Issue by Corveauxx** [wabbajack-tools/wabbajack#1359]
Reopening this suggestion that was originally tabled in issue #57. The issue was closed under false pretenses. Concurrent downloads (download thread) limiting does nothing to change bandwidth usage or "download speed" of the program. This is inherently prohibitive for some users. Whether one would download 1 mod or 4 at the same time, one's bandwidth for the program will likely remain near maximum usage (assuming download servers are optimized and working at capacity). 

This is a particularly important potential feature for Wabbajack and its users for two pertinent reasons:

**A.** given the nature of the immense size of downloads and the autonomous properties of the installation process, many users are forced to check back on their download and installation periodically rather than actively. When factoring in ISP-controlled throttling for users that are constantly operating at their download maximum many users may awaken to an overnight or long period download that was halted just minutes or hours into the download process. This measures out to a grand amount of time wasting and energy waste from the device being left on with no persisting downloads. I admit that this may potentially be a bug in which downloads halt the moment internet connections are temporarily dropped, but I don't have the information to assert that claim.

**B.** Wabbajack downloads can potentially prohibit the use of other online services and programs on a user's PC or network if not throttled by the end-user correctly -- especially if they don't have great download on their plan to begin with. Part of operating on a network involves conscientious use of internet. While this can be controlled to a degree when streaming video or downloading a game on a client such a Steam, the same can not be said for Wabbajack which at times will host official mod lists downloading in the size of hundreds of GB of data for hours at a time. 

A possible inefficient workaround is **not** having Nexus premium due to download speed caps at 1 or 2 MB/s. This is counter-intuitive for the consumer.

In summation, the end user ought to be able to choose exactly how much (in KB or MB) they want to cap their upper download rate at. P2P file transfer, video streaming, and game download services typically offer this for their bandwidth heavy programs/players/etc.

**Comment by erri120** [comment]
Can be done with https://github.com/bezzad/Downloader

**Comment by Corveauxx** [comment]
I'm of the opinion that that is outside the scope of what the common end user would be familiar or willing to use. Wabbajack is not a high-tech program and, in some ways, is targeted towards individuals who want to take the complication out of modding.

**Comment by Corveauxx** [comment]
Ignore my deleted post, I didn't realize that was a framework integration

**Comment by researched** [comment]
See https://github.com/wabbajack-tools/wabbajack/issues/1419 for additional problems with WJ downloads, e.g. it uses all bandwidth even when no files are downloaded at the time.

**Comment by GamerLadyJules** [comment]
So since I installed Wabbajack a few days ago my work from home partner has complained about not being able to work due to the network choking.  

At first we thought maybe it was our broadband, so we rebooted the router, checked speeds etc.  He has never complained about network issues before when I have downloaded mods manually without Wabbajack.  So we have pinned the network issues to when I'm using Wabbajack specifically.

Even when reducing concurrent downloads to one, I still feel my entire network is bogged down by Wabbajack.

Then I came here and read this and see now it uses ALL bandwidth available.

Solution:
- Have the option within Wabbajack to NOT use all bandwidth available
- Have bandwidth usage options

**Comment by EzioTheDeadPoet** [comment]
@GamerLadyJules For now you will need to use 3rd party software to limit the download speeds WJ uses as it A. isn't a big priority at least currently (to my knowledge) and B. a change like that would be a bit more complicated and needs some bigger rewriting of older code.
