### ISSUE TITLE
Replace internal StoreHandlers with GameFinder lib

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#1368]
Project: https://github.com/erri120/GameFinder

**Comment by AGiantDino** [comment]
The Elder Scrolls V: Skyrim Special Edition (PC) (BethesdaSoftworks.SkyrimSE-PC): C:\Program Files\WindowsApps\BethesdaSoftworks.SkyrimSE-PC_1.11.0.0_x64__3275kfvn8vcwc

Dishonoredr Definitive Edition (PC) (BethesdaSoftworks.DishonoredDE-PC): C:\Program Files\WindowsApps\BethesdaSoftworks.DishonoredDE-PC_1.2.0.0_x64__3275kfvn8vcwc

Fallout 4 (PC) (BethesdaSoftworks.Fallout4-PC): C:\Program Files\WindowsApps\BethesdaSoftworks.Fallout4-PC_1.9.0.0_x64__3275kfvn8vcwc

The Elder Scrolls IV: Oblivion (PC) (BethesdaSoftworks.TESOblivion-PC): C:\Program Files\WindowsApps\BethesdaSoftworks.TESOblivion-PC_1.0.0.0_x86__3275kfvn8vcwc

The Elder Scrolls III: Morrowind (PC) (BethesdaSoftworks.TESMorrowind-PC): C:\Program Files\WindowsApps\BethesdaSoftworks.TESMorrowind-PC_1.0.0.0_x86__3275kfvn8vcwc
