### ISSUE TITLE
NTFS LSZ Compression Prompt Feature

### ISSUE THREAD

**Issue by Aosana** [wabbajack-tools/wabbajack#1374]
**Is your feature request related to a problem? Please describe.**

One of Wabbajack's least well-known features is the NTFS LSZ Compression option that reduces the size of mod lists during installation. This is because the option is hidden away with other useful features like Performance Threads in the small Settings menu. Users often overlook this feature when installing mod lists, even though it may help them save drive space on their machines.

**Describe the solution you'd like**

To remedy this issue, a small prompt asking users if they would like to utilize the NTFS LSZ Compression features before installing a mod list should suffice. It should explain exactly what the feature entails, such as the benefits of saving disk space and the drawbacks of possibly increasing loading times.

**Describe alternatives you've considered**

An alternative would to simply make the feature more well-known outside of installation, whether mod list authors themselves recommend its use or by Wabbajack itself mentioning it somewhere.

**Comment by halgari** [comment]
I have yet to hear of this causing a single issue. I wonder if we should just enable it by default.

**Comment by Unnoen** [comment]
I'm personally against having it enabled by default, but I definitely think it could be made easier to access and maybe explaining it a bit more (explaining what it is, how it works, possible tradeoffs, etc).
