### ISSUE TITLE
Update all resolution settings of SSE Display Tweaks after installation

### ISSUE THREAD

**Issue by jdsmith2816** [wabbajack-tools/wabbajack#1385]
The latest version of SSE Display Tweaks now manages resolution and resolution upscaling.  All instances of `SSEDisplayTweaks.ini` should be modified to set resolution in the same manner that SkyrimPrefs is currently modified.

I say all instances of SSEDisplayTweaks.ini as it's common practice to keep config for a mod in a separate folder from the mod itself so as to avoid wiping out customizations upon reinstallation of the mod when it updates..

Section and value to change in SSEDisplayTweaks.ini is below:

```ini
[Render]
Resolution=1920x1080
```

**Comment by halgari** [comment]
fixed in master, will be in the next version
