### ISSUE TITLE
Build 2.4.3.1 Only Works in Downloads Folder 

### ISSUE THREAD

**Issue by p51douglas** [wabbajack-tools/wabbajack#1402]
Not all users report this, but a few have. Builds prior to 2.4.3.1 worked fine at any install location, and would update to new released versions fine. Updating to 2.4.3.1 resulted in WJ opening main window, then going to small rectangle, then terminating itself. Moving to new locations on different drives did not fix. WJ resets did not fix. Completely removing WJ on drive(s) and appdata and downloading again and running from Downloads works.

**Comment by neochaosexcel** [comment]
Does not appear to actually have to be the Downloads folder used by Windows. It seems like a folder named Downloads on any drive works just as well.
