### ISSUE TITLE
Unmatched localization files are lost in compilation

### ISSUE THREAD

**Issue by apoapse1** [wabbajack-tools/wabbajack#1437]
**Describe the bug**

In short, Wabbajack automatically ignores any .txt file that is not matched. This is a problem when a list includes custom localization files -- stored as .txt files in the data/interface folder. In particular, merged localization files from zMerge are not appropriately compiled. I recommend automatically including any text files in the data/interface folder, but we can specify it, for instance, to ones ending in "-[language name].txt".

**Additional Context**

Win 10, SSE.

**Wabbajack Version**

2.4.4.1

**Logs**

N/A

**Comment by EzioTheDeadPoet** [comment]
not sure about the order of operations rn, but you could check to use the .txt based tag files I made to force include those files. 
a build for this is in #bleeding-edge-testing on the discord.

**Comment by apoapse1** [comment]
True, it's not impossible to work around. I'm just suggesting a new default because it's somewhat hard to diagnose but easy to prevent (and Hal told me to make the bug submission).

**Comment by EzioTheDeadPoet** [comment]
Yeah my comment was mostly meant as a workaround you can use for now.

**Comment by apoapse1** [comment]
Yep. Much appreciated, thanks!

**Comment by EzioTheDeadPoet** [comment]
#1436 will change this cause that code was related to those tagfiles not working as well.
they where excluded before they could have been read. now they get read and dealt with based on what kind of tagfile they are and all remaining `.txt` files will get included in the installation.

**Comment by EzioTheDeadPoet** [comment]
here is a link to a preview build with that change.
https://mega.nz/file/99lUzQ5L#8CdKeijJRyZTaMjpgiPd_Aczuz0ribVzu29GCUco9So
