### ISSUE TITLE
Check available disk space ahead of installation

### ISSUE THREAD

**Issue by Cyclonit** [wabbajack-tools/wabbajack#145]
**Is your feature request related to a problem? Please describe.**
Some mod lists require a large amount of disk space (e. g. Lexy's), often more than a user may expect. If the disk space runs out during installation the installer fails ungracefully. 

**Describe the solution you'd like**
WJ should check if the installl and download locations have sufficient space ahead of starting the installation.

**Comment by Noggog** [comment]
Probably doable sooner or later.
If someone knows where to get the expected size out of an install, I can tie it to the GUI pretty easily.
I'd have to do research to find how to obtain that info offhand, though.

**Comment by erri120** [comment]
https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/NexusApi/Dtos.cs
We can get the size of mods from Nexus pretty easy.

**Comment by tr4wzified** [comment]
Should maybe be closed? Was implemented but thrown out.
