### ISSUE TITLE
Wabbajack not locating any game folders, might have to do with Steam's "config.vdf, libraryfolders.vdf".

### ISSUE THREAD

**Issue by pascalizer** [wabbajack-tools/wabbajack#1480]
**Describe the bug**

The issue i've been having was that Wabbajack refused to detect the install location of 2 different games, FO4 and Skyrim.
What was the strange thing was that i was able to have it detect my install a day before the issue started happening. I finally managed to fix it by browsing the internet which gave me the idea to place the FO4 game and it's appmanifest into "SteamApps" inside the Steam root folder.

**Additional Context**

Windows 10, both SSE and FO4

**Wabbajack Version**

2.4.4.3

**Logs**

I do not know where the log files are kept, my apologies for not sharing the log file because of this.

**Comment by erri120** [comment]
Wabbajack uses [GameFinder](https://github.com/erri120/GameFinder) to find games. Logs are kept in the `Wabbajack/logs` folder.

**Comment by erri120** [comment]
Turns out Steam changed their config format in the latest update which broke some things. I've updated GameFinder to correctly parse this new format, should be fixed in the next Wabbajack update.
