### ISSUE TITLE
.git folders created by Synthesis failling compiles

### ISSUE THREAD

**Issue by SovnSkyrim** [wabbajack-tools/wabbajack#1512]
**Is your feature request related to a problem? Please describe.**

WJ failing to compile with .git folders created by Synthesis Patchers

**Describe the solution you'd like**

If Wabbajack cannot find source for a file within the tools folder of the list, it simply ignores them as they are useless to users anyway.

**Describe alternatives you've considered**

Ignore all .git folders made by Synthesis somehow?

**Additional context**
Those folders
http://prntscr.com/16rxoau

Log of a compile failing due to them
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/6718402/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Use the `WABBAJACK_IGNORE.txt` files....
read the Readme for info on how to.
