### ISSUE TITLE
"No-nudity" Tag

### ISSUE THREAD

**Issue by Fornication** [wabbajack-tools/wabbajack#1513]
I would like there to be an optional tag for "no nudity". I think this would allow users to have a better handle on decision making and their expectations for a list. Someone who plays Skyrim in their living room with their family in the background may be okay with decapitations seen in vanilla skyrim, but not nudity as seen in some lists, despite them not being tagged as NSFW. This may also apply to those interested in streaming or recording videos, among other things.

Solution: add a no-nudity tag.

Alternatives:

- Add a nudity tag: may not be the best idea, since this kind of forces list makers to tag their lists, instead of allowing list users the extra option of declaring "no nudity"
- Make all lists with nudity NSFW: pretty far reaching and would not be popular with the WJ list curators
- Do nothing: :(

**Comment by EzioTheDeadPoet** [comment]
We have already custom tags implemented, so we could already tag the lists. 🤔
It is just a matter of getting all the information about all lists to add the correct tag. (Also I would use both tags tbh, as their is no escape then and some lists have both depending on the Profile choosen.)
