### ISSUE TITLE
LoversLab login issues

### ISSUE THREAD

**Issue by AnhKien1996** [wabbajack-tools/wabbajack#1523]
**Hmm. Anybody else having problems connecting Wabbajack to LoversLab? I try to download the Tsukiro Mod through the Wabbajacks own cloud service.. The pack requires me to login into LoversLab, I created an account and verified it. When I try to give rights to Wabba, the screen goes white and doesn't do anything. Thanks!
Nexus works correctly **

Win 10
Wabbajack  2.5.0.5

![Capture](https://user-images.githubusercontent.com/86628343/123870684-e65ceb80-d95c-11eb-8189-e0688b55249a.PNG)

**Comment by LostDragonist** [comment]
Yes, some people are having that issue.  We're trying to figure out why.  The best thing we have to a solution right now is to download the files manually.  

Go to http://www.wabbajack.org/#/modlists/search?machineURL=tsukiro.
Change "10 rows" at the bottom to "1000 rows."
Go back up to the top and click on "Type" to sort by it.
Download anything that has type "LoversLabOAuthDownloader" and put it in your Tsukiro downloads folder.
Restart WJ and start the install again.

**Comment by peyoterick** [comment]
Doing this results in the attached
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/6737433/Wabbajack.current.log)
 installation failure and log error:

**Comment by peyoterick** [comment]
https://github.com/wabbajack-tools/wabbajack/issues/1523#issuecomment-871034016

**Comment by topcheese** [comment]
When you right click in order to go back a screen, you get a "Invalid Client ID."  I'm noticing there aren't any permissions being granted in the LL screenshot, so could that be a reason it's not working?  The white screen is just an empty HTML page.

**Comment by MajorSG** [comment]
v2.5.3.1 Still cant login to LL on windows 7

**Comment by HiForAll** [comment]
> Yes, some people are having that issue. We're trying to figure out why. The best thing we have to a solution right now is to download the files manually.
> 
> Go to http://www.wabbajack.org/#/modlists/search?machineURL=tsukiro. Change "10 rows" at the bottom to "1000 rows." Go back up to the top and click on "Type" to sort by it. Download anything that has type "LoversLabOAuthDownloader" and put it in your Tsukiro downloads folder. Restart WJ and start the install again.
