### ISSUE TITLE
Cant detect steam games in last steam client beta

### ISSUE THREAD

**Issue by w0rldx** [wabbajack-tools/wabbajack#1551]
The Problem is very simple in newer version of Steam (Steam Client Beta - July 29) they change the libary structure how games saved on other partition to match the new ui feature in that. After that Wabbajack can not longer read games out from other partitions. Cause of file change ("C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf"). 

![uipafwv](https://user-images.githubusercontent.com/20070711/127642821-266c464f-5e95-4cef-a026-27bbf5194365.png)

This cause following problem:

![huzxoBY](https://user-images.githubusercontent.com/20070711/127642192-e65b6a60-5d37-4274-886b-f52d62f99fc8.png)

Log file:
[Wabbajack 2021-07-30 09_03_07.log](https://github.com/wabbajack-tools/wabbajack/files/6907005/Wabbajack.2021-07-30.09_03_07.log)

**Comment by erri120** [comment]
Do they post a changelog anywhere?

**Comment by w0rldx** [comment]
> Do they post a changelog anywhere?

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2974049913511655206

**Comment by erri120** [comment]
Could you go to one of your libraries (eg `E:\\Games\\Steam`) and check the `libraryfolder.vdf` file in there just in case they changed more.

**Comment by w0rldx** [comment]
> Could you go to one of your libraries (eg `E:\\Games\\Steam`) and check the `libraryfolder.vdf` file in there just in case they changed more.

![K3XBcX3](https://user-images.githubusercontent.com/20070711/127648758-b4fe2832-3a3d-47e3-bb67-e9a44b5bc4bf.png)

**Comment by erri120** [comment]
Fixed in the GameFinder lib which Wabbajack uses: https://github.com/erri120/GameFinder/releases/tag/v1.6.3.
