### ISSUE TITLE
Validation Tool

### ISSUE THREAD

**Issue by TateTaylorUSA** [wabbajack-tools/wabbajack#1552]
**Is your feature request related to a problem? Please describe.**

Despite modified installations being against Wabbajack's rules people still request support when they have added mods on top. I have spent an annoying amount of time troubleshooting for people who, in the end, had a modified installation. This is very frustrating.

**Describe the solution you'd like**

A validation tool. It will validate the user's hashes for the mod folders, modlist.txt, and loadorder.txt against the .wabbajack. It will export some type of file (preferably encrypted in some manner) that will then be submitted back to the modlist curator. The file will tell you if the validation pass or failed. If it failed it will list the inconsistencies.

**Describe alternatives you've considered**

A zEdit Script or some type of .dll solution. I do not like these methods as much because they wouldn't be as user friendly and wouldn't build off the framework already established in the Wabbajack client.

**Additional context**

This idea was brought forth to me by [VictorF](https://github.com/MediumLowQuality) and [Parapets](https://github.com/Exit-9B).

**Comment by TateTaylorUSA** [comment]
Add-on to this idea: Also make the tool look for unis000.exe and similar files to quickly detect if the user has a pirated install. This will probably take a bit more work than than just comparing a Wabbajack to your modlist file and such, but I think it would be useful.

**Comment by EzioTheDeadPoet** [comment]
> Add-on to this idea: Also make the tool look for unis000.exe and similar files to quickly detect if the user has a pirated install. This will probably take a bit more work than than just comparing a Wabbajack to your modlist file and such, but I think it would be useful.
Thing with this is they know we detect it is pirated and just now have debug steps to fix that. At least that's how I see that going down.

**Comment by MediumLowQuality** [comment]
> Thing with this is they know we detect it is pirated and just now have debug steps to fix that. At least that's how I see that going down.

You would think people would figure this out, but we've had several Keizaal users in the last couple days request support and then volunteer screenshots of the game folders that are clearly pirated, which you would expect to be the most obvious thing not to do. Whether or not most figure it out, this does act as a filter against the users who don't.
