### ISSUE TITLE
Let users install modlists offline

### ISSUE THREAD

**Issue by ovnx** [wabbajack-tools/wabbajack#1565]
**Is your feature request related to a problem? Please describe.**

When installing a modlist, even when all the files have been downloaded, the installer connects to [https://github.com/wabbajack-tools/opt-out-lists/blob/master/ServerWhitelist.yml](https://github.com/wabbajack-tools/opt-out-lists/blob/master/ServerWhitelist.yml). This means that the list can't be installed when no internet connection is present, so that if the project ever stops, or the GitHub is down, it won't work.

**Describe the solution you'd like**

Make it possible to skip the ServerWhitelist.yml file by either letting the user download it manually or bypass it altogether.

**Describe alternatives you've considered**

Otherwise in order to archive a modlist you must save the entire installation folder rather than just the downloads (which seems totally unnecessary)

**Comment by EzioTheDeadPoet** [comment]
If I remember correctly a change like that has been made. In the past at least to some extent. 

But having any way of circumventing the whitelist would simply enable the use of any mods no matter their legality.

Better offline installs are something to think about but not something I would focus on, to be honest especially if it means completely ignoring the whitelist.

**Comment by ovnx** [comment]
> If I remember correctly a change like that has been made. In the past at least to some extent.
> 
> But having any way of circumventing the whitelist would simply enable the use of any mods no matter their legality.
> 
> Better offline installs are something to think about but not something I would focus on, to be honest especially if it means completely ignoring the whitelist.

In that case would it be possible to include the current ServerWhitelist.yml file in the program in a non user-editable way? (Encoded somehow or checked with a hash). Then if the program can’t access the online file, it falls back to the included one?
