### ISSUE TITLE
Unable To Download - Elysium

### ISSUE THREAD

**Issue by Whiestorm89** [wabbajack-tools/wabbajack#1612]
**Describe the bug**

Three file can't download via Wabbajack:

- TUDM- the ultimate dodge mod v4 x64.rar
- CC's Enhanced Ore Veins SSE - Fixed Iron Ore Cubemap.ra
- Impoved_Camera-1.0_Beta4.7z
**Additional Context**
OS: Win 10
Game: Skyrim SE

**Wabbajack Version**

v2.5.3.1
**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/7196498/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Seems like GDrive issues. Check to get those mods from their sources.
Improved Camera is on reddit (title might still say 3)
TUDM v4 I have no clue personally but a google search should find it, same for the ore veins.

This is not a WJ issue so I will close this now. Feel free to join the [discord](https://discord.gg/wabbajack) if you need help with the searching.
