### ISSUE TITLE
File hash check MO2 issue

### ISSUE THREAD

**Issue by xXSoulGamerXx** [wabbajack-tools/wabbajack#1616]
3.18 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
3.18 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
3.2 - Running in D:\Wabbajack\2.5.3.1
3.2 - Running in D:\Wabbajack\2.5.3.1
3.3 - Detected Windows Version: 10.0.19043.0
3.3 - Detected Windows Version: 10.0.19043.0
3.3 - System settings - (15.9GB RAM) (17GB Page), Display: 1360 x 768 (5.9GB VRAM - VideoMemorySizeMb=10240)
3.3 - System settings - (15.9GB RAM) (17GB Page), Display: 1360 x 768 (5.9GB VRAM - VideoMemorySizeMb=10240)
3.3 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
3.3 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
3.54 - Getting new Wabbajack version list
3.54 - Getting new Wabbajack version list
3.69 - Steam: Found no Regex matches in Steam Config at d:/steam\config\config.vdf
3.69 - Steam: Found no Regex matches in Steam Config at d:/steam\config\config.vdf
3.69 - Steam: Found no path-matches in Library Folders file at d:/steam\steamapps\libraryfolders.vdf
3.69 - Steam: Found no path-matches in Library Folders file at d:/steam\steamapps\libraryfolders.vdf
3.7 - Steam: Found game Grand Theft Auto: San Andreas (12120) at "d:/steam\steamapps\common\Grand Theft Auto San Andreas"
3.7 - Steam: Found game Grand Theft Auto: San Andreas (12120) at "d:/steam\steamapps\common\Grand Theft Auto San Andreas"
3.7 - Steam: Found game Sid Meier's Civilization IV: Colonization (16810) at "d:/steam\steamapps\common\Civilization IV Colonization"
3.7 - Steam: Found game Sid Meier's Civilization IV: Colonization (16810) at "d:/steam\steamapps\common\Civilization IV Colonization"
3.7 - Steam: Found game Crusader Kings II (203770) at "d:/steam\steamapps\common\Crusader Kings II"
3.7 - Steam: Found game Crusader Kings II (203770) at "d:/steam\steamapps\common\Crusader Kings II"
3.7 - Steam: Found game Steamworks Common Redistributables (228980) at "d:/steam\steamapps\common\Steamworks Shared"
3.7 - Steam: Found game Steamworks Common Redistributables (228980) at "d:/steam\steamapps\common\Steamworks Shared"
3.7 - Steam: Found game SteamVR (250820) at "d:/steam\steamapps\common\SteamVR"
3.7 - Steam: Found game SteamVR (250820) at "d:/steam\steamapps\common\SteamVR"
3.7 - Steam: Found game Vampire: The Masquerade - Bloodlines (2600) at "d:/steam\steamapps\common\Vampire The Masquerade - Bloodlines"
3.7 - Steam: Found game Vampire: The Masquerade - Bloodlines (2600) at "d:/steam\steamapps\common\Vampire The Masquerade - Bloodlines"
3.7 - Steam: Found game Grand Theft Auto V (271590) at "d:/steam\steamapps\common\Grand Theft Auto V"
3.7 - Steam: Found game Grand Theft Auto V (271590) at "d:/steam\steamapps\common\Grand Theft Auto V"
3.7 - Steam: Found game Dead Island Definitive Edition (383150) at "d:/steam\steamapps\common\DIDE"
3.7 - Steam: Found game Sid Meier's Civilization IV (3900) at "d:/steam\steamapps\common\Sid Meier's Civilization IV"
3.7 - Steam: Found game Dead Island Definitive Edition (383150) at "d:/steam\steamapps\common\DIDE"
3.75 - Steam: Found game Sid Meier's Civilization IV: Warlords (3990) at "d:/steam\steamapps\common\Sid Meier's Civilization IV Warlords"
3.75 - Steam: Found game Sid Meier's Civilization IV (3900) at "d:/steam\steamapps\common\Sid Meier's Civilization IV"
3.75 - Steam: Found game Stardew Valley (413150) at "d:/steam\steamapps\common\Stardew Valley"
3.75 - Steam: Found game Sid Meier's Civilization IV: Warlords (3990) at "d:/steam\steamapps\common\Sid Meier's Civilization IV Warlords"
3.75 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "d:/steam\steamapps\common\Skyrim Special Edition"
3.75 - Steam: Found game Stardew Valley (413150) at "d:/steam\steamapps\common\Stardew Valley"
3.75 - Steam: Found game Left 4 Dead (500) at "d:/steam\steamapps\common\left 4 dead"
3.75 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "d:/steam\steamapps\common\Skyrim Special Edition"
3.75 - Steam: Found game Sid Meier's Civilization: Beyond Earth (65980) at "d:/steam\steamapps\common\Sid Meier's Civilization Beyond Earth"
3.75 - Steam: Found game Left 4 Dead (500) at "d:/steam\steamapps\common\left 4 dead"
3.75 - Steam: Found game BioShock (7670) at "d:/steam\steamapps\common\Bioshock"
3.75 - Steam: Found game Sid Meier's Civilization: Beyond Earth (65980) at "d:/steam\steamapps\common\Sid Meier's Civilization Beyond Earth"
3.75 - Steam: Found game Sid Meier's Civilization IV: Beyond the Sword (8800) at "d:/steam\steamapps\common\Sid Meier's Civilization IV Beyond the Sword"
3.75 - Steam: Found game BioShock (7670) at "d:/steam\steamapps\common\Bioshock"
3.75 - Steam: Found game Sid Meier's Civilization IV: Beyond the Sword (8800) at "d:/steam\steamapps\common\Sid Meier's Civilization IV Beyond the Sword"
3.76 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1207660064 does not have a value BUILDID
3.76 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1207660064 does not have a value BUILDID
3.76 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1207664463 does not have a value BUILDID
3.76 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1207664463 does not have a value BUILDID
3.76 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
3.76 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
3.76 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
3.76 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
3.76 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
3.76 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
5.37 - Wabbajack Version: 2.5.3.1
5.37 - Wabbajack Version: 2.5.3.1
5.75 - Build server is alive
5.75 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
5.77 - Build server is alive
5.77 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
5.94 - Build server is alive
5.94 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
5.94 - Build server is alive
5.94 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
30.4 - Starting to install Serenity2
30.42 - Cleaning VFS, this may take a bit of time
30.47 - Starting Installer Task
30.47 - Installation has Started
30.47 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
30.92 - Configuring Processor
30.93 - Install Folder: D:\Serenity 2
30.93 - Downloads Folder: D:\Serenity 2\downloads
30.93 - Game Folder: d:\steam\steamapps\common\Skyrim Special Edition
30.93 - Wabbajack Folder: D:\Wabbajack\2.5.3.1
30.93 - Drive watcher is starting. Will warn at 8GB and error at 4GB
30.93 - Starting Drive watcher on D:\ currently 353.8GB free out of 931.5GB
30.94 - Starting Drive watcher on d:\ currently 353.8GB free out of 931.5GB
30.94 - Validating Game ESMs
30.94 - Creating Output Folders
31.63 - Optimizing ModList
31.66 - Optimizing ModList directives
32.9 - Looking for files to delete
32.96 - Cleaning empty folders
33.41 - Looking for unmodified files
34.25 - Updating ModList
34.25 - Optimized 107919 directives to 107919 required
34.27 - Hashing Archives
34.27 - Looking for files to hash
34.48 - Found 1006 total files, 1008 matching filesize
241.3 - Downloading Missing Archives
241.3 - Missing 2 archives
241.3 - Getting Nexus API Key, if a browser appears, please accept
242.78 - Logged into the nexus as souleater1000
242.78 - Nexus calls remaining: 2500 daily, 100 hourly
242.99 - Logged into the nexus as souleater1000
242.99 - Nexus calls remaining: 2500 daily, 100 hourly
242.99 - Loading server whitelist
243.24 - Loaded permissions for 532 servers and 253 Google Drive files
243.24 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
243.25 - Downloading Veydosebrom Regions-26293-1-1-2-1613156140.7z
243.25 - Downloading enbseries_skyrimse_v0462.zip
243.69 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
244.39 - Loading for alternative to nJ59BDEM0qc=
244.73 - Requesting manual download for Veydosebrom Regions NexusDownloader+State|SkyrimSpecialEdition|26293|185536
244.73 - 
245.09 - Download failed for enbseries_skyrimse_v0462.zip and no upgrade from this download source is possible
635.41 - Hashing Remaining Archives
635.41 - Looking for files to hash
635.5 - Found 1007 total files, 1009 matching filesize
635.82 - Unable to download enbseries_skyrimse_v0462.zip (HTTPDownloader+State|http://enbdev.com/enbseries_skyrimse_v0462.zip)
635.82 - Cannot continue, was unable to download one or more archives
635.82 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3
636.05 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
636.06 - File hash check (-42) 1baf6a7b025f9154605a0e3ba44c6af32fab9d8e755b0482171ecad622eb04f3

**Comment by xXSoulGamerXx** [comment]
this not the first time it happen 
it happen sereval time other modpacks 
i end up not install the other because this issue

**Comment by Althro** [comment]
This is not an issue with the wabbajack software, rather one where the modlist you are using is unable to get a file. Please join the wabbajack discord (https://discord.gg/wabbajack) and one of the team will be able to help you with this easier.

**Comment by EzioTheDeadPoet** [comment]
Known ENB Error (the author updated without changing the version). Links on how and where the file is found can be get on the Wabbajack discord, as per the license of the enb that only forbids nexus hosting.
