### ISSUE TITLE
Can't login into LoversLab through Wabbajack's client

### ISSUE THREAD

**Issue by Tripfy** [wabbajack-tools/wabbajack#1617]
New installation of Wabbajack, version 2.5.3.1, new LL account, activated.
Wabbajack allows me to Login without issues into Nexus and other accounts, but gets stuck on LoversLab.
I get to login and then it's blank white html page. When I quit the Wabbajack and start it again, it gives me Continue screen on LL account and then blank white page. Windows 10, English
It's frustrating as this prevents me from downloading the Elysium mod set.
![LL1](https://user-images.githubusercontent.com/91376893/134772502-0871d02c-c06a-4ee3-b5ff-0eeefc2e3320.jpg)
![LL2](https://user-images.githubusercontent.com/91376893/134772504-dc79fbbb-968d-4902-9eec-ce51b93e1ea3.jpg)

**Comment by EzioTheDeadPoet** [comment]
Update windows 10 to the latest version using the windows upgrade tool.

**Comment by BlazeOfHell** [comment]
21h1 version build 19043.1237 - latest according to microsoft version history https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44

latest entry in log is 
145.95 - Scheme Handler Got: wabbajack : wabbajack://loverslab/?code=(string that should not be public I assume)
145.95 - Got Scheme callback wabbajack://loverslab/?code=(string that should not be public I assume)
332.43 - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.<GetAuthedClient>b__43_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 134
   at Wabbajack.Common.Utils.CatchAndLog(Func`1 f) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Logging.cs:line 163
332.43 - System.Exception: Must log into Lovers Lab to continue
332.44 - File hash check (-42) 3aa0271491f5f4824184aac3cee1aff58f352c08e09fa31bbc3846b08e257d62

**Comment by EzioTheDeadPoet** [comment]
Do you have a PC/Laptop with an Intel CPU ? 
Also have you tried a VPN yet ?

**Comment by BlazeOfHell** [comment]
Ryzen 3600x
Using VPN with US/EU/Asia selected made no difference for me

**Comment by EzioTheDeadPoet** [comment]
https://www.microsoft.com/software-download/windows10
try to use the updater linked on that site. besides that this is very odd.
Have you updated your driver's.

**Comment by Tripfy** [comment]
> https://www.microsoft.com/software-download/windows10
> try to use the updater linked on that site. besides that this is very odd.
> Have you updated your driver's.

Please, do not tell people blindly to just update their Windows, without knowing what it can cause, I had a panic attack and honestly wanted to kill you, especially since every other game and program worked until today on my pc.

I have updated my Windows using the "Download update" feature on that site. I'd to warn anyone who does that, as it took several hours to download and prepare yesterday (even with fast internet and OS on SSD), I let it update overnight and **when I came back to pc today, my desktop was empty, I've lost all of my documents, pictures, videos, downloads, I was logged out of all the services on my pc and my user profile was not accessible**, I had 10 temporary user profiles and my original user profile was locked as "special profile".

Yeah after several hours of trying to figure out how to revert all the changes and changing several passwords into all the apps so that I could access them again, the wabbajack managed to finally log into lovers lab. But for god's sake, this is not normal, fix this issue on your side or with LL. I had to restart the wabbajack three times before it would start working anyway as it got stuck several times on "Installing" and nothing was happening, no progress bars or anything.
