### ISSUE TITLE
AFKMods downloads not documented

### ISSUE THREAD

**Issue by tyhawk** [wabbajack-tools/wabbajack#1636]
AFKMods support has been added to Wabbajack in #417, but has not been documented on https://github.com/wabbajack-tools/wabbajack#creating-your-own-modlist along with the other possible download sites such as Mega, Dropbox and Google Drive. Could this be added to the documentation?

**Comment by erri120** [comment]
We don't support AFKMods anymore because the servers are really bad and can't handle more than 10 users at once.
