### ISSUE TITLE
[Game Support Request] STALKER - Anomaly

### ISSUE THREAD

**Issue by hauntedabyss** [wabbajack-tools/wabbajack#1646]
**Is your feature request related to a problem? Please describe.**

 
The modding scene is now using MO2 as its primary mod manager for stalker games. The modding scene is getting huge and 250+ mod lists are becoming a thing.
Mod lists such as EFP are a huge step forward for the community. Unfortunately I tried to use another mod list but it broke my game causing issues as shader folder and User.itx was specifically for that build and MO2 didn't change per profile. Many modders would love to have wabbajack has a way to switch profiles per mod overhaul.
EFP page below for reference.
https://github.com/Minotaur21/Escape-From-Pripyat/wiki/Introduction

I would love to have support for anomaly at the least.
There is things to take note.
ENB, Shader folder and user.itx being commonly specific for eatch mod list and must be required per list.
There is also a new way to mod Anomoly using DLTX mods support for this would be excellent aswell.

Perhaps the ability to Make patches easier aswell perhaps that would be were DLTX would fit in?( I am sorry for any vagueness as I am not a code master.)

Thank you for your Time and Any help.

**Comment by hauntedabyss** [comment]
Thank you very much for your time.
I understand it starts off as a Zip but escape from pripyat is the biggest
Mod List currently for the game and it is using wabbajack. Maybe something
to consider looking at how he is doing it. I just know the shaders and
Configs are the biggest hassle to changing profiles as I have experienced
so far.

**Comment by LostDragonist** [comment]
There is no evidence that any WJ modlist named "Escape from Pripyat" exists.  In fact, Escape from Pripyat 3.0 is just a giant modpack that you download from a Google Drive and doesn't have anything to do with WJ.

**Comment by EzioTheDeadPoet** [comment]
Modding of this game is already big without a need for Wabbajack. So I will close this as not planned.
