### ISSUE TITLE
Add percentage and progress for downloads

### ISSUE THREAD

**Issue by extract** [wabbajack-tools/wabbajack#1662]
**Is your feature request related to a problem? Please describe.**

I don't get enough information to know if the downloads have gotten stuck and I need to restart. I think this would be rather simple seeing as there's already a progress bar.

**Describe the solution you'd like**

Just some numbers telling me the speed/percentage and potentially ETA (or an option to toggle?).

**Additional context**

Sorry if it already exists and I'm using an old version of Wabbajack.

![Wabbajack_2021-10-18_17-48-04](https://user-images.githubusercontent.com/4999714/137765317-79b603e1-96d0-4f3d-ba34-c1cefcaf3567.png)

**Comment by Xetaxheb** [comment]
seconding this
sat there two hours on a small file thinking it was just large (amidianborn so a reasonable suspicion... but it was just the dragonborn file)

even just simply exposing whatever raw data is being used to calculate the bar and prepending it every second or few to the text ( x / y )

**Comment by extract** [comment]
Issue still exists. Sometimes the downloading phase stops and doesn't continue. Information if download is on-going is important. Either percentage, downloading speed or size / totalSize Mb, would be fine.

**Comment by extract** [comment]
still does.

**Comment by halgari** [comment]
Much improved in 3.0
