### ISSUE TITLE
Use common download directory for modlists

### ISSUE THREAD

**Issue by extract** [wabbajack-tools/wabbajack#1671]
**Is your feature request related to a problem? Please describe.**

Many mods have very similar mods (eg texture mods, sound mods, bruma etc), so having a Wabbajack general download folder for all mods could speed up downloads. It would also lower the amount of duplicated downloaded mods.
Because you hash check the files could always overwrite if the hash doesn't look right.

**Describe the solution you'd like**

Something like DRIVE:\wabbajack\downloads
instead of
DRIVE:\modlist\downloads
DRIVE:\anothermodlist\downloads

**Describe alternatives you've considered**

Keep as is? Just a feature

**Additional context**

None

**Comment by Drazden** [comment]
You can do this yourself simply by setting the downloads folder to the same shared one whenever you install a list
