### ISSUE TITLE
Installation Failed (MO2Installer)

### ISSUE THREAD

**Issue by Beefycakes780** [wabbajack-tools/wabbajack#1696]
**Describe the bug**
Tried reloading the app several times and used the disk option to continue, and the installation keeps failing at the Mo2 installer.  I know the problem isn't storage I have over 100 gbs left. 

"Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives"
**Additional Context**

Win 10 
SSE

**Wabbajack Version**

Wabbajack v2.5.3.1
fed371a6f1956ee74801c18be22a6d628c68bc0f

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/7449939/Wabbajack.current.log)

**Comment by Drazden** [comment]
This is not an issue with mo2, please join our discord and check the serenity channel to find the enb file you need.

**Comment by EzioTheDeadPoet** [comment]
Going to close this now due to being answered.
