### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BezmambI** [wabbajack-tools/wabbajack#1699]
**Describe the bug**

<An error occurred while downloading one file, downloaded it more than once. After several crashes, the application gave this error.>

**Additional Context**

<Windows 10; Game SSE>

**Wabbajack Version **

<2.5.3.1>

**Logs**
[Wabbajack 2021-10-31 23_53_07.log](https://github.com/wabbajack-tools/wabbajack/files/7460365/Wabbajack.2021-10-31.23_53_07.log)

**Comment by EzioTheDeadPoet** [comment]
You deleted all the relevant info from the log file and the only error you kept is the one created by you closing the program. 

Join the [discord](https://discord.gg/wabbajack) for more detailed support with a full log.

**Comment by BezmambI** [comment]
I found another log

[Wabbajack 2021-11-01 12_26_07.log](https://github.com/wabbajack-tools/wabbajack/files/7460557/Wabbajack.2021-11-01.12_26_07.log)
