### ISSUE TITLE
Elysium modlist Installation failed, unable to download ultra.ini

### ISSUE THREAD

**Issue by FeeltheWindHSB** [wabbajack-tools/wabbajack#1730]
Wabbajack installation always fails at this poin where it  have to download a file named "ultra.ini"

Here's the log:

0.47 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0.47 - Running in G:\Wabbajack\2.5.3.1
0.54 - Detected Windows Version: 10.0.22000.0
0.54 - System settings - (15.9GB RAM) (3GB Page), Display: 1920 x 1080 (3.9GB VRAM - VideoMemorySizeMb=10240)
0.54 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.55 - Getting new Wabbajack version list
0.77 - Steam: Found game The Binding of Isaac: Rebirth (250900) at "G:\SteamLibrary\steamapps\common\The Binding of Isaac Rebirth"
0.77 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "G:\SteamLibrary\steamapps\common\Skyrim Special Edition"
0.77 - Steam: Found game Devil May Cry 5 (601150) at "G:\SteamLibrary\steamapps\common\Devil May Cry 5"
0.77 - Steam: Found game Hades (1145360) at "C:\Program Files (x86)\Steam\steamapps\common\Hades"
0.77 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0.77 - Steam: Found game DARK SOULS™ III (374320) at "C:\Program Files (x86)\Steam\steamapps\common\DARK SOULS III"
0.77 - Steam: Found game FINAL FANTASY IX (377840) at "C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY IX"
0.78 - Steam: Found game Dishonored 2 (403640) at "C:\Program Files (x86)\Steam\steamapps\common\Dishonored2"
0.78 - Steam: Found game DARK SOULS™: REMASTERED (570940) at "C:\Program Files (x86)\Steam\steamapps\common\DARK SOULS REMASTERED"
0.78 - Steam: Found game Hades (1145360) at "c:/program files (x86)/steam\steamapps\common\Hades"
0.78 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.78 - Steam: Found game DARK SOULS™ III (374320) at "c:/program files (x86)/steam\steamapps\common\DARK SOULS III"
0.78 - Steam: Found game FINAL FANTASY IX (377840) at "c:/program files (x86)/steam\steamapps\common\FINAL FANTASY IX"
0.78 - Steam: Found game Dishonored 2 (403640) at "c:/program files (x86)/steam\steamapps\common\Dishonored2"
0.78 - Steam: Found game DARK SOULS™: REMASTERED (570940) at "c:/program files (x86)/steam\steamapps\common\DARK SOULS REMASTERED"
0.78 - GOG: Found game Little Nightmares - The Residence (1185734803) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Little Nightmares - Scarecrow sack (1268928435) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Little Nightmares - Upside-down teapot (1352220891) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Cyberpunk 2077 (1423049311) at "C:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077"
0.78 - GOG: Found game Little Nightmares (1433377508) at "c:\gog games\little nightmares"
0.78 - GOG: Found game The Witcher 3: Wild Hunt - Game of the Year Edition (1495134320) at "C:\Program Files (x86)\GOG Galaxy\Games\The Witcher 3 Wild Hunt GOTY"
0.78 - GOG: Found game Little Nightmares - Tengu mask (1611302854) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Little Nightmares - Hideaway (1675156362) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Little Nightmares - Fox mask (1828170949) at "c:\gog games\little nightmares"
0.78 - GOG: Found game Little Nightmares - The Depths (1863057712) at "c:\gog games\little nightmares"
0.91 - EpicGamesStore: Found game Grand Theft Auto V at "C:\GTAV"
0.94 - Origin: Found no Ids and Paths in the MFST files
1.17 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\Coldwood Interactive\Unravel for Game Origin.OFR.50.0000823
1.17 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\Coldwood Interactive\Unravel for Game Origin.OFR.50.0000823
1.17 - Origin: Game Origin.OFR.50.0000823 was found using the Api but has no Path
1.17 - Origin: Found game Unravel Standard Edition - PCDD - WW (Origin.com) (Origin.OFR.50.0000823) at ""
1.34 - Wabbajack Version: 2.5.3.1
2.03 - Build server is alive
2.03 - Build server is alive
2.03 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
2.03 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
9.12 - Starting to install Elysium
9.13 - Cleaning VFS, this may take a bit of time
9.18 - Starting Installer Task
9.18 - Installation has Started
9.18 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
9.39 - Configuring Processor
9.4 - Install Folder: G:\Elysium Skyrim
9.4 - Downloads Folder: E:\Elysium Skyrim
9.4 - Game Folder: G:\SteamLibrary\steamapps\common\Skyrim Special Edition
9.4 - Wabbajack Folder: G:\Wabbajack\2.5.3.1
9.4 - Drive watcher is starting. Will warn at 8GB and error at 4GB
9.41 - Starting Drive watcher on G:\ currently 248GB free out of 465.8GB
9.41 - Starting Drive watcher on E:\ currently 286.7GB free out of 443.2GB
9.41 - Validating Game ESMs
9.42 - Creating Output Folders
9.51 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
9.51 - Optimizing ModList
9.51 - Optimizing ModList directives
12.21 - Looking for files to delete
12.21 - Cleaning empty folders
13.35 - Looking for unmodified files
13.82 - Updating ModList
13.82 - Optimized 241594 directives to 241594 required
13.89 - Hashing Archives
13.89 - Looking for files to hash
16.69 - Found 18265 total files, 2099 matching filesize
16.92 - Downloading Missing Archives
16.92 - Missing 1 archives
16.92 - Getting Nexus API Key, if a browser appears, please accept
16.95 - Loading server whitelist
17.18 - Loaded permissions for 586 servers and 263 Google Drive files
17.18 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
17.2 - Downloading ultra.ini
17.21 - (Retry 1 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\ultra.ini], waiting 100ms
17.31 - (Retry 2 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\ultra.ini], waiting 200ms
17.52 - (Retry 3 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\ultra.ini], waiting 400ms
17.94 - (Retry 4 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\ultra.ini], waiting 800ms
18.75 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\ultra.ini], waiting 1600ms
20.36 - Loading for alternative to joAkOFfS7Wc=
20.38 - No alternative for joAkOFfS7Wc= could be found
20.6 - Hashing Remaining Archives
20.6 - Looking for files to hash
21.54 - Found 18265 total files, 2099 matching filesize
21.78 - Unable to download ultra.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|ultra.ini)
21.78 - Cannot continue, was unable to download one or more archives
21.78 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
21.87 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
22.47 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
564.67 - Starting to install Elysium
564.69 - Starting Installer Task
564.69 - Installation has Started
564.69 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
565.38 - Configuring Processor
565.38 - Install Folder: G:\Elysium Skyrim
565.38 - Downloads Folder: E:\Elysium Skyrim
565.38 - Game Folder: G:\SteamLibrary\steamapps\common\Skyrim Special Edition
565.38 - Wabbajack Folder: G:\Wabbajack\2.5.3.1
565.38 - Drive watcher is starting. Will warn at 8GB and error at 4GB
565.38 - Starting Drive watcher on G:\ currently 248GB free out of 465.8GB
565.38 - Starting Drive watcher on E:\ currently 286.7GB free out of 443.2GB
565.38 - Validating Game ESMs
565.39 - Creating Output Folders
565.61 - Optimizing ModList
565.61 - Optimizing ModList directives
568.21 - Looking for files to delete
568.21 - Cleaning empty folders
569.33 - Looking for unmodified files
570.61 - Updating ModList
570.61 - Optimized 241594 directives to 241594 required
570.64 - Hashing Archives
570.64 - Looking for files to hash
571.56 - Found 18265 total files, 2099 matching filesize
571.81 - Downloading Missing Archives
571.81 - Missing 1 archives
571.81 - Getting Nexus API Key, if a browser appears, please accept
571.81 - Loading server whitelist
571.85 - Loaded permissions for 586 servers and 263 Google Drive files
571.85 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
571.92 - Downloading ultra.ini
573.75 - Hashed download is incorrect
573.75 - Loading for alternative to joAkOFfS7Wc=
573.87 - No alternative for joAkOFfS7Wc= could be found
574.1 - Hashing Remaining Archives
574.1 - Looking for files to hash
575.17 - Found 18266 total files, 2100 matching filesize
575.43 - Unable to download ultra.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|ultra.ini)
575.43 - Cannot continue, was unable to download one or more archives
575.43 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
575.43 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
576.12 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
850.07 - Starting to install Elysium
850.09 - Starting Installer Task
850.09 - Installation has Started
850.09 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
850.77 - Configuring Processor
850.77 - Install Folder: G:\Elysium Skyrim
850.77 - Downloads Folder: E:\Elysium Skyrim
850.77 - Game Folder: G:\SteamLibrary\steamapps\common\Skyrim Special Edition
850.77 - Wabbajack Folder: G:\Wabbajack\2.5.3.1
850.77 - Drive watcher is starting. Will warn at 8GB and error at 4GB
850.77 - Starting Drive watcher on G:\ currently 248GB free out of 465.8GB
850.77 - Starting Drive watcher on E:\ currently 286.7GB free out of 443.2GB
850.77 - Validating Game ESMs
850.79 - Creating Output Folders
851 - Optimizing ModList
851 - Optimizing ModList directives
853.62 - Looking for files to delete
853.62 - Cleaning empty folders
854.72 - Looking for unmodified files
856.04 - Updating ModList
856.04 - Optimized 241594 directives to 241594 required
856.08 - Hashing Archives
856.08 - Looking for files to hash
857.04 - Found 18266 total files, 2100 matching filesize
857.28 - Downloading Missing Archives
857.29 - Missing 1 archives
857.29 - Getting Nexus API Key, if a browser appears, please accept
857.29 - Loading server whitelist
857.4 - Loaded permissions for 586 servers and 263 Google Drive files
857.4 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
857.5 - Downloading ultra.ini
857.51 - Hashed download is incorrect
857.51 - Loading for alternative to joAkOFfS7Wc=
857.53 - No alternative for joAkOFfS7Wc= could be found
857.73 - Hashing Remaining Archives
857.73 - Looking for files to hash
858.76 - Found 18266 total files, 2100 matching filesize
859.02 - Unable to download ultra.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|ultra.ini)
859.02 - Cannot continue, was unable to download one or more archives
859.02 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
859.02 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
859.68 - File hash check (-42) fd1c28be7cfc4f8da5407acb066b4c651b8ace3b80796547c09d85d69bb0aec5
1074.76 - Loading ModLists from GitHub
1075.27 - (Retry 1 of 5), got exception (32) The process cannot access the file because it is being used by another process: [C:\Users\ildur\AppData\Local\Wabbajack\ModListImages\50e95ef295848448], waiting 100ms

**Comment by EzioTheDeadPoet** [comment]
Verify your Skyrim via steam and then if the list requires the pre AE update SE version run the downgrader.
https://www.nexusmods.com/skyrimspecialedition/mods/57618/?tab=description the FULL one.
