### ISSUE TITLE
Request: Ignore non-WJ games in logs

### ISSUE THREAD

**Issue by Patchier** [wabbajack-tools/wabbajack#1734]
**Is your feature request related to a problem? Please describe.**

Not so much a problem, just a privacy concern.

**Describe the solution you'd like**

Only show games with current WJ support in logs.

**Describe alternatives you've considered**

This particular suggestion has no alternatives.

**Comment by JanuarySnow** [comment]
to be honest it did always seem a bit weird that it listed every single game on your system, when they were completely superfluous to the operation of the application.

**Comment by DokuseiSan** [comment]
So, for example, if you want to install a Skyrim Special Edition modlist, you want Wabbajack to only check for a SSE installation and no other games?

**Comment by EzioTheDeadPoet** [comment]
it still has to check for all installed games, they just want the logging removed. Personally I think it is no issue as it is only stored locally and can always be edited before sending.
