### ISSUE TITLE
Coma in modlist full path is allowed by Wabbajack, but breaks Mod Organizer / UVFS

### ISSUE THREAD

**Issue by azraerl** [wabbajack-tools/wabbajack#1774]
**Describe the bug**

As per subject, example path: `C:\Modlists\Skyrim, but Wabbajack\` works just fine during Wabbajack install process, but attempt to run game via portable MO2 leads to UVFS files not being mapped properly.

**Additional Context**

OS: Windows 10
Game type: SSE

**Wabbajack Version**

2.5.3.4

**Logs**

N/A

**Comment by LostDragonist** [comment]
This seems more like problem for the MO2 devs, not WJ.  It's also nearly impossible to look into anything like this without the proper MO2 logs.

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Use the "Open Folders" button to open the logs folder.
4) Recreate your problem.
5) Close MO.
6) Upload the mo_interface.log and the most recent usvfs log here. You may need to compress them.

**Comment by azraerl** [comment]
Indeed, this should be solved outside of Wabbajack.

For now, solved this by updating modlist README stating that special characters in path are not supported.
