### ISSUE TITLE
Unable to login with CefSharp

### ISSUE THREAD

**Issue by kell90** [wabbajack-tools/wabbajack#1777]
As the title says, it appears as though many websites do not like Wabbajack's built-in browser. I tried to install Elysium today, which required many modding website accounts to work. Logging into my accounts is extremely difficult with the built-in browser to the point where I just gave up. 

A good solution might be somehow embedding a Chromium browser into Wabbajack? Maybe? I'm not sure. Not my area of expertise. 

I have an account with a website that requires I use Google auth to sign in. That is impossible through the Wabbajack browser, and I'm unable to make an account with any emails I have.

I imagine this issue has cropped up a few times before - I saw some forum posts from back in August sounding optimistic this would be addressed. Any news?

**Comment by EzioTheDeadPoet** [comment]
If the issue is VP then you can just download that one file WJ needs from there manually and put it in your downloads folder and WJ we won't need you to login.

**Comment by erri120** [comment]
> A good solution might be somehow embedding a Chromium browser into Wabbajack? Maybe? I'm not sure. Not my area of expertise.

We use CefSharp which are bindings for the Chromium Embedded Framework.

**Comment by kell90** [comment]
> If the issue is VP then you can just download that one file WJ needs from there manually and put it in your downloads folder and WJ we won't need you to login.

Sounds like this should be a decent solution, assuming WJ only needs a few files from the sites it can't get into. So just by having the files in the downloads directory, it should skip over it automatically when I start the download process?

**Comment by EzioTheDeadPoet** [comment]
> > If the issue is VP then you can just download that one file WJ needs from there manually and put it in your downloads folder and WJ we won't need you to login.
> 
> Sounds like this should be a decent solution, assuming WJ only needs a few files from the sites it can't get into. So just by having the files in the downloads directory, it should skip over it automatically when I start the download process? 

If the files are in the downloads folder you specified, yes.

If the lists need more or less files of those sites depends on the sites you are talking about and what lists you are installing.

**Comment by halgari** [comment]
The problem is in a security check in GMail. What's happening is Chromium/CEF sets its user agent to include "Chromium" or "CEF" then Gmail sees that and is throwing the error page. The fix for this is to hard-code the user agent during CEF initialization to use a standard chrome UserAgent, something like : `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

**Comment by halgari** [comment]
A PR for this should be simple, just modify the agent string during CEF initialization, and use the string I pasted above

**Comment by jarno9981** [comment]
For me it works to set the useragent on navigation starting with webview2 maybe it works to with cefsharp
