### ISSUE TITLE
My Elysium installation doesnt work.

### ISSUE THREAD

**Issue by Maximen53** [wabbajack-tools/wabbajack#1788]
## I did the downgrade for SkyrimAE, but now it fails again but with less messages :

25,7 - Wabbajack Folder: C:\Wabbajack&modlists\2.5.3.4
25,7 - Drive watcher is starting. Will warn at 8GB and error at 4GB
25,7 - Starting Drive watcher on C:\ currently 636,9GB free out of 930,9GB
25,7 - Validating Game ESMs
25,73 - Creating Output Folders
26,42 - Optimizing ModList
26,42 - Optimizing ModList directives
30,64 - Looking for files to delete
30,64 - Cleaning empty folders
32,06 - Looking for unmodified files
33,38 - Updating ModList
33,38 - Optimized 241594 directives to 241594 required
33,45 - Hashing Archives
33,45 - Looking for files to hash
33,75 - Found 1598 total files, 1552 matching filesize
34,35 - Downloading Missing Archives
34,35 - Missing 4 archives
34,35 - Getting Nexus API Key, if a browser appears, please accept
34,37 - Loading server whitelist
34,63 - Loaded permissions for 632 servers and 275 Google Drive files
34,63 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d
34,68 - Downloading Skyrim_Default.ini
34,68 - Downloading Elysium - Dyndolod 3D Output.7z
34,68 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
34,68 - Downloading xLODGen.84.7z
34,76 - Hashed download is incorrect
34,76 - Loading for alternative to JbYP1w8FSfY=
34,81 - No alternative for JbYP1w8FSfY= could be found
34,82 - Loading for alternative to uq8KT2b+f9A=
34,83 - No alternative for uq8KT2b+f9A= could be found
34,93 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d
35,29 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d
35,93 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d
36,13 - Loading for alternative to Ypeg2MKgzlQ=
36,18 - No alternative for Ypeg2MKgzlQ= could be found
1573,61 - Hashing Remaining Archives
1573,61 - Looking for files to hash
1574,02 - Found 1598 total files, 1552 matching filesize
1575 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
1575 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
1575 - Unable to download Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar (HTTPDownloader+State|https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar)
1575 - Cannot continue, was unable to download one or more archives
1575 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d
1575,05 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1575,37 - File hash check (-42) 57f96794a362169dcb36d6b19dbccb31e46dea20523e08e1e3f50cbf60ac873d

## If you know what is going on tell me please.

**Comment by LostDragonist** [comment]
1. Game needs to be installed in English
2. Download Nemesis from the Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/60033
3. Alternate xlodgen link: https://mega.nz/file/sF5AWIoD#wi89GWmMsPoUEb7yHHjcfmfApaAAzFrUGru5UV3CsqM
4. Did you really create a new issue for this?
5. In the future, the discord would probably be a better idea for help.

**Comment by Maximen53** [comment]
> 1. Game needs to be installed in English
> 2. Download Nemesis from the Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/60033
> 3. Alternate xlodgen link: https://mega.nz/file/sF5AWIoD#wi89GWmMsPoUEb7yHHjcfmfApaAAzFrUGru5UV3CsqM
> 4. Did you really create a new issue for this?
> 5. In the future, the discord would probably be a better idea for help.



> 1. Game needs to be installed in English
> 2. Download Nemesis from the Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/60033
> 3. Alternate xlodgen link: https://mega.nz/file/sF5AWIoD#wi89GWmMsPoUEb7yHHjcfmfApaAAzFrUGru5UV3CsqM
> 4. Did you really create a new issue for this?
> 5. In the future, the discord would probably be a better idea for help.

Sorry... So I just need to download them in the download file and it will work ?

**Comment by LostDragonist** [comment]
That's the idea, yes.  Put the files in the downloads folder you specified and restart the install.
