### ISSUE TITLE
Cannot get the known folder path

### ISSUE THREAD

**Issue by Yippee38** [wabbajack-tools/wabbajack#179]
**Describe the bug**
When I hit the "Begin" button, I get an error saying, "11.12 - Cannot get the known folder path.  It may not be available on this system. - Can't continue"

**Additional context**
Win 7, 64-bit, SP1  SSE

**Logs**
0.2 - Loading Modlists from Github
7.26 - Wabbajack Build - 42d8347c76c2332994d2680e3bea1310b17fd576
9.09 - Exception while caching Mod List image Lexy's LOTD Unofficial Autoinstaller
Property 'UriSource' or property 'StreamSource' must be set.
:EndInit:0:0
:<.ctor>b__1:0:0

10.29 - Validating Dawnguard.esm
10.35 - Validating Dragonborn.esm
10.37 - Exception while caching slide MystiriousDawn's HD Skyrim Overhaul (19421)
An error occurred while sending the request.
:Throw:0:0
:HandleNonSuccessAndDebuggerNotification:0:0
:GetResult:0:0
:MoveNext:0:0
The request was aborted: Could not create SSL/TLS secure channel.
:EndGetResponse:0:0
:GetResponseCallback:0:0

10.48 - Validating HearthFires.esm
10.49 - Validating Update.esm
10.53 - Loading Nexus Mod Permissions
10.65 - Loaded permissions for 2 authors
10.65 - Loading Server Whitelist
10.69 - Loaded permissions for 41 servers and 15 GDrive files
10.69 - Running validation checks
11.08 - No Validation failures
11.08 - Loading VFS Cache
11.12 - Missing 645 archives
11.12 - Getting Nexus API Key, if a browser appears, please accept
11.12 -    at Syroot.Windows.IO.KnownFolder.GetPath(KnownFolderFlags flags)
   at Wabbajack.Lib.Downloaders.ManualDownloader..ctor() in d:\work\1\s\Wabbajack.Lib\Downloaders\ManualDownloader.cs:line 34
   at Wabbajack.Lib.Downloaders.DownloadDispatcher..cctor() in d:\work\1\s\Wabbajack.Lib\Downloaders\DownloadDispatcher.cs:line 13
11.12 - System.Runtime.InteropServices.ExternalException (0x80070002): Cannot get the known folder path. It may not be available on this system.
   at Syroot.Windows.IO.KnownFolder.GetPath(KnownFolderFlags flags)
   at Wabbajack.Lib.Downloaders.ManualDownloader..ctor() in d:\work\1\s\Wabbajack.Lib\Downloaders\ManualDownloader.cs:line 34
   at Wabbajack.Lib.Downloaders.DownloadDispatcher..cctor() in d:\work\1\s\Wabbajack.Lib\Downloaders\DownloadDispatcher.cs:line 13
11.12 - Cannot get the known folder path. It may not be available on this system. - Can't continue

**Solution**

**Comment by erri120** [comment]
You need to enable SSL/TLS https://manage.accuwebhosting.com/knowledgebase/3008/How-do-I-enable-TLS-12-on-Windows-7.html

**Comment by Yippee38** [comment]
Thank you.

**Comment by Yippee38** [comment]
I followed the instructions you linked above.  That didn't help.  I then followed these instructions:  [https://documentation.cpanel.net/display/CKB/How+to+Configure+Microsoft+Windows+7+to+use+TLS+Version+1.2](url).  That didn't help either.  I'm still getting the same error.

**Comment by tr4wzified** [comment]
Gonna spin up a Windows 7 VirtualBox and check this out later today.

**Comment by tr4wzified** [comment]
Fixed as of https://github.com/wabbajack-tools/wabbajack/commit/7b20b40ce008c911d35eae98eaf590ac930249c9
