### ISSUE TITLE
Offer the ability to start the installation from a specific step

### ISSUE THREAD

**Issue by tstavrianos** [wabbajack-tools/wabbajack#18]
**Is your feature request related to a problem? Please describe.**
Currently the modlists will run through the entire process by only asking for the game directory.

**Describe the solution you'd like**
I would like the option to have process stop at each step (checkbox maybe?) and then manually click to continue. This is incase I am using the machine at the same time and want the extraction/installation to run when I want it to.
Steps at which it should stop or wait should be after Download and after extraction.

**Describe alternatives you've considered**
Currently I shutdown the program when I notice that its near the end, if I need to use the computer for something else at the same time.

**Additional context**
Not a high priority requirement, just nice to have for people with older/slower machines.

**Comment by Mdc211** [comment]
Or a pause button would be great

**Comment by Noggog** [comment]
I think pause/stop buttons are the way to go here?

**Comment by Noggog** [comment]
Merging into #484
