### ISSUE TITLE
Wabbajack Licentia Modlist instalation failed

### ISSUE THREAD

**Issue by Belgianoo** [wabbajack-tools/wabbajack#1802]
Hello guys !

I've been trying to install the Licentia modlist from Wabbajack and at the end of the install i recived some error messages that I will copy the bellow and the message "instalation failed". I tried closing and reopening the instalation window several times , but that dosen't seem to fix the problem . I have to mention that I followed every pre-instalation step from the guide. 

I've got the following messages:

![image](https://user-images.githubusercontent.com/97345850/148645629-4b0c12ef-4b09-4816-b4c1-04ad14257c2e.png)
![image](https://user-images.githubusercontent.com/97345850/148645660-57b7ae40-97fe-40a2-a6f4-929d93247abf.png)
![image](https://user-images.githubusercontent.com/97345850/148645676-30f6369d-4c8e-482f-b84b-7d5c2e191d22.png)
![image](https://user-images.githubusercontent.com/97345850/148645694-8d248bec-dce8-4ec6-8da9-cd3af4fbc985.png)

If someone could help me i will be forever greatfull.

**Comment by LostDragonist** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/57618

Need to use the 353 to 342 downgrader

**Comment by Belgianoo** [comment]
> 

Thank you, i wil try this.

**Comment by Belgianoo** [comment]
It worked ! Thank you !
