### ISSUE TITLE
Delete old version of wabbajack after updating

### ISSUE THREAD

**Issue by keatit71** [wabbajack-tools/wabbajack#1809]
It's annoying to me that after updating wabbajack won't delete it's old versions meaning I have to delete them manually 

When updating the previous version of wabbajack should be deleted.

Only alternative is to delete the old version manually.

**Comment by EzioTheDeadPoet** [comment]
it keeps only the last 3 versions in case the latest one has issues. so people have backups of older versions that work. all other older versions get deleted automatically.
