### ISSUE TITLE
Add some way to resume an installation.

### ISSUE THREAD

**Issue by lastrosade** [wabbajack-tools/wabbajack#1812]
When an install fails for whatever reason there is no visible way to resume the installation.

When I retry the installation wabbajack will rehash everything and rebuild all the BSAs.

There should be some DB or index of successfully built BSAs that wabbajack can just skip.
There should also be an option to skip checking the hashes if the modlist didn't get updated or only check the hashes of the new items.

in my case my internet dropped near the end of the installation of Aldrnari and wabbajack failed to connect to something thus stopping the install.

The whole hashing and building of BSAs takes hours with Aldrnari.

Thanks!

**Comment by EzioTheDeadPoet** [comment]
> in my case my internet dropped near the end of the installation of Aldrnari and wabbajack failed to connect to something thus stopping the install.

This step is done before any hashing when installing a list. And if a download has failed you don't enter the BSA building steps.
Since the whole installation gets cancelled.
