### ISSUE TITLE
 File hash check (-42) error (Oblivion's Through the valleys modlist)

### ISSUE THREAD

**Issue by Epoppys** [wabbajack-tools/wabbajack#1813]
Hi, everyone

I have Win 10 and i was trying to install the "Through the valleys's Oblivion modlist" using the 2.5.3.4 Wabbajack version and i cant get it to work. I tried copying the "Oblivion - meshes.bsa" manually but it didn´t work

Here it is the log:

0,86 - Wabbajack Build - d78c89e7023e64e51ffd6d6daf5440b3be79622c
0,87 - Running in E:\Escritorio\Juegos\Programas y carpetas\Wabbajack\2.5.3.4
0,95 - Detected Windows Version: 10.0.19043.0
0,95 - System settings - (6,9GB RAM) (3,9GB Page), Display: 1366 x 768 (2GB VRAM - VideoMemorySizeMb=9114)
0,95 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,98 - Getting new Wabbajack version list
1,19 - Steam: Found game The Elder Scrolls III: Morrowind (22320) at "E:\Games\SteamLibrary\steamapps\common\Morrowind"
1,19 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "E:\Games\SteamLibrary\steamapps\common\Oblivion"
1,2 - Steam: Found game The Elder Scrolls Online (306130) at "E:\Games\SteamLibrary\steamapps\common\Zenimax Online"
1,2 - Steam: Found game Paladins (444090) at "E:\Games\SteamLibrary\steamapps\common\Paladins"
1,2 - Steam: Found game Counter-Strike: Global Offensive (730) at "E:\Games\SteamLibrary\steamapps\common\Counter-Strike Global Offensive"
1,21 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
1,21 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
1,21 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
1,22 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
2,12 - Wabbajack Version: 2.5.3.4
2,67 - Build server is alive
2,68 - Build server is alive
2,68 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514
2,68 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514
23,47 - Starting to install Through The Valleys
23,49 - Cleaning VFS, this may take a bit of time
23,53 - Starting Installer Task
23,53 - Installation has Started
23,53 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514
24,07 - Configuring Processor
24,09 - Install Folder: E:\Games\Oblivion modded
24,09 - Downloads Folder: E:\Games\SteamLibrary\steamapps\common\Oblivion\downloads
24,09 - Game Folder: E:\Games\SteamLibrary\steamapps\common\Oblivion
24,09 - Wabbajack Folder: E:\Escritorio\Juegos\Programas y carpetas\Wabbajack\2.5.3.4
24,09 - Drive watcher is starting. Will warn at 8GB and error at 4GB
24,1 - Starting Drive watcher on E:\ currently 21,9GB free out of 930,1GB
24,1 - Validating Game ESMs
24,1 - Creating Output Folders
24,36 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
24,36 - Optimizing ModList
24,36 - Optimizing ModList directives
25,4 - Looking for files to delete
25,4 - Cleaning empty folders
25,84 - Looking for unmodified files
26,08 - Updating ModList
26,08 - Optimized 29791 directives to 29791 required
26,11 - Hashing Archives
26,11 - Looking for files to hash
26,28 - Found 443 total files, 228 matching filesize
26,47 - Downloading Missing Archives
26,47 - Missing 1 archives
26,48 - Getting Nexus API Key, if a browser appears, please accept
26,53 - Loading server whitelist
26,83 - Loaded permissions for 638 servers and 284 Google Drive files
26,83 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514
26,86 - Downloading Data_Oblivion - Meshes.bsa
65,77 - Hashed download is incorrect
65,79 - Loading for alternative to gZruVY5oikU=
66,08 - No alternative for gZruVY5oikU= could be found
66,15 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
66,15 - Hashing Remaining Archives
66,15 - Looking for files to hash
66,39 - Found 445 total files, 228 matching filesize
66,67 - Unable to download Data_Oblivion - Meshes.bsa (GameFileSourceDownloader+State|Oblivion|1.2.0416|data\oblivion - meshes.bsa)
66,67 - Cannot continue, was unable to download one or more archives
66,7 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514
67,01 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
67,27 - File hash check (-42) 3f7395880916f214aeaf39229c515800db749b024c19bd919d7f7e815ddf0514

**Comment by EzioTheDeadPoet** [comment]
Verify your game with steam and restart the installation.

**Comment by genthad** [comment]
could a solve problem? verfiyfing my games doesnt help.. i literally start it with steam
