### ISSUE TITLE
Morrowind MOISE - unable to download certain files

### ISSUE THREAD

**Issue by delperdj** [wabbajack-tools/wabbajack#1819]
**Describe the bug and Wabbajack log**

0.35 - Wabbajack Build - d78c89e7023e64e51ffd6d6daf5440b3be79622c
0.36 - Running in G:\Wabbajack\2.5.3.4
0.37 - Detected Windows Version: 10.0.19044.0
0.37 - System settings - (31.9GB RAM) (4.8GB Page), Display: 2560 x 1440 (9.8GB VRAM - VideoMemorySizeMb=10240)
0.37 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.37 - Outside of standard install folder, not updating
0.4 - Steam: Found no Regex matches in Steam Config at g:/steam\config\config.vdf
0.42 - Steam: Found game Chernobylite (1016800) at "G:\Steam\steamapps\common\Chernobylite"
0.42 - Steam: Found game Jump King (1061090) at "G:\Steam\steamapps\common\Jump King"
0.42 - Steam: Found game Inscryption (1092790) at "G:\Steam\steamapps\common\Inscryption"
0.42 - Steam: Found game Hardspace: Shipbreaker (1161580) at "G:\Steam\steamapps\common\Hardspace Shipbreaker"
0.42 - Steam: Found game Unravel (1225560) at "G:\Steam\steamapps\common\Unravel"
0.42 - Steam: Found game Unravel Two (1225570) at "G:\Steam\steamapps\common\UnravelTwo"
0.43 - Steam: Found game Mass Effect™: Andromeda (1238000) at "G:\Steam\steamapps\common\Mass Effect Andromeda"
0.43 - Steam: Found game It Takes Two (1426210) at "G:\Steam\steamapps\common\ItTakesTwo"
0.43 - Steam: Found game Escape Simulator (1435790) at "G:\Steam\steamapps\common\Escape Simulator"
0.43 - Steam: Found game Road 96 (1466640) at "G:\Steam\steamapps\common\Road 96"
0.43 - Steam: Found game Age of Empires IV (1466860) at "G:\Steam\steamapps\common\Age of Empires IV"
0.43 - Steam: Found game The Elder Scrolls III: Morrowind (22320) at "G:\Steam\steamapps\common\Morrowind"
0.43 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "G:\Steam\steamapps\common\Oblivion"
0.43 - Steam: Found game Steamworks Common Redistributables (228980) at "G:\Steam\steamapps\common\Steamworks Shared"
0.43 - Steam: Found game No Man's Sky (275850) at "G:\Steam\steamapps\common\No Man's Sky"
0.43 - Steam: Found game Sid Meier's Civilization VI (289070) at "G:\Steam\steamapps\common\Sid Meier's Civilization VI"
0.43 - Steam: Found game Fallout 4 (377160) at "G:\Steam\steamapps\common\Fallout 4"
0.43 - Steam: Found game Wallpaper Engine (431960) at "G:\Steam\steamapps\common\wallpaper_engine"
0.43 - Steam: Found game Surviving Mars (464920) at "G:\Steam\steamapps\common\Surviving Mars"
0.44 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "G:\Steam\steamapps\common\Skyrim Special Edition"
0.44 - Steam: Found game Chess Ultra (518060) at "G:\Steam\steamapps\common\Chess Ultra"
0.44 - Steam: Found game Satisfactory (526870) at "G:\Steam\steamapps\common\Satisfactory"
0.44 - Steam: Found game Dead Cells (588650) at "G:\Steam\steamapps\common\Dead Cells"
0.44 - Steam: Found game Between the Stars (727130) at "G:\Steam\steamapps\common\Between the Stars"
0.44 - Steam: Found game Breathedge (738520) at "G:\Steam\steamapps\common\Breathedge"
0.44 - Steam: Found game Shadow of the Tomb Raider (750920) at "G:\Steam\steamapps\common\Shadow of the Tomb Raider"
0.44 - Steam: Found game Mars Horizon (765810) at "G:\Steam\steamapps\common\Mars Horizon"
0.44 - Steam: Found game The Beast Inside (792300) at "G:\Steam\steamapps\common\The Beast Inside"
0.44 - Steam: Found game Age of Empires II: Definitive Edition (813780) at "G:\Steam\steamapps\common\AoE2DE"
0.44 - Steam: Found game The Forgotten City (874260) at "G:\Steam\steamapps\common\The Forgotten City"
0.44 - Steam: Found game Age of Empires III: Definitive Edition (933110) at "G:\Steam\steamapps\common\AoE3DE"
0.44 - Steam: Found game Bloons TD 6 (960090) at "G:\Steam\steamapps\common\BloonsTD6"
0.44 - Steam: Found game The Ascent (979690) at "G:\Steam\steamapps\common\The Ascent"
0.44 - Steam: Found game Chernobylite (1016800) at "g:/steam\steamapps\common\Chernobylite"
0.44 - Steam: Found game Jump King (1061090) at "g:/steam\steamapps\common\Jump King"
0.44 - Steam: Found game Inscryption (1092790) at "g:/steam\steamapps\common\Inscryption"
0.44 - Steam: Found game Hardspace: Shipbreaker (1161580) at "g:/steam\steamapps\common\Hardspace Shipbreaker"
0.44 - Steam: Found game Unravel (1225560) at "g:/steam\steamapps\common\Unravel"
0.44 - Steam: Found game Unravel Two (1225570) at "g:/steam\steamapps\common\UnravelTwo"
0.44 - Steam: Found game Mass Effect™: Andromeda (1238000) at "g:/steam\steamapps\common\Mass Effect Andromeda"
0.44 - Steam: Found game It Takes Two (1426210) at "g:/steam\steamapps\common\ItTakesTwo"
0.44 - Steam: Found game Escape Simulator (1435790) at "g:/steam\steamapps\common\Escape Simulator"
0.44 - Steam: Found game Road 96 (1466640) at "g:/steam\steamapps\common\Road 96"
0.44 - Steam: Found game Age of Empires IV (1466860) at "g:/steam\steamapps\common\Age of Empires IV"
0.44 - Steam: Found game The Elder Scrolls III: Morrowind (22320) at "g:/steam\steamapps\common\Morrowind"
0.44 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "g:/steam\steamapps\common\Oblivion"
0.44 - Steam: Found game Steamworks Common Redistributables (228980) at "g:/steam\steamapps\common\Steamworks Shared"
0.44 - Steam: Found game No Man's Sky (275850) at "g:/steam\steamapps\common\No Man's Sky"
0.44 - Steam: Found game Sid Meier's Civilization VI (289070) at "g:/steam\steamapps\common\Sid Meier's Civilization VI"
0.44 - Steam: Found game Fallout 4 (377160) at "g:/steam\steamapps\common\Fallout 4"
0.44 - Steam: Found game Wallpaper Engine (431960) at "g:/steam\steamapps\common\wallpaper_engine"
0.44 - Steam: Found game Surviving Mars (464920) at "g:/steam\steamapps\common\Surviving Mars"
0.44 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "g:/steam\steamapps\common\Skyrim Special Edition"
0.44 - Steam: Found game Chess Ultra (518060) at "g:/steam\steamapps\common\Chess Ultra"
0.44 - Steam: Found game Satisfactory (526870) at "g:/steam\steamapps\common\Satisfactory"
0.44 - Steam: Found game Dead Cells (588650) at "g:/steam\steamapps\common\Dead Cells"
0.44 - Steam: Found game Between the Stars (727130) at "g:/steam\steamapps\common\Between the Stars"
0.44 - Steam: Found game Breathedge (738520) at "g:/steam\steamapps\common\Breathedge"
0.45 - Steam: Found game Shadow of the Tomb Raider (750920) at "g:/steam\steamapps\common\Shadow of the Tomb Raider"
0.45 - Steam: Found game Mars Horizon (765810) at "g:/steam\steamapps\common\Mars Horizon"
0.45 - Steam: Found game The Beast Inside (792300) at "g:/steam\steamapps\common\The Beast Inside"
0.45 - Steam: Found game Age of Empires II: Definitive Edition (813780) at "g:/steam\steamapps\common\AoE2DE"
0.45 - Steam: Found game The Forgotten City (874260) at "g:/steam\steamapps\common\The Forgotten City"
0.45 - Steam: Found game Age of Empires III: Definitive Edition (933110) at "g:/steam\steamapps\common\AoE3DE"
0.45 - Steam: Found game Bloons TD 6 (960090) at "g:/steam\steamapps\common\BloonsTD6"
0.45 - Steam: Found game The Ascent (979690) at "g:/steam\steamapps\common\The Ascent"
0.45 - GOG: GOG was not found in the registry
0.45 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.47 - EpicGamesStore: Found game Darkest Dungeon II at "G:\Program Files\Epic Games\DarkestDungeonII"
0.47 - EpicGamesStore: Found game Far Cry 6 at "G:\Program Files\Epic Games\FarCry6"
0.47 - Origin: Found no Ids and Paths in the MFST files
0.48 - Origin: Found no Ids for use with the Api
0.75 - Wabbajack Version: 2.5.3.4
1.22 - Build server is alive
1.22 - Build server is alive
1.22 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
1.22 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
2.49 - Loading ModLists from GitHub
455.31 - Starting to install MOISE
455.32 - Cleaning VFS, this may take a bit of time
455.33 - Starting Installer Task
455.33 - Installation has Started
455.33 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
455.56 - Configuring Processor
455.57 - Install Folder: G:\Moise
455.57 - Downloads Folder: G:\Moise\Downloads
455.57 - Game Folder: G:\Steam\steamapps\common\Morrowind
455.57 - Wabbajack Folder: G:\Wabbajack\2.5.3.4
455.57 - Drive watcher is starting. Will warn at 8GB and error at 4GB
455.57 - Starting Drive watcher on G:\ currently 87.3GB free out of 931.5GB
455.57 - Validating Game ESMs
455.57 - Creating Output Folders
456.25 - Optimizing ModList
456.25 - Optimizing ModList directives
456.4 - Looking for files to delete
456.4 - Cleaning empty folders
456.49 - Looking for unmodified files
456.57 - Updating ModList
456.57 - Optimized 17496 directives to 17496 required
456.58 - Hashing Archives
456.58 - Looking for files to hash
457.23 - Found 7238 total files, 6 matching filesize
464.2 - Downloading Missing Archives
464.2 - Missing 205 archives
464.2 - Getting Nexus API Key, if a browser appears, please accept
464.9 - Logged into the nexus as MeDontKnow
464.9 - Nexus calls remaining: 10000 daily, 500 hourly
465.12 - Logged into the nexus as MeDontKnow
465.12 - Nexus calls remaining: 10000 daily, 500 hourly
465.13 - Loading server whitelist
465.27 - Loaded permissions for 642 servers and 284 Google Drive files
465.27 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
465.3 - Downloading UI Expansion v1.1-46071-1-1-1565640975.zip
465.3 - Downloading Vivec and Velothi Arkitektora  - ATLAS HQ-46266-1-0-1546272773.rar
465.3 - Downloading Vurt's Bitter Coast Trees II - Remastered and Optimized-46418-1-1551452907.7z
465.3 - Downloading Landscape Retexture 2K-42575-2-5.rar
465.31 - Downloading RR - Better Meshes V1.4-43266-1-4-1579806968.rar
465.31 - Downloading seagulldeathfix-43128-1-18.7z
465.32 - Downloading R-Zero's Random Replacers - Iron Towershield-44025-1-0.7z
465.36 - Downloading Nix-Hound Replacer 1.0-43620-1-0.7z
465.44 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
465.54 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
465.98 - Downloading MOAR_Meshes_1.05-44057-1-05.rar
466.35 - Downloading Kagouti-42523-1.rar
466.36 - Downloading Ingredients Mesh Replacer 2.2-44067-2-2.7z
466.72 - Downloading Dwemer Armoury-43335-0-95.7z
466.83 - Downloading Correct_UV_Rocks_1.5-46104-1-5-1579767969.7z
466.98 - Downloading Alit-42520-1.rar
467.07 - Downloading Aesthesia Groundcover - darker-46377-1-1557670851.7z
467.32 - Downloading Solstheim Tree Replacer II-37856-1-2-1592711914.7z
467.33 - Downloading Vurts Silt Strider Retexture-30696.rar
467.68 - Downloading Vurts_Lava_and_Smoke11a-28519.rar
467.89 - Downloading Vurt Mournhold Deadtrees-45770-1-0.zip
468.22 - Downloading Volendrung retexture-43330-1-0.rar
468.76 - Downloading Vivec and Velothi Arkitektora  - HQ-46266-2-0-1546272606.rar
469.25 - Downloading Vanilla Land v.1.1-45953-1-1.rar
469.9 - Downloading Telvanni - Arkitektora of Vvardenfell HQ - Bump Maps - Missing Glow Maps-43795-1-1555671296.7z
469.96 - Downloading AoVv Telvanni Bump Maps HQ-43530-1-0.7z
469.98 - Downloading AoVv Telvanni HQ-43530-1-1.7z
470.63 - Downloading Swamp Rocks - Default-45673-1-1.zip
471.37 - Downloading VSW_Solstheim_Graphical_Replacer_V2.1.0-46810-2-1-0-1584270620.7z
471.82 - Downloading Skeleton and Metal Sparks blood retexture-43359-1-0.7z
473.15 - Downloading Silverware Repolished-46385-1-3-1560408598.7z
473.26 - Downloading Sewer vanilla HQ-43144-1.rar
474.1 - Downloading SetInStone-21377.rar
474.82 - Downloading Mist Retexture-44322-1-0.7z
475.16 - Downloading Remiros' Ascadian Isles Trees - Vanilla-45779-2-1-1556198681.7z
475.22 - Downloading Redoran Arkitektora - HQ-46235-2-0-1545605818.rar
475.3 - Downloading Real Reflective Weapons - Iron-43077-1-3.7z
475.41 - Downloading R-Zero's Random Retextures - Quill-44025-1-0.7z
475.75 - Downloading Plant Life v2-1-37947-2-1.zip
475.77 - Downloading Pherim's Fire Fern and Fire Petal-43568-1-2.7z
476.14 - Downloading Saints and Tribunal Frescoes HQ (upd)-43810-1-0a.7z
476.7 - Downloading Melchior's Magnificent Manuscript-45626-1-2-1555374336.7z
477.66 - Downloading Tyddys Telvanni Fixes-43795-1.7z
477.66 - Downloading Lougians colovian helm fix-43795-1.7z
477.68 - Downloading JiFFY Morrowind UI Revamped-43922-1-06.zip
478.29 - Downloading Improved Weapon Meshes - Steel-43120-1-3.7z
478.31 - Downloading Kwama Egg sacs and Eggs Replacer-43555-1-1.7z
478.86 - Downloading HQ Textures-43520-1-0.7z
479.13 - Downloading Ordo Arkitektora HQ-43940-1-0.7z
479.18 - Downloading Hlaalu Arkitektora - HQ-46246-2-0-1545762177.rar
479.34 - Downloading 16x9 Version-39329-v1-0.zip
479.38 - Downloading Hackle-lo fixed-42784-1-0a.7z
479.4 - Downloading Guars-42521-1.rar
480.84 - Downloading Glow in the Dahrk-45886-2-11-1-1615063427.7z
481.2 - Downloading FULL DWM RTX HQ-44264-1-0.7z
483.36 - Downloading EKM Vanilla-Based Paper Lanterns v1.0-43837-v1-0.7z
483.64 - Downloading Dust adept helm retexture-43330-1-0.rar
485.24 - Downloading Urns Bump Mapped - HQ-43541-1-0.7z
485.47 - Downloading Darknut's Creature Textures TB-43421-1-0.zip
486.03 - Downloading Darknut's Creature Textures BM-43422-1-0.zip
487.3 - Downloading Darknut's Creature Texture addendum-43441-1-0.zip
487.35 - Downloading Darknut's Creature Textures-43420-1-0.zip
488.05 - Downloading Darknut's Better Clothes Textures-43423-1-0.7z
488.34 - Downloading DNArmorTex10241.2.zip-43416-1-2.zip
488.47 - Downloading Detailed Brooms_1.0-43528-1-0.rar
488.8 - Downloading Deadric Ruins -39125-3-1.zip
489.64 - Downloading HQ Textures-43486-1-0.zip
489.73 - Downloading Colovian helm and heavy leather boots retexture-43330-1-0.rar
490.06 - Downloading Main File-38369-1-0.7z
490.96 - Downloading Bloastpore retexture simple retexture-42384-1-2.rar
492.37 - Downloading Better Meshes 111-38170-1-11.7z
492.42 - Downloading Better Kegstands 1_1-37708-1-1.7z
493.08 - Downloading Better Barnacles-43605-.7z
493.72 - Downloading Ascadian Isles Plants-36810-1.rar
494.03 - Downloading Armors Retexture - Outlander Styles  HQ-44210-1-0.7z
494.06 - Downloading Animated Main Menu for Skyrim UI Overhaul for Morrowind-43341-1-0.zip
494.25 - Downloading Alternate Skies-42629-v1.7z
494.64 - Downloading Aesthesia groundcover-46377-1-1549880413.7z
494.81 - Downloading Aesthesia Strongholds 2k-46445-1-1552479237.7z
495.43 - Downloading TESPCD Plugin Conflict Detector-3874.zip
495.72 - Downloading Where are all birds going-43128-1-17.7z
495.79 - Downloading What Thieves Guild-47728-1-31-1592656468.zip
497.19 - Downloading Wey New Argonians (1.75)-43766-1-75.7z
497.45 - Downloading Waterfalls Tweaks-46271-1-0-1548330045.zip
497.7 - Downloading abotWaterlife126d-42417-1-26d-1577784021.7z
498.19 - Downloading Error fix-45941-1-0.rar
498.59 - Downloading Vurts Mournhold Trees 10a-35400.rar
498.65 - Downloading Vurt's Grazelands Trees v1.31-35368-.7z
499.24 - Downloading Vurts Bitter Coast Tree II v1dot1-37489-1.7z
499.96 - Downloading Voiced Vivec and Yakety Yagrum-40994-1-1.rar
500.15 - Downloading Psy_VGRCreatureEdition_1_2.7z
500.61 - Hashed download is incorrect
500.61 - Loading for alternative to 1zaFi6AMHJw=
500.95 - No alternative for 1zaFi6AMHJw= could be found
500.95 - Downloading Visual Pack Combined-44311-3-0.rar
501.06 - Downloading Vanilla-friendly West Gash Tree Replacer-44173-2-0.7z
501.45 - Downloading Merged and Compatibility Versions-43931-3-1-0-1600156439.7z
502.47 - Downloading Unique Jewelry Redone-46151-1-0-1541950623.7z
502.83 - Downloading Unique Finery Replacer v3dot2-25725-1.zip
503.6 - Downloading Ultimate Icon Replacer v1-36948-1.zip
503.81 - Downloading Ultimate Icon Replacer Lefty v1dot1 FIXED-36948-1.zip
504.03 - Downloading Trueflame-33432.rar
504.91 - Downloading Texture_Fix__Bloodmoon_1.1.7z
505.05 - Downloading Texture Fix 2.0.7z
505.06 - Downloading Texture Fix - Extended-46018-1-2-1565558085.7z
505.18 - Downloading TelvanniMeshImprovement1-2-1.zip-42343-1-2-1.zip
505.42 - Downloading Telvanni Fireplace Replacer-43232-1-0.rar
505.52 - Downloading Tamriel Data (HD)-44537-7-1-1579298818.7z
505.97 - Downloading Spell Scroll Text Overhaul V 1.1-42936-1-1.7z
506.21 - Downloading SIR_TBandBM_v3-19467.zip
506.45 - Downloading Darker Crates-42453-.7z
506.48 - Downloading Skip Tutorial 1_0-27266.zip
506.76 - Downloading Skies .IV-43311--IV.zip
507.27 - Downloading Shiny Septims - Dulled Version-42113-1-2.rar
507.3 - Downloading Scamp Replacer 1.0-44314-1-0.7z
507.43 - Downloading Robe Overhaul-43748-1-3.7z
507.54 - Downloading PPR_Normal-19600.zip
507.93 - Downloading PPR_Index Addon-19600.zip
508.26 - Downloading Project Atlas-45399-0-6-5-1583081881.7z
508.6 - Downloading -Pluginless Khajiit Head Pack--43110-1-0.7z
509.39 - Downloading Patch for Purists-45096-3-2-1-1575286395.7z
509.46 - Downloading Main file full package-39122-1-2.zip
510.52 - Downloading Psy_OMI-29906.7z
511.35 - Downloading ORR - Vanilla Glass-19882.zip
512.19 - Downloading New Best Bodies by Liztail - Clean-47678-3-3-1583853195.zip
512.47 - Downloading Netch Bump mapped-42851-1-1.rar
512.84 - Downloading Negative Lights Remover-42306-1-0.7z
513.56 - Downloading NastierCtong12-22601.rar
515.11 - Downloading Morrowind Optimization Patch-45384-8-0-1568378230.7z
516.13 - Downloading Ministry of truth Bump mapped-42921-1-0.rar
516.24 - Downloading razor-23825.rar
517.68 - Downloading Luminous Atronachs-42613-1-0.7z
518 - Downloading LLL - Optimal pack-45718-1-1.zip
518.48 - Downloading LFGT 1-0-29206.7z
519.59 - Downloading Long Live The Limeware - Retexture-44045-1-0.7z
519.82 - Downloading Long Live The Glassware - Retexture-44016-1-0.7z
521.06 - Downloading lgnpc_gnaar_mok_1.20.zip
521.77 - Downloading lgnpc_vivec_redoran_1.70.zip
521.82 - Downloading lgnpc_vfq_2.22.zip
522.02 - Downloading lgnpc_tel_mora_1.31.zip
522.4 - Downloading lgnpc_soul_sickness_patch.zip
522.6 - Downloading lgnpc_seyda_neen_2.10.zip
522.69 - Downloading lgnpc_secret_masters_1.31.zip
522.7 - Downloading lgnpc_paxredoran_1.30.zip
522.73 - Downloading lgnpc_nolore_1.10.zip
522.97 - Downloading lgnpc_khuul_2.30.zip
523.03 - Downloading lgnpc_indarys_1.60.zip
523.17 - Downloading lgnpc_hla_oad_1.40.zip
523.19 - Downloading lgnpc_aldruhn_1.30.zip
523.27 - Downloading lgnpc_ald_velothi_1.20.zip
523.41 - Downloading Less Generic Tribunal Fixed-44819-2.rar
523.44 - Downloading Less Generic Nerevarine v1_4-23335-1-4.zip
523.49 - Downloading Less_Generic_Bloodmoon_V1_3-23346-1-3.zip
523.57 - Downloading Improved Weapon Meshes - Ebony-43484-1-2.7z
523.86 - Downloading Improved Better Skulls-46012-2-6-1566053352.7z
524.81 - Downloading Idle Talk-46948-0-71-1586604370.zip
524.84 - Downloading HiRez Armors - Native Styles V2 Fixed and Optimized-47919-2-2-1589456393.7z
524.96 - Downloading 16x10 Version-39329-1.zip
525.03 - Downloading Great Service-47767-1-11-1592332753.zip
525.61 - Downloading flora_bush_01 replacer-1-3-42941-1-3.rar
525.64 - Downloading DMI_2017.07.15-43101-2017-07-15.zip
526.03 - Downloading Dunmer Lanterns Replacer-43219-10-2-1570655849.7z
526.04 - Downloading DjangosRugsandTaps1_6-36872-1-6.rar
526.39 - Downloading Djangos Dialogue 1.42-47253-1-42-1592244472.zip
527.26 - Downloading DjangosDialogue1_3-37328-1-3.zip
528.02 - Downloading Mournhold LOD V1.0-43255-1-0.zip
528.05 - Downloading Tapestries -fixed archive--22551-1-1.zip
528.28 - Downloading WIP Detailed Correct UV Rocks-44321-0-92.7z
528.45 - Downloading DelayedDBAttacksTest-14891-2-1.zip
528.53 - Downloading DNWeaponsComplete.zip-43418-1-0.zip
529.28 - Downloading Daedric Lord Armor Morrowind Edition-44081-1-03-1541699966.7z
530.18 - Downloading Daedric Lord Armor Face of God-45037-1-1a.7z
530.92 - Downloading Crabmeat ingredient replacer-43387-1-0.7z
531.39 - Downloading Correct UV Mudcrab-42130-1-0.7z
532.16 - Downloading ContainerWeightMaxed-45698-1-1a.zip
532.4 - Downloading Concept Art Ghostfence Replacer-43316-1-2.zip
532.54 - Downloading Concept Art Based Loading Screens 1.0-43603-1-0.rar
532.78 - Downloading PB Cliff Racer Replacer 2.0-48978-2-0-1603655038.zip
532.96 - Downloading CCR Normal v2-21837-1.zip
533.35 - Downloading Bloated Caves-43141-1-2.7z
533.4 - Downloading Bitter Coast Sounds Plugin-42988-.zip
534.21 - Downloading Better_Clothes-42262-1-1.zip
534.65 - Downloading Better Waterfalls-45424-1-1.7z
534.69 - Downloading Better Robes ENG-42773-0-3-1.7z
534.98 - Downloading Better Heads-42226-1-1.rar
537.62 - Downloading Better Dialogue Font-36873.7z
537.74 - Downloading Better Bodies-42399-2-2.rar
537.83 - Downloading Morrowind Better Blood-33426.7z
538.44 - Downloading BetterAlmalexia-23388.rar
538.61 - Downloading BB Dwarven Spectre-29671.7z
539.05 - Downloading SWGs Banners-21405.zip
539.72 - Downloading Psy_Azura_Replacer1.7z
540.16 - Hashed download is incorrect
540.16 - Loading for alternative to cvgYvhqGNIE=
540.27 - No alternative for cvgYvhqGNIE= could be found
540.27 - Downloading AST redware texture replacer-50163-1-0-1629380676.7z
540.39 - Downloading AST beds remastered-45206-1-0.7z
541.69 - Downloading Ash Vampire Reworked-43633-b0-1.rar
541.8 - Downloading Arukinns Better Books and Scrolls-43100-1-0.7z
542.21 - Downloading Arukinns Better Banners Signs and Signposts English-41658-1-1.7z
542.34 - Downloading Apel rain replacer v 1_0-42555-1-0.rar
542.74 - Downloading Apel lighhouse retexture v2-42532-v2.rar
542.77 - Downloading Apel fire retexture v2-42554-v2.rar
542.99 - Downloading Apels Bitter Coast Region Retexture v1-42661-v1.rar
543.43 - Downloading AOF_Containers-32427.rar
543.43 - Downloading Animation Compilation 0.40-43982-0-40.7z
543.47 - Downloading Wrye Mash 2019 - x64 -  manual installation archive.-45439-v100-1572029142.7z
543.66 - Downloading mlox.exe
544.56 - Downloading MWSE-Update for Nightly Builds-45468-nightly-builds-1624232443.zip
544.62 - Downloading Morrowind.ini
544.63 - Hashed download is incorrect
544.63 - Loading for alternative to pFPJ9f2pE/g=
544.64 - Downloading MGE XE Manual Install-41102-0-11-6-1560626592.7z
544.65 - Downloading Morrowind Code Patch-19510-2-4.7z
544.73 - No alternative for pFPJ9f2pE/g= could be found
544.73 - Downloading Mod.Organizer-2.4.2.7z
549.85 - Hashing Remaining Archives
549.85 - Looking for files to hash
550.19 - Found 7443 total files, 209 matching filesize
550.22 - Unable to download Morrowind.ini (GameFileSourceDownloader+State|Morrowind|1.6.1820|morrowind.ini)
550.22 - Unable to download Psy_Azura_Replacer1.7z (HTTPDownloader+State|https://www.moddb.com/addons/start/52259)
550.22 - Unable to download Psy_VGRCreatureEdition_1_2.7z (HTTPDownloader+State|https://www.moddb.com/addons/start/52262)
550.22 - Cannot continue, was unable to download one or more archives
550.22 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9
550.26 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
550.39 - File hash check (-42) 0a7815eab3d799aeacc544cf53052edb8ebe0fc2a02a143dfeb41c0f96c050c9

**Comment by erri120** [comment]
go to the support channel for the MOISE modlist https://discord.gg/NdmGpGzqg8
