### ISSUE TITLE
Gamepass Support for Stardew Valley

### ISSUE THREAD

**Issue by Drazden** [wabbajack-tools/wabbajack#1822]
**Is your feature request related to a problem? Please describe.**

Recently, SMAPI for Stardew Valley has begun to support Gamepass installations. This means that wabbajack lists can now be successfully installed with these versions. However, as traditionally we havent supported gamepass, Wabbajack cant actually detect the installed gamepass version and requires the steam or gog version to be present.

**Describe the solution you'd like**

Basic support for gamepass titles so wabbajack can detect SDV for gamepass.

**Describe alternatives you've considered**

As the gamepass userbase is likely very small, this could just be shelved.

**Additional context**

Check the stardew valley discord channel, or contact Yagisan or Myself.

**Comment by erri120** [comment]
GameFinder supports Gamepass games so WJ does as well. Just need the ID for the game
