### ISSUE TITLE
File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f

### ISSUE THREAD

**Issue by EllisHammond** [wabbajack-tools/wabbajack#1850]
Downloading Living Skyrim Mod Pack

0.26 - Wabbajack Build - f9f0ecdd80ef88be26f63b7ece801f0f3deb0961
0.26 - Running in D:\Skyrim Mash\WabbJack\2.5.3.5
0.27 - Detected Windows Version: 10.0.19043.0
0.27 - System settings - (31.8GB RAM) (4.8GB Page), Display: 2560 x 1440 (7.8GB VRAM - VideoMemorySizeMb=10240)
0.27 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.28 - Getting new Wabbajack version list
0.29 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key appid
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key name
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key installdir
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key LastUpdated
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key SizeOnDisk
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key BytesToDownload
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key BytesDownloaded
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key BytesToStage
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_218620.acf does not contain a value with key BytesStaged
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key appid
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key name
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key installdir
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key LastUpdated
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key SizeOnDisk
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key BytesToDownload
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key BytesDownloaded
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key BytesToStage
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_221100.acf does not contain a value with key BytesStaged
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key appid
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key name
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key installdir
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key LastUpdated
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key SizeOnDisk
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key BytesToDownload
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key BytesDownloaded
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key BytesToStage
0.3 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_228380.acf does not contain a value with key BytesStaged
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key appid
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key name
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key installdir
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key LastUpdated
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key SizeOnDisk
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key BytesToDownload
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key BytesDownloaded
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key BytesToStage
0.31 - Steam: ACF Manifest at D:\SteamGames\steamapps\appmanifest_794260.acf does not contain a value with key BytesStaged
0.31 - Steam: Found game Vermillion (1608400) at "C:\Program Files (x86)\Steam\steamapps\common\Vermillion"
0.31 - Steam: Found game Grim Dawn (219990) at "C:\Program Files (x86)\Steam\steamapps\common\Grim Dawn"
0.31 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0.31 - Steam: Found game SteamVR (250820) at "C:\Program Files (x86)\Steam\steamapps\common\SteamVR"
0.31 - Steam: Found game Barony (371970) at "C:\Program Files (x86)\Steam\steamapps\common\Barony"
0.31 - Steam: Found game VRChat (438100) at "C:\Program Files (x86)\Steam\steamapps\common\VRChat"
0.31 - Steam: Found game Beat Saber (620980) at "C:\Program Files (x86)\Steam\steamapps\common\Beat Saber"
0.31 - Steam: Found game Blade & Sorcery (629730) at "C:\Program Files (x86)\Steam\steamapps\common\Blade & Sorcery"
0.31 - Steam: Found game SURV1V3 (722180) at "C:\Program Files (x86)\Steam\steamapps\common\SURV1V3"
0.31 - Steam: Found game Phasmophobia (739630) at "C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia"
0.31 - Steam: Found game Last Epoch (899770) at "C:\Program Files (x86)\Steam\steamapps\common\Last Epoch"
0.31 - Steam: Found game Among Us (945360) at "C:\Program Files (x86)\Steam\steamapps\common\Among Us"
0.31 - Steam: Found game Terraria (105600) at "D:\SteamGames\steamapps\common\Terraria"
0.31 - Steam: Found game New World (1063730) at "D:\SteamGames\steamapps\common\New World"
0.31 - Steam: Found game Ready or Not (1144200) at "D:\SteamGames\steamapps\common\Ready Or Not"
0.31 - Steam: Found game DEVOUR (1274570) at "D:\SteamGames\steamapps\common\Devour"
0.31 - Steam: Found game Battlefield™ 2042 (1517290) at "D:\SteamGames\steamapps\common\Battlefield 2042"
0.31 - Steam: Found game Football Manager 2022 (1569040) at "D:\SteamGames\steamapps\common\Football Manager 2022"
0.31 - Steam: Found game Muck (1625450) at "D:\SteamGames\steamapps\common\Muck"
0.31 - Steam: Found game Crab Game (1782210) at "D:\SteamGames\steamapps\common\Crab Game"
0.33 - Steam: Found game The Elder Scrolls III: Morrowind (22320) at "D:\SteamGames\steamapps\common\Morrowind"
0.33 - Steam: Found game Kenshi (233860) at "D:\SteamGames\steamapps\common\Kenshi"
0.33 - Steam: Found game SimCity 4 Deluxe (24780) at "D:\SteamGames\steamapps\common\SimCity 4 Deluxe"
0.33 - Steam: Found game Rocket League (252950) at "D:\SteamGames\steamapps\common\rocketleague"
0.33 - Steam: Found game Cities: Skylines (255710) at "D:\SteamGames\steamapps\common\Cities_Skylines"
0.33 - Steam: Found game Age of Mythology: Extended Edition (266840) at "D:\SteamGames\steamapps\common\Age of Mythology"
0.33 - Steam: Found game RimWorld (294100) at "D:\SteamGames\steamapps\common\RimWorld"
0.33 - Steam: Found game Rec Room (471710) at "D:\SteamGames\steamapps\common\RecRoom"
0.33 - Steam: Found game Mount & Blade: Warband (48700) at "D:\SteamGames\steamapps\common\MountBlade Warband"
0.33 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\SteamGames\steamapps\common\Skyrim Special Edition"
0.33 - Steam: Found game Foxhole (505460) at "D:\SteamGames\steamapps\common\Foxhole"
0.33 - Steam: Found game Total War: WARHAMMER II (594570) at "D:\SteamGames\steamapps\common\Total War WARHAMMER II"
0.33 - Steam: Found game STAR WARS™ Jedi Knight II: Jedi Outcast™ (6030) at "D:\SteamGames\steamapps\common\Jedi Outcast"
0.33 - Steam: Found game Splitgate (677620) at "D:\SteamGames\steamapps\common\Splitgate"
0.33 - Steam: Found game The Elder Scrolls V: Skyrim (72850) at "D:\SteamGames\steamapps\common\Skyrim"
0.33 - Steam: Found game Valheim (892970) at "D:\SteamGames\steamapps\common\Valheim"
0.33 - Steam: Found game Vermillion (1608400) at "c:/program files (x86)/steam\steamapps\common\Vermillion"
0.33 - Steam: Found game Grim Dawn (219990) at "c:/program files (x86)/steam\steamapps\common\Grim Dawn"
0.33 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.33 - Steam: Found game SteamVR (250820) at "c:/program files (x86)/steam\steamapps\common\SteamVR"
0.33 - Steam: Found game Barony (371970) at "c:/program files (x86)/steam\steamapps\common\Barony"
0.33 - Steam: Found game VRChat (438100) at "c:/program files (x86)/steam\steamapps\common\VRChat"
0.33 - Steam: Found game Beat Saber (620980) at "c:/program files (x86)/steam\steamapps\common\Beat Saber"
0.33 - Steam: Found game Blade & Sorcery (629730) at "c:/program files (x86)/steam\steamapps\common\Blade & Sorcery"
0.33 - Steam: Found game SURV1V3 (722180) at "c:/program files (x86)/steam\steamapps\common\SURV1V3"
0.33 - Steam: Found game Phasmophobia (739630) at "c:/program files (x86)/steam\steamapps\common\Phasmophobia"
0.33 - Steam: Found game Last Epoch (899770) at "c:/program files (x86)/steam\steamapps\common\Last Epoch"
0.33 - Steam: Found game Among Us (945360) at "c:/program files (x86)/steam\steamapps\common\Among Us"
0.33 - GOG: GOG was not found in the registry
0.33 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.36 - EpicGamesStore: Found game Assassin's Creed: Valhalla at "C:\Program Files\Epic Games\AssassinsCreedValhalla"
0.36 - EpicGamesStore: Found game Trackmania at "C:\Program Files\Epic Games\TrackmaniaNext"
0.36 - EpicGamesStore: Found game Alien: Isolation at "C:\Program Files\Epic Games\AlienIsolation"
0.36 - Origin: InstallPath for Origin.OFR.50.0001523 does not exist at C:\Program Files\EA Games\STAR WARS Battlefront II
0.8 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Sports\FIFA 19 for Game Origin.OFR.50.0002663
0.8 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Sports\FIFA 19 for Game Origin.OFR.50.0002663
0.8 - Origin: Game Origin.OFR.50.0002663 was found using the Api but has no Path
0.9 - Wabbajack Version: 2.5.3.5
1.04 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\Zachtronics\SHENZHEN IO for Game Origin.OFR.50.0002891
1.04 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\Zachtronics\SHENZHEN IO for Game Origin.OFR.50.0002891
1.04 - Origin: Game Origin.OFR.50.0002891 was found using the Api but has no Path
1.13 - Build server is alive
1.13 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
1.28 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\STAR WARS Battlefront II for Game Origin.OFR.50.0001523
1.28 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\STAR WARS Battlefront II for Game Origin.OFR.50.0001523
1.28 - Origin: Game Origin.OFR.50.0001523 was found using the Api but has no Path
1.34 - Build server is alive
1.34 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
1.5 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\Numantian Games\They Are Billions for Game Origin.OFR.50.0003306
1.5 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\Numantian Games\They Are Billions for Game Origin.OFR.50.0003306
1.5 - Origin: Game Origin.OFR.50.0003306 was found using the Api but has no Path
1.5 - Origin: Found game KINGSTON PREORDER EDITION (WEST EU) - PC - WW (Origin.OFR.50.0004498) at "D:\SteamGames\steamapps\common\Battlefield 2042"
1.5 - Origin: Found game FIFA 19 Ultimate Edition (Premier) - PC - WW (Origin) (Origin.OFR.50.0002663) at ""
1.5 - Origin: Found game SHENZHEN I/O - PC - WW (Origin) (Origin.OFR.50.0002891) at ""
1.5 - Origin: Found game Star Wars Battlefront II: Standard Edition - PC - ROW (Origin) (Origin.OFR.50.0001523) at ""
1.5 - Origin: Found game They Are Billions - PC - WW - (Origin) (Origin.OFR.50.0003306) at ""
8.33 - Starting to install Living Skyrim 3
8.34 - Cleaning VFS, this may take a bit of time
8.39 - Starting Installer Task
8.39 - Installation has Started
8.39 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
8.78 - Configuring Processor
8.79 - Install Folder: D:\Skyrim Mash\Living Skyrim
8.79 - Downloads Folder: D:\Skyrim Mash\Living Skyrim\downloads
8.79 - Game Folder: D:\SteamGames\steamapps\common\Skyrim Special Edition
8.79 - Wabbajack Folder: D:\Skyrim Mash\WabbJack\2.5.3.5
8.79 - Drive watcher is starting. Will warn at 8GB and error at 4GB
8.79 - Starting Drive watcher on D:\ currently 290.9GB free out of 931.5GB
8.79 - Validating Game ESMs
8.8 - Creating Output Folders
8.89 - Optimizing ModList
8.89 - Optimizing ModList directives
11.93 - Looking for files to delete
11.95 - Cleaning empty folders
13.12 - Looking for unmodified files
13.85 - Updating ModList
13.85 - Optimized 291932 directives to 291932 required
13.91 - Hashing Archives
13.91 - Looking for files to hash
13.98 - Found 1163 total files, 1134 matching filesize
14.15 - Downloading Missing Archives
14.16 - Missing 4 archives
14.16 - Getting Nexus API Key, if a browser appears, please accept
14.5 - Logged into the nexus as mynameispingu
14.5 - Nexus calls remaining: 8884 daily, 500 hourly
14.7 - Logged into the nexus as mynameispingu
14.7 - Nexus calls remaining: 8884 daily, 500 hourly
14.7 - Loading server whitelist
14.96 - Loaded permissions for 649 servers and 284 Google Drive files
14.96 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
14.99 - Downloading LS3 SSELODGen Output 3.0.0.7z
14.99 - Downloading LS3 DynDOLOD Output 3.7.0.7z
14.99 - Downloading LS3 Grass Cache 3.7.0.7z
14.99 - Downloading The Great Town of Karthwasten Patch Collection-37471-2-0-1602375433.7z
15.31 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
167.18 - Loading for alternative to ZoFwChVFnnU=
167.52 - No alternative for ZoFwChVFnnU= could be found
192.29 - Loading for alternative to Qz5nRCOoSkY=
192.58 - No alternative for Qz5nRCOoSkY= could be found
308.87 - Loading for alternative to rzRYtK/MQkY=
308.96 - No alternative for rzRYtK/MQkY= could be found
309.06 - Hashing Remaining Archives
309.06 - Looking for files to hash
309.13 - Found 1163 total files, 1135 matching filesize
335.59 - Unable to download LS3 DynDOLOD Output 3.7.0.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/LS3 DynDOLOD Output 3.7.0.7z_9b754cec-0a86-4b35-801b-a5b88d935efc)
335.59 - Unable to download LS3 Grass Cache 3.7.0.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/LS3 Grass Cache 3.7.0.7z_1b18e31d-915c-40b8-a798-fcbb2e391fcd)
335.59 - Unable to download LS3 SSELODGen Output 3.0.0.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/LS3 SSELODGen Output 3.0.0.7z_589e52ca-9d4e-4648-ae1f-603a517aaae3)
335.59 - Cannot continue, was unable to download one or more archives
335.59 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f
335.61 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
335.81 - File hash check (-42) a16aeffa732ee3091623f0418eb1b4c86eff0c9b22a35423f06afbb7f804935f

**Comment by erri120** [comment]
335.59 - Cannot continue, was unable to download one or more archives

Check with modlist support, one archive failed to download.
