### ISSUE TITLE
White screen when try to log in LL

### ISSUE THREAD

**Issue by Jiudp** [wabbajack-tools/wabbajack#1870]
please someone help me
i use windows 10 21h2
last version wabbjack
already tried to use vpn

first i click in login
![image](https://user-images.githubusercontent.com/99374103/153781360-89ae177a-83bf-4d30-a301-76cda89d9efe.png)

then
![image](https://user-images.githubusercontent.com/99374103/153781376-a2f98c13-4ce9-4bd1-8b15-d527beb296be.png)

and withe screen
![image](https://user-images.githubusercontent.com/99374103/153781404-51967c54-cf22-4a98-90cf-bdbc18c35760.png)

Log:
[Wabbajack 2022-02-11 19_44_55.log](https://github.com/wabbajack-tools/wabbajack/files/8056964/Wabbajack.2022-02-11.19_44_55.log)

**Comment by Drazden** [comment]
This is an issue with the loverslab api, not wabbajack. Unfortunately their API is not functional right now.

**Comment by Jiudp** [comment]
ohh, thank you so much, I had no idea about that

Em dom, 13 de fev de 2022 21:11, Drazden ***@***.***>
escreveu:

**Comment by Jiudp** [comment]
I partially solved the problem by downloading an older version of wabbajack
and using the version of tsukiro compatible with the old version of
wabbajack, looks like they changed the mods address and domain something
like that

Em dom, 13 de fev de 2022 21:34, Jiudp's Channel ***@***.***>
escreveu:
