### ISSUE TITLE
[Request] Show a "# BSA archives remaining" during the "Building BSAs" stage of the installation.

### ISSUE THREAD

**Issue by CrazieIvan** [wabbajack-tools/wabbajack#1892]
Hello, 

If you've gone through the Aldrnari installation, you probably have an idea how long the BSA building stage takes.  It only shows a file counter for each individual BSA which resets when a new BSA starts building, but it doesn't show the number of remaining BSAs.  Would it be possible to add that?  That would be immensely helpful.  

Thank you very much!

**Comment by OliM9595** [comment]
This would be great. At the moment you just don't know how many you have left and need to go though the log to get a rough estimate.
