### ISSUE TITLE
[Request] Delete or move unused mods in/from download folder

### ISSUE THREAD

**Issue by deadcode0815** [wabbajack-tools/wabbajack#1906]
Downloading mods for a modlist (over several versions of modlist) leads to a (over)growing downloadfolder size. Old and unused mods never get deleted and consume more and more drive space.

It would be nice to have a feature to move mods needed for a particular modlist to another folder.

I know I could download mods needed for a modlist to a new empty folder, but I want to avoid that.

A feature like "deleting all unused mods" comes in mind, but maybe some of the unused mods are used for another modlist...

I want to finally achieve that I can create a pack (downloaded mods + wabbajackfile) to regenerate the list whenever I want to and put them on my "long time storage"

**Comment by Unnoen** [comment]
This is something I wanted to tackle with the 3.0 UI update.
It may not be in the initial release, but it's definitely something I want to do.

A potential problem though is that if you use a "global" downloads folder, moving mods for one list to another folder would likely mean that another list is now missing some mods.

**Comment by deadcode0815** [comment]
I'm totally aware about other mods "missing" some files after moving mods out of the global download folder.

**Comment by Xetaxheb** [comment]
create a text cache file in %appdata%/wabbajack
assign wabbajack installs a uuid on install
record uuid associated list of zips downloaded in text cache (as well as install+version name and original location?)

"Clean unused mods" button
read text cache and present two column list of ("packs zips to keep" | "packs zips to ignore/delete") with move left/right arrows
parse downloads folder being cleaned to index filenames
remove matches with "packs zips to keep"
delete remaining indexes

maybe throw a step in there of a little file list with sizes and names to confirm/oversee what's going to be deleted and uncheck ones to keep


could even have an "import .wabbajack file info" button if .wabbajack files have enough data to reconstruct a text cache entry, aka can infer what zips get downloaded by a wabbajack install;; for importing existing installs info or for keeping downloads a pack you have yet to install (but are looking at) might use
