### ISSUE TITLE
Modlist installation failed

### ISSUE THREAD

**Issue by dacic-master** [wabbajack-tools/wabbajack#1917]
This is the log:

9.34 - Getting upgrades list
10.53 - File hash check (-42) 93104609b5d9c7f42fd855a8cdadb5d5fd18bbe25c6b5f122effb29a153b69ad
10.61 - Downloading Data_ccQDRSSE001-SurvivalMode.esl
10.61 - Downloading Data_ccBGSSSE037-Curios.bsa
10.61 - Downloading Data_ccBGSSSE001-Fish.bsa
10.61 - Downloading Data_ccBGSSSE025-AdvDSGS.esm
10.61 - Downloading Data_ccBGSSSE025-AdvDSGS.bsa
10.61 - Downloading Data_ccQDRSSE001-SurvivalMode.bsa
10.61 - Downloading Data_ccBGSSSE001-Fish.esm
10.61 - Downloading Data_ccBGSSSE037-Curios.esl
10.63 - Hashed download is incorrect
10.63 - Loading for alternative to tMBpj6hFsf8=
10.64 - No alternative for tMBpj6hFsf8= could be found
10.64 - Downloading Data_Update.esm
10.64 - Hashed download is incorrect
10.64 - Loading for alternative to P4vwTZ48vtU=
10.64 - No alternative for P4vwTZ48vtU= could be found
10.64 - Downloading Data_Skyrim.esm
10.65 - Hashed download is incorrect
10.65 - Loading for alternative to aSqpPvCAKbA=
10.65 - No alternative for aSqpPvCAKbA= could be found
10.65 - Downloading Data_Skyrim - Sounds.bsa
10.67 - Hashed download is incorrect
10.67 - Loading for alternative to 2LsvJHFWOhg=
10.67 - No alternative for 2LsvJHFWOhg= could be found
10.67 - Downloading Data_Skyrim - Shaders.bsa
10.91 - Hashed download is incorrect
10.91 - Loading for alternative to gVQKrJZltug=
10.91 - No alternative for gVQKrJZltug= could be found
10.91 - Downloading Data_Skyrim - Misc.bsa
11.03 - Hashed download is incorrect
11.03 - Loading for alternative to w7YJ2li+67E=
11.03 - No alternative for w7YJ2li+67E= could be found
11.03 - Downloading Data_Skyrim - Meshes1.bsa
11.92 - Hashed download is incorrect
11.92 - Loading for alternative to SwnAPr6pbzg=
11.92 - No alternative for SwnAPr6pbzg= could be found
11.92 - Downloading Data_Skyrim - Meshes0.bsa
12.66 - Hashed download is incorrect
12.66 - Loading for alternative to bTGCQi1fCH8=
12.66 - No alternative for bTGCQi1fCH8= could be found
12.66 - Downloading Data_Skyrim - Interface.bsa
13.92 - Hashed download is incorrect
13.92 - Loading for alternative to l/34Syb1rXg=
13.92 - No alternative for l/34Syb1rXg= could be found
13.92 - Downloading Data_HearthFires.esm
14 - Hashed download is incorrect
14 - Loading for alternative to XlKELPX7jog=
14 - No alternative for XlKELPX7jog= could be found
14 - Downloading Data_Dragonborn.esm
15.43 - Hashed download is incorrect
15.43 - Loading for alternative to 7ZEj5ntJZIc=
15.43 - No alternative for 7ZEj5ntJZIc= could be found
15.43 - Downloading Data_Dawnguard.esm
15.45 - Hashed download is incorrect
15.45 - Loading for alternative to F76LaGyCAJA=
15.45 - No alternative for F76LaGyCAJA= could be found
15.45 - Downloading SkyrimSE.exe
15.91 - Hashed download is incorrect
15.91 - Loading for alternative to v593yGFgPDo=
15.91 - No alternative for v593yGFgPDo= could be found
16.06 - Hashed download is incorrect
16.06 - Loading for alternative to oct60LUJHOc=
16.06 - No alternative for oct60LUJHOc= could be found
16.26 - Hashed download is incorrect
16.26 - Loading for alternative to L2b/YNPnYDg=
16.26 - No alternative for L2b/YNPnYDg= could be found
17.73 - Hashed download is incorrect
17.73 - Loading for alternative to TxUe36eG4W0=
17.73 - No alternative for TxUe36eG4W0= could be found
17.91 - Hashed download is incorrect
17.91 - Loading for alternative to TvzBPkbzJjI=
17.91 - No alternative for TvzBPkbzJjI= could be found
26.29 - Hashed download is incorrect
26.29 - Loading for alternative to oIYZPu4jH2g=
26.29 - No alternative for oIYZPu4jH2g= could be found
26.36 - Hashed download is incorrect
26.36 - Loading for alternative to tkLxNtnmNYY=
26.36 - No alternative for tkLxNtnmNYY= could be found
32.65 - Hashed download is incorrect
32.65 - Loading for alternative to 6ILjbi2XOOA=
32.65 - No alternative for 6ILjbi2XOOA= could be found
32.7 - Hashing Remaining Archives
32.7 - Looking for files to hash
32.79 - Found 824 total files, 551 matching filesize
32.97 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|skyrimse.exe)
32.97 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dawnguard.esm)
32.97 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\dragonborn.esm)
32.97 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\hearthfires.esm)
32.97 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - interface.bsa)
32.97 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - meshes0.bsa)
32.97 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - meshes1.bsa)
32.97 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - misc.bsa)
32.97 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - shaders.bsa)
32.97 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim - sounds.bsa)
32.97 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\skyrim.esm)
32.97 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\update.esm)
32.97 - Unable to download Data_ccBGSSSE001-Fish.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse001-fish.bsa)
32.97 - Unable to download Data_ccBGSSSE001-Fish.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse001-fish.esm)
32.97 - Unable to download Data_ccBGSSSE025-AdvDSGS.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse025-advdsgs.bsa)
32.97 - Unable to download Data_ccBGSSSE025-AdvDSGS.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse025-advdsgs.esm)
32.97 - Unable to download Data_ccBGSSSE037-Curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse037-curios.bsa)
32.97 - Unable to download Data_ccBGSSSE037-Curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse037-curios.esl)
32.97 - Unable to download Data_ccQDRSSE001-SurvivalMode.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccqdrsse001-survivalmode.bsa)
32.97 - Unable to download Data_ccQDRSSE001-SurvivalMode.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccqdrsse001-survivalmode.esl)
32.98 - Cannot continue, was unable to download one or more archives
32.98 - File hash check (-42) 93104609b5d9c7f42fd855a8cdadb5d5fd18bbe25c6b5f122effb29a153b69ad
32.99 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
34.48 - File hash check (-42) 93104609b5d9c7f42fd855a8cdadb5d5fd18bbe25c6b5f122effb29a153b69ad

**Comment by EzioTheDeadPoet** [comment]
Verify Your game installation and properly install all the Creation Club (Anniversary Edition DLC) after buying it.
This is a user error not a software error.
