### ISSUE TITLE
Witcher: Enhanced Edition Support

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#1958]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like Wabbajack to be able to compile lists for Witcher: Enhanced Edition using MO2's Simple Games plugin, which already supports the game.

**Describe alternatives you've considered**

N/A

**Additional context**

Thanks for all you do!

**Comment by EzioTheDeadPoet** [comment]
Since the 3.0 looks around the corner I will work on adding it to 3.0 once I get time and think about doing it. 👍
