### ISSUE TITLE
"Unknown Error" in Launcher when launched in C:\ or any root directory

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#1966]
**Describe the bug**

Recent Updates fixed the more common causes for Unknown Errors, but now there seems to be a new/old but overlooked (due to rare occurrence). This new error involves downloading and running the main/launcher Wabbajack.exe in any direct root directory `X:\Wabbajack.exe`

**Additional Context**

Ideally this error would be checked for and a message displayed on how to fix it or a routine could be created, that would be offered to run with the message:

Automatically copy the Wabbajack.exe into a folder like `X:\Wabbajack\Wabbajack.exe` and either remove and/or make a shortcut to where it fist was launched.

The later might be over engineered when a message could do the trick, but the message and routine could be used for any folder known to cause issues with Wabbajack.

**Wabbajack Version**

2.5.3.22

**Comment by richardcocks** [comment]
Thank you, I had the same issue trying to run it from my %downloads% folder.

Copying to %programfiles%\wabbajack was slightly more successful, enough to get a permission denied error.

Finally copying to %appdata%\wabbajack was actually a success.

**Comment by EzioTheDeadPoet** [comment]
It is recommended to have it in your drives root directory.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 6/19/22, 14:20 richardcocks ***@***.***> wrote:

   
  Thank you, I had the same issue trying to run it from my %downloads% folder. 
  Copying to %programfiles%\wabbajack was slightly more successful, enough to get a permission denied error. 
  Finally copying to %appdata%\wabbajack was actually a success.

**Comment by sophimoo** [comment]
Not sure how no-one else is having this issue but it will not launch in any other folder other than the C:/ this feels a bit ridiculous as I do not like having random application folders cluttering my home directory

**Comment by EzioTheDeadPoet** [comment]
You can create any folder tree there as long as it isn't in a Windows managed folder (read user folders, programm files, etc).
This is because starting in any of those folders makes issues when running the app more likely.
