### ISSUE TITLE
Personalise installer's look

### ISSUE THREAD

**Issue by tstavrianos** [wabbajack-tools/wabbajack#20]
**Is your feature request related to a problem? Please describe.**
All installers look identical at the moment.

**Describe the solution you'd like**
Add the ability to include custom text and or a logo at the installation screen, to personalise each installer. Will make them pop out more and have a more professional feel.
As a good to have but ok if we don't advanced version of the above, allow creating a a complete theme for the installer (altering/translating the text of the all the fields, changing font sizes and colours, etc...)

**Comment by tstavrianos** [comment]
Different option:
- Get a list of distinct nexus mod ids that are included in the installer (or allow the modlist author to specify such a list)
- Randomize the order
- Grab the logo/thumbnail for each mod and have it get displayed while the installer is running

**Comment by tr4wzified** [comment]
Semi-included in #29

**Comment by tstavrianos** [comment]
Covered by pr #73
