### ISSUE TITLE
Modlist Installation Problem

### ISSUE THREAD

**Issue by QuirkySheDevil** [wabbajack-tools/wabbajack#2059]
Hi Ya'all, 

I have been trying to install the masterstroke modlist but it keeps saying it can't due to mod organizer. I have no idea how to fix the problem. I have tried deleting then reinstalling the modlist files, uninstalling all downloads and then redownloading the list, and uninstalling then reinstalling wabbajack. I have tried each of the above several times in different ways. Attached are the most recent log files by wabbajack. 
Thanks for any help, QuirkySheDevil

[Wabbajack 2022-08-26 16_27_10.log](https://github.com/wabbajack-tools/wabbajack/files/9459242/Wabbajack.2022-08-26.16_27_10.log)
[Wabbajack 2022-08-28 23_43_42.log](https://github.com/wabbajack-tools/wabbajack/files/9459243/Wabbajack.2022-08-28.23_43_42.log)
[Wabbajack 2022-08-30 22_54_20.log](https://github.com/wabbajack-tools/wabbajack/files/9459244/Wabbajack.2022-08-30.22_54_20.log)

**Comment by EzioTheDeadPoet** [comment]
please refer to the Modlist specific discord or forum for support with the installation of individual lists.
