### ISSUE TITLE
No logging written to disk

### ISSUE THREAD

**Issue by tyhawk** [wabbajack-tools/wabbajack#2079]
**Describe the bug**

Logging is either not written to disk at all, or not to the 2.x log location or the Wabbajack output folder.

**Additional Context**

I have an issue with the new version which I would love to report, but the logging doesn't seem to get written to disk. I expect them to be in `wabbajack-dir/logs`, but the only logs I see are from the 2.x version.

**Wabbajack Version**

3.0.1.x

**Comment by halgari** [comment]
Move the logging output to the same place 2.5 put it

**Comment by EzioTheDeadPoet** [comment]
rn the logs are stored in the logs folder of the individual version used.

**Comment by tyhawk** [comment]
There is no `logs` directory in the  3.0.1.x subdirectories. There are language folders, `Extractors`,  `temp` and `Wabbajack.exe.WebView2`.
There is a `logs` directory in the root folder of Wabbajack, but no new logs in there.

So I still can't find the logging directory.

**Comment by EzioTheDeadPoet** [comment]
#2104 is more detailed about the cause and describes where logs end up currently.
