### ISSUE TITLE
Wabbajack not closing webviews

### ISSUE THREAD

**Issue by redhelling21** [wabbajack-tools/wabbajack#2080]
**Describe the bug**

Wabbajack does not seem to close each opened Webview after a download is completed.

**Additional Context**

OS : Microsoft Windows NT 10.0.19044.0
Game : Skyrim SE
Wabbajack not located in a system folder

**Wabbajack Version**

3.0.1.4

**Logs**

There is unfortunately no error in the logs. Only lines of the type : 

> 00:05:42.979 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:05:50.171 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:05:57.428 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:04.719 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:11.955 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:19.430 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:27.671 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:35.692 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000
00:06:42.367 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0 - Remaining Limit: 10000

**Screenshot**
![Capture](https://user-images.githubusercontent.com/7909885/191627907-6834ff72-16ef-4f51-bc1f-4976f2a122ee.PNG)

**Comment by halgari** [comment]
Fixed in a recent 3.0 build

**Comment by baconsplit** [comment]
![image](https://github.com/wabbajack-tools/wabbajack/assets/63647668/765c8945-dcd1-4039-8e2a-6822ac4faa69)
hate to reopen this, but I seem to have the same problem.
OS : Up to date Windows 10
Game : Skyrim SE
Wabbajack not located in a system folder

Wabbajack Version

3.4.0.0

Logs
same logs as OP, only the download finished logs.
