### ISSUE TITLE
MINOR: Browse Modlist page filter is reset on reaccessing the page

### ISSUE THREAD

**Issue by LordTheGhost** [wabbajack-tools/wabbajack#2084]
### Bug

When starting again Wabbajack with an existing filter, on accessing the `Browse Modlist` page, the gallery only show corresponding filtered result.

When going back to that page without reloading Wabbajack, the filters parameters are still filled, but the gallery is not filtered.

It appears the binding is not executed on reload of the page thus showing unsaved result on the gallery while the filters are still shown.

### User info: 

- Win10
- Wabbajack 3.0.1.5

> First launch: filtered with one result from Skyrim SE

![image](https://user-images.githubusercontent.com/103041299/192299217-466e09ae-82ec-46c5-a031-02c2d4f2f23f.png)

> On reloading the page, with the first results being for FO4

![image](https://user-images.githubusercontent.com/103041299/192299507-76812096-6297-4dce-b5c8-d89abd5cc84c.png)

**Comment by EzioTheDeadPoet** [comment]
still a bug
