### ISSUE TITLE
Compile failing with "Resolution failed for"

### ISSUE THREAD

**Issue by tyhawk** [wabbajack-tools/wabbajack#2089]
Compilation fails every single time with the error `"Resolution failed for: (         =) C:\Wabbajack\Modlist\path\downloads\modname.zip |` after hashing all the files.

Windows 10, Skyrim LE, MO2

Wabbajack version 3.0.1.x

**Logs**

Unable to add logs due to #2079

**Comment by EzioTheDeadPoet** [comment]
then modname.zip is missing valid sources or it isn't on a whitelisted host.

**Comment by tyhawk** [comment]
Actually, I get that error for all the files in the download folder, 95% ofg which are Nexus downloads with (valid) .meta files and worked just fine and didn't return this error on version 2 of Wabbajack. I will try to dig up the logs and post those. Hopefully I'll be able to provide a little more (useful) information.

**Comment by EzioTheDeadPoet** [comment]
WJ 3.0 requires a fresh login into your Nexus Account.

@halgari maybe we need a big warning - pop-up if the login is missing. 🤔

**Comment by tyhawk** [comment]
Aha! That could be the problem. I never logged in again because I'm not downloading anything with Wabbajack. I will test it this weekend and let you know if that solved my issue.

A missing login pop-up would be very helpful indeed.

**Comment by EzioTheDeadPoet** [comment]
to check if the files are there and downloadable during the compile wj needs a logged in account.

**Comment by tyhawk** [comment]
Logging in to Nexus resolved my issue.
