### ISSUE TITLE
Logs generate in the wrong folder

### ISSUE THREAD

**Issue by chri3i** [wabbajack-tools/wabbajack#2104]
**Describe the bug**

- logs get generated at the root of the 'version folder' (3.0.1.9/Wabbajack_current.log for example)

**Wabbajack Version**

3.0.1.7 (not sure if earlier) - 3.0.1.9

**Logs**

I do not have/find a wabbajack.exe.log to attach but I attach a pic to show where the log ends up and that it doesn't produce one in the intended ``logs`` folder. By comparing the dates of the screenshotted log files, you can see that my quick test compile did not get a log in the ``logs`` folder.

![WabbajackLogGeneration](https://user-images.githubusercontent.com/79586869/194079167-d9a2be0e-e62e-4492-8ca2-b72f000b88a3.png)

![WabbajackLogGenerationNotInTheLogFolder](https://user-images.githubusercontent.com/79586869/194079519-a7424982-ac6b-4977-a4f9-b7ebe822b524.png)

**Comment by EzioTheDeadPoet** [comment]
logs are now in the `logs` folder inside of the version folder.
