### ISSUE TITLE
Incomplete installs after WJ reports a successful installation

### ISSUE THREAD

**Issue by aljoxo** [wabbajack-tools/wabbajack#2110]
**Describe the bug**

Some users are posting crash logs after installation in which they crash at main menu. Upon further inspection, it appears the game is not loading any plugins (SKSE or Game). 

When telling users to delete the mods folder and reinstall with 2.5.3.28, the issue does not reappear. Have also had similar issues (textures/meshes being broken on install and werewolf freezes during transformation that were fixed in a similar capacity, but not as many user reports and the issues are less common).

**Additional Context**

One user, when asked to share a picture of their MO2, also had a borked looking MO2, in which the LEFT side of MO2 was not organized correctly - while this could have been a user related error with some type of MO2 sorting making it look weird, it might be indicative of the issue.

**Wabbajack Version**

3.0

**Logs**

Crash Logs: https://discord.com/channels/605449136870916175/921172013744267314/1029758116507689011
MO2 screenshot (user): https://discord.com/channels/605449136870916175/921172013744267314/1029843128108195841
MO2 screenshot (dev): https://discord.com/channels/605449136870916175/921172013744267314/1029843859926171668

if there is a more ideal way for me to format this bug report, let me know, submitting it like so because it seems sufficient.
if you would like more information about the users themselves, let me know and I can request.

**Comment by EzioTheDeadPoet** [comment]
you can drag and drop files into the comments/text fields on GitHub to upload them directly, same goes for images!

makes it easier to read only here without having to go to discord first.

**Comment by aljoxo** [comment]
This might be better, sorry

[Crash_2022_10_9_22-26-19.txt](https://github.com/wabbajack-tools/wabbajack/files/9781350/Crash_2022_10_9_22-26-19.txt)
[Crash_2022_10_9_22-59-29.txt](https://github.com/wabbajack-tools/wabbajack/files/9781351/Crash_2022_10_9_22-59-29.txt)
[Crash_2022_10_10_10-10-29.txt](https://github.com/wabbajack-tools/wabbajack/files/9781352/Crash_2022_10_10_10-10-29.txt)
[Crash_2022_10_12_21-59-40.txt](
![usermo2](https://user-images.githubusercontent.com/110573889/195733067-90137818-c4ff-4968-8b4d-3fad68a896a9.png)
https://github.com/wabbajack-tools/wabbajack/files/9781353/Crash_2022_10_12_21-59-40.txt)
![devmo2](https://user-images.githubusercontent.com/110573889/195733071-3689634d-74d2-49c2-b8ea-5c74a36385a7.png)

**Comment by EzioTheDeadPoet** [comment]
@halgari maybe you know how this could happen.

**Comment by aljoxo** [comment]
Not entirely the same issue (but maybe related?), but another user installed on 3.0.2.3 and got these errors when trying to load the list.

![image](https://user-images.githubusercontent.com/110573889/196838309-294a26e4-18b6-4e8e-a34b-f475c17a468f.png)
![image](https://user-images.githubusercontent.com/110573889/196838319-b98c174b-1707-4fd6-a3f5-db25bb3ebe76.png)

**Comment by EzioTheDeadPoet** [comment]
@aljoxo @GravenImages do you know what antivirus software was used together with Wabbajack during the failed installations ? Because that would also explain the missing/broken DLLs.

**Comment by GravenImages** [comment]
For mine, Windows Defender with exceptions made to relevant folders.

**Comment by EzioTheDeadPoet** [comment]
@aljoxo, was the list compiled with 3.0 ?
And did you use tag files like the `WABBAJACK_x` or tags like that insider the notes of your ModOrganizer2 Mods ?

**Comment by aljoxo** [comment]
All my tag files are done in the Notes of MO2, with few exceptions to ignore some "optional" folders in my own output mods

**Comment by EzioTheDeadPoet** [comment]
@halgari I know you are busy with Vortex these days, but this is a fairly critical issue, that @cacophony-wj  seems to be having as well with his users. And @Dace617 mentioned seeing similar issues with other lists as well. I will ask them both to post any logs or even stuff they remember here as well so it is condensed in one spot.

**Comment by EzioTheDeadPoet** [comment]
My assumption right now is that it might be related to the new Win11 security feature which for me when upgrading from Win 10 to 11 was left off but is on by default when fresh installing Win 11:  
![image](https://user-images.githubusercontent.com/52624146/202990682-6e5350f8-a8f6-4690-90c7-ad1bd7d1c0eb.png)
![image](https://user-images.githubusercontent.com/52624146/202990694-4366a911-6c85-4995-b945-06e5418edf8a.png)

**Comment by tr4wzified** [comment]
I assume this was related to the BSA file corruption issue solved in 3.5.0.0, closing this
