### ISSUE TITLE
Wabbajack 3.0 not interpreting spaces correctly in compilation

### ISSUE THREAD

**Issue by GravenImages** [wabbajack-tools/wabbajack#2111]
**Describe the bug**

Wabbajack 3.0 (currently using 3.0.1.9) seems to not interpret spaces in links, such as a mod sourced from dropbox, correctly during compilation.

**Additional Context**
Using Windows 11 22h2, compiling Morrowind, issue is specifically with Texture Fix 2.0 on Dropbox which should be in the whitelist

**Wabbajack Version**

3.0.1.9

**Logs**

Log attached.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9768498/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Spaces aren't allowed in links anywhere so I don't understand this issue ?

**Comment by EzioTheDeadPoet** [comment]
@GravenImages you need to replace the spaces with `%20` in the meta file for 
`directURL=https://www.dropbox.com/sh/7fv2wojbp6y3uo9/AAAJJNHGtbsISsob7Uz_N4FNa/Texture%20Fix%202.0.7z?dl=1`
then it will work.
