### ISSUE TITLE
Readme doesn't open upon installing a list anymore

### ISSUE THREAD

**Issue by chri3i** [wabbajack-tools/wabbajack#2112]
**Describe the bug**

Readme doesn't open upon downloading/installing a list

**Additional Context**

Many people ignored the list readme as it was before already but now, that it doesn't open at all, it seems like nobody is reading a readme, which makes it quite a bit harder to maintain lists.

**Wabbajack Version**

3.0.1.9

**Comment by screaminglake** [comment]
Bump to this.  It does open after installing but most lists require steps before install or offer solutions for failed installs and many come asking for support without knowing the documentation even exists.

**Comment by halgari** [comment]
Thanks for the bump, it'll be in the next version, out in the next 24 hours

**Comment by EzioTheDeadPoet** [comment]
@halgari There are now cases where it opens 3 times. Once in the end and iirc twice in the beginning or the other way around. 
@TDarkShadow might know it better or has some log files. He mentioned it in the high priority issues channel on discord.

**Comment by EzioTheDeadPoet** [comment]
Going to close this now, since the last time I installed a list, the Readme opened as expected at the end.
