### ISSUE TITLE
Skyrim Anniversary Edition (GOG) Not Detected

### ISSUE THREAD

**Issue by PcNm** [wabbajack-tools/wabbajack#2118]
**Describe the bug**

Doesn't detect the game installation. ("Can't find game SkyrimSpecialEdition")
Stings like a bug. Could also be a feature request, however.

**Additional Context**

Skyrim Anniversary Edition, GOG, Win 10.

**Wabbajack Version**

WABBAJACK v3.0.1.9

**Logs**

There are no logs. WABBAJACK brings up the Documents folder when asked for the logs folder. It's empty.

**Comment by Telkhine** [comment]
Are there any workarounds for this issue? I'm running into this problem as well.

**Comment by GravenImages** [comment]
No, Wabbajack isn't designed to work with Skyrim on GOG yet, and support isn't likely for some time yet.

**Comment by Althro** [comment]
No list supports it yet either. That _may_ change soon, but until then there's no list that supports it.

**Comment by Telkhine** [comment]
For my personal use case, I don't need support for other authors lists. I'm making my own and wanted an easy way to get mine installed on my wife's computer. So a work around via a patch or config file change was all I was wondering about. However it doesn't look like there is anything of the sort. So I'll do it the old fashioned way.

**Comment by EzioTheDeadPoet** [comment]
moved to #2159 because I missed this issue.
