### ISSUE TITLE
Wabajack Update not working 3.0.2.0

### ISSUE THREAD

**Issue by TobiasC95** [wabbajack-tools/wabbajack#2128]
Tried the tested proven, delete APPDATA trick and relaunching. But it still only goes onto the splash screen, and then closes.
Could I get some help on this please.

Thanks

**Comment by Code1Eye** [comment]
same here, after 3.0.2.0 update wabbajack no longer launches

**Comment by RPencis** [comment]
same here, after 3.0.2.0 update wabbajack no longer launches, the only error in logs is: The manifest directory C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests does not exist!

**Comment by PunishMints** [comment]
I have the same issue on my Steam Deck running Windows 10 Pro. Wabbajack version 2.5.3.28 works except for not being able to log into Nexus Mods.

**Comment by EzioTheDeadPoet** [comment]
@PunishMints  Could you post a log file! Cause the issue you replied to just wasn't closed yet and was already addressed.

**Comment by TobiasC95** [comment]
Hi, I have managed to sort it out today. I just had to do a complete
uninstall and reinstall. I think some of the files must have been corrupted
during download or something. Hard to say why it works now.
