### ISSUE TITLE
Nexus API Call Limit

### ISSUE THREAD

**Issue by throwawaysubmit** [wabbajack-tools/wabbajack#2135]
v 3.0.2.3 Can't seem to download any modlists, when the Nexus download page opens this error occurs and all files are 0kb.  Any advice?

**Comment by erri120** [comment]
The Nexus API only allows a limited number of calls per day (iirc 2500). If you have used them all you need to wait till the next reset.

**Comment by throwawaysubmit** [comment]
I haven't used any calls whatsoever though.  I just reinstalled the latest version of Wabbajack and have been attempting to update the Septimus modlist after the recent Skyrim patch nerfed it.  I haven not dl'd anything from Nexus in over a month, but every download I attempt to make from any playlist throws up this error.

**Comment by erri120** [comment]
> I haven't used any calls whatsoever though. I just reinstalled the latest version of Wabbajack and have been attempting to update the Septimus modlist after the recent Skyrim patch nerfed it. I haven not dl'd anything from Nexus in over a month, but every download I attempt to make from any playlist throws up this error.

Can you send the log file (`logs/Wabbajack.current.log`)?

**Comment by throwawaysubmit** [comment]
This problem still persists on 3.0.30, which these are the log files for

[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/9883945/Wabbajack.00.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9883946/Wabbajack.current.log)

These are the logs for the previous version I had installed 3.0.2.3
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9883949/Wabbajack.current.log)
[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/9883950/Wabbajack.00.log)
[Wabbajack.01.log](https://github.com/wabbajack-tools/wabbajack/files/9883951/Wabbajack.01.log)

I bought Skyrim Enhanced Edition off steam about 3 weeks before the patch, so Septimus 3 was already installed and working.  I'm now trying to reinstall with the previous install files from before the patch through Wabbajack.   Furthermore any modlist I try to download (as with septimus), all the files show up as 0kb in Nexus and this Call Limit error is what I get.  Please advise.
