### ISSUE TITLE
Download from gallery doesn't proceed to next stage

### ISSUE THREAD

**Issue by GravenImages** [wabbajack-tools/wabbajack#2143]
**Describe the bug**
Multiple users are having an issue where they'll click to download a modlist from the gallery, the icon changes (I assume to an "in progress" symbol), but never changes to the "play button" or to the install path/download path page.

**Additional Context**

I've noticed it across many games, most notably Skyrim

**Wabbajack Version**

I've seen this reported using 3.0.1.9 to 3.0.2.3

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9874332/Wabbajack.current.log)

**Comment by GravenImages** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9874382/Wabbajack.current.log)
Another long from the same person who provided the above link, they got this when trying to install from disk. Seems like downloading from gallery might be corrupting?

**Comment by The-Second-Soda** [comment]
I am having this problem too I have tried re installing Wabbajack but I cant find any fixes

**Comment by AbstractRude** [comment]
Also having this problem, but I think I attributed it to only being unofficial packs.

**Comment by EzioTheDeadPoet** [comment]
It should show something here:
![image](https://user-images.githubusercontent.com/52624146/200088394-012a5e25-7ae7-436c-8ea5-e7809ac92773.png)

If it doesn't it must be a network issue, which is related to #2087

**Comment by EzioTheDeadPoet** [comment]
Will Close this for now since a lot has changed on the network backend and it is also possible that a few individual files had issues with the CDN downloader due to some server corruption.

If anyone reading this has encountered this again please open a new issue (if there isn't a new one that's open already) and provide the file it happend to and a log of the download attempt.
