### ISSUE TITLE
Installs fail for patched esm file of a mod

### ISSUE THREAD

**Issue by chri3i** [wabbajack-tools/wabbajack#2144]
**Describe the bug**

failed installs for a mod I changed records of after version 3.0.3.0

**Wabbajack Version**

3.0.3.0 although the compile was done with 3.0.2.3

**Logs**

Logs of one full install and one retry are attached.
[fullinstallfirsttryWabbajack.10.log](https://github.com/wabbajack-tools/wabbajack/files/9892036/fullinstallfirsttryWabbajack.10.log)
[retryWabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9892037/retryWabbajack.current.log)

**Comment by Althro** [comment]
This is also happening for Creation Club content that has not been modified.

I'll drop a log in later as I'm out atm but wanted to mention as well.

**Comment by halgari** [comment]
Thanks, I'm installing Ruvaak now to try and replicate it, I think this is a case of something going wrong in the installer and the new verification system catching the bad install. I'll dig into it more when it breaks on my system.

**Comment by Althro** [comment]
Log as promised.

[Wabbajack.current(2).log](https://github.com/wabbajack-tools/wabbajack/files/9894538/Wabbajack.current.2.log)

**Comment by chri3i** [comment]
3.0.3.1 has fixed it for me after a recompile of the list. thank you.
