### ISSUE TITLE
Broken Manual Downloads

### ISSUE THREAD

**Issue by throwawaysubmit** [wabbajack-tools/wabbajack#2146]
**Describe the bug**

Successfully downloaded Septimus 3 over 2 months ago, was running fine until the patch nerfed it.  After Septimus 4 was uploaded, tried  to update my  install but Wabbajack returns the "Nexus API Call Limit Reached - Remaining Limit 10000"  and the Nexus download page show's file sizes of 0kb.  This problem persists across any modlist I try to download.  Have not used my Nexus Mods account to download anything since I installed Septimus 3 2 months ago.

**Additional Context**

Windows 11 current version, Skyrim Legendary Edition Steam, Clean Skyrim Install, CC content downloaded, Clean wabbajack install, not in root or downloads folder.

**Wabbajack Version**

Wabbajack 3.0.3.1 ( and prior version)

**Logs**
[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/9896458/Wabbajack.00.log)
[Wabbajack.01.log](https://github.com/wabbajack-tools/wabbajack/files/9896459/Wabbajack.01.log)
[Wabbajack.02.log](https://github.com/wabbajack-tools/wabbajack/files/9896460/Wabbajack.02.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9896461/Wabbajack.current.log)

![nexus](https://user-images.githubusercontent.com/116392795/198893580-12f62606-ba89-4944-8701-973229dea8e5.jpg)

**Comment by Althro** [comment]
Have you relogged into the Wabbajack application since updating to version 3.x? If not, you will need to do so.

**Comment by throwawaysubmit** [comment]
> Have you relogged into the Wabbajack application since updating to version 3.x? If not, you will need to do so.

Do you mean log into Nexus through Wabbajack? Or is there a login to Wabbajack?  Please be more specific when troubleshooting please.  I am logged into my Nexus account in Chrome and in the Wabbajack application.  I have cleared the browser cache in Wabbajack.  I am still getting this error.

**Comment by Althro** [comment]
In the top right of the application, there is a settings "cog".

![Wabbajack_l46WSefrH0](https://user-images.githubusercontent.com/70860633/198897929-6d0f35a0-ce1c-41ac-ae15-3e9ac46db09e.png)

Click on it and repress the "login" next to the nexus. 

![Wabbajack_Q5cQnh1TMN](https://user-images.githubusercontent.com/70860633/198897930-02510609-f262-405b-a6f0-360d698962ac.png)

That should reset your connection. Failing that, reset your wabbajack installation by doing the following: 
1. Close Wabbajack
2. Press Windows + R on your keyboard and type in %localappdata%.
3. You should see a Windows Explorer window pop-up; find and delete the folder called Wabbajack.
4. Restart Wabbajack and complete the steps given above to re-authenticate Wabbajack with your nexus token.

**Comment by throwawaysubmit** [comment]
> In the top right of the application, there is a settings "cog".
> 
> ![Wabbajack_l46WSefrH0](https://user-images.githubusercontent.com/70860633/198897929-6d0f35a0-ce1c-41ac-ae15-3e9ac46db09e.png)
> 
> Click on it and repress the "login" next to the nexus.
> 
> ![Wabbajack_Q5cQnh1TMN](https://user-images.githubusercontent.com/70860633/198897930-02510609-f262-405b-a6f0-360d698962ac.png)
> 
> That should reset your connection. Failing that, reset your wabbajack installation by doing the following:
> 
> 1. Close Wabbajack
> 2. Press Windows + R on your keyboard and type in %localappdata%.
> 3. You should see a Windows Explorer window pop-up; find and delete the folder called Wabbajack.
> 4. Restart Wabbajack and complete the steps given above to re-authenticate Wabbajack with your nexus token.

I have deleted the Wabbajack folder in the localappdata, I have logged into my Nexus Mods account in Chrome and deleted the API key.  I have deleted the Wabbajack installation and redownloaded the most current version (3.0.3.1) I have reinstalled Wabbajack.  I have logged into to Nexus using the cogwheel in Wabbajack, I have downloaded the Septimus Modlist and set the installation.  Wabbajack generates a new API key.  The problem STILL persists - 0kb files in the pop browser and Nexus API Call Limit reached in Wabbajack.  

[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/9896752/Wabbajack.00.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9896753/Wabbajack.current.log)

**Comment by Althro** [comment]
I'm not sure what to recommend next regarding this.

I would recommend joining the Wabbajack discord server (https://discord.gg/wabbajack ) and asking in the #wabbajack-help channel. You are likely to get a quicker response than on github and possibly help from someone who can assist further/has come across this before.

**Comment by Althro** [comment]
Just to check, do you have nexus premium? If you do not, then it will be manual downloads. Some files are small and may not register as being above a kb.

**Comment by throwawaysubmit** [comment]
> Just to check, do you have nexus premium? If you do not, then it will be manual downloads. Some files are small and may not register as being above a kb.

I don't have Nexus Premium, but I've compared the files by opening them in Chrome on Nexus and the file sizes are larger than 0kb.

**Comment by EzioTheDeadPoet** [comment]
Renamed the issue, since the API limit should have no effect on manual downloads.

**Comment by throwawaysubmit** [comment]
Clean install of Skyrim,  clean install of Wabbajack, run as admin, problem still present.

[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/9965480/Wabbajack.00.log)
[Wabbajack.01.log](https://github.com/wabbajack-tools/wabbajack/files/9965481/Wabbajack.01.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9965482/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Don't run the game as admin.

**Comment by EzioTheDeadPoet** [comment]
You problem seems like a problem on your ISP, Network or maybe even PC.

**Comment by j550k** [comment]
im having the same issue, it looks to me like wabbajack is pointing me towards old archived versions of mods, that are for some reason 0kb. ive done all the same troubleshooting, deleting and reinstalling everything, trying all the fixes, trying a handful of different modpacks, still nada.

**Comment by marcythany** [comment]
Same problem here :(
Did everything, and keeps giving me this strange error.
