### ISSUE TITLE
GOG detection of Skyrim Special Edition + Anniversary Upgrade [Pending]

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#2159]
**What's the problem?**

@Althro: Wants people to be able to install his list with GOG versions of the game.

**The solution @Althro would like:**

Adding detection info for the GOG version of the Game.

**Alternatives I have considered:**

Telling people to wait or buy the steam version or wait. 

**Reasons why I personally would wait with adding support:**

Adding it now could likely cause an influx of people that only own a GOG copy of Skyrim trying to install a majority of list that don't support GOG causing a support nightmare for associated Support Discord servers and the main Wabbajack Discord server.

**Comment by Althro** [comment]
There is not a large number of users that will likely use this, however this number may grow in the future given Nexus has now purchased copies of the GOG edition for their DP store. The aforementioned "influx" can be resolved via bot commands or auto-response cues in automated bots in support servers. Similar to how the downgrading was handled initially before the stock-game functionality was expanded.

**Comment by EzioTheDeadPoet** [comment]
> So after 3 years, your best answer was to ignore tens of thousands of users of GOG and force them to buy Steam versions. Steam the very reason why most of us quit playing games or reach out to other platforms like GOG.


GOG copies of the games are supported by the tool, but complain to Bethesda for making their game versions different and to the majority of players still preferring to use steam copies.

Because the former makes it so every list author needs to buy all store versions and make separate setups for them. And the latter is why no one cares about supporting GOG for games like Skyrim.

So this feature is already in the app but no players that own GOG copies care enough to actually use it. 

Please get your facts straight before complaining.
