### ISSUE TITLE
Double clicking a Wabbajack file installs wabbajack to wherever the Wabbajack file is

### ISSUE THREAD

**Issue by Dace617** [wabbajack-tools/wabbajack#2165]
**Describe the bug**

After the file association fix a couple of versions ago, double clicking a Wabbajack file will just install a copy of Wabbajack wherever the Wabbajack that was opened is. This can lead to weird issues like having Wabbajack in System32, Desktop, Downloads etc.

**Wabbajack Version**

3.0.3.1

**Logs**

**Comment by erri120** [comment]
> double clicking a Wabbajack file will just install a copy of Wabbajack wherever the Wabbajack that was opened is

Can you elaborate more? What do you mean with “install a copy of Wabbajack”?

**Comment by Dace617** [comment]
If I place a wabbajack file in a folder, say C:\List Install\ , double clicking the wabbajack file will quite literally redownload the latest version of wabbajack *into* C:\List Install\
