### ISSUE TITLE
Wabbajack hanging on splash screen

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2175]
**Describe the bug**

![image](https://user-images.githubusercontent.com/26418143/200144179-bb1b9345-b655-410b-b585-3ab385b6d519.png)

Multiple PC's have this issue, seen it on both windows 10 and 11. wabbajack doesnt generate any logs. Wabbajack is up to date.

**Additional Context**

Manually installing or repairing webview2 seems to fix the issue.

**Comment by EzioTheDeadPoet** [comment]
Part of issue #2176, to keep the issues cleaner I will close this now. Thanks for putting in the time to report it 👍
