### ISSUE TITLE
Edge WebView Wabbajack Startup Error

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#2176]
**Describe the bug**

Wabbajack sometimes won't launch for some users until [Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) is manually installed or repaired.

**Additional Context**

According to @Dace617 around WJ version 3.0.1.9 WJ stopped installing webview2 for users.

**Wabbajack Version**

Version: 3.0.3.1

**Comment by erri120** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by erri120** [comment]
Ideally the launcher should get the evergreen bootstrapper after downloading a new Wabbajack version
