### ISSUE TITLE
Wabbajack logs show Version 0.0.1.0 for every mod list version when installing

### ISSUE THREAD

**Issue by Dace617** [wabbajack-tools/wabbajack#2177]
**Describe the bug**

In the Wabbajack log when displaying which modlist is being installed the version number is supposed to be printed after the name of the modlist. In every case it is showing as "[Modlist Name] - 0.0.1.0" 

**Wabbajack Version**

3.0.3.1

**Logs**
Issue described is on line 17 `00:01:45.271` of this log. it can be seen in any other log though.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9944938/Wabbajack.current.log)

**Comment by throwawaysubmit** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9965499/Wabbajack.current.log)
