### ISSUE TITLE
Can't link Nexus account

### ISSUE THREAD

**Issue by TyraniteNG** [wabbajack-tools/wabbajack#2180]
I just get this message and it keeps loading infinitely
Checking if the site connection is secure
users.nexusmods.com needs to review the security of your connection before proceeding.
What can I do?

**Comment by EzioTheDeadPoet** [comment]
We need a log file, information about the Wabbajack version you are using. 

Without that we can't identify your issue, since for most other people things are working fine.

**Comment by throwawaysubmit** [comment]
This is a cloudflare gateway page.  Possibly linked to my issue of downloads being 0kb?

**Comment by EzioTheDeadPoet** [comment]
issue seems only present in unsupported WJ 2.5.x.x
