### ISSUE TITLE
Wabbajack is no longer respecting the WABBAJACK_ALWAYS_DISABLE tag.

### ISSUE THREAD

**Issue by Yagisan** [wabbajack-tools/wabbajack#2181]
**Describe the bug**

I have several development tools in my modlist. They are not intended to be distributed to end users, as improper use will break the game. They are disabled using the WABBAJACK_ALWAYS_DISABLE tag in Mod Organizer 2. 

![WABBAJACK_ALWAYS_DISABLE_Source](https://user-images.githubusercontent.com/172080/200356289-8ee6417d-57ed-48eb-80ee-ac3142265861.png)

In the 2.x releases of WabbaJack this was honoured, and the disabled mods were not distributed to end users. However, with the current release, this is now completely ignored.

![WABBAJACK_ALWAYS_DISABLE_Target](https://user-images.githubusercontent.com/172080/200357044-f38a675d-e2c4-4cd8-a8cc-2fc69202cf5e.png)

This is not desirable.

**Additional Context**

OS: Windows 10 Home. Version 21H2 (OS Build 19044.2130)
Game : Stardew Valley 1.5.6 GoG Release.

**Wabbajack Version**

Wabbajack 3.0.3.1

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9953404/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
In Wabbajack 3.0 it is intended to use the WJ UI to select folders to ignore. 
But since I know where I have to alter the code to import the old tags into the new system I will look into it and add it hopefully for the next update to support those tags again.
