### ISSUE TITLE
NTFS LZS Compression Setting is ignored and/or not persisted

### ISSUE THREAD

**Issue by t3h0th3rLL** [wabbajack-tools/wabbajack#2219]
**Describe the bug**

Ticking the checkbox "Use NTFS LZS compression during install" has no effect, the installed modlist will not be compressed.
Upon checking in settings again, the checkbox is unticked again.

**Additional Context**

OS: Windows 10 Pro 22H2 (OS Build 19045.2251)
Game Types: SSE, Skyrim VR, Cyberpunk 2077

**Wabbajack Version**

v3.0.4.1 (according to Discord as early as v3.0.1.5 most likely since v3.x)

**Logs**

There are no relevant log entries related to this issue.

**Comment by EzioTheDeadPoet** [comment]
the checkbox isn't present in the 3.0 settings

**Comment by t3h0th3rLL** [comment]
It certainly shows up in the UI:
![image](https://user-images.githubusercontent.com/12899713/203590247-df414543-3a05-4068-8b26-6af5a50c2880.png)

**Comment by EzioTheDeadPoet** [comment]
I was blindsided by somehow expecting the setting to be part of the Performance tab.
Did you restart WJ after changing the setting ?
And did you try a WJ reset ? 

Also depending on how well the base compression of certain files is NFTS LZS compression doesn't even touch them by design because they are already compressed to the maximum.

**Comment by t3h0th3rLL** [comment]
I've done all kinds of cleanups, cleared out %appdata% reinstalled WJ a few times. Reboots inbetween. No change.

Here's a List that was installed with pre WJ 3.0: ![image](https://user-images.githubusercontent.com/12899713/203606752-f903293f-b919-493d-ba1d-8c19b385f467.png) As you can see a fair chunk of on disk reduction. 
The same list installed today with 3.0.4.1: 
![image](https://user-images.githubusercontent.com/12899713/203616012-cf910816-ead7-4148-8b45-ffadc087a0d7.png)

**Comment by EzioTheDeadPoet** [comment]
@Unnoen @halgari I am sadly not that informed with the compression used and the installer you 2 might know more about this if the feature got removed or if it just doesn't work properly etc.

**Comment by t3h0th3rLL** [comment]
Setting still gets reverted and no effect in v3.0.5.0

**Comment by EzioTheDeadPoet** [comment]
needs investigating

**Comment by EzioTheDeadPoet** [comment]
still needs investing and possibly fixing.

**Comment by JanuarySnow** [comment]
The setting doesnt appear to connect or get referenced in the code anymore.
