### ISSUE TITLE
Killer Control Centre blocks viewing modlists

### ISSUE THREAD

**Issue by SAFry76** [wabbajack-tools/wabbajack#2228]
**Describe the bug**

on a fresh install of WJ, when you click 'browse modlists' it says none available

**Additional Context**

This is on a w11 laptop, my w10 desktop worked fine. looking at the log it said that my connection was being shut down. Eventually through a process of elimination I found that an app called Killer Control Centre seemed to be blocking WJ on wifi. Posted the solution on Discord and somebody else popped up to say the fix had just worked for them too. You have to disable the Prioritization Engine and I disabled Auto Bandwidth too. 
This software was bundled with my Dell/Alienware laptop but also I think it's a feature of the Intel chipset because it shows up in my Intel Driver Support app. So it might come up fairly frequently. 

**Wabbajack Version**

3.0.4.1

**Logs**

<!-- Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. 

![image](https://user-images.githubusercontent.com/119138386/204111464-322996ba-1cec-44ad-958e-bc6f183fe159.png)

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10097145/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
https://wiki.wabbajack.org/user_documentation/Troubleshooting%20FAQ.html#wabbajack-modlists-not-loading-or-downloading
