### ISSUE TITLE
Add an indicator to the Resource_settings.json file to denote what units the "Throughput" field uses.

### ISSUE THREAD

**Issue by StaryMic** [wabbajack-tools/wabbajack#2235]
**Is your feature request related to a problem? Please describe.**

It's bothered me that I can't tell if I'm meant to write the Throughput field in KBs or MBs because if I uncap Wabbajack then it basically DDOSes my own wifi and makes my PC unusable for many hours.

**Describe the solution you'd like**

A simple comment that says something like "In kilobytes per second" would help make it clearer what should be typed in that field.

Mainly a small thing that bugs me but it would be helpful nonetheless.

**Comment by erri120** [comment]
[JSON doesn't support comments](https://www.json.org/json-en.html). The alternative is `.jsonc` (JSON with comments) which was created by Microsoft [as part of VS Code](https://github.com/Microsoft/node-jsonc-parser). JSON with comments is not standardized, and implementation support is lacking. The .NET library we are using for parsing JSON (`System.Text.Json`) [can handle comments](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsoncommenthandling), however we create the JSON file programmatically and can't insert comments that way.

I would handle this with a docs page that explains the settings.

**Comment by StaryMic** [comment]
I'd be fine with having it in the documentation for Wabbajack. It's where I checked for it first in fact. For now, do you mind telling me if it's KB, B, or MB?
