### ISSUE TITLE
Wabbajack modlist install corrupts personal MO2 portable install

### ISSUE THREAD

**Issue by DianaTESGotH** [wabbajack-tools/wabbajack#2238]
Describe the bug
I maintain a personal MO2 dev build for testing mods, and it got borked on me last week, freezing and crashing when managing my mods, installing or uninstalling mods. I installed Windows 11 a few days ago, then clean installed all my apps including MO2. The issue appeared to be resolved until I started installing WJ modlists again. Now my personal MO2 dev build is borked again.

I have a new clean install of MO2 after uninstalling the old and cleaning my registry. This all started after installing a WJ modlist (Licentia, I suspect). It crashes on me while I work on my latest AE list. I try to install a mod, it crashes or freezes. If I delete an old mod I no longer want, it crashes.
Here are my crashDumps I uploaded for the MO2 devs to review, but they never replied to my issue.

The issue appeared to be resolved after a clean installation of Windows 11; however, it resurfaced after once again using Wabbajack to install Licenta. (In my own MO2 dev build, not a Wabbajack modlist build) aparently, when I try to install certain mods from my downloads folder, I find a .meta.lock in the downloads folder after MO2 CTDs during the install. 
Example of the latest MO2 CTD with new .meta files produced:
Realistic Ragdolls and Force SE-1439-1-92.zip.meta.ZVuREs
Realistic Ragdolls and Force SE-1439-1-92.zip.meta.lock

I think I have resolved my issue. I uninstalled Licentia, cleaned out AppData Wabbajack files, cleaned my registry. Rebooted my PC and fresh installed MO2. MO2 is now working as expected for me again. I don't know why the Licentia WJ is interfering with my personal MO2 builds. 

It could be a windows issue, but the last discussions about are a couple of years old. It was suspected then to be a "QSetting reading the .meta files, it does stuff like creating a .meta.lock file for thread safety and other such things"...
https://discord.com/channels/265929299490635777/271306913944174601/681108904276787246

My dev build is where I do most of my work, so I'll be keeping it and not risk installing anymore WJ modlists til this issue is resolved.

WJ Version: 3.0.4.1 
OS Version: Windows 11
Game: SSE

[MO2 crashDumps.zip](https://github.com/wabbajack-tools/wabbajack/files/10149240/MO2.crashDumps.zip)

**Comment by EzioTheDeadPoet** [comment]
Wait you had MO2 open while installing a WJ list ?

**Comment by DianaTESGotH** [comment]
> Wait you had MO2 open while installing a WJ list ?

No, not while installing with WJ. This is after the fact. The list was already installed and in it's own separate portable folder.

**Comment by EzioTheDeadPoet** [comment]
very very odd and weird. do the installs share the same `downloads` folder ? And do you use the feature to open multiple MO2 instances at the same time ?

**Comment by DianaTESGotH** [comment]
They do share the same downloads folder. I have only ever had one instance of MO2 open at a time. I did not know there was a feature to have several instances open.

**Comment by EzioTheDeadPoet** [comment]
> Forgive me if I am wrong, but isn't sharing the downloads folder between WJ lists a nono so that the lists don't try to use the wrong archives?
> 
> I even use a powershell script that removes obsolete downloads before installing list updates.



This is only a problem when you compile multiple lists that you want to share for installing WJ knows 100% exactly what it needs.

**Comment by DianaTESGotH** [comment]
> 

I don't build lists to compile for WJ. I have a MO2 instance for testing mods, not list building. 
And, this only happens when I install the Licentia Black WJ modlist. Over the past week I have installed a WJ Dev build I help test, and it did not corrupt my personal modlist. I have also installed ADT, AVO, and Elysium Remastered all without issue. Last night I installed Licentia Black, and just had to go back through to delete all instance of that specific WJ list, cleaned my AppData files, etc... and fixed my personal MO2 dev build again. Out of the modlists I just mentioned, this corruption of my personal MO2 dev build instance only happens with Licentia Black.

**Comment by DianaTESGotH** [comment]
I am going to attempt moving my WJ installation to another drive today, and test with installing Licentia Black to another drive as well.

**Comment by DianaTESGotH** [comment]
After moving Wabbajack and Licentia Black to a separate drive than my default game drive, my MO2 dev list is functional again. Why only this WJ modlist affects my personal dev build is confusing. The WJ Dev build I help test, ADT, AVO, and Elysium Remastered do not highjack other portable instances of MO2. Hopefully this information can help the WJ dev team narrow down the possible causes of this issue.

**Comment by DianaTESGotH** [comment]
> Quick question (could be relevant)
> 
> How did you install your personal MO2: Extracting the archive or using the installer?
> 
> I assume it shouldn't matter, but you never know.

I extract the archive.

**Comment by DianaTESGotH** [comment]
> How was the instance made?
> 
> * Forcing a Portable instance by creating a 'portable.txt' file before starting.
>   or
> * Creating a Portable instance entirely using the first-launch wizard (or Instance Manager)
> 
> _Currently doing a test run of installing Licentia Black after making 2 such instances. I've merged my downloads folders into a shared downloads folder_


> * Creating a Portable instance entirely using the first-launch wizard (or Instance Manager)

**Comment by DianaTESGotH** [comment]
No worries. It's passed my bedtime, but I will check back in the morning. It will be nice if you are able to help get to the bottom of this, and I am happy to answer any questions you have that might help.

**Comment by DianaTESGotH** [comment]
Hmm, I am on Windows 11, but this happened on Windows 10 too. I first reported this on the MO2 discord before I upgraded to Windows 11. What happened when I would install mods, especially FOMODs in my dev list, it would crash. It created new .meta files that had strange extensions, 
i.e. 
Realistic Ragdolls and Force SE-1439-1-92.zip.meta.ZVuREs
Realistic Ragdolls and Force SE-1439-1-92.zip.meta.lock
All that info in in the OP. 
Another user of the Licentia Black modlist had the same issue as I did, then cacophony suggested I reach out to the WJ staff and explain the issue. And, given I am not the only one who has experienced this issue, I do hope it can be figured out and not just chucked off as an OS issue, because this happened to me on both Windows versions.

**Comment by DianaTESGotH** [comment]
Yes, it is not Defender, and that is the only AV I use. Not to mention I also use exlusions on my Game files.
Licentia Black does not use Realistic Ragdolls and Force SE, so I also doubt "that whatever is happening happens to occur when installing something included in that list."

**Comment by DianaTESGotH** [comment]
I appreciate the effort. Hopefully with all this information in this thread, it will make it a litle easier for the devs of either MO or WJ to narrow down. And, I have a workaround by moving my WJ and modlists installed with it to a separate drive. I can then copy the mods and profiles into a new MO2 portable install on my default game drive.

**Comment by EzioTheDeadPoet** [comment]
reason for this hasn't been found yeah
forget

**Comment by EzioTheDeadPoet** [comment]
This issue is basically waiting for more people to mention stuff about it.

**Comment by terrylava** [comment]
I just had this same bug twice in a row. It's something to do with wabbajack corrupting the meta files when it's setting all the mods to hidden after an install. I have a shared downloads folder with 5000 mods in it from various mod sites. Installed a few different WJ lists with it over time, but eventually I keep running into the same thing. It becomes very likely to crash after installing or removing a mod in MO2. The only way I've been able to get it working is to delete/move all the meta files out of the download folder, and requery all the nexus ones. I just spent 2 weeks sorting the non-nexus ones out of the folder, and querying again. Played in between, editing a few different modlists in the meantime. Then i installed another instance of SME by phoenix, and immediately started running into the problem in all instances of MO2 that use that download folder.

**Comment by terrylava** [comment]
[wjmo2metactd.zip](https://github.com/wabbajack-tools/wabbajack/files/11780091/wjmo2metactd.zip)
I'm no expert, but when trying to unhide all, it kept crashing, and each time making a bunch of wintersun.meta.lock files. I deleted the original meta file, and re-queried nexus, and tried unhide all again, and it got stuck on another file. Here's the bad meta, and a good meta, if anyone knows what the problem is. I'm no expert but that file time in the bad one looks funny.
