### ISSUE TITLE
Wabbajack crashes when compiling a mod list

### ISSUE THREAD

**Issue by Yagisan** [wabbajack-tools/wabbajack#2242]
**Describe the bug**

Wabbajack 3.0.4.1 crashes when attempting to compile a Stardew Valley Modlist. This does not occur with 3.0.4.0

Wabbajack 3.0.4.1 was installed via the wabbajack autoupdater.

**Additional Context**

OS: Windows 10 Home. Version 21H2 (OS Build 19044.2130)
Game : Stardew Valley 1.5.6 GoG Release.

**Wabbajack Version**

3.0.4.1

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10152757/Wabbajack.current.log)

**Comment by Yagisan** [comment]
I have unfortunately now replicated this with Fallout 4.

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10253720/Wabbajack.current.log)

**Comment by Yagisan** [comment]
Replicated on commit a4137255de293fd616c54882c8b06a391a82c0c2

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10336311/Wabbajack.current.log)

**Comment by Yagisan** [comment]
Replicated in 3.0.6.2

**Comment by Yagisan** [comment]
Still there in 3.0.6.2

**Comment by tr4wzified** [comment]
Turns out this was related to the ReactiveUI.WPF NuGet package not working correctly with .NET 6 for the Windows version WJ was targeting, issue does not occur when changing WPF project to     <TargetFramework>net7.0-windows10.0.19041</TargetFramework>

**Comment by Yagisan** [comment]
For the sake of the bot - Still present in 3.2.01

**Comment by EzioTheDeadPoet** [comment]
Just to note it here as well, an upgrade of the app to .NET 7.0 has fixed this before according to some discord conversations.

**Comment by tr4wzified** [comment]
It does fix it. We should probably bump it ASAP, easy fix.

**Comment by EzioTheDeadPoet** [comment]
the latest pre-releases should include this fix now
