### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by Astolfoho** [wabbajack-tools/wabbajack#2243]
problem to install 

Elysium-Remastered mod list

https://github.com/TitansBane/Elysium-Remastered/blob/main/README.md

############ Wabbajack log file - 2022-12-06 17:40:29.1213 ############
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1129540, Name = Orc Massage, Path = C:\Program Files (x86)\Steam\steamapps\common\Orc Massage }
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1222670, Name = The Sims™ 4, Path = C:\Program Files (x86)\Steam\steamapps\common\The Sims 4 }
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 227320, Name = You Need A Budget 4 (YNAB), Path = C:\Program Files (x86)\Steam\steamapps\common\YNAB 4 }
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 228980, Name = Steamworks Common Redistributables, Path = C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared }
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, Path = C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition }
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 730, Name = Counter-Strike: Global Offensive, Path = D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive }
00:00:00.000 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Unable to open HKEY_LOCAL_MACHINE\Software\GOG.com\Games
00:00:00.009 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests does not contain any .item files
00:00:00.009 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not contain any .mfst files
00:00:00.328 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.328 [INFO] (Wabbajack.MainWindowVM) Process Location: C:\Mods\3.0.4.1\Wabbajack.exe
00:00:00.328 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.4.1
00:00:00.499 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 8c60dc1197af3158fd844a3f0ae068766df2f0fc
00:00:00.499 [INFO] (Wabbajack.MainWindow) Running in C:\Mods\3.0.4.1
00:00:00.526 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.22623.0
00:00:00.526 [INFO] (Wabbajack.MainWindow) System settings - (31.7GB RAM) (18.9GB Page), Display: 2560 x 1440 (7.8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.526 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:37.777 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:37.777 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:37.777 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:37.777 [INFO] (Wabbajack.InstallerVM) Preparing MegaDownloader
00:00:38.946 [INFO] (Wabbajack.InstallerVM) Preparing WabbajackCDNDownloader
00:00:38.946 [INFO] (Wabbajack.InstallerVM) Preparing GoogleDriveDownloader
00:00:38.970 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Elysium Remastered - 0.0.1.0
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: C:\Mods\DATA
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: C:\Mods\DATA\downloads
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: C:\Mods\3.0.4.1
00:00:39.183 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:40.220 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:40.229 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:40.692 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:40.744 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:40.744 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 302974 directives to 302974 required
00:00:40.793 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:40.793 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:40.793 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:40.808 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:40.808 [INFO] (Wabbajack.Installer.StandardInstaller) Found 43 total files, 41 matching filesize
00:00:41.952 [WARN] (Wabbajack.InstallerVM) While loading slide|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Wabbajack.InstallerVM.PopulateNextModSlide(ModList modList)
00:00:44.740 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 2275 archives
00:00:44.740 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:00:45.266 [FATAL] (Wabbajack.Installer.StandardInstaller) File MegaDownloader+State|https://mega.nz/file/lNUjnQYZ#Q0DDeiMzUKbDzqak4ct3BpTXjAthIP-Z2Lud77tZ84k failed validation
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:45.266 [INFO] (Wabbajack.Installer.StandardInstaller) Found 43 total files, 41 matching filesize
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Mod.Organizer-2.4.4.7z (HTTPDownloader+State|https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Skyrim Script Extender (SKSE64)-30379-2-0-20-1633684151.7z (NexusDownloader+State|SkyrimSpecialEdition|30379|233411)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Additional Clockwork-47087-3-0-4-1665222016.zip (NexusDownloader+State|SkyrimSpecialEdition|47087|322413)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Animated Armoury - Fixes-47213-3-0-1-1623312818.zip (NexusDownloader+State|SkyrimSpecialEdition|47213|208423)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Apocalypse spells for Spellcasters-58017-1-31-5-1666358425.7z (NexusDownloader+State|SkyrimSpecialEdition|58017|325523)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Audio Overhaul Skyrim (Non-SKSE - Epic Game Store - Game Pass Users)-12466-3-4-3-1667962254.zip (NexusDownloader+State|SkyrimSpecialEdition|12466|330279)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Bijin AIO SE for USSEP-1825-AIOSE.7z (NexusDownloader+State|SkyrimSpecialEdition|1825|30620)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Bring Meeko to Lod SE-25246-1-0-1555935905.7z (NexusDownloader+State|SkyrimSpecialEdition|25246|89238)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download BURP - Desatured Textures-50109-1-1-1622733710.7z (NexusDownloader+State|SkyrimSpecialEdition|50109|207099)
00:00:45.275 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Canis Hysteria-52397-1-0-4-1647397910.zip (NexusDownloader+State|SkyrimSpecialEdition|52397|270434)

**Comment by EzioTheDeadPoet** [comment]
not a Wabbajack issue please bring this issue to the support server for the list you are installing.

**Comment by EzioTheDeadPoet** [comment]
Or it might be a nexus related issue.
Or you have some 3rd Party app like the K!ller Control Center (an example) messing with your internet connection.

Either Way it is not a Wabbajack issue.
