### ISSUE TITLE
Can't Find Cyberpunk from Epic Games Library

### ISSUE THREAD

**Issue by G33kman** [wabbajack-tools/wabbajack#2253]
Trying to install the Cyberpunk Thing Modpack but after I click the start (play) button it fails immediately.

Steps I've taken:

- Ran the Game once
- Searched online for solutions
- Verified the game
- Reinstalled the game completely
- Pulled my hair out...

I have been modding games for years and have used Wabbajack plenty of times previously so  I feel confident that I'm doing what I'm supposed to.

Operating System: Windows 10 Pro
Game Library: Epic Games
Game Location: E:\Games\Cyberpunk2077
MO2 Install Location: E:\MO2077
Wabbajack Version: 3.0.4.1

**Logs**
The Log is short since the install fails right away but I still put the log on pastebin so that it doesn't make the post long...

https://pastebin.com/FytgNstd

Thanks for any insight!

**Comment by EzioTheDeadPoet** [comment]
https://github.com/wabbajack-tools/wabbajack/wiki/01.-Supported-Games-and-Mod-Managers
Epic Games Cyberpunk isn't supported yet.

@erri120 could you work with this user to get the IDs so we can use them to add support for it. When you have time to do so ?

**Comment by erri120** [comment]
From the log:
```log
Found EGSGame { CatalogItemId = 563d27afe4544a648a0c222d73dedd84, DisplayName = Cyberpunk 2077 - REDmod, InstallLocation = E:\Games/Cyberpunk2077 }
Found EGSGame { CatalogItemId = 5beededaad9743df90e8f07d92df153f, DisplayName = Cyberpunk 2077, InstallLocation = E:\Games/Cyberpunk2077 }
```

**Comment by G33kman** [comment]
Yeah, I'm not sure why there are two IDs listed... I'm assuming it's because I installed the game twice but not real sure.
Thanks for the update though!
I'll _patiently_ wait for Epic to be supported.. :D

**Comment by erri120** [comment]
One is REDMod, the other is the game.

**Comment by G33kman** [comment]
Oh, that's because I enabled the checkbox for mods from the CDPR launcher... I get it now.
Best of luck with getting this all figured out!
