### ISSUE TITLE
Failed install - due to file corruption 

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2266]
Lizzy - On behalf of Wildlander support.

**Describe the bug**

Failed install - due to file corruption

**Wabbajack Version**

3.0.5.0

**Logs**

https://cdn.discordapp.com/attachments/881254575640838254/1059926958999347320/Wabbajack.current.log

Bit of a weird one here - the user downloaded all of the zip files, then wabbajack threw a tantrum trying to unzip them. The user manually deleted and redownloaded the offending zip files and then wabbajack found a few more "failed hash checks".

All in all it took a hour of constant running and deleting to get it to install correctly. 

I suspected bad sectors on the harddrive or AV interfereance. But the user had it turned off - and chkdsk found nothing.

**Comment by Mieekaserra** [comment]
Conversation with user starts here https://discord.com/channels/344256550640287755/881254575640838254/1059919373185331330

on wildlander discord

**Comment by EzioTheDeadPoet** [comment]
Have they tried crystal disk info yet ?

**Comment by EzioTheDeadPoet** [comment]
still unser investigation

**Comment by EzioTheDeadPoet** [comment]
This issue hasn't appeared again so, for now I'll leave this marked as stale unless some more feedback or user reports get attached that show the same issue.

**Comment by selsie** [comment]
I had the issue as well.
Wabbajack downloaded a file, found it corrupt, downloaded it AGAIN (not appending, as would be the sensible thing to do for a 13GB file) and saved the new file with [original file name][long hash(?) string].7z
deleting the damaged files (I had 7zip check the whole download folder) and renaming the files with the long hash solved the problem.
