### ISSUE TITLE
[Bug] Blocked folders not blocked fully

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2272]
---

**Edit @EzioTheDeadPoet :**

The bug of the stalling was and is easily fixed by restarting WJ and usually caused by the OS messing with WJ in some way.

The main issue why this is still open, is that WJ seems to fail at blocking the Blacklisted folders, if a subfolder is created in a blacklisted folder.

---

From wildlander Support.

**Describe the bug**

Install appears to be stalled, nothing on the progress bar, on the UI. Or in the logs.
![image](https://user-images.githubusercontent.com/26418143/210788054-00f45116-cb75-472f-bc78-0277cdc8e0c1.png)

**Additional Context**
Windows 10

**Wabbajack Version**

4.0.5.0

**Logs**
https://cdn.discordapp.com/attachments/881254575640838254/1060545240739622992/Wabbajack.current.log

**Comment by Mieekaserra** [comment]
I know the user is running inside of C:\Users\XXXXX\Downloads\Wildlander-Install\

So i've got him to move his folder out of the users folder - But i thought wabbajack was supposed to stop them running from this location?

**Comment by Mieekaserra** [comment]
bump.

**Comment by EzioTheDeadPoet** [comment]
still needs to be looked at.
