### ISSUE TITLE
[Bug] Wabbajack Browser Not Working Correctly?

### ISSUE THREAD

**Issue by Astridburr** [wabbajack-tools/wabbajack#2274]
**Describe the bug**

Whenever I goto login to say Nexus or Loverslab or even open up a page to download something from LL, the browser shows nothing but a blank page, and whenever I click on said blank page, WJ crashes and i'm forced to reopen/restart Wabbajack, i'm curious as to what could be causing it as I've freshly reinstalled Wabbajack multiple times and have restarted my computer aswell. Any context or help is appreciated ty!! 

**Additional Context**

OS: Windows 10 and I usually run FO 4 and Skyrim SE/AE.

**Wabbajack Version**

Wabbjack Version: 3.0.5.0

As far as I know, I haven't gotten anything that spews out an error code, it just shuts down without so much as an error code and forces me to restart/reopen Wabbajack, again any help is appreciated!

**Comment by EzioTheDeadPoet** [comment]
Problem on your PC caused by a broken Edge WebView2 installation, most common on "debloated" broken windows installations.

Please install/repair WebView2 by following the answer in this link:
https://superuser.com/questions/1751709/how-to-reinstall-microsoft-edge-webview2-runtime

**Comment by ChrisNonyminus** [comment]
I'm having this issue too and did not debloat Windows.

**Comment by EzioTheDeadPoet** [comment]
> I'm having this issue too and did not debloat Windows.
> Maybe you should reopen this.

Make sure you use the latest version of Windows 10 or 11, whichever you have installed.

Also don't use any LTSC or however those versions are called either. They are not supported.

If you already did take all that into your troubleshooting steps:
<https://wiki.wabbajack.org/user_documentation/Troubleshooting%20FAQ.html#wabbajack-shows-a-black-screen-when-trying-to-x>
