### ISSUE TITLE
Sanity checking errors on file both during compile and Installation

### ISSUE THREAD

**Issue by Althro** [wabbajack-tools/wabbajack#2285]
**Describe the bug**

A sanity check error is occurring when attempting to compile with this mod: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=1000150204&nmm=1&game_id=110

Whilst cleansing the WJ patch cache did allow me to compile, upon one of my testers attempting to install, the sanity check error reappears. 

**Additional Context**

Windows 11 22H2, Skyrim Special Edition (Both GOG and Steam editions installed)

**Wabbajack Version**

3.0.6.0

**Logs**

[Wabbajack.01.log](https://github.com/wabbajack-tools/wabbajack/files/10482439/Wabbajack.01.log)
[Wabbajack.02.log](https://github.com/wabbajack-tools/wabbajack/files/10482441/Wabbajack.02.log)
[Wabbajack.03.log](https://github.com/wabbajack-tools/wabbajack/files/10482442/Wabbajack.03.log)
[Wabbajack.current (1).log](https://github.com/wabbajack-tools/wabbajack/files/10482445/Wabbajack.current.1.log)

**Comment by halgari** [comment]
not stale yet, still looking into this
