### ISSUE TITLE
Stalled Install 5 days

### ISSUE THREAD

**Issue by drogongod** [wabbajack-tools/wabbajack#2288]
**Describe the bug** Stalled Install 5 days

![image](https://user-images.githubusercontent.com/16511480/216549281-92cb7bf9-a314-43df-9d41-f0743039d1ea.png)

Skyrim Tsukiru

![image](https://user-images.githubusercontent.com/16511480/216549746-1477cd61-44e2-4fec-9af0-cb64b4ed0ca7.png)
Windows 11 64 gigs ram

Wabbajack Version 3.0.6.2

**Wabbajack Version**

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10577054/Wabbajack.current.log)

**Comment by Mieekaserra** [comment]
If you have a stalled install like this - you can safely restart the program and it'll resume where it stalled out.
