### ISSUE TITLE
[full_inu] Armor Pack 01 SSE not recognized by wabbajack

### ISSUE THREAD

**Issue by CptDooguls** [wabbajack-tools/wabbajack#2297]
I downloaded it manually, looked for network optimization but its go and nothing works. Installer will not proceed.

**Comment by EzioTheDeadPoet** [comment]
No log provided and no indication what the user was trying to do. 

There are many reasons why a file won't be accepted by WJ where 90% aren't the fault of WJ but the modlist that's being installed.

And if a Modlist is being compiled, then reading [wiki.wabbajack.org](https://wiki.wabbajack.org) will have all relevant answers.
