### ISSUE TITLE
Failing to Compile No Match In Stack

### ISSUE THREAD

**Issue by aljoxo** [wabbajack-tools/wabbajack#2302]
**Describe the bug**

Attempting to compile on Wabbajack 3.0.6.2 and 3.0.5.0 throws me No Match In Stack issues on my own Output files. I have attempted to reupload my own output, I have fully reset Wabbajack, neither of these seem to have solved the issue.

**Additional Context**

OS: Windows 10 Home (21H2)
Game: Skyrim Special Edition
Wabbajack Modlist: Arisen

**Wabbajack Version**

3.0.6.2 and 3.0.5.0

**Logs**

All of the logs have identical failings on the contents of my DynDOLOD Output, but I can post more logs if it would be helpful.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10855546/Wabbajack.current.log)

**Comment by aljoxo** [comment]
The original log in the post was 3.0.5.0, here is a log from 3.0.6.2

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10856057/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Did you make a fresh archive and did you make sure to pack in LODGen, TexGen and DynDOLOD files into the archive?

Because this sounds simply like your outputs archive is missing files.

**Comment by aljoxo** [comment]
Closing issue since CDN fixes it I guess
