### ISSUE TITLE
Downloads folder cannot have different name for compilation

### ISSUE THREAD

**Issue by TDarkShadow** [wabbajack-tools/wabbajack#2308]
**Describe the bug**

When the downloads folder in a modlist folder is not named 'downloads', Wabbajack will fail to compile the modlist.

**Additional Context**

OS: Windows 10 (Pro), 22H2 build 19045.2673
Game; Fallout New Vegas
Game is installed under `C:\Games\GOG\Fallout New Vegas`.
Wabbajack is installed / placed under `D:\Modding\Wabbajack`.
Modlist is initialized as a git repo and is under `E:\Projects\RadiantMojaveModlist`.

You can check the files in this archived branch.
https://github.com/RadiantMojave/modlist/tree/archive/metasNotDownloads

**Wabbajack Version**

3.0.6.2

**Logs**

<details>
<summary>Details</summary>
############ Wabbajack log file - 2023-03-02 09:31:33.1061 ############

`00:00:00.013 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 440, Name = Team Fortress 2, Path = C:\Games\Steam\steamapps\common\Team Fortress 2 }`
`00:00:00.013 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1151340, Name = Fallout 76, Path = E:\Games\Steam\steamapps\common\Fallout76 }`
`00:00:00.026 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1454587428, Name = Fallout: New Vegas, Path = C:\Games\GOG\Fallout New Vegas }`
`00:00:00.026 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests does not exist!`
`00:00:00.026 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not contain any .mfst files`
`00:00:00.467 [INFO] (Wabbajack.MainWindowVM) Assembly Location: `
`00:00:00.467 [INFO] (Wabbajack.MainWindowVM) Process Location: D:\Modding\Wabbajack\3.0.6.2\Wabbajack.exe`
`00:00:00.467 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.6.2`
`00:00:00.651 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 3587b188e03f0bcb453f97c749f5b8bbccb39510`
`00:00:00.651 [INFO] (Wabbajack.MainWindow) Running in D:\Modding\Wabbajack\3.0.6.2`
`00:00:00.689 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19045.0`
`00:00:00.689 [INFO] (Wabbajack.MainWindow) System settings - (15,9GB RAM) (72GB Page), Display: 1920 x 1080 (7,9GB VRAM - VideoMemorySizeMb=10240)`
`00:00:00.701 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list`
`00:00:10.665 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Add Roots`
`00:00:14.325 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Indexing Game Files`
`00:00:14.507 [INFO] (Wabbajack.Compiler.MO2Compiler) Including 464 stock game files from FalloutNewVegas as download sources`
`00:00:14.530 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Cleaning Invalid Archives`
`00:00:14.574 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Indexing Data`
`00:00:14.818 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Generating Compilation Stack`
`00:00:14.818 [INFO] (Wabbajack.Compiler.MO2Compiler) Generating compilation stack`
`00:00:16.207 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Running Compilation Stack`
`00:00:16.303 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Updating Extra files`
`00:00:16.303 [INFO] (Wabbajack.Compiler.MO2Compiler) Compiler Step: Finding Errors`
`00:00:16.303 [WARN] (Wabbajack.Compiler.MO2Compiler)      metas\Mod.Organizer-2.4.4.7z.meta - No Match in Stack`
`00:00:16.303 [WARN] (Wabbajack.Compiler.MO2Compiler)      metas\Root Builder 4.4.2-31720-4-4-2-1676456105.zip.meta - No Match in Stack`
`00:00:16.303 [WARN] (Wabbajack.Compiler.MO2Compiler)      metas\4GB Patcher-62552-1-5-1618787921.7z.meta - No Match in Stack`
`00:00:16.303 [WARN] (Wabbajack.Compiler.MO2Compiler)      metas\New Vegas Script Extender (NVSE)-67883-6-2-9-1668040642.7z.meta - No Match in Stack`
`00:00:16.303 [FATAL] (Wabbajack.Compiler.MO2Compiler) Exiting due to no way to compile these files`
`00:00:16.315 [INFO] (Wabbajack.CompilerVM) Failed Compilation : Compilation Failed|System.Exception: Compilation Failed`
`   at Wabbajack.CompilerVM.<StartCompilation>b__138_0() in c:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Compilers\CompilerVM.cs:line 318`
</details>

**Comment by EzioTheDeadPoet** [comment]
This issue is because your downloads folder is inside of MO2 if you have it located somewhere else outside of MO2 you can name it how ever the F you want. The problem is WJ needs to hash the MO2 folder for files that it needs to replicate. And in case some people don't move the downloads all in a centralized place wabbajack is set to ignore the `downloads`
 folder by default since it is the MO2 default.

Example of how I do it:
 `D:\WJ Downloads\{list_name}` with the list being `D:\WJ Projects\{list_name}` (list_name doesn't need to be the same name, it is just how I do it) 

But you could also just use the compiler settings to tell WJ to ignore the `metas` folder and it would work IF you want a custom folder name and the folder present inside the MO2 location.

This is not a bug.
