### ISSUE TITLE
manualURL Prompt Issue

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#2309]
**Describe the bug**

If two different meta files using manualURL have the same URL, then only one prompt is displayed even if the prompts are different.

Example:

```
manualURL=https://www.loverslab.com/files/file/26009-sexlab-parasites-kynes-blessing-se-february-2023/
prompt=Please download ParasitesSE20230226.7z
```

and

```
manualURL=https://www.loverslab.com/files/file/26009-sexlab-parasites-kynes-blessing-se-february-2023/
prompt=Please download ParasitesTexturesSE20230226.7z
```

Will show the first prompt for both files during installation. The manualURL must be unique to have the different prompts show up.

**Additional Context**

I'm not really sure if this is a bug but it definitely took some work to figure out why this was happening. At minimum should probably be documented on the Wiki in the section regarding manualURL. 

Just let me know if you need anything else and I'll get it for you. :)

**Wabbajack Version**

3.0.6.2

**Logs**

N/A

**Comment by EzioTheDeadPoet** [comment]
A possible workaround is to make it clear in the prompt that the page needs 2 files and naming both of them. (That way users have an easier time guessing the right file.)
Downside until there is a proper fix for it you would need to update all double prompts each time.

**Comment by EzioTheDeadPoet** [comment]
There is a new potential solution of only having one file use `manualURL` (so the app can login to the website) and having all other files use `directURL` again.
