### ISSUE TITLE
Add setting for default WorkQueue size

### ISSUE THREAD

**Issue by y785** [wabbajack-tools/wabbajack#231]
**Is your feature request related to a problem? Please describe.**
WorkQueue defaults to ``Environment.ProcessorCount`` thread count/queue size. During download phase this isn't necessarily an issue. However; during extraction, on my PC, this spawns x16 7zip processes each with 1~4GB memory. For smaller packages, this doesn't happen, but the FO4/SSE modlists include some rather large overhaul mods which  take time to extract -- thus causing multiple processes to queue with large memory overheads. I'm not sure if this can be remedied through a 7z argument or not.

**Describe the solution you'd like**
A .json config option to set default size.

**Additional context**
I wasn't able to install FO4/SSE packs without recompiling Wabbajack with a lower WorkQueue size, since I don't have 40~64GB memory, but I do have a 16-core processor.

**Comment by cahaseler** [comment]
A hacky workaround that did the job for me and my Ryzen 3600 / 16 GB of RAM: Open up task manager, expand the wj processes, and when you come close to maxing our your RAM, End Task on a 7zip process. The software can recover fine and retry the unzipping, but this buys enough time that you're not overloading your PC.

**Comment by Cheesypoofy1** [comment]
I've noticed something got changed in the past month that limits Wabbajack to only use a 6 thread queue for me whereas before it would utilize all 16 of my processor threads.  Seeing how 16 threads worked fine for me in the past when installing The Ultimate VR Hybrid List (110GB Install + 70GB Downloads), I would like the option of using more than 6 although not necessarily all 16 of my CPU threads.  I figure Wabbajack would only have an issue if there were a physical or user-set limit on the amount of RAM/virtual RAM available to Windows OS.

**Comment by halgari** [comment]
WJ isn't very CPU bound. So the current calculation is the lowest thread count recommended by:

* Number of cores in your system
* The speed of the drive on which Wabbajack.exe resides. The caching folder on that drive gets a lot of use, so every 50MB/sec of disk performance on that drive gives you 1 thread
* GB of RAM minus 2GB (for the OS) divided by 2GB. So 16GB of ram would get you: 16 - 2 / 2 = 7 threads. 

Changing these values too much results in sluggish systems during installs. The OS needs at least 2GB of RAM to operate, and each thread in Wabbajack can use upwards of 2GB of RAM while decompressing .7z files.

For a 16 core system you probably want at least 32GB of ram, and most likely a NVME drive. Anything less than that and Wabbajack is going to be slowed down by a lack of RAM and IO.

I realize this thread count also affects downloads, and so we can look into calculating thread sizes for downloads differently.

**Comment by Noggog** [comment]
Setting workqueue sizes via the GUI has been added.  I believe this issue is complete.
