### ISSUE TITLE
Installation failed - File in use by another process

### ISSUE THREAD

**Issue by Sabonnel1979** [wabbajack-tools/wabbajack#2315]
**Describe the bug**

i Keep getting an installation failed message then the cannot access file # File in use by another process, could anyone tell me how to fix this

I have seen this post 

https://github.com/wabbajack-tools/wabbajack/issues/860

but honestly dont understand what i need to do, if someone could give me brief "idiots" guide or tell me what i need to do/change it would be much appreciated

Version 3.0.6.2

log file if needed

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10974106/Wabbajack.current.log)

**Comment by Mieekaserra** [comment]
I've seen this before - on a user who was running a installation was getting some "next slide" errors so thought it had failed, he then used the back button and managed to restart the install again. 

Esentially having two install threads running at once.

**Comment by arieller** [comment]
Restarting the client solved the error for me

**Comment by EzioTheDeadPoet** [comment]
Note to myself:
Wiki FAQ needs expanding about the reasons why File Used by another process issues can happen, and the fixes for each cause.

**Comment by JanuarySnow** [comment]
Is it intended behavior that pressing the back button does not cancel the installation?

The downloads continue in the background while you are back on the WJ main menu.
