### ISSUE TITLE
No Wabbajack downloads - Nexus api call finished: 0 - Remaining limit: 10 000

### ISSUE THREAD

**Issue by ilnurshams** [wabbajack-tools/wabbajack#2333]
Describe the bug

Once I run Wabbajack, choose the install from disk option download won't start. In the bottom says - Nexus api call finished: 0 - Remaining limit: 10 000.  And nothing happening. I am trying to install "Skyrim VR Minimalistic Overhaul" according to the guide here - https://github.com/hitmantb/skvrmo/blob/main/README.md#installation

Additional Context

Completely new installation of Win 11, Steam, Skyrim VR , Clean Wabbajack v3.0.6.2 not in root or downloads folder. Everything new and fresh! 

Wabbajack Version

Wabbajack v3.0.6.2

Logs
[Wabbajack.00.log](https://github.com/wabbajack-tools/wabba
![2023-05-06 011711](https://user-images.githubusercontent.com/132715928/236577651-3563ac23-39f6-40c9-a513-bb37ba0bae31.png)
jack/files/11410458/Wabbajack.00.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/11410459/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Logout and back in to nexus in the settings.

**Comment by ilnurshams** [comment]
Of course I did that :) the issue is not that simple :) I've tried everything already

**Comment by snake06088** [comment]
p.s update. if you push "click here"  - then the next download will come, and everything seems to work as it should
![cc57a84f128b41f399f029d5a88d8be8](https://github.com/wabbajack-tools/wabbajack/assets/70540499/26fbff9a-ce89-46fb-9bfd-abae5fbf6b73)

**Comment by snake06088** [comment]
update 2: found out that when 5 seconds pass and the download should start, the download happens to the default download directory in the user profile. and when you click "click here", the download is transferred to the resources directory, as a result, I have 2 identical files saved, the first to the standard downloads folder, the second to the path that I indicated

**Comment by ilnurshams** [comment]
I bought a Nexus Premium subscription and fixed the issue. Apparently, only manual downloads are available with a free account.
