### ISSUE TITLE
The process cannot access the file 'Wabbajack.current.log' because it is being used by another process.

### ISSUE THREAD

**Issue by Leviathanas** [wabbajack-tools/wabbajack#2342]
**Describe the bug**

Wabbajack throws this error when at last stage of Tahrovin SSE VR modpack installation:
`00:11:50.989 [ERROR] (Wabbajack.InstallerVM) The process cannot access the file 'C:\Tahrovin\3.1.0.0\logs\Wabbajack.current.log' because it is being used by another process.|System.IO.IOException: The process cannot access the file 'C:\Tahrovin\3.1.0.0\logs\Wabbajack.current.log' because it is being used by another process.
`
**Additional Context**

Windows 10, fully updated.
AMD r5 3600
AMD 5700XT
16GB ddr4
Updated to Nexus premium halfway trough Wabbajack downloading files.

What I have tried:
- System restart, multiple times.
- Have renamed the logs to force it to create new ones.
- Renamed entire log folder to force it to create a new one.
- Disabled Defender (no other antivirus present).
- Added Wabbajack folder, logs folder and specific log to defender exceptions.
- Added Wabbajack %localapps% folder to defender exceptions.
- Started Wabbajack with nothing else running.
- Running wabbajack on single CPU thread

Similar issue:
(https://github.com/wabbajack-tools/wabbajack/issues/860)

**Wabbajack Version**
Wabbajack 3.1.0.0

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/11547984/Wabbajack.current.log)
Also added older (but larger) log:
[Wabbajack.current old.log](https://github.com/wabbajack-tools/wabbajack/files/11547998/Wabbajack.current.old.log)

**Comment by Leviathanas** [comment]
Found a workaround:

- Redownloaded the modslist into new folder: Target Modlist: C:\Tharovin2
- Made New: Modlist Installation Location: C:\Tharovin2Install
- Specified old folder as: Resource Download Location: C:\Tharovin (So I dont have to re-download everything)

Installation went without a hitch, mod pack is working in VR now.

**Comment by Mieekaserra** [comment]
Not a BUG: 

Your issue was because your download folder was C:\Tharovin\. As wabbajack was running  in C:\Tahrovin\3.1.0.0\. When it was hashing the downloads it was trying to hash every subdirectory underneath the download folder, which include, the install folder, the downloads and wabbajack's folder itself - including the log file wabbajack was writing to!

To prevent issues like this your downloads folder should have been defined as something like C:\Tharovin\Downloads
