### ISSUE TITLE
hashing files

### ISSUE THREAD

**Issue by kleshas** [wabbajack-tools/wabbajack#2346]
**Describe the bug**

Installing SME latest, and WJ seems to be hashing ALL files in the download folder, including ones not in the SME list.

**Additional Context**

Windows 10 Pro, 22H2

**Wabbajack Version**

v3.1.0.0

**Logs**

n/a

Is this expected?  If so, can you make it an option.  SME is only a few tens of GB and I have over 400GB of other files that WJ seems to need to hash.

**Comment by EzioTheDeadPoet** [comment]
If you use a shared downloads folder this is never going to be possible since WJ needs to look for which of the files in there have the hashes it needs.

The way you remove most of the already "optional" hashing steps is by setting the installation and the downloads path to empty folders.
