### ISSUE TITLE
Blank browser on 3.1.0.0 resolved on older version

### ISSUE THREAD

**Issue by lobotomy-x** [wabbajack-tools/wabbajack#2353]
Tried every possible fix including full reinstalling webview2 and edge, cleaning out everything related to wabbajack 3.1.0.0, restarting pc, trying out on a different user account, etc. Finally found an old closed issue stating the same issue and that 2.5.3.28 worked for them. Issue was closed and they were told not to use the unsupported version and just to try the same things I've already done. Gave it a shot and lo and behold it works perfectly and I've already downloaded two modlists without issues. 

Please look into it further because clearly something happened since that release.

**Comment by EzioTheDeadPoet** [comment]
Your windows installations are busted or outdated.

**Comment by EzioTheDeadPoet** [comment]
using 2.5 isn't supported and will cause issues.

**Comment by EzioTheDeadPoet** [comment]
The only authentication issues present are for LL and VP.

Both sites but especially LL have broken APIs (which does also affect 2.5.x.x).

The only issue that is actually present with downloads in the current release tag is an already fixed on the main branch oversight when moving to a new downloader by one of the new contributors.

This is an preview build posted with the code that fixes the new downloader:
https://github.com/UrbanCMC/wabbajack/releases/download/3.1.0-debug-1/wabbajack-download-debug.7z

In the next few days/weeks it should be released officially and digitally signed and with even more fixes and QoL improvements.
