### ISSUE TITLE
User placed the Installation folder *inside* the downloads' folder. Meta chaos and failed installation occurred.

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2372]
**Describe the bug**

As per title. - from Wildlander Discord.

**Additional Context**

I told you that they would find a "unique" way to bypass your checks @JanuarySnow 

**Wabbajack Version**

Wabbajack Version: 3.2.0.0

**Logs**
[message(5).txt](https://github.com/wabbajack-tools/wabbajack/files/12089516/message.5.txt)

**Comment by EzioTheDeadPoet** [comment]
![](https://media.giphy.com/media/lb5nMu0UIh4YM/giphy.gif)
