### ISSUE TITLE
MOISE Downloader gets stuck at Texture_Fix__Bloodmoon_1.1.7z

### ISSUE THREAD

**Issue by TigerMonkeyOne** [wabbajack-tools/wabbajack#2373]
**Describe the bug**

MOISE Downloader gets stuck at Texture_Fix__Bloodmoon_1.1.7z

**Additional Context**

COre i7, 1660 Super, 16gb ram Win 10, yada, yada

**Wabbajack Version**

Wabbajack 3.2.0.0

**Logs**

I don't have one

**Comment by GravenImages** [comment]
Don't think this belongs here, but I will copy a pinned message from Moise's support discord for this.
`Issues downloading Texture_Fix_Bloodmoon_1.1? 
Download the file from the following link and place it in the download location you set when installing the list then try the installation again in Wabbajack.
https://www.dropbox.com/sh/7fv2wojbp6y3uo9/AABdOQ5DflPDV3wb4bMx_snla/Texture_Fix__Bloodmoon_1.1.7z?dl=1 `

I have updated the readme page for this modlist to include this mirror link too, for other people that aren't in/don't want to join the support server.
