### ISSUE TITLE
[Feature Request] Tag/filter SSE mod lists that require the Anniversary Upgrade

### ISSUE THREAD

**Issue by CrazieIvan** [wabbajack-tools/wabbajack#2390]
Would you good people please consider creating a mandatory and clearly visible "AE" tag for all Skyrim mod lists that require the Anniversary Upgrade?  Not all AE list creators tag their mod lists for AE (e.g. Keizaal, Elysium), and the ones that do use inconsistent tags like "AE DLC" or "Anniversary Edition", and I think some even use "Creation Club Content" to mean "AE" which is very misleading and confusing because those are not the same thing.  But really, the biggest issue is that the tags are difficult to notice in an ocean of blue tags.  I think it would make sense if the AE tag is not optional, is consistent, and is made to stand out a little bit, so that SE users can easily make out the non-AE mod lists.  After all this tag is special because it indicates lists that are not compatible with SE, unlike the rest of the tags which just describe mod list features.

Or alternatively a way to filter out (exclude) AE lists would be really nice because technically AE is a different game from SE, for the purposes of choosing compatible mod lists.
I appreciate your consideration!

example
![01](https://github.com/wabbajack-tools/wabbajack/assets/69615600/903e3c84-3974-4ab0-a712-6a2489402fc4)

**Comment by EzioTheDeadPoet** [comment]
@tr4wzified maybe something to consider with your UI rework.

That said I personally think that it is hard to justify a dedicated UI feature for a thing that only effects a single game out of a large list of supported games.

**Comment by awalkonthebeach** [comment]
+1 
No "new feature" required here IMO.  I completely agree with the alternative suggestion in the OP, which is that Skyrim AE should have been a separate game category, just like SE is separate from LE.  There is really no point in seeing both SE and AE on the same screen, and for user who  can't install AE, it complicates the browsing.
Ideally, when a user opens a game category in WJ, they should be able to play any of the lists they see.
