### ISSUE TITLE
Wabbajack with GOG Fallout 4 GOTY version.

### ISSUE THREAD

**Issue by Kussh** [wabbajack-tools/wabbajack#2397]
**Describe the bug**

I get the error "Can't find game Fallout4" despite Wabbajack having found the installation directory of the game in the log file.

**Wabbajack Version**

Wabbajack v.3.2.0.1

**Comment by EzioTheDeadPoet** [comment]
1. The internal WJ index needs updating for games that are supported.
2. Most lists won't support the GOG version of the game.

**Comment by Kussh** [comment]
> 1. The internal WJ index needs updating for games that are supported.
> 2. Most lists won't support the GOG version of the game.

Thanks for the clarification.

**Comment by EzioTheDeadPoet** [comment]
If you want to try your luck you can use the preview build for the next WJ version which I updated today.
