### ISSUE TITLE
Update friendly behavior

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#24]
**Is your feature request related to a problem? Please describe.**
When updating a modlist already installed, you only need to download certain files and some minor/medium adjustments to your already installed mods. But if you try to use the new installer, it will delete all your installation and it will start again.

**Describe the solution you'd like**
To have a separation between downloading step and installing step, like two buttons, where you choose what process start. This way you won't hurt your installation and you will be able to download the new files.

**Describe alternatives you've considered**
Also to be able to add a changelog to the installations will help.

**Additional context**
For the updating purposes, it would be nice to print out what changes would be made if the installation continues, in order to make them manually.

**Comment by Noggog** [comment]
This all done /w #23 and #24?

**Comment by halgari** [comment]
Done in master, we now only download the files required, and we also only extract and install the files that have changed or are missing.
