### ISSUE TITLE
All versions cannot be logged in to two websites stuck on the loading page

### ISSUE THREAD

**Issue by qweqwedasdas** [wabbajack-tools/wabbajack#2401]
![07H`0BQYG%$268R5BTQ%Z}X](https://github.com/wabbajack-tools/wabbajack/assets/140939721/0e8f6c91-d0c5-4193-943e-ebfcb311ac93)

**Comment by EzioTheDeadPoet** [comment]
https://wiki.wabbajack.org/user_documentation/Troubleshooting%20FAQ.html#wabbajack-shows-a-black-screen-when-trying-to-x
