### ISSUE TITLE
Cannot click on anything in Nexus webview to start mod downloading

### ISSUE THREAD

**Issue by Tenoke** [wabbajack-tools/wabbajack#2421]
I could download mods before but had to stop the process. When I retry now (including after completely reinstalling wabjack, deleting wabjack in appdata etc.) I can see the Nexus webview but it doesnt register my clicks on the page to start a download.

I can navigate to the download button via Tab and press enter, but mouseclicks are ignored.

**Comment by EzioTheDeadPoet** [comment]
In app Browser issues like that were addressed with #2416.

If you encounter the issue after 3.3.0.0 is released as an official version we can look into this again.

**Comment by korah91** [comment]
It happens to me in 3.3.0.0. I have just fresh installed Wabbajack for the first time. When the tab of the mod opens, something appears for a milisecond, which I think its the cookie accepting advert. Maybe Wabbajack disables those cookies and Nexus doesnt allow to do anything more after that?

**Comment by EzioTheDeadPoet** [comment]
Ok this is an problem that seems unrelated to things I mentioned in my previous comment and is also tracked in issue #2427 where we managed to collect slightly more data about it. Any future information is ideally put there.
