### ISSUE TITLE
Error: Don't run Wabbajack as Admin

### ISSUE THREAD

**Issue by MorbidEden** [wabbajack-tools/wabbajack#2426]
**Describe the bug**

First time trying to launch Wabbajack in a custom folder on a secondary drive I get an Error popup stating "Don't run Wabbajack as Admin!" I do not have "Run as Administrator" checked in file properties.

**Additional Context**

OS: Win 11 Pro 22H2 Build 22621.2428

**Wabbajack Version**

3.2.0.1

**Logs**

No logs created.

**Comment by EzioTheDeadPoet** [comment]
https://wiki.wabbajack.org/user_documentation/Troubleshooting%20FAQ.html#dont-run-as-admin

**Comment by MorbidEden** [comment]
Missed that somehow. Thank you.
