### ISSUE TITLE
Manual Downloading on Nexus Mods can't use mouse only keyboard

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#2427]
**Describe the bug**

Manual Downloading doesn't accept mouse input on nexus mods, after a popup similar to a cookie popup has flashed the screen. 
Using `tab` to navigate the browser window still works.

**Additional Context**

Win10 (Confirmed), Win 11 (Of the users I asked so far it was only Win 10 but I also only asked 2 for their Win version and can't test 11 with premium rn)

**Wabbajack Version**

3.2.0.1 and 3.3.0.0-Preview have been tested and show this behavior.

**Comment by Mieekaserra** [comment]
from a user - this is the cookie:

![image](https://github.com/wabbajack-tools/wabbajack/assets/26418143/22585848-fcde-4e49-a453-45b694ddd666)

**Comment by Mieekaserra** [comment]
It would do. Its a Nexus change which hasn't been fixed yet.

Work around is to spam f5 until you can accept the cookie shown in the screenshot

**Comment by EzioTheDeadPoet** [comment]
Note for a possible relation:

- [Wabbajack.App.Wpf/UserIntervention/ManualDownloadHandler.cs#L24](https://github.com/wabbajack-tools/wabbajack/blob/ae7402be581389caa63374d067968f1dfad66bf1/Wabbajack.App.Wpf/UserIntervention/ManualDownloadHandler.cs#L24) check if that element is an iframe and possibly add an exception for the element.

**Comment by EzioTheDeadPoet** [comment]
**Update**: The message seems to be part of an iframe.
![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/33c24543-5adc-4f4e-8114-48ac04209774)

To-Do: figure out an identifier that is consistent to not clear that iframe.

**Comment by EzioTheDeadPoet** [comment]
Fixed in https://github.com/wabbajack-tools/wabbajack/releases/tag/3.3.0.1-pre
