### ISSUE TITLE
Wabbajack crashes on launch

### ISSUE THREAD

**Issue by thearnavjalan** [wabbajack-tools/wabbajack#2431]
https://github.com/wabbajack-tools/wabbajack/assets/68914183/e3e7caf7-f474-4d3c-a2c7-63b6da92fa05

This is the 3.0.0.0 version , and i have no idea what is going on.

**Comment by Mieekaserra** [comment]
Its known.

temp workaround:
create 3.2.0.1 folder where-ever you run wabbajack from
download and unzip https://github.com/wabbajack-tools/wabbajack/releases/download/3.2.0.1/3.2.0.1.zip to 3.2.0.1 folder and run wabbajack.exe inside of there

**Comment by thearnavjalan** [comment]
Thanks for the workaround , it worked.
