### ISSUE TITLE
0xc0000005 - Unexpected parameters error

### ISSUE THREAD

**Issue by r00tgrizzly** [wabbajack-tools/wabbajack#2440]
**Describe the bug**
I get this bug when mods are downloading. Wabbajack will download a couple of mods, then this error closes the application. 

**Additional Context**

Win 11, Skyrim AE
**Wabbajack Version**
 3.2.0.1

**Logs**
![image](https://github.com/wabbajack-tools/wabbajack/assets/108587257/354ca67b-ca2f-4297-b3d1-a3c31b66f739)

[Wabbajack.03.log](https://github.com/wabbajack-tools/wabbajack/files/13276996/Wabbajack.03.log)

**Comment by EzioTheDeadPoet** [comment]
make sure to use the latest pre-release for reporting bugs.

**Comment by Treefidi** [comment]
Using the latest 3.3.0.0-pre2 and still get this error. Can typically download 5-15 mods before clicking "Slow Download" results in the crash. Seems guaranteed after filling out the queue, then starting another when one finishes.

Wabbajack log doesn't produce anything useful, or any crash dumps in %LocalAppData%\CrashDumps. Only error message I can find is in Event Viewer below.

Setup info and solutions tried:
- MSI Z490-A Pro, i7-10700KF, RTX 3070, 32GB RAM, NVMe, Windows 10 22H2
- Proper folder structure (i.e: E:\Wabba\WJ.exe, C:\Lists\Install)
- Windows Defender exceptions for each folder (download, install, Steam, WJ, no 3rd-party AV)
- Disabling Defender
- Fresh 3.3.0.0-pre2 WJ install (AppData too)
- Updating to .NET 8 Framework
- Repaired/Re-installed WebView2
- Reduced RAM per thread (1021 → 512)
- Set Downloads + Installer MaxTasks to 1 in resource_settings.json
- Set ALL MaxTasks to 1
- Disabling XMP + CPU/GPU undervolts
- Confirmed Pagefile @ 25-60GB
- Moved Download folder to NVMe
- Run DISM/SFC
- Memtest'd RAM for 4 hours, 0 errors.

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/13278121/Wabbajack.current.log)

```
Log Name:      Application
Source:        .NET Runtime
Date:          11/7/2023 1:44:56 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-2TJC3B2
Description:
Application: Wabbajack.exe
CoreCLR Version: 8.0.23.47906
.NET Version: 8.0.0-rc.2.23479.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Wabbajack.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-11-07T07:44:56.1962385Z" />
    <EventRecordID>218217</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-2TJC3B2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Wabbajack.exe
CoreCLR Version: 8.0.23.47906
.NET Version: 8.0.0-rc.2.23479.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Wabbajack.App.Main()
</Data>
  </EventData>
</Event>
```

**Comment by enjibeamedyou** [comment]
> Had the exact same problem on latest pre-release/stable. Reducing to 400 Mb RAM per thread did the trick for me. Was able to download Tempus Maledictum almost from scratch in one go.

I apologize if I sound dumb as I am not that great with PC, with that being said, I also have the invalid parameters problem and if your fix is true, how do I reduce my MB ram per thread?

**Comment by EzioTheDeadPoet** [comment]
> > Had the exact same problem on latest pre-release/stable. Reducing to 400 Mb RAM per thread did the trick for me. Was able to download Tempus Maledictum almost from scratch in one go.
> 
> I apologize if I sound dumb as I am not that great with PC, with that being said, I also have the invalid parameters problem and if your fix is true, how do I reduce my MB ram per thread?

In the settings of the app.

**Comment by enjibeamedyou** [comment]
> > > Had the exact same problem on latest pre-release/stable. Reducing to 400 Mb RAM per thread did the trick for me. Was able to download Tempus Maledictum almost from scratch in one go.
> > 
> > 
> > I apologize if I sound dumb as I am not that great with PC, with that being said, I also have the invalid parameters problem and if your fix is true, how do I reduce my MB ram per thread?
> 
> In the settings of the app.

I've tweaked my settings, and I still get an error, I have 3460 threads, 16 gb ram, mx110 gpu if that helps, and I set it at 200 mb ram per thread.

**Comment by EzioTheDeadPoet** [comment]
3460 threads is literally impossible

**Comment by enjibeamedyou** [comment]
> 3460 threads is literally impossible

Not really tech savvy, but this is what it says on the performance tab

![image](https://github.com/wabbajack-tools/wabbajack/assets/150957306/ba0d7153-e57b-4fac-aab0-af5dd6dc9e2e)

**Comment by EzioTheDeadPoet** [comment]
![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/cc867de2-729e-411a-a9b0-caf93685d00b)
Your CPU has 8 threads.

**Comment by Treefidi** [comment]
> * Reduced RAM per thread (1021 → 512)

Just chiming in again to say: I did drop my RAM/thread down from 512MB to 100MB when I did all my testing, did not solve the issue for me.

**Comment by nikapaka00** [comment]
same here did try lots but still got same error

**Comment by nikapaka00** [comment]
but for me it wasnt a problem before i change my OS (was using 11 now it is 10) 
didnt get this error ever but now i got it

**Comment by EzioTheDeadPoet** [comment]
This issue should be fixed in the latest release.
