### ISSUE TITLE
Mediafire Popups

### ISSUE THREAD

**Issue by neochiken** [wabbajack-tools/wabbajack#2458]
Users of Tahrovin are getting Pop-up ads replacing the download window when manually downloading from mediafire
![image](https://github.com/wabbajack-tools/wabbajack/assets/30303959/70bdbe16-ff16-4adc-834a-6d31f474744b)

**Comment by neochiken** [comment]
the mods I know for a fact are impacted are:
https://www.mediafire.com/file/bks3dfn1kt62fay/[NINI]+Damaged+Feather.7z/file # [NINI] Damaged Feather
https://www.mediafire.com/file/ttxnmx35glfnl23/[NINI]+Adler.7z/file # [NINI] Adler
https://www.mediafire.com/file/bnqmaf6r5odxnd1/%255BNINI%255D_Operator_%255BSE%255D_-_CBBE.7z # Ninirim's Operator Armor

**Comment by tr4wzified** [comment]
Is this still an issue?

**Comment by neochiken** [comment]
MediaFire seems to have fixed it on their end
