### ISSUE TITLE
Having an issue when installing FUS for Skyrim VR

### ISSUE THREAD

**Issue by glenny3214** [wabbajack-tools/wabbajack#2460]
Here is the log file:

[Wabbajack.01.log](https://github.com/wabbajack-tools/wabbajack/files/13468410/Wabbajack.01.log)

I just need some help. I had the modlist installed before, but I was cleaning out some folders and had deleted FUS since it was 40+ Gigs before remembering what it was. Obviously, it was too big for the Recycle Bin, so it permanently deleted. I did a complete refresh and clean install of Skyrim VR after I received that error, but no luck. Even di what someone had said and deleted all of Skyrim's files and had Steam re-verify the files to reinstall them. All of this did not work. Please help.

**Comment by EzioTheDeadPoet** [comment]
please go to the discord support servers for issues with installing lists
