### ISSUE TITLE
Wabbajack does not remap gamePath in ModOrganizer.ini for Fallout 4

### ISSUE THREAD

**Issue by Yagisan** [wabbajack-tools/wabbajack#2461]
I have built my list using Fallout 4 GoG version.
Build log.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/13480026/Wabbajack.current.log)

I install my list using Fallout 4 Steam version.
Install log
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/13480045/Wabbajack.current.log)

Wabbajack does NOT remap the ModOrganizer.ini gamePath to the found install of Fallout 4.
Expected behaviour is Wabbajack remaps this.
Installed ModOrganizer.ini
[ModOrganizer.txt](https://github.com/wabbajack-tools/wabbajack/files/13480094/ModOrganizer.txt)

Windows 11.
Build: Fallout 4 GoTY - GoG.
Install: Fallout 4 Goty - Steam.

**Wabbajack Version**
3.4.0.0

**Comment by EzioTheDeadPoet** [comment]
@Yagisan can you confirm this behavior on the latest release ?
