### ISSUE TITLE
bsa's corrupting many times on install

### ISSUE THREAD

**Issue by Nazushvel** [wabbajack-tools/wabbajack#2462]
**Describe the bug**

I have attempted to download Elysium around 20 times at this point. Each time it fails on one of 3 files saying that the bsa is corrupted and to delete it and rerun wabbajack. 
I have attempted:
Deleting it and rerunning wabbajack
Manually downloading it from Nexus
Cleaning wabbajack
Using an older version of wabbajack
Using a different mirror on the nexus
Completely clearing the modpack & wabbajack and rerunning it

None of these have changed anything.

Also to clear some of the common ones.
I have over 300GB of freespace after the total size of the modpack
This is on an SSD C Drive
I have attempted this on my SSD D drive which has 2 TB free
Pagefile has been increased
I have 32GB of RAM

I have included the log from a completely fresh wabbajack install. It is using an older version but its the same log error as the updated version. It does give a little more information on the full stack so maybe that might help shed light into things.

**Additional Context**

OS: Win 10
Game: Skyrim AE
Modpack: Elysium Remastered

**Wabbajack Version**

Attempted with both 3.2.0.1 & 3.4.0.0

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/13629314/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
- This is an issue with either the BSAs being bigger than the soft cap of slightly under 3 or 4GB (forgot the actually value since I set my CAO to limit to the real deal when working on it).
- Or it is the bug that recently popped up with the mess that was/is the latest game update Bethesda pushed for which we can't do anything about either.

**Comment by Doido243** [comment]
I'm installing this same modpack and found a way to make it work normally. You have to keep the task manager open and finish all the microsoft edge webview2 that wabbajack opens

**Comment by tr4wzified** [comment]
WebView issue fixed in 3.4.2.0, BSA corruption issue fixed in 3.5.0.0
