### ISSUE TITLE
Wabbajack-CLI not working in 3.4.0.0

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#2465]
**Describe the bug**

Many people have reported that the Wabbajack CLI doesn't work.

**Wabbajack Version**

3.4.0.0

**Logs**

![image](https://github.com/wabbajack-tools/wabbajack/assets/52624146/d99bcb00-9636-4bdf-8ba2-3424b82b7b85)

**Comment by 13Voltz** [comment]
Install [.NET runtime 8](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

**Comment by EzioTheDeadPoet** [comment]
I already had it installed 😂.
The problem was that the build processes and output structure we used back on .NET 6.0 were somehow not possible to do with .NET 8.0 anymore which caused this error to either break the main app or the CLI after building depending on which order they were built in for the release.

But this is fixed in the latest release I just forgot to close this issue.
