### ISSUE TITLE
3.4.1.0 Autogenerated cli bat path is incorrect

### ISSUE THREAD

**Issue by 13Voltz** [wabbajack-tools/wabbajack#2472]
3.4.1.0 

In root dir, wabbajack-cli.bat attempts to access "C:\Wabbajack\3.4.1.0\wabbajack-cli.exe" as of 3.4.1.0 the correct path would be "C:\Wabbajack\3.4.1.0\cli\wabbajack-cli.exe"

**Comment by tr4wzified** [comment]
Fixed in 3.4.2.0+
