### ISSUE TITLE
"Page not found" error when getting Nexus API keys with Wabbajack

### ISSUE THREAD

**Issue by adam-poteralowicz** [wabbajack-tools/wabbajack#2475]
**Describe the bug**

"Page not found" message is displayed in WebView during modlist installation, in stage of Nexus API keys retrieval.
The problem seems to be that the wrong web URL is loaded inside the webview. It currently is:
`https://www.nexusmods.com/users/myaccount?tab=api`
but it should be:
`https://next.nexusmods.com/settings/api-keys`

**Additional Context**

Win 11, SSE

**Wabbajack Version**

3.4.1.0

**Comment by EzioTheDeadPoet** [comment]
This is being worked on. 
I am currently investigating if there are still accounts that would need the old method as a fallback implemented.
But a fix for this is on the way.

**Comment by Frakovich** [comment]
Have the same problem here ... not fixed for me. 
still have : https://www.nexusmods.com/users/myaccount?tab=api


Win 11, Family edition
Wabbajack Version 3.4.1.0

**Comment by EzioTheDeadPoet** [comment]
https://github.com/tr4wzified/wabbajack/releases/tag/3.4.1.0-pre-release-auto-request-apikey pre-release with a fix until we we can make a proper build.

**Comment by zacychan123** [comment]
Got the same issue the one day I finally get off work and want to play 🤣any fixes yet

**Comment by EzioTheDeadPoet** [comment]
> Got the same issue the one day I finally get off work and want to play 🤣any fixes yet 

literally the message above yours. 😂

**Comment by zacychan123** [comment]
Sorry sir I will download now, thanks

**Comment by DR-Dillon** [comment]
Unfortunately having this same issue. :(

**Comment by EzioTheDeadPoet** [comment]
read the previous messages for the workarounds until we release a new main update.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 1/12/24, 03:51 DR Dillon ***@***.***> wrote:

   
  Unfortunately having this same issue. :(

**Comment by tr4wzified** [comment]
Fixed in 3.4.2.0+
