### ISSUE TITLE
Pretty useless

### ISSUE THREAD

**Issue by Sirmadsen** [wabbajack-tools/wabbajack#2489]
This is a pretty useless app when there is now way to bypass manual approval of EVERY MOD without a premium subscription. Let me make this clear, you are literally forced to manually click download on more than 2,000 mods on larger packages, some upwards to 5,000. No, this is not a feature request, it's cry-post because that is some pretty bad behavior.

**Comment by Lartza** [comment]
Do suggest your ultimate monetization plan for Nexus so they can cater to free customers while paying for servers. (Don't actually...)

**Comment by CritLoren** [comment]
You're not forced to do anything, you can just get a smaller modlist, or go and use collections with hit or miss patching. We abide by Nexus' terms and not bypassing their API access - a feature they charge users for. Trying to work around it would put us at odds with Nexus and that would be bad for everyone.

Here's some tips:
 - Download in batches, you don't need to manually download all of them in the same session, you can download a few every evening, next time you restart Wabbajack it'll continue just like before;
 - Save up some money and buy a single month of Nexus premium, if you've got a day job it's understandable you value your time, so consider how much time you'd be saving by paying the $5 or however much it was now for one month.

**Comment by Aegis270** [comment]
It may seem like it takes a while, but even without premium it's still much faster than manually building a modlist of that size and quality yourself. 

You don't have to curate mods to pick the diamonds out of the rough, WJ does that for you.

You don't have to manually scroll through the mods one by one to get to the downloads page, WJ does that for you.

You don't have to spend days or weeks on conflict resolution and patching, the modlist creator does that for you. 

All you have to do is manually click a button a certain number of times, which you would have had to do anyways for building a modlist. All the rest of the work is done for you.
