### ISSUE TITLE
Wabbajack throws and exception when parsing Steam manifest

### ISSUE THREAD

**Issue by 2KDrop** [wabbajack-tools/wabbajack#2505]
**Describe the bug**

Steam manifest file is unable to be parsed leaving me unable to install lists for Steam games

**Additional Context**

Windows 10, Skyrim Special Edition but most likely affects all Steam related games

**Wabbajack Version**

3.5.0.1

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/14256986/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
You are still banned from using WJ for trying to evade the ban of a banned list.

**Comment by 2KDrop** [comment]
I'm sorry but I'm not sure what you mean? The only lists I've downloaded and installed were always available through either Wabbajack itself or Licentia MAX from the Jolly Co-operators discord.

**Comment by EzioTheDeadPoet** [comment]
My device seems to just have opened an old log by someone else that was banned.

**Comment by EzioTheDeadPoet** [comment]
https://github.com/LostDragonist/steam-library-setup-tool/releases/tag/3.2

Use this tool to scan and list all your libraries one of them is probably corrupted or broken and needs fixing on your end.

**Comment by 2KDrop** [comment]
Ah, left me a bit worried there for a moment. I'll get back to you ASAP (hopefully by tomorrow) as it's quite late for me at this moment.

**Comment by 2KDrop** [comment]
Tried launching that tool, loaded all of my libraries fine so I'm not sure what could be going wrong on Wabbajack's end. I do use the steam beta client but I don't see how that could cause a failure in parsing the manifest file

**Comment by 2KDrop** [comment]
Found the issue, one of my drives was named with a quotation mark as part of its name, which was causing GameFinder to be unable to parse the LibraryFolders.vdf file.
