### ISSUE TITLE
Downloads stop working when using free Nexus

### ISSUE THREAD

**Issue by nxllxvxid** [wabbajack-tools/wabbajack#2510]
When using a non-premium Nexus account if you queue multiple files to download some will pause and not download, nor will hash check find that these files are incomplete

Windows 11 Pro Insider Preview Build 26068.ge_release.240209-1555, any game

Wabbajack Version 3.5.0.2

**Comment by elinmyr** [comment]
Same issue. It's my understanding Wabbajack should be prompting me to manually download mods with a non-premium account. Instead, it just spams the log with download errors/failures.

Upgraded to nexus premium and it works perfectly. If this is not intended behavior, it's definitely bugged.

**Comment by EzioTheDeadPoet** [comment]
If you encounter this issue you need to logout and back in to Nexus with Wabbajack.

**Comment by nxllxvxid** [comment]
> Same issue. It's my understanding Wabbajack should be prompting me to manually download mods with a non-premium account. Instead, it just spams the log with download errors/failures.
> 
> Upgraded to nexus premium and it works perfectly. If this is not intended behavior, it's definitely bugged.

no this is not the error I am reporting. it does everything it needs to do with poppin windows and allowing me to click, but when they are in the queue they will randomly stop downloading.

**Comment by Mieekaserra** [comment]
Think that's either a blip in your internet connection (or nexus's)  that causes that.

You may see in your log error messages such as internal server errors or timeouts. You just need to retry the downloads.
