### ISSUE TITLE
Unable to install skyrim mods

### ISSUE THREAD

**Issue by Sizematter5** [wabbajack-tools/wabbajack#2511]
Hello guys i have tried to install various mods for skyrim using wabbajack, each time i try when it gets to the end of the download it crashes or fails. ive got these errors.
aller) Unable to download Data_ccbgssse037-curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.esl)
00:13:06.524 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.bsa)

**Comment by EzioTheDeadPoet** [comment]
this is not a Wabbajack issue but instead with how you setup your game before installing the list, which is explained in the written instructions for lists.
