### ISSUE TITLE
Game Support: Stalker Anomaly

### ISSUE THREAD

**Issue by Rage-GitHub** [wabbajack-tools/wabbajack#2517]
So, like #1646 this is a request or info dump for Stalker Anomaly support.

The idea is that from what I understand, ModDB actually supports automatic downloads, similar to Nexus, but at a more limited rate. You can request downloads via the addon page using the download button, which most people on there do use for their main downloads, by specifying the link like so: https://www.moddb.com/addons/start/266153 The only significant change in the link would be the addon ID at the end, the **266153**. This automatically starts a download via the fastest mirror available, and if it fails, can retry on another mirror. This way, you also aren't redistributing files and instead downloading them directly from the source, contributing to the authors values.

And **_if_** there was an addon that needed to be downloaded elsewhere, it could be done like any other mod that is used in a Wabbajack list and use the direct URL to specify a google drive ID, or even the Wabbajack CDN. The majority of time people host their extra files on Google Drive anyway.

A modpack, one you guys probably already know, Gamma does it in a similar fashion which pulls all the downloads and just specifies install instructions via the file or folder name the addons archive. You can actually even take a look at this via the [api list](https://stalker-gamma.com/api/list) that Grok provides. There is also actually a [metadata txt file](https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_data/modpack_maker_list.txt) that is used to make the list of mods and their install instructions, similar to Wabbajack.

So to say the least, from my understanding, this could be as simple as adding support like you guys did when [Valheim](https://github.com/wabbajack-tools/wabbajack/pull/2248) was added. Personally, I would do this myself but I have zero knowledge on any of this and would rather have someone who is more experienced and trusted to do this.

**Comment by EzioTheDeadPoet** [comment]
Not possible because the game is not supported by Gamefinder.
