### ISSUE TITLE
Can't find game SkyrimSpecialEdition 

### ISSUE THREAD

**Issue by CaptainTournesolCloud** [wabbajack-tools/wabbajack#2523]
**Describe the bug**

Wabbajack cannot find Skyrim SE, thus I cannot being downloading any modlist

**Additional Context**

New Windows 11 install. Fresh Skyrim and Wabbajack install. I verified the intergrity of Skyrim's files and I deleted wabbajack's appdata folder.

**Wabbajack Version**

3.5.0.1

**Logs**
`############ Wabbajack log file - 2024-03-31 20:52:52.6565 ############
00:00:00.000 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Unable to open HKEY_LOCAL_MACHINE\Software\GOG.com\Games
00:00:00.006 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests does not exist!
00:00:00.006 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:/ProgramData/Origin/LocalContent does not exist!
00:00:00.006 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Data folder C:/ProgramData/EA Desktop does not exist!
00:00:00.258 [INFO] (Wabbajack.MainWindowVM) Assembly Location: C:\Games\Wabbajack\3.5.0.1\Wabbajack.dll
00:00:00.258 [INFO] (Wabbajack.MainWindowVM) Process Location: C:\Games\Wabbajack\3.5.0.1\Wabbajack.exe
00:00:00.258 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.5.0.1
00:00:00.258 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: b244aa4729869b4a69a22761c31a67d5a8c883b89861371c88e07f574297f096
00:00:00.258 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: b244aa4729869b4a69a22761c31a67d5a8c883b89861371c88e07f574297f096
00:00:00.385 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 5facc21865ebdd55e6be504e359a2dc1a66a6705
00:00:00.385 [INFO] (Wabbajack.MainWindow) Running in C:\Games\Wabbajack\3.5.0.1
00:00:00.385 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.22631.0
00:00:00.385 [INFO] (Wabbajack.MainWindow) System settings - (31.2GB RAM) (40GB Page), Display: 2560 x 1440 (15.8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.398 [INFO] (Wabbajack.LauncherUpdater) Deleting old Wabbajack version at: C:\Games\Wabbajack\3.5.0.1\Wabbajack.exe.WebView2\EBWebView\OriginTrials\0.0.1.4
00:00:00.398 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Dishonored Plus
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Librum VR
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Total Skyrim Overhaul
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Legends of the Frost
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Somnium
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Librum VR
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Somnium
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Librum SE
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Dishonored Plus
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Aurora - A Visual Overhaul
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Legends of the Frost
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image The Phoenix Flavour
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Aurora - A Visual Overhaul
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Tempus Maledictum
00:00:03.254 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Happy Fun Times
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Librum SE
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Total Skyrim Overhaul
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image The Phoenix Flavour
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Tempus Maledictum
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Aldrnari
00:00:03.267 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Arkay's Commandment
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Slidikins' Strenuous Skyrim
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Magnum Opus
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Degenerate Dungeon
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Fallout VR Essentials Overhaul
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Yggdrasil VR
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Degenerate Dungeon
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Skyrim Modding Essentials
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Yggdrasil VR
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image MOISE
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ultimate VR Essentials
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Arkay's Commandment
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Skyrim Modding Essentials
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Lost in Space
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Magnum Opus
00:00:03.283 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Happy Fun Times
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Slidikins' Strenuous Skyrim
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Welcome to Paradise
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Lost in Space
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ultimate VR Essentials
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Fallout VR Essentials Overhaul
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image MOISE
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Aldrnari
00:00:03.302 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Welcome to Paradise
00:00:03.371 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image ADT
00:00:03.371 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image ADT
00:00:03.637 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Nervears Nwahs
00:00:04.852 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image SSEE
00:00:05.863 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Path of the Dovahkiin
00:00:05.863 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Path of the Dovahkiin
00:00:05.902 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image SSEE
00:00:09.512 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Silent Skyrim
00:00:12.526 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Silent Skyrim
00:00:27.242 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:27.242 [INFO] (Wabbajack.InstallerVM) Preparing MegaDownloader
00:00:27.242 [INFO] (Wabbajack.Downloaders.ModDB.MegaDownloader) Logging into Mega without credentials
00:00:27.448 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:27.448 [INFO] (Wabbajack.LoginManagers.NexusLoginManager) Logging into Nexus Mods
00:00:29.582 [INFO] (Wabbajack.Services.OSIntegrated.TokenProviders.NexusApiTokenProvider) Setting token nexus-login
00:00:30.480 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:30.480 [INFO] (Wabbajack.InstallerVM) Preparing WabbajackCDNDownloader
00:00:30.480 [INFO] (Wabbajack.InstallerVM) Preparing GoogleDriveDownloader
00:00:30.490 [ERROR] (Wabbajack.InstallerVM) Can't find game SkyrimSpecialEdition|System.Exception: Can't find game SkyrimSpecialEdition
   at Wabbajack.Downloaders.GameFile.GameLocator.GameLocation(Game game) in C:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameLocator.cs:line 149
   at Wabbajack.InstallerVM.<BeginInstall>b__134_0() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 506`

**Comment by EzioTheDeadPoet** [comment]
Please join the discord for support with this issue.
https://discord.gg/wabbajack
