### ISSUE TITLE
[Feature Request] Ignore Hash file mismatch option when installing from CLI

### ISSUE THREAD

**Issue by Onitone** [wabbajack-tools/wabbajack#2526]
**Is your feature request related to a problem? Please describe.**

In the event one mod updates, the mod author must **immediately** update, otherwise the hash files will not match between new and old versions.

**Describe the solution you'd like**

I think that, should the user be savvy enough to use the CLI, they can be trusted with an unsupported install, such that the installer will ask if the user would like to install the files despite hash mismatch.

**Describe alternatives you've considered**

Alternatives range from recompiling the modlist myself to simply waiting.

**Additional context**

In the event a mod author loses their access to the original mod list between updates, the mod list could potentially stop working permanently. I suspect this last ditch effort to install could prevent alot of headache for the mod authors. This could happen due to mechanical failure of the building PC.

**Comment by EzioTheDeadPoet** [comment]
It doesn't work that way because WJ does more than just extract some archives.
This can't be implemented without breaking everything or literally re-writing the whole app to be worse at replicating the proper installation.
