### ISSUE TITLE
[Against Nexus TOS] Automate downloading for Free Nexus Users

### ISSUE THREAD

**Issue by einekratzekatze** [wabbajack-tools/wabbajack#2536]
Problem: Packs like Fallout New Vegas: Begin Again have over 600 mods, which needs 600 clicks, every like 3 seconds. So a user needs to sit and click for half an hour.

Solution: some kind of script that clicks download for you. 

(If this is ToS related, simply close/won't fix the Issue)

**Comment by JanuarySnow** [comment]
it is against Nexus TOS, therefore wont ever be implemented.
