### ISSUE TITLE
Unable to download Fallout4.ini (GamefileSourceDownloader+State Fallout4VR  1.2.72 Fallout4.ini

### ISSUE THREAD

**Issue by Finnedsgang** [wabbajack-tools/wabbajack#2537]
At the end of the installation process of the Mad God's Classic Overhaul VR for Fallout 4 VR 
I receive this error message :

Unable to download Fallout4.ini (GamefileSourceDownloader+State Fallout4VR  1.2.72 Fallout4.ini 

**Additional Context**

I downloaded all the classic files
I double checked in the Fallout 4 Folder on Steam and there is a file Fallout4_Default.ini, i also changed the name to Fallout4.ini, but with no luck.
I also checked in the Fallout 4 VR folder, and there's a file called Fallout4.ini, but the installation, seems can't find it or access to it.

I started both games the first time to have the folders populated. 

I've the Goty Version with 32 DLC and Fallout VR. 

Windows 10 - Steam Key - latest version of both games

**Wabbajack Version**
3.5.0.1. 

**Logs**
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Fallout4.ini
00:02:00.570 [ERROR] (Wabbajack.Installer.StandardInstaller) Missing game file Fallout4.ini. This could be caused by missing DLC or a modified installation.
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:02:00.570 [INFO] (Wabbajack.Installer.StandardInstaller) Found 254 total files, 165 matching filesize
00:02:00.570 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4.ini (GameFileSourceDownloader+State|Fallout4VR|1.2.72.0|fallout4.ini)
00:02:00.570 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by Finnedsgang** [comment]
I found a solution, the problem seems the default language. (In my case is Italian). Changing to English, solved the problem

**Comment by EzioTheDeadPoet** [comment]
"User Error"
