### ISSUE TITLE
FO4 - Life in the ruins. Unable to download multiple data files

### ISSUE THREAD

**Issue by CasByrCol** [wabbajack-tools/wabbajack#2544]
Wondering if someone can tell me what the issue is here. Trying to install Life in the ruins and every time all of the downloads are finished it runs into the below errors. Any info or a possible fix is greatly appreciated:

00:11:47.013 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1138 total files, 1093 matching filesize
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download GFSDK_GodraysLib.x64.dll (GameFileSourceDownloader+State|Fallout4|1.10.980.0|gfsdk_godrayslib.x64.dll)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Medium.ini (GameFileSourceDownloader+State|Fallout4|1.10.980.0|medium.ini)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download High.ini (GameFileSourceDownloader+State|Fallout4|1.10.980.0|high.ini)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4.ccc (GameFileSourceDownloader+State|Fallout4|1.10.980.0|fallout4.ccc)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download installscript.vdf (GameFileSourceDownloader+State|Fallout4|1.10.980.0|installscript.vdf)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCworkshop01.esm (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\dlcworkshop01.esm)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4.exe (GameFileSourceDownloader+State|Fallout4|1.10.980.0|fallout4.exe)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4Launcher.exe (GameFileSourceDownloader+State|Fallout4|1.10.980.0|fallout4launcher.exe)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures2.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - textures2.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download steam_api64.dll (GameFileSourceDownloader+State|Fallout4|1.10.980.0|steam_api64.dll)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Ultra.ini (GameFileSourceDownloader+State|Fallout4|1.10.980.0|ultra.ini)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCRobot.esm (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\dlcrobot.esm)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4.esm (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4.esm)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCRobot - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\dlcrobot - voices_en.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Misc.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - misc.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Startup.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - startup.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures1.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - textures1.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures4.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - textures4.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures6.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - textures6.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Shaders.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - shaders.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Materials.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - materials.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCRobot - Main.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\dlcrobot - main.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Interface.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - interface.ba2)
00:11:47.057 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by SpadieM** [comment]
Figured it out, I did some searching and it turns out that this modlist has been updated to work with the newest version of Fallout 4, post-next-gen update. So try making a backup of your rolled back version and updating to the newest available version on steam, and then continuing with the Wabbajack install. I didn't need to redownload any Wabbajack stuff either, it's all extracting now! Good luck!
