### ISSUE TITLE
FO4 - Life in The Ruins - Unable to download Fallout4.exe and Data_Fallout4 - Interface.ba2

### ISSUE THREAD

**Issue by Punkcln** [wabbajack-tools/wabbajack#2547]
Downloading the Life in Ruins modlist for FO4 and encounter this error at the end of downloading step.
**What I've tried so far:**
1. Closing and restarting Wabbajack, pressing the play button again, still the same problem. Tried this for more than a few times now.
2. Verifying game files on STEAM, still same thing on the log.
3. Booted up the game, reached main menu, exited, problem persisted.
**Folder setups I've done**
1. I have Wabbajack and LifeinTheRuins folders on the SSD (E:\Wabbajack , E:\LifeIntheRuins , E:\LifeIntheRuins\downloads)
2. On Wabbajack installation screen of the modlist, I put the following in the boxes:
Target modlist: E:\Wabbajack\3.5.0.1\downloaded_mod_lists\wj-featured_@@_life_in_the_ruins.wabbajack
Modlist Installation location: E:\LifeIntheRuins
Resource download location: E:\LifeIntheRuins\downloads
3. I deleted my old Fallout4 folder from steamapps\common and let the reinstall made a new one (reinstall was on 14/5/2024)

**Wabbajack log** Wabbajack.current
00:00:00.604 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:25.533 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:25.533 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:25.533 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:25.566 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Life in the Ruins - 0.0.1.0
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: E:\LifeIntheRuins
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: E:\LifeIntheRuins\downloads
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: E:\SteamLibrary\steamapps\common\Fallout 4
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: E:\Wabbajack\3.5.0.1
00:00:25.583 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:26.382 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:26.382 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:26.685 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:26.770 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:26.770 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 146693 directives to 146693 required
00:00:26.800 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:26.800 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:26.800 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:26.800 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:26.811 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1153 total files, 1111 matching filesize
00:00:26.859 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 2 archives
00:00:26.859 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 2 archives
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Fallout4.exe
00:00:27.249 [ERROR] (Wabbajack.Installer.StandardInstaller) Missing game file Fallout4.exe. This could be caused by missing DLC or a modified installation.
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Interface.ba2
00:00:27.249 [ERROR] (Wabbajack.Installer.StandardInstaller) Missing game file Data_Fallout4 - Interface.ba2. This could be caused by missing DLC or a modified installation.
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:27.249 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:27.264 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:27.264 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1153 total files, 1111 matching filesize
00:00:27.301 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4.exe (GameFileSourceDownloader+State|Fallout4|1.10.980.0|fallout4.exe)
00:00:27.301 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Interface.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.980.0|data\fallout4 - interface.ba2)
00:00:27.301 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

I've seen some people getting similar issues but their fixes are updating the game to the newest version or verifying the game files, which I already did. Any help is appreciated.

**Comment by Mieekaserra** [comment]
Fallout4 updated Earlier. you'll need to downgrade to 1.10.980.0 or wait for list to recompile.
