### ISSUE TITLE
Incorporate "cli" verification as part of the normal Wabbajack installation.

### ISSUE THREAD

**Issue by KMan9454** [wabbajack-tools/wabbajack#2549]
I'd like to see the "cli" command be just the last step of the Wabbjack install.  Many times I've seen WJ complete successfully but the installation was corrupt.  This causes all the issues you would expect.

Many WJ users, are simply unfamiliar with how to run the command.  This then requires more time than it should to walk them through it.  

Wabbajack has everything in front of it to be able to run the command and it would only add a little time, depending on the user setup, to complete.

The result would be that when the installation is done, it would be really done.

I bring this up as a support person for a couple of large Wabbajack lists and I see this all the time.

Thanks for any consideration of this request.

**Comment by EzioTheDeadPoet** [comment]
This verification already happens as part of the installation process.

**Comment by KMan9454** [comment]
I replied to an email regarding this.

**Comment by EzioTheDeadPoet** [comment]
> This verification already happens as part of the installation process.
