### ISSUE TITLE
Cannot login to Nexus

### ISSUE THREAD

**Issue by bcbbrog55** [wabbajack-tools/wabbajack#2551]
**Describe the bug**

When entering Nexus login info, it displays error page not found on the nexus website. This does not allow login, even if I copy the link to another browser.

**Additional Context**

Win 11

**Wabbajack Version**

3.5.0.2

![Screenshot 2024-05-22 190450](https://github.com/wabbajack-tools/wabbajack/assets/5049978/b0f7e0e6-cf6b-426a-9ee5-85611bef3620)

**Comment by SolarusRex** [comment]
I am also encountering this issue. I have noticed that nexus is currently doing maintenance work which is affecting their performance, so this may be a temporary side effect, or part of the maintenance changed the intended webpage.

**Comment by Arqan93** [comment]
For me it says I'm logged out when trying to download a mod, but when I press "LOG IN", it show that I'm already logged in.
![1](https://github.com/wabbajack-tools/wabbajack/assets/170590022/67871e64-a952-4e65-83ec-c13791ce8a6b)
![2](https://github.com/wabbajack-tools/wabbajack/assets/170590022/9ee26914-9f3d-484a-b745-481dccf3f008)

**Comment by hadluk** [comment]
Having the same issue atm if its a nexus issue as Arqan93 is saying it should pass soon. Will try again tomorrow then. I have no issues loggin in but wabbajack does not understand that Im logged in it seems like to me.

**Comment by Drew-source** [comment]
i tried to use the new nexusloginhandler code and rebuilt the app with dotnet but no luck.

**Comment by EzioTheDeadPoet** [comment]
fixed by #2559
