### ISSUE TITLE
browser auto-closes whenever i hover over a clickable link

### ISSUE THREAD

**Issue by gibby545** [wabbajack-tools/wabbajack#2553]
**Describe the bug**
While manual downloading mods in a modpack, the browser comes up but after the first manual download will auto minimize the page when i hover over the download link, or any other clickable link. tab closes the page so keyboard controls are also out. 

**Additional Context**

SSE, Windows 10

**Wabbajack Version**
3.5.0.2

**Logs**

**Comment by tr4wzified** [comment]
Need a log before we can start investigating this one. Feel free to reopen if you got one.
