### ISSUE TITLE
Nexusmods login error

### ISSUE THREAD

**Issue by Rimuruuuuuu** [wabbajack-tools/wabbajack#2555]
This is more like a question than a bug report, because the bug has been reported already, is there a way to manually login to nexusmods from Wabbajack?

**Comment by Mieekaserra** [comment]
As a work around, try the following steps

1. Log in to nexus mods as per normal.
2. On error page, right click and select "Inspect"
3. Click the "Application" tab in the options - should be near the right
4. Select cookies then nexusmods.com
5. Find cookie named "nexusmods_session" 

either

6a. Rename it to "SessionUser" (which will "log you out", attempt to relog back in and you'll be gucci)
6b. Add a cookie in for the  "SessionUser", using the value from "nexusmods_session" (I haven't tested but see no reason it wouldn't work with a similar refresh/logout/in)

**Comment by Rimuruuuuuu** [comment]
> As a work around, try the following steps
> 
> 1. Log in to nexus mods as per normal.
> 2. On error page, right click and select "Inspect"
> 3. Click the "Application" tab in the options - should be near the right
> 4. Select cookies then nexusmods.com
> 5. Find cookie named "nexusmods_session"
> 
> either
> 
> 6a. Rename it to "SessionUser" (which will "log you out", attempt to relog back in and you'll be gucci) 6b. Add a cookie in for the "SessionUser", using the value from "nexusmods_session" (I haven't tested but see no reason it wouldn't work with a similar refresh/logout/in)

Oh my god it finally worked, thank you so much.
