### ISSUE TITLE
Cannot continue, was unable to download one or more archives

### ISSUE THREAD

**Issue by STNath** [wabbajack-tools/wabbajack#2564]
**Describe the bug**

I was downloading the Eldergleam modlist for Skyrim AE yesterday. Followed all of the steps on the nexus page of this modlist. However, it was taking way longer than expected so I went to bed while Wabbajack was downloading the last ten files. In the morning, I came back to an error message. Tried restarting the install, it keeps giving the same logs. Already tried logging out & logging back in again to Nexus.

**Additional Context**

Windows 11

**Wabbajack Version**

v3.6.0.0

**Logs**

https://github.com/wabbajack-tools/wabbajack/files/15446498/Wabbajack.06.log

**Comment by EzioTheDeadPoet** [comment]
Not a WJ issue. You are either missing DLC or haven't followed the written instructions correctly.
