### ISSUE TITLE
Nexus Mods login issue

### ISSUE THREAD

**Issue by DRYN07** [wabbajack-tools/wabbajack#2567]
For a few days there were a login authentication issue on nexus. The Nexus status page says it is solved but I still cannot download with wabbajack.

![image](https://github.com/wabbajack-tools/wabbajack/assets/29770761/762673e4-bcc6-4a24-bb0f-82922effced7)

**Comment by EzioTheDeadPoet** [comment]
You need to update Wabbajack

**Comment by DRYN07** [comment]
Well, it was clear enough that I didn't think of it. Although Wabbajack didn't indicate that there was a new version.
