### ISSUE TITLE
Starfield support added, but compilation currently impossible due to file format differences

### ISSUE THREAD

**Issue by cacophony-wj** [wabbajack-tools/wabbajack#2587]
**Describe the bug**

Although Starfield and its hashes were added to the repository, WJ currently fails to recognize some of the files during compilation, presumably due to changes in the files' structure

**Additional Context**

Starfield, Windows 11

**Wabbajack Version**

3.6.1.1

Attached as a file / link

[Wabbajack.00.log](https://github.com/user-attachments/files/15810645/Wabbajack.00.log)

This report is made on behalf of another author, the log is not from my machine

**Comment by tr4wzified** [comment]
Got a beta release out with Starfield support.

- Source: https://github.com/tr4wzified/wabbajack/commits/starfield-ba2/
- Download: https://mega.nz/file/4GB3wCTS#6vGbQuKz4rIOE4PRPXCHmna27-_SvbXiUzTbvlGONqc
