### ISSUE TITLE
the button to change default app for .json is not there...

### ISSUE THREAD

**Issue by portal-draakje** [wabbajack-tools/wabbajack#2594]
![Schermafbeelding 2024-07-06 140141](https://user-images.githubusercontent.com/69325629/346300914-2c0378ec-1899-48ec-90c9-b4f837cda7ee.png)
i want to change the default app but the button to change it is not there. i did also try to go in to the windows settings but there at the place microsoft says it needs to be, there were the options to change most default apps. but i did not find the .json so i dont know how to change the default app for .json...

              > but the button is not there...

https://www.google.com/search?q=how+to+set+app+for+file+type+windows+11

_Originally posted by @EzioTheDeadPoet in https://github.com/wabbajack-tools/wabbajack/issues/2202#issuecomment-2211980485_

**Comment by EzioTheDeadPoet** [comment]
It is not our job to teach you how to set default apps on windows for your file types.

**Comment by EzioTheDeadPoet** [comment]
You can just create a dummy file that you give the file ending `.json` and set the default app using that.

**Comment by portal-draakje** [comment]
i did already try that.

**Comment by portal-draakje** [comment]
> You can just create a dummy file that you give the file ending `.json` and set the default app using that.

if someone has the same problem it's more easy if someone else did already ask how to solve it. because if someone knows how to solve it, and he keeps it for him self, than this type of chats are useless...

**Comment by portal-draakje** [comment]
i think it's fun to think with multiple humans about one problem.
