### ISSUE TITLE
Inability for Compiler to Manage BSAs with Atypical Characters

### ISSUE THREAD

**Issue by Nickchapman3773** [wabbajack-tools/wabbajack#2601]
[Wabbajack.00.log](https://github.com/user-attachments/files/16316917/Wabbajack.00.log)

If BSAs contain characters like + in the title, it causes the compiler to stop reading anything beyond that. For example, xx_katana+sheath.nif gets treated as xx_katana.nif. These textures (as far as I can tell) work appropriately in-game without issue. In the WJ compilation process it reports duplicate xx_katana.nif and errors.

**Comment by tr4wzified** [comment]
This should have been fixed as of 3.7.1.0. Please report back if this is still an issue you're experiencing, with the game you're using and a full log.
