### ISSUE TITLE
TexConv.exe failures.  

### ISSUE THREAD

**Issue by BlakeLivSim** [wabbajack-tools/wabbajack#2603]
Consistently (but randomly, not seemingly due to a particular mod or filename) the Wabbajack installation fails (In this case, using the Opus Magnum modlist for FO4).  This is on WJ 3.7.0.0, Windows 10.  

Log reports the following more or less the same when the error occurs: 

> 00:01:28.725 [ERROR] (Wabbajack.InstallerVM) Error executing C:\Wabbajack\3.7.0.0\Tools\texconv.exe - Exit Code -1073741819 - Check the log for more information - "C:\Wabbajack\3.7.0.0\temp\5484_a4b486d9-0c2e-4743-bc38-b9c3918b8683\74160645-71b2-4413-926e-5addbf4e784d.DDS" -ft DDS -f BC3_UNORM -o "C:\Wabbajack\3.7.0.0\temp\5484_a4b486d9-0c2e-4743-bc38-b9c3918b8683\c21652c5-d361-4ec2-8a5f-e656ae196333" -w 512 -h 512 -m 10 -if CUBIC -singleproc|System.Exception: Error executing C:\Wabbajack\3.7.0.0\Tools\texconv.exe - Exit Code -1073741819 - Check the log for more information - "C:\Wabbajack\3.7.0.0\temp\5484_a4b486d9-0c2e-4743-bc38-b9c3918b8683\74160645-71b2-4413-926e-5addbf4e784d.DDS" -ft DDS -f BC3_UNORM -o "C:\Wabbajack\3.7.0.0\temp\5484_a4b486d9-0c2e-4743-bc38-b9c3918b8683\c21652c5-d361-4ec2-8a5f-e656ae196333" -w 512 -h 512 -m 10 -if CUBIC -singleproc

**Additional Context**
This was on a fresh install of FO4 

**Wabbajack Version**

**Logs**
[Wabbajack.28.log](https://github.com/user-attachments/files/16404040/Wabbajack.28.log)
[Wabbajack.29.log](https://github.com/user-attachments/files/16404041/Wabbajack.29.log)
[Wabbajack.30.log](https://github.com/user-attachments/files/16404042/Wabbajack.30.log)
[Wabbajack.31.log](https://github.com/user-attachments/files/16404043/Wabbajack.31.log)
[Wabbajack.32.log](https://github.com/user-attachments/files/16404044/Wabbajack.32.log)
[Wabbajack.33.log](https://github.com/user-attachments/files/16404045/Wabbajack.33.log)
[Wabbajack.34.log](https://github.com/user-attachments/files/16404046/Wabbajack.34.log)
[Wabbajack.35.log](https://github.com/user-attachments/files/16404047/Wabbajack.35.log)
[Wabbajack.36.log](https://github.com/user-attachments/files/16404048/Wabbajack.36.log)
[Wabbajack.37.log](https://github.com/user-attachments/files/16404049/Wabbajack.37.log)

**Comment by Mieekaserra** [comment]
your missing the C++  pre-requirement

https://aka.ms/vs/16/release/vc_redist.x64.exe

may also need https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by BlakeLivSim** [comment]
Odd. I'm an Unreal developer so I have and use VS regularly, but I assumed maybe one niche runtime was missing.  I tried to install those files you mention and this is what it tells me : 
![VC_redist x86_qIY3vr5tB0](https://github.com/user-attachments/assets/b4e8e124-cb6e-495a-912f-64d62559defd)
![VC_redist x64_(2)_V7OZM8f1SX](https://github.com/user-attachments/assets/6d386bdd-1a43-4f1d-afdc-faa7c1f0b25a)

**Comment by tr4wzified** [comment]
Just wondering why you suggested installing those C++ redistributables @Mieekaserra? Encountered this issue before? I don't recognize it.

Is this the latest version of Magnum Opus from the gallery? I see version 0.1.0 mentioned. Old Wabbajacks won't work from 3.7.0.0 onwards because a breaking change was made in the texture compression department of BSAs so this error sounds like it's related.

**Comment by Mieekaserra** [comment]
Try installing  https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.4-windows-x64-installer as well then @BlakeLivSim 

@tr4wzified seen it a total of 3 times. Exit Code -1073741819 means very helpfully "missing depenancy"

**Comment by tr4wzified** [comment]
Assuming Mieekaserra's fix resolved the issue. If not, then reopen this with more info
