### ISSUE TITLE
Windows error when writing manual helper report

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2611]
**Describe the bug**

Has user's report that when they get the line "building manual helper report" they get a windows error
![image](https://github.com/user-attachments/assets/4afa2f57-9234-4f14-b80d-2e613b9aaf5d)

**Wabbajack Version**

3.7.2

**Logs**

https://cdn.discordapp.com/attachments/666599178788536331/1277668930525331540/Wabbajack.current.log?ex=66ce016a&is=66ccafea&hm=f7739a1de31af30e8acc3d94d92af5dfa09527e50aabf6aaffdb2854810b1ce3&

**Comment by KrumRum** [comment]
Same issue here, tried multiple different folders, re-installing the game, etc.

![cannot find](https://github.com/user-attachments/assets/d3d87a62-cbd6-4ace-a338-cdf8d097845b)

**Comment by tr4wzified** [comment]
Fixed in 3.7.2.1
