### ISSUE TITLE
WJ app looking for wrong "compiler_setting" name. 

### ISSUE THREAD

**Issue by Seatmeister** [wabbajack-tools/wabbajack#2615]
**Describe the bug**

When loading a compiler_setting. file via the WJ app it searches for "compiler_settings" (with S at the end) not "_setting" despite WJ itself generating said file as "compiler_setting".  This can be fixed simply be fixed by renaming the file to the correct file name.

**Additional Context**

---

**Wabbajack Version**

v3.7.2.1

**Logs**

No log.

**Comment by EzioTheDeadPoet** [comment]
https://github.com/search?q=repo%3Awabbajack-tools%2Fwabbajack+CompilerSettings&type=code

https://github.com/search?q=repo%3Awabbajack-tools%2Fwabbajack+compiler_setting&type=code

This seems very unlikely 🤔

**Comment by EzioTheDeadPoet** [comment]
https://github.com/search?q=repo%3Awabbajack-tools%2Fwabbajack+etting&type=code even here it looks like the only file type extension for compiler settings is `.comiler_settings`. 

So you likely got your file from somewhere else and it caused some confusion 🤔 

Please send more info describing exactly what you tried.
