### ISSUE TITLE
Ensure changing the NXM links to match game IDs doesn't break Wabbajack's client

### ISSUE THREAD

**Issue by Pickysaurus** [wabbajack-tools/wabbajack#2625]
**Describe the bug**
Currently, several NXM links use a different ID to the game domain found on the website. 

| Game | Game ID | NXM ID |
|--------|--------|--------|
| Skyrim SE| `skyrimspecialedition` | `SkyrimSE` |
| Fallout NV | `newvegas` | `falloutnv` | 
| TESO | `elderscrollsonline` | `teso` |

We want to align these with the Game IDs but ensure the popular apps that use NXM links won't be impacted. 

**Additional Context**
https://github.com/Nexus-Mods/Vortex/issues/16552

**Comment by tr4wzified** [comment]
Hey, thanks for notifying us about this. I'll have a look later today to see if this affects WJ :)
