### ISSUE TITLE
Cyberpunk 2077 Squeegeepunk Issues

### ISSUE THREAD

**Issue by VRsingthegamez** [wabbajack-tools/wabbajack#2627]
**Describe the bug**

I have been having problems with the Squeegeepunk and have tried asking their discord to no answer. Basically, there are times when I launch my save in game, it crashes after trying to load. I saw some mods appearing as causing the crash and I tried disabling the Enviromental Textures, HD Mod, HD reworked project, and the Frame Generation mod that is included depending on the gpu or just in general. My theory is a lack of VRAM but I'm not fully sure at this point. There are times it does load in and the game works fine. I have tried Overwriting and verifying and even fresh install and still nothing. Before the latest Cyberpunk patch it was working fine but the list was updated for that patch afterwards to my understanding. 
**Additional Context**

Windwos 10 RTX 3070 16gb of Ram Ryzen 7 5700x3d 

**Wabbajack Version**

3.7.3.0

**Logs**

'00:00:00.726 [INFO] (Wabbajack.MainWindowVM) Assembly Location: D:\wabbajack\3.7.3.0\Wabbajack.dll
00:00:00.726 [INFO] (Wabbajack.MainWindowVM) Process Location: D:\wabbajack\3.7.3.0\Wabbajack.exe
00:00:00.726 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.7.3.0
00:00:00.726 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: bd86defaa0e80fb1777027742554edfcd686970c57e6d69149a4f618bd7226b6
00:00:00.726 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: bd86defaa0e80fb1777027742554edfcd686970c57e6d69149a4f618bd7226b6
00:00:01.040 [INFO] (Wabbajack.MainWindow) Wabbajack Build - cd020d08211efeab6c0d01635a65604f0d016a35
00:00:01.040 [INFO] (Wabbajack.MainWindow) Running in D:\wabbajack\3.7.3.0
00:00:01.049 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19045.0
00:00:01.049 [INFO] (Wabbajack.MainWindow) System settings - (15.9GB RAM) (12GB Page), Display: 1920 x 1080 (7.8GB VRAM - VideoMemorySizeMb=10240)
00:00:01.049 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:01.102 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:05:10.018 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Loading modlist D:\wabbajack\3.7.3.0\downloaded_mod_lists\LostOutpost_@@_squeegeepunk.wabbajack
00:05:10.036 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Indexing files
00:05:10.036 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Scanning files
00:05:10.276 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 170.4MB file at mods\Smoke Texture Overhaul\archive\pc\mod\!!!Smoke FX Extras.archive
00:05:10.276 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 425.7MB file at mods\Smoke Texture Overhaul\archive\pc\mod\!!!Smoke Overhaul and Retexture.archive
00:05:10.386 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 167MB file at mods\Archive Conflict Checker Tool\Root\red4-conflicts.exe
00:05:10.804 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 129.4MB file at dlls\Qt6WebEngineCore.dll
00:05:10.934 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 656.3MB file at mods\TV Adverts Fixes\archive\pc\mod\AdvertsFixes.archive
00:05:12.162 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 555.7MB file at mods\Environment Textures Overhaul\archive\pc\mod\ETO_1.1_2K.archive
00:05:13.209 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 666.2MB file at mods\Cyberpunk 2077 HD Reworked Project\archive\pc\mod\HD Reworked Project.archive
00:05:13.350 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 1.1GB file at mods\Cosmopolitan Night city\archive\pc\mod\##Cosmopolitan_Night_city_enhanced.archive
00:05:13.369 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 340.4MB file at mods\Cosmopolitan Night city\archive\pc\mod\##Cosmopolitan_Dog_town_enhanced.archive
00:05:13.628 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Hashing 211.6MB file at mods\Clothing Shadows Fix\archive\pc\mod\ZClothingShadowsFix.archive
00:05:20.787 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Found 17 errors
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\red4ext\plugins\mod_settings\user.ini | Sizes do not match got 4714 expected 2461
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\StealthRunner\settings.json | Hashes do not match, got C2zIn/SgP04= expected vzyVAscAemo=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\flashlight\config.json | Hashes do not match, got Z9LY0jGBEZE= expected NDPKFzQ/Cjk=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\NovaTraffic\settings\settings.json | Hashes do not match, got kczXnemJFXg= expected CiHDQVTxz2s=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Nova Crowds (CET - Randomized Crowds and Increased Density)\bin\x64\plugins\cyber_engine_tweaks\mods\NovaCrowds\settings\settings.json | Hashes do not match, got x4FRJ09aK+Q= expected CP57Vlf+QaI=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\Weathermancer\settings.json | Hashes do not match, got X/biSxTAP9E= expected bvENAFWtvsM=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\CP77RPC2\data\config.json | Hashes do not match, got 0bqpH7UJnOs= expected Cz3NQdrZKOs=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\betterScopes\config\config.json | Hashes do not match, got JUOg74RJFyk= expected KoNdcpo24pQ=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\FSR3 Frame Gen for Cyberpunk 2077 (AMD)\bin\x64\dlss-enabler.log | Sizes do not match got 33763 expected 130
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\NPCD_Hotline\mod_user_settings.json | Sizes do not match got 207 expected 209
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\RenderPlaneFix\data\config.json | Sizes do not match got 348 expected 193
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\DamageScaling\settings.json | Hashes do not match, got fms20txHTBU= expected zXVg7f9Gx3M=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\BetterSleeves\data\config.json | Sizes do not match got 731 expected 625
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\SilentSilencersAndKnives\settings.json | Hashes do not match, got VfYHWHjRbWU= expected X6L5nIFlnH8=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\FSR3 Frame Gen for Cyberpunk 2077 (NVIDIA)\bin\x64\dlss-enabler.log | Sizes do not match got 36368 expected 130
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\onlySmartWeaponCrossHair\config.json | Hashes do not match, got db6+Zhw01cc= expected q6pb3oD9R4s=
00:05:20.787 [ERROR] (Wabbajack.CLI.Verbs.VerifyModlistInstall) mods\Squeegeepunk - Configs\bin\x64\plugins\cyber_engine_tweaks\mods\ImmersiveFirstPerson\config.json | Hashes do not match, got NvB+bbMAUPg= expected 49ZVR2ZoG70=
00:05:20.787 [INFO] (Wabbajack.CLI.Verbs.VerifyModlistInstall) Report written to D:\wabbajack\3.7.3.0\temp\19836_f3643072-a2db-419e-b24d-da0107c48ad1\3c658cbd-f17d-40f5-9532-125d4d84e251.html
00:11:41.783 [INFO] (Wabbajack.MainWindow) Beginning shutdown...
00:11:41.783 [INFO] (Wabbajack.MainWindow) Clearing D:\wabbajack\3.7.3.0\temp
00:11:41.783 [INFO] (Wabbajack.MainWindow) Finished clearing D:\wabbajack\3.7.3.0\temp'

**Comment by EzioTheDeadPoet** [comment]
this is not a WJ issue. Please go to the correct support discord or forum linked for individual list.
you can find them on the websites list gallery: https://www.wabbajack.org/gallery
