### ISSUE TITLE
Allow NSFW filter to work like unofficial lists filter in wabbajack gallery

### ISSUE THREAD

**Issue by keatit71** [wabbajack-tools/wabbajack#2630]
When I'm looking for a wabbajack list it would be nice to see all lists that are available rather than sfw or nsfw.

It would be nice to have the show NSFW toggle work the same as the show unofficial lists toggle and just combine the nsfw lists with the rest of them rather than show only nsfw lists.

**Comment by EzioTheDeadPoet** [comment]
There are no plans on changing the old UI for this version of the app since complete UI redesign is in the works.
But you can experience the desired behavior on the Gallery featured on the website:
https://www.wabbajack.org/gallery

**Comment by keatit71** [comment]
Will the new UI in the app support the feature I want?

**Comment by EzioTheDeadPoet** [comment]
Honestly haven't tried it. 
But even then it would be something to look at when the time for that comes. But making that change now is not a critical bug so it won't be changed in the current UI.

**Comment by tr4wzified** [comment]
Yes, I'm adding a category option for all lists similiar to how mod category search works on Nexus.

**Comment by keatit71** [comment]
Cool I'll close this issue then and look forward to the new version.

**Comment by tr4wzified** [comment]
I thought you might be interested to see it working in the new gallery. You can check the checkmark at the top to include NSFW lists, and optionally if you only want to browse NSFW lists you can use the new 'has tag' filter.
Heads up for those at work, some slightly NSFW thumbnails appearing: 
[GeyEBDMc3j.webm](https://github.com/user-attachments/assets/f942e9a1-4db3-4f5c-a0a2-90c4bc35cd0d)
