### ISSUE TITLE
Cannot enter the password for nexus because the window is closing in a second.

### ISSUE THREAD

**Issue by bbckoo** [wabbajack-tools/wabbajack#2631]
**Describe the bug**

When I want to insert my data from nexus, the window is closing in a second.

**Additional Context**

Microsoft 11, SSE

**Wabbajack Version**

Wabbajack 3.7.3.0

**Logs**
[Wabbajack.current.log](https://github.com/user-attachments/files/17465720/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Do you use a "debloated" Windows 11 ?

**Comment by bbckoo** [comment]
No. Problem solved by reinstalling Wabbajack.

În lun., 21 oct. 2024 la 21:56, Luca ***@***.***> a scris:
