### ISSUE TITLE
Unable to add Always Enabled Mods if the folder name contains special characters

### ISSUE THREAD

**Issue by reyqune** [wabbajack-tools/wabbajack#2632]
**Describe the bug**

The setting Always Enabled Mods when you compile a list, doesn't work if you have a folder that includes unexpected characters in the folder name. They just won't get added at all. The only way to include them is to manually add them in the .compiler_settings file.

Example, could not add a folder called `Normal Volo's Eye` 

it had to be added as `"mods\\Normal Volo\u0027s Eye"` in the .compiler_settings file

**Wabbajack Version**

3.7.3.0

**Comment by EzioTheDeadPoet** [comment]
I just tested this and on the main branch of WJ this feature works as intended.
I tested the feature on the version listed in the report and it also works as intended there.

In a big list you might get confused by the mods not being listed where you expect them to be. But the mods are still compiled and part of the installation.

**Comment by reyqune** [comment]
Fully reinstalled Wabbajack, and it seems to be working now.
