### ISSUE TITLE
Why is Wabbajack so picky about installation paths?

### ISSUE THREAD

**Issue by GF-Huang** [wabbajack-tools/wabbajack#2641]
Can anyone elaborate on why I can't install in a protected folder? 

Why is it not even allowed to install in the user folder (`C:\Users\XXX\AppData\Local\Programs\Wabbajack\Wabbajack.exe`)?

**Comment by GF-Huang** [comment]
@Mieekaserra As far as I know, windows will not modify manually created folders under `C:\Users\XXX\AppData\Local\Programs`. 

Can you provide more evidence that Windows does this?

**Comment by EzioTheDeadPoet** [comment]
There have been many cases where modding tools broke in that folder or full on installs with WJ failed because of windows/AV software messing stuff up due to false positives. 

So we won't change this.
