### ISSUE TITLE
No standard SE modpacks work 

### ISSUE THREAD

**Issue by lomo2302** [wabbajack-tools/wabbajack#2666]
**Describe the bug**
all of them have atleast one mod that cannot be downloaded and can't be found online due to nexus no longer having the mod so the 2 hours i spent downloading are down the drain

 windows 11 and skyrim se without ae

**Wabbajack Version**
latest

**Logs**

00:00:29.721 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download ESLify Everything - ESPFE Everything-75248-3-2-1-1666022766.rar (NexusDownloader+State|SkyrimSpecialEdition|75248|324806)
00:00:29.721 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by Mieekaserra** [comment]
You can find help for missing mods on the modlist discord. Those normally deal with mods deleted off nexus (like the one you provided)

**Comment by lomo2302** [comment]
> You can find help for missing mods on the modlist discord. Those normally deal with mods deleted off nexus (like the one you provided)

I looked and searched each thread on the discord server and haven't found a single file where are they?

**Comment by EzioTheDeadPoet** [comment]
please go to the support channels for the lists you are trying to install.
