### ISSUE TITLE
slideshow of mods while installing

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#29]
**Is your feature request related to a problem? Please describe.**
I get bored while staring to the screen while wabbajack runs, and only being able to watch the progress bars and logs messages.

**Describe the solution you'd like**
It would be nice if while wabbajack does its thing (installing or downloading), that start showing the short mod notes and images from nexus in like a slideshare presentation. This will work only for mods stored on Nexus. Not synched because some mods donwload/install too fast, but like 5 secs for every mod and then cycles again to the first mod. This way people would have an idea of what it is actually installing

**Describe alternatives you've considered**
It can be a report to the end, but I probably won't read it because my hype to start playing.

**Additional context**

**Comment by tr4wzified** [comment]
This issue should be closed now.
