### ISSUE TITLE
Entering 2FA code does not redirect to authorization page.

### ISSUE THREAD

**Issue by nollidnosnhoj** [wabbajack-tools/wabbajack#296]
**Describe the bug**
If you have 2FA (Two-factor authentication) enabled in your nexus account, when you login into Nexus in Wabbajack, and enter the 6 digit code for two step authentication, it will not redirect to the authorization page. However, if you go back to the Nexus homepage (by clicking the link), it will redirect to the authorization page. Not as big of an issue since you could find your way to the authorization page. I could probably try and fix this in my spare time, since I need to improve on my C#/problem solving. 

I've uploaded a video showing the issue: https://www.dropbox.com/s/xp2003vzmccwkbk/8RQu9wBoAJ.mp4?dl=0

**Additional context**
Win 10, SSE

**Logs**
```
0 - Wabbajack Build - 5fc57883d97da5cbcf45f75f007054e6ae02ad6b
2.04 - Loading ModLists from Github
9.88 - Benchmarking E:\NOISE
12.35 - 1011.5MB/sec for E:\NOISE
12.35 - Benchmarking E:\NOISE\downloads
12.35 - 1011.5MB/sec for E:\NOISE\downloads
12.36 - Benchmarking E:\wabbajack
12.36 - 1011.5MB/sec for E:\wabbajack
12.37 - Recommending a queue size of 8 based on disk performance and number of cores
12.4 - Validating Game ESMs
12.41 - Validating Dawnguard.esm
12.49 - Validating Dragonborn.esm
12.66 - Validating HearthFires.esm
12.68 - Validating Update.esm
12.73 - Validating Modlist
12.74 - Loading Nexus Mod Permissions
13.4 - Loaded permissions for 1 authors
13.4 - Loading Server Whitelist
13.74 - Loaded permissions for 58 servers and 17 GDrive files
13.74 - Running validation checks
13.83 - No Validation failures
13.84 - Optimizing Modlist
13.88 - Optimizing Modlist directives
13.9 - Looking for files to delete
13.94 - Looking for unmodified files
17 - Updating Modlist
17.01 - Optimized 23299 directives to 23299 required
17.02 - Hashing Archives
17.05 - Downloading Missing Archives
17.06 - Missing 323 archives
17.06 - Getting Nexus API Key, if a browser appears, please accept
17.09 - 
110.8 - Downloading College Modifications-16662-0-1-0.7z
110.81 - Downloading Elven Weapons for Silence-27726-1-1.7z
110.82 - Downloading SkyRem - Eve-26325-1-0-1559759793.zip
110.82 - Downloading ELE - SE v1.2.2-1377-1-2-2-1543800567.7z
```

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by Noggog** [comment]
Reproduced.  Might just be a Nexus quirk, but we'll see if there's any tricks we can do to route around that.

**Comment by nollidnosnhoj** [comment]
Just a suggestion: You could try using a web scrapper and find the "Back to Nexus Home" link and use the address to redirect, so you can obtain the member_id cookie. However, I do not know how efficient that is, since it's going through the dom.

**Comment by halgari** [comment]
Yep it's a problem with the Nexus' site over the holiday weekend
