### ISSUE TITLE
IniParser Error with Fallout New Vegas

### ISSUE THREAD

**Issue by LadyZeefa** [wabbajack-tools/wabbajack#299]
**Describe the bug**
After the additions of wabbajack's iniParser Fallout New Vegas has failed to install using any beta version beyond Beta4. The parser indicates that part of the ini is in an unknown file format. Fallout New Vegas inis have a lot of useless messages inside that may be causing the issue. I will be attaching my Fallout New Vegas Prefs.ini for reference.
[falloutprefsini.txt](https://github.com/wabbajack-tools/wabbajack/files/3990325/falloutprefsini.txt)

**Additional context**
Please list your OS (Win 10, Win 7, etc.) and Game type (SSE, FO4, etc.) 
Windows 10 and Fallout New Vegas Ultimate Edition

**Logs**
Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. Refere to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) page if you do not know how to post the stack trace in a code block.
[Wabbajackbeta9.exe.log](https://github.com/wabbajack-tools/wabbajack/files/3990297/Wabbajackbeta9.exe.log)
**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by Noggog** [comment]
@halgari I think you're the best one suited to taking a first look at this

**Comment by halgari** [comment]
Fixed in master, we now fallback to not setting the screensize if the ini format is wonky
