### ISSUE TITLE
Customization of modlists (after we have our initial guides and variations setup)

### ISSUE THREAD

**Issue by TheBlueJoo** [wabbajack-tools/wabbajack#30]
**Is your feature request related to a problem? Please describe.**
Lack of modularity or customization (not a time sensitive request) Long-term QoL change.

**Describe the solution you'd like**
For mods with multiple texture, color, difficulty, etc options, perhaps a more customizable UI for WJ allowing for the end user to choose options for mods within the modlist.

**Describe alternatives you've considered**
Perhaps allow end user to access parts of the FOMOD that wouldn't break the load order 
On nexus sites with several files, the user would normally choose one that best fits their desired image. Perhaps WJ could be customized to access the site and give the end user the option of which preselected file they would like.

**Additional context**
Again, not an immediate issue by any stretch.

**Comment by Cyclonit** [comment]
I have done a little bit of thinking regarding this suggestion. Some of the required changes/additions are fairly straight forward, others however do require substantial changes in the compilation workflow.

1. group directives by mod
Disabling a mod in a mod list equates to removing all directives for that mod. Thus, directives should be grouped accordingly during compilation, such that the installer can present the user with the option to disable a mod. 

2. resolve dependencies between mods and patches
When mod A requires a patch to be compatabile with mod B, that patch should not be enabled if B is disabled. WJ thus needs awareness about dependencies between mods and their patches. 

3. add custom dependencies during compilation 
WJ may be able to determine some dependencies on its own, but the modlist creator requires the means to add dependencies between mods in cases where  automatic detection does not work. 

4. ability to add one mod multiple times
It must be possible to add different variations of individual mods to allow for alternatives with regards to texture quality / selected models. 

5. mod groups/categories 
The modlist creator should be able to categorize mods in their list (i. e. low quality/high quality) and users should be able to disable/enable entire groups/categories at once.
