### ISSUE TITLE
Author Notes and Nexus Mod Pages

### ISSUE THREAD

**Issue by MariusKlug** [wabbajack-tools/wabbajack#33]
Hey there,

as a guide writer, there are two things I would like to see before I make my guide a WJ install: 

1) A popup window both in the beginning and the end of the install process, where I can write my own notes and thoughts and so on, could possibly write something about this specific list, and in the end just a goodbye note or so. 

2) the previously discussed self-paced (click to see next) slideshow of the mods that are being installed, with a button to get to the mod page, if possible a link to the mod authors donations as on their mod page, and a button to instantly endorse the mod. 

This would mean that all users read what I have to say about my mod pack and they see all mods and have a low threshold to see their mod page (recognition of the author), donate, and give endorsements. Plus guide authors can put their own donation page at the end.

All in all, this would probably make me switch to MO2 (from Vortex) and WJ, as I see no ethical conflict anymore and the main complaints are met (recognition and financial issues).

**Comment by erri120** [comment]
See #73
