### ISSUE TITLE
7z.exe and 7z.dll

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#35]
**Describe the bug**
If you build a WJ installer with those files present, the end-user won't be able to use the installer from the same directory where is doing the installation.

**Additional context**
Please list your OS (Win 10, Win 7, etc.) and Game type (SSE, FO4, etc.) 

**Solution**
Warn before creating the autoinstaller about the presence of those files and refuse to build the autoinstaller.

**Comment by scottpwr** [comment]
My 7z.exe wont run at all, no matter what location I am starting from.

**Comment by halgari** [comment]
fixed in master
