### ISSUE TITLE
Corrupted

### ISSUE THREAD

**Issue by thehackedone** [wabbajack-tools/wabbajack#356]
At least with Fallout I am either getting a corrupted mod pack error or this even weirder error. On the previous releases someone about my install of Two point hospital...?
Win 10, the FOEE mod I think? I will include a screen shot
https://i.imgur.com/Vt16aKs.png
**Describe the bug**

**Additional context**
Please list your OS (Win 10, Win 7, etc.) and Game type (SSE, FO4, etc.) 

**Logs**
Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. Refere to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) page if you do not know how to post the stack trace in a code block.

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Not a bug, F4EE needs to be updated to the latest version of Wabbajack. Otherwise you could use Wabbajack 1.0 beta 10 instead.
