### ISSUE TITLE
Non negitive number

### ISSUE THREAD

**Issue by Strawbqwerty** [wabbajack-tools/wabbajack#38]
**Describe the bug**
A clear and concise description of what the bug is. Building mod install list. Final log entry:  Non negative number required. Parameter name count-Can not continue
I have followed the You tube tutorial. Verified game files. Clean install of Mod organizer. Empty mod and down load folders.

**Additional context**
Please list your OS (Win 10, Win 7, etc.) and Game type (SSE, FO4, etc.)  W10 pro Skyrim SE

**Solution**Had to do a totally clean re install of sky rim,still having other issues though.
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Fixed in master
