### ISSUE TITLE
"VCRUNTIME140_1.dll was not found" Result from List Install. B-15

### ISSUE THREAD

**Issue by NekoJess88** [wabbajack-tools/wabbajack#380]
Both myself and another WJ user have received the following "VCRUNTIME140_1.dll was not found" error when attempting to start MO2 after a Modlist install via WJ Beta 15.

I'm not sure if there are more who have experienced this, but In coincidence, I do not believe.

**Comment by LostDragonist** [comment]
MO 2.2.2 requires the Microsoft Visual C++ 2015-2019 redistributables available here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.  Probably the x64 one.

**Comment by tr4wzified** [comment]
Should Wabbajack auto-install that runtime if it isn't found on the users system? Not sure if that's in our scope.

**Comment by erri120** [comment]
Wabbajack doesn't have admin rights, the Modlist readme should state the requirements

**Comment by erri120** [comment]
I don't think Wabbajack should mess with that. If the user is not able to read the readme and get this requirement than we should just ignore it.

**Comment by tr4wzified** [comment]
Agreed
