### ISSUE TITLE
Wabbajack fails to see TES IV: Oblivion as a valid Bethesda game when using GOG

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#382]
**Describe the bug**
Oblivion is found, but not detected as a modlist installable game. Encountered a user in #bevilex-support on Discord that wasn't able to install due to this.

**Additional context**
OS unknown, but shouldn't be relevant. Wabbajack Beta 15.

**Logs**

`0.14 - Wabbajack Build - e38d67fee15047930e04078513e3b151dd4c38f8
4.66 - Loading ModLists from Github
19.77 - Tried to open a non-existant readme: https://www.wabbajack.org/modlist/bevilex
63 - Benchmarking A:\DRM Free Games\Belivix\Wabbajack
66.42 - 744.8MB/sec for A:\DRM Free Games\Belivix\Wabbajack
66.43 - Recommending a queue size of 6 based on disk performance, number of cores, and 15.9GB of system RAM
66.46 - Total number of Steam Libraries found: 0
66.48 - Searching for Steam Games in c:/steam\steamapps
66.49 - Steam Game Steamworks Common Redistributables(228980) is not supported, skipping
66.49 - Steam Game Sid Meier's Civilization VI(289070) is not supported, skipping
66.51 - Found Steam Game: "Fallout 4"(377160) at c:/steam\steamapps\common\Fallout 4
66.52 - Found Steam Game: "The Elder Scrolls V: Skyrim Special Edition"(489830) at c:/steam\steamapps\common\Skyrim Special Edition
66.52 - Steam Game Left 4 Dead 2(550) is not supported, skipping
66.54 - Steam Game Halo: The Master Chief Collection(976730) is not supported, skipping
66.54 - Total number of Steam Games found: 2
66.56 - Found 3 SubKeys for GOG
66.57 - GOG Game "STAR WARS Battlefront II"(1421404701) is not supported, skipping
66.57 - Found GOG Game: "Stardew Valley"(1453375253) at C:\Program Files (x86)\GOG Galaxy\Games\Stardew Valley
66.58 - GOG Game "The Elder Scrolls IV: Oblivion"(1458058109) is not supported, skipping
66.59 - Total number of GOG Games found: 1
117.43 - Exiting because we couldn't find the game folder.
117.47 - Tried to open a non-existant readme: https://www.wabbajack.org/modlist/bevilex`

**Solution**
We should probably whitelist the id for it, I'd do it myself but I don't own Oblivion on GOG and am unable to test. The id is unusual though, the normal GOTY version on GOG I can find (https://www.gog.com/game/elder_scrolls_iv_oblivion_game_of_the_year_edition_deluxe_the) has the following id: 1242989820.

**Comment by erri120** [comment]
redirect to the build in `#bleeding-edge-testing` fixed here: 01ff7cb093f19dfd9a33d6415e11a1e5f4ac05de
to get gog ids use this site: https://www.gogdb.org/
