### ISSUE TITLE
Wabbajack leaves behind empty folders when updating a modlist and fails to activate certain mods

### ISSUE THREAD

**Issue by Mdc211** [wabbajack-tools/wabbajack#396]
**Describe the bug**
If a user has a modlist installed and then reinstalls over it to update it, any mods that got deleted as part of the update will have an empty folder remain in the downloads folder. This causes many empty mods to appear at the bottom of MO2.  It also seems to be the case that if a user updates over an old list, some mods and esps might be disabled by default in MO2 even though they should not be.  

https://cdn.discordapp.com/attachments/614661600850345994/667865956927799317/unknown.png
**Additional context**
Windows 10,  Skyrim SE but that should not be relevent

**Logs**
N/A

**Solution**

**Comment by IKilledBlitz** [comment]
To add to this, the log spits out the "Error when cleaning empty folders" message every single time you update over the top of something

**Comment by Noggog** [comment]
This may have been fixed indirectly with #493 .  Would have to test

**Comment by halgari** [comment]
I downloaded a list, modified it, reinstalled the list, and confirmed the old folder no longer exists.
