### ISSUE TITLE
Some users report incorrect display resolutions

### ISSUE THREAD

**Issue by Mdc211** [wabbajack-tools/wabbajack#409]
**Describe the bug**
After an install is completed, some users open skyrim and the resolution is set incorrectly within the INI file.  Wabbajack did change the resolution, just not to the correct one.  

**Additional context**
Windows 10.  If it matters I compile with the resolution set at 1440p

**Logs**
N/A

**Solution**

**Comment by halgari** [comment]
Fixed months ago with the DPI fixes to resolution calculation
