### ISSUE TITLE
FOMOD file support

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#41]
**Is your feature request related to a problem? Please describe.**
Some modlists still relly in old mods that used the old FOMOD format, like New Vegas Modlists

**Describe the solution you'd like**
Include the .FOMOD extension amont the ones supported.

**Describe alternatives you've considered**
For now, ask to users to change manually the extension of the file from .FOMOD to .7z.

**Additional context**
I will try to do a pull request if I could add that to the code.

**Comment by erri120** [comment]
Could add `.omod` to add

**Comment by giraldiego** [comment]
> Could add `.omod` to add

that would be awesom, I am just learning, are you able to compile the WJ in your machine without issues?

**Comment by erri120** [comment]
I can. Check the pull requests for my contributing file maybe that can help you. I do intend on contributing some code so ill take a look tomorrow

**Comment by giraldiego** [comment]
> I can. Check the pull requests for my contributing file maybe that can help you. I do intend on contributing some code so ill take a look tomorrow

thank you very much

**Comment by halgari** [comment]
Is  .omd a renamed .zip? If so it's fairly easy to add, we simply have to add it to an existing list of known extensions.

**Comment by LostDragonist** [comment]
Far from it.  omods are their own format that does weird things with data streams and whatever else.  It will require some sort of custom code.  Every time omod support comes up with MO2, we kick around the idea of including code from OBMM because no one has the time to figure out the format.

**Comment by giraldiego** [comment]
until now, at least for nvg mods, the .fomod comes inside a 7z and also the .fomod is 7z

**Comment by erri120** [comment]
Lol just noticed that OBMM is also written in C#: 
[https://www.nexusmods.com/oblivion/mods/2097?tab=files](Source Code)
Ill look into omod files, have Oblivion but not FNV installed currently.

**Comment by giraldiego** [comment]
> 
> 
> Is .omd a renamed .zip? If so it's fairly easy to add, we simply have to add it to an existing list of known extensions.

it seems it is a 7z in disguise

**Comment by erri120** [comment]
![16-09-2019 15-38-15 CWindowsSystem32cmd exe](https://user-images.githubusercontent.com/16577545/64962623-474e2900-d887-11e9-84be-d0404b38d6b2.png)
getting close I think

**Comment by erri120** [comment]
Able to extract config, readme and script from `.omod` files now:

[out.zip](https://github.com/halgari/wabbajack/files/3616739/out.zip)
Next up is getting the data and plugins

**Comment by erri120** [comment]
I can know extract data from `data.crc`. The extractor I did is standalone currently (Ill upload to Github soon) but it works somehow. How do we handle installation?

**Comment by erri120** [comment]
Repo for extractor is [here](https://github.com/erri120/OMOD-Extractor). Will modify a lot and remove bloat from OBMM.

**Comment by erri120** [comment]
OMODExtractor is now kinda done, tested against the most used omod files: DarkUId DarN and DarNifiedUI.

**Comment by erri120** [comment]
Should be closed since fomod is added in a254f0d99a45296b76fd7db30d2b4e33dabd1efa
