### ISSUE TITLE
When a mod doesn't exist, offer alternative URL input

### ISSUE THREAD

**Issue by halbet** [wabbajack-tools/wabbajack#42]
**Is your feature request related to a problem? Please describe.**
When a mod or version of a mod is deleted off Nexus, the AutoInstaller cannot complete and must be recompiled.

**Describe the solution you'd like**
When a mod cannot be found, offer a popup box to specify a new nexus URL for the newer version of that mod.

**Additional context**
Perhaps include a warning that it is not guaranteed to work if the update introduces conflicts.

**Comment by halgari** [comment]
Will not do, it the original source is no longer valid it is likely the new source is a pirated copy.
