### ISSUE TITLE
Reactive UI: Bindings and Routing

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#427]
- Data Binding with Rx: https://reactiveui.net/docs/handbook/data-binding/
- Routing with Rx:  https://reactiveui.net/docs/handbook/routing/

_the following was first posted on Discord_
***
so from my testing I'm already liking Rx Routing more than what we have atm:
The thing that throws me off whenever I see WJs WPF XAMLs is the fucking bindings, I know that with DataContext we can get _some_ info in the Editor but using
```csharp
this.WhenActivated(disposable =>
{
  this.Bind(ViewModel, x => x.vmProperty, x => x.viewProperty).DisposeWith(disposable);
});
```
is just soooo good.

Than the routing:
I still have no real idea how `ContentPresenter` works and find it very funky to work with, with RxRouting we make your `MainWindowVM` implement `IScreen` to get `RoutingState`. 
```csharp
Router.Navigate.Execute(new SomethingVM());
```
can get us anywhere.
Ofc we had to swap out the entire `ContentPresenter` block with 
```xml
<rxui:RoutedViewHost
  x:Name="RoutedViewHost"/>
```
and bind that to the `RoutingState Router` in `MainWindowVM` using the RxBindings shown above.
`ViewModels` would also need to implement `IRoutableViewModel` for `UrlPathSegment` and `HostScreen`.
***

How to implement in Wabbajack:

We need to start by changing all UserControls to `reactiveUi:ReactiveUserControl` and the `MainWindow` from `mahapps` to `reactiveUI:Window` (still need to check how that is done @Noggog maybe you got an idea).

`reactiveUi:ReactiveUserControl` references the VM using `x:TypeArguments`. In the `View.xaml.cs` we can bind to the VM using:

```csharp
this.WhenActivated(disposable =>
{
  this.Bind(ViewModel, x => x.vmProperty, x => x.viewProperty).DisposeWith(disposable);
});
```

ViewModel comes from `ReactiveUserControl`/`ReactiveWindow`.

Since routing is done using `Router.Navigate.Execute(new SomethingVM()):` we would need to change the `MainWindowVM.NavigateTo` functions and remove the `ActivePane` and all `Lazy<..VM>` fields.

Our current UI code base is all over the place and making this change will likely require some massive changes but it's well worth it.

**Comment by Noggog** [comment]
We're doing the bindings via `ReactiveUserControl` already.  Maybe there's a few views not converted over, but for the most part it's swapped.
https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack/Views/Installers/InstallationView.xaml.cs

On that note, be aware that I added and am using extension methods that have a bit more type safety than the stock ones provided.  `BindToStrict`, `BindStrict` etc.  They can still be tricked given certain `Expression`s but overall are much more compile-time safe.

----- 

As far as migrating away from using `ContentPresenter` /w XAML resources to handle the view swapping to RxUI's `Router` systems, I'm totally fine with giving them a spin.

Only reservation is they seem to encourage the `NavigationStack` concepts discussed here #350 , whereas I typically prefer #349 patterns.  Not a huge deal though.  And we can get around it by just using Router's `NavigateAndReset` for every call, and not relying on their navigate back concepts, I'd say.

**Comment by erri120** [comment]
The current `MainWindow` is a `mahapps:Window`, any idea how to swtich to `rxui:ReactiveWindow`?

**Comment by Noggog** [comment]
> we would need to change the MainWindowVM.NavigateTo functions and remove the ActivePane and all Lazy<..VM> fields.

I think we would replace the ActivePane with their Router, and of course the `NavigateTo` calls would to the router instead.  But I think the Lazy<VM> fields can stay.  From the docs, they sort of hint at this:
```
 // Manage the routing state. Use the Router.Navigate.Execute
        // command to navigate to different view models. 
        //
        // Note, that the Navigate.Execute method accepts an instance 
        // of a view model, this allows you to pass parameters to 
        // your view models, or to reuse existing view models.
        //
        GoNext = ReactiveCommand.CreateFromObservable(() => Router.Navigate.Execute(new FirstViewModel()));```

We can just reference the lazy reused VM members and pass those into Navigate, rather than creating a new one on every navigation.. requiring all the Rx observable wiring to be recreated every time. 

> The current MainWindow is a mahapps:MetroWindow, any idea how to swtich to rxui:ReactiveWindow?

That I don't know offhand.  That might be somewhat of a pain point.  I imagine if we wanted both, RxUI is pretty good about exposing their systems as Interfaces.  So we might just make our own subclass of MetroWindow, that implements all the interfaces needed for the RxUI systems.  (IActivatableView)?

I have less faith in MahApps being flexible enough to not require inheriting from MetroWindow
