### ISSUE TITLE
Not taking in account files inside the data folder of the game

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#43]
**Describe the bug**
sometime modlist authors put things directly in the data folder or the game but WJ don't detect that, it only detects files in the root directory of the game.

**Additional context**
What I did was to create manually a Game Folder Files in the MO2 with only the files I knew WJ won't recreate (to avoid the previous reported bug)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
We no longer hard-fail when we don't have enough space to install the list, so this no longer an issue.
