### ISSUE TITLE
Don't embed dlls (figure out one-click installation)

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#441]
**Is your feature request related to a problem? Please describe.**
We currently embed 7zip, libcef, and several other programs inside Wabbajack.exe. Writing/Extracting these files takes startup time, and it's a rather janky approach all around. With the shift to .NET core should we move to a `one-click` framework?

Few Options: 

* ClickOnce - 
  - Integrated into VS, deploys in a way (FTP) that would be easy to integrate with the CDN
  - Doesn't seem to themeable? It's a little strange to have a white dialog pop up for an instant before each launch
* Squirrel
  - More programmable
  - Seems a bit abandoned from the GH page?
* http://simpldeploy.com/
  - Looks more modern, and is in active development
  - It's a pretty new project
* https://github.com/ravibpatel/AutoUpdater.NET
  - ?? don't know much about this one

**Comment by Noggog** [comment]
Haven't found the time to give it my full undivided research attention yet, but it's definitely been on my mind.

Thoughts so far:
**Squirrel**
does seem to be in a dying state.  Not too sure on the specifics of what problems exist that are keeping users from using it currently.. but it's definitely not under active development.  Might still be usable, and it's just new features and some advanced edge case problems?

**ClickOnce**
I would get annoyed at a constant white popup on startup.  If the featureset of other options are par, id probably use them just to avoid that.  Might as well.
- I'm unsure of other downsides it has.  I think the only one I can remember is there's no easy way to downgrade?  That's just fuzzy memory, though.

**AutoUpdater.NET*
Looks decent.  I'd give this one a shot and see how it goes?  I like what looks to be the in-code customization of its behavior.

**simplDeploy**
Eh, might work.  Gives me janky vibes.  Might just be the website, lack of code examples?  And am I missing something or is it closed source?  No github links or anything.

-------

For me, though, these types of questions/choices are hard to process without trying them.  I think the pros/cons we care about will distill into focus upon actually trying them out and seeing the pain points.

I'm going to be trying each and seeing what I think before I speak too much more on which I think we should use.

**Comment by Noggog** [comment]
One thing we need to probably consider is a lot of these solutions install new versions into new folders in say, %localappdata%.   This will mean all settings and downloaded modlists, cached vfs, etc, will all be "lost" on updating.

This might be inspiration to move our settings/cache data to a common %localappdata% folder that all WJ instances point to, rather than having all of that be local to the folder?  That way, new install comes along, but then finds the same old settings/files for use in the common area.

Some downsides with that though.. now you can't really run two WJ's at once, or have two different WJ setups /w separate settings (do we even care?).

**Comment by Noggog** [comment]
Also reading into MSIX, which seems to be Microsoft's replacement of ClickOnce.  UWP (the windows store, lol) was what they championed after ClickOnce, which had some nice features for installing things... but had the downside of requiring you to write basically mobile apps for a desktop.  

That's dying off, but MSIX seems to be leveraging the UWP install systems, while allowing normal apps to also be installed?  It seems like it doesn't have to be installed via the windows store, either.  Can be one-off download + double click still?

Not too sure, still looking into it
https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/june/devops-msix-the-modern-way-to-deploy-desktop-apps-on-windows

**Comment by erri120** [comment]
Closed with 2f2d9273b03c794eefd9f4a004ffb319c56d9730

**Comment by Noggog** [comment]
I think there's still another half to do to complete the puzzle, which is figuring out the Azure CI side to set up the zips/xml needed when we publish a build to support the #463 on the serverside.   That, and I think we need to also set up some file shuffling to move all the messy files to a subfolder, and create a shortcut to the wabbajack.exe, like halgari was thinking.  Once both of those is complete, I think our new build publishing system will be complete.
