### ISSUE TITLE
Manifest rework

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#452]
Will do

**Comment by Noggog** [comment]
Copy paste:
as always, I'd prefer any manifest setup to be strongly typed /w real objects.  Obviously serialized to json or html for actual display that we see in the browser.   But the more they're real objects, the easier it will be to wire to the GUI if we eventually want a display or utilize data from it to show in the actual app.  Even if we dont have a full on manifest WPF displayer view.. we may still want to latch onto certain bits of info and modify some display slightly based on XyZ

**Comment by erri120** [comment]
We definitely should create a GUI for viewing the contents of the Modlist in Wabbajack. Its just good UX and makes sense. For this I would recommend a new `ReactiveWindow` instead of `ReactiveUserControl` which acts independent of the main Wabbajack window.
UX:
- starts Wabbajack
- loads Modlist
- opens the manifest in Wabbajack
- new window will open
- user can start installation while the other window is open
Reasoning:
User can view the manifest independent whether they are installing or chilling in the main menu.
Implementation:
Create new `ManifestWindow : ReactiveWindow` or `ManifestWindow : ReactiveMetroWindow` (maybe I can finish #427 prior to this).
Window layout would be simple with just basic window controls (minimize, maximise and close) and a scrollbar.
Layout of the actuall content display should be simple for now. I don't know how you can add Links in WPF but just a list of links would be ok for the start. Since we don't have to display _everything_ we should also decide on what. On that topic I appeal towards just listing all Mods (whatever their origin is).

**Comment by erri120** [comment]
JSON serialization for the website so I can add some more gallery features.

**Comment by Noggog** [comment]
Love it. 

> For this I would recommend a new `ReactiveWindow` instead of `ReactiveUserControl`
I would still recommend implementing it as a `ReactiveUserControl`, that way we can put it anywhere we want.  If what we want is to put it in its own window, that's super easy.  You just then make a new `ReactiveWindow`, whose content is just the ManifestView.   That way, though, if we want to put the ManifestView anywhere else for a slightly different purpose, or change our mind of exactly where we want it displayed, it's flexible enough to go anywhere.

> I don't know how you can add Links in WPF
I haven't yet had the need to have "links" in the form of raw text /w hyperlink functionality.  Just haven't looked into it much.
Worst case scenario we just make a button /w whatever look we like (content could just be underlined textbox colored blue, lol), and have it fire commands that open the browser like we do now for readmes etc.

**Comment by erri120** [comment]
`Hyperlink` element is a thing: [Docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.hyperlink?redirectedfrom=MSDN&view=netframework-4.8)

**Comment by erri120** [comment]
Closed with 1b428cd03b4f63ae18f4173e08d1b6b13755cf4d
