### ISSUE TITLE
Wabbajack Won't Match Files Created By "Skyrim VR - USSEP 4.2.2 and SSE 1.5.97 Compatibility Patch"

### ISSUE THREAD

**Issue by Timboman** [wabbajack-tools/wabbajack#465]
Well,  got a new conundrum for you guys. I'm trying to set up a new VR Essentials lists and decided to try and use the new "Skyrim VR - USSEP 4.2.2 and SSE 1.5.97 Compatibility Patch" mod which is a patcher that creates modified versions of the base game BSA and ESM files to bring them in line with the latest SSE updates and ensure compatibility with the newest USSEP (which doesn't even let VR boot otherwise). I got everything compiled, generated the Patched files, cleaned those patched ESMs, installed USSEP, and put ALL the relevant vanilla game BSAs into the Downloads folder so it could pull files it needed from them and then fed that basic starting point into WJ as a test.
[Wabbajack_15.exe.log](https://github.com/wabbajack-tools/wabbajack/files/4146233/Wabbajack_15.exe.log)

Technically the patch doesn't actually touch USSEP at all, it doesn't even require it. It's entirely based off the vanilla game files
To bring them in line with the SSE updates that have happened since the engine forked for SSE and VR that USSEP seems to rely on now to function

And Yes all the relevant vanilla BSAs were in the Download directory so that WJ was using them as sources
![unknown](https://user-images.githubusercontent.com/36910038/73625206-d8912280-4611-11ea-9b70-cfe3d085503d.png)

Tho as can be seen in the log it IS ignoring the Skyrim VR specific BSA file:
439.29 - Resolution failed for: D:\MO2 VR Essentials Downloads\Skyrim_VR - Main.bsa

**Comment by Timboman** [comment]
Forgot the link to the source mod again, woops.
[https://www.nexusmods.com/skyrimspecialedition/mods/31673](url)

**Comment by erri120** [comment]
Closed with #472
