### ISSUE TITLE
Identify the culprit for a link checking error.

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#47]
**Is your feature request related to a problem? Please describe.**
When creating an autoinstaller with WJ, sometimes it fails during the link checking process due to an error with the .meta file for a file, however, the log file shows the last mod that was checked successfully but not the mod that caused the error. One can assume that the mod that caused it should be the next in the stack after the last one successful, but sometimes this is not the case and the culprit could have been in a parallel process and threw the error late.

This happens for errors like:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).

C:\oss\Wabbajack\Wabbajack\Wabbajack.Common\Utils.cs:line 281
110.91 - Value cannot be null.
Parameter name: source - Can't continue

**Describe the solution you'd like**
Implement a catch to log what was the mod that actually threw the error.

**Describe alternatives you've considered**

**Additional context**

**Comment by halgari** [comment]
This is fixed in master
