### ISSUE TITLE
Implement Nexus Game IDs for all games

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#477]
Manual downloading requires the use of the Nexus Game ID (not the nexus game name) for Skyrim SE this is 1704. We can get these numbers by looking at the numbers in them manual download links of the page. We should add these codes for all supported games.

**Comment by erri120** [comment]
Nexus Game IDs? Haven't checked the manual downloading code, can you link use of that id?

**Comment by halgari** [comment]
If you look at the links for the manual download buttons they contain "gameID" as well as "fileid". We then use JS to search for these `a` refs and highlight them.

**Comment by halgari** [comment]
fixed in #485
