### ISSUE TITLE
Modlist gallery filter/search

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#481]
Modlist Gallery needs some display improvements:
- Filter by game (combobox and/or on/off game icon 'checkboxes')
- Filter by name.  
- Sort by name/recently updated (maybe not downloads or anything, as we don't want to get runaway top installed lists?)
- Hide lists under maintenance?

Most of these should be debounced and wired into a filter call on the DynamicData observable chain that eventually binds to the display collection, so that things update live

- Easy clear all filters button
- Would also be good to maybe save these settings.  Most users will want to filter to the same game every time they open WJ

**Comment by Noggog** [comment]
Also, do we perhaps want to do a random shuffle of the modlists?  Just to keep one list from always being the top one displayed?  Might be nice to just help all get a fair shake at being downloaded

**Comment by LordOfRhun** [comment]
I am currently working on this
>     * Would also be good to maybe save these settings.  Most users will want to filter to the same game every time they open WJ

Maybe there could be a check box in the settings disable the shuffle which would be enable by default  ?
> Also, do we perhaps want to do a random shuffle of the modlists? Just to keep one list from always being the top one displayed? Might be nice to just help all get a fair shake at being downloaded

**Comment by LordOfRhun** [comment]
> Also, do we perhaps want to do a random shuffle of the modlists? Just to keep one list from always being the top one displayed? Might be nice to just help all get a fair shake at being downloaded
Hey while coding as saw this implemented.

https://github.com/wabbajack-tools/wabbajack/blob/1bbbda4f350c0af12bb71b695e3ee7f58f3e84e4/Wabbajack/View%20Models/Gallery/ModListGalleryVM.cs#L82-L83
But in my experience it doesn't seems to work,

**Comment by halgari** [comment]
Fixed in master
