### ISSUE TITLE
Pause mechanics

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#484]
Would be nice to be able to pause WJ.  Could be done fairly easily by hooking into WorkQueue's desired thread observable and temporarily setting it to zero when paused.

This would be a slow pause, though, as any current jobs would still finish up first.  Better than nothing, though

**Comment by CrazieIvan** [comment]
A pause both during the downloads and installation stages would be really nice.  Most list installations are very long, and I sometimes I do other work on my PC at the same time that requires either the internet or hard disk bandwidth that's currently being used up by WJ.  
Thanks for your consideration!

**Comment by EzioTheDeadPoet** [comment]
you can right now effectively "pause" the installation and downloads by simply closing WJ. (unfinished downloads get reset tho)
not Ideal but it might take some time to implement a full pause system, but you can also reduce the number of threads used by WJ which will reduce the used bandwidth of the drive and your internet.

**Comment by CrazieIvan** [comment]
Good to know.   I'd never think to close the program during the installation, cuz I didn't know what kind of a disaster that might create.

**Comment by EzioTheDeadPoet** [comment]
If you stop during downloads it only has to redownload the downloads that were in progress and anything that wasn't downloaded already. And if you stop it during Installation it just has to rehash the partial Installation that already is there and rebuild from there.

So if you do it it will take longer to finish the more often you do it, as it has to redo some steps but it can be paused and if you need your PC at that time it might still be worth it.
