### ISSUE TITLE
Braindump on Autoupdate/Install mechanics

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#486]
Here's what we need across-the-board for a great setup experience:

* A `.exe` download, could be a self-extracting zip, but I'd like to avoid telling users to click to download a .zip, then extract the contents (all of them) to some folder, then find an executable to run
  * Could use an official installer, if we can install without admin privileges
* Auto-updating we need a way to detect updates, (we have this via AutoUpdater.NET) download them, and install them.
  * AutoUpdater.NET requires us to compile and sign `ZipExtractor.exe` which requires us to sign the exe and then build our own copy of the library
  * AutoUpdater.NET requires .NET framework, so we're back to needing .NET Framework after we just yanked all requirements for the framework
  * Frankly I don't like the way AutoUpdater.NET has turned out, the .NET core code hasn't seen work in almost a year, and the main project has no indication that it will support .NET core anytime soon. 
* Having multiple versions installed at once would be nice, in case an update breaks something and we want users to roll back temporarily
* Users should have an easy way to start the application, they shouldn't have to hunt through a folder of 400 files to find `Wabbajack.exe`

If we have a folder structure like this:

```
Wabbajack.exe
\Versions\0.9.17.0\Wabbajack.exe
\Versions\1.0.0.1\Wabbajack.exe
``` 

We could easily update Wabbajack while it's running. We simply create a new Wabbajack folder, then spawn a new process and kill the current one. Users would always run the top level `.exe` which would spawn into the process with the most recent version number. In addition, we could build this folder structure on the server, for example:

```
Wabbajack.exe
\Versions\0.9.17.0\Wabbajack.exe
``` 

```
Wabbajack.exe
\Versions\1.0.0.1\Wabbajack.exe
``` 

During an update, 0.9.17.0 would be running, it would download the .zip for 1.0.0.1, extract it in the parent folder, which would overwrite the launcher, and create the new `1.0.0.1` folder. At that point we could also clone over any settings, browser cache, and vfs caches to the new folder.

EDIT: 
Looked into MSIX, and the biggest issue I have with it is that each app must be reviewed and validated by Microsoft. This can take up to 2 days, and publishing can take upto a 24hours. I don't like that timing. So I guess it's time to look more into the approach above.

**Comment by Noggog** [comment]
We can probably work out our own setup, I suppose.  It's really just a download, unzip, start process.  Not too crazy.  We do that all the time already.

**Comment by Noggog** [comment]
Also, we need to think about how we're going to migrate or centralize old WJ settings/caches to the newer install.

Either we can move them as we upgrade?  Or we can have them be in a centralized shared place.
