### ISSUE TITLE
VFS Compiler Error

### ISSUE THREAD

**Issue by PierreDespereaux** [wabbajack-tools/wabbajack#523]
**Describe the bug**
Whenever I try to compile my update I get this error:

28302.95 - Compiler error - System.IO.DirectoryNotFoundException: C:\Games\Modding\Wabbajack\0.9.18.0\vfs_staging\4b5c2579-7b4d-4859-9ab1-e2df7672cebd

I have attempted compiling on b15 as well as the most recent version, 9.18.

**Additional context**
Windows 10 attempting to compile for Skyrim: Special Edition.

**Logs**
[Wabbajack 2020-02-14 03_36_17.log](https://github.com/wabbajack-tools/wabbajack/files/4205879/Wabbajack.2020-02-14.03_36_17.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Fixed in 0.9.19 as part of some other fixes.
