### ISSUE TITLE
Keeps Trying to Download 0.9.19.0

### ISSUE THREAD

**Issue by Quest79** [wabbajack-tools/wabbajack#538]
I downloaded the exe. I downloaded 0.9.19.0.zip. Put in same folder. Open exe and it tries to download the file again (very slowly) Why is it not detecting its own file?

[https://i.imgur.com/nfWhUN7.png](https://i.imgur.com/nfWhUN7.png)

**Comment by LostDragonist** [comment]
The file needs to be extract into a folder like this 
![image](https://user-images.githubusercontent.com/7862539/74624827-3ee46d80-5107-11ea-96d7-e99b89adbbea.png)

**Comment by halgari** [comment]
LostDragonist is correct, either wait for the app to self-download, or extract the folder into the structure he described above. But either way, don't run Wabbajack from your desktop.
