### ISSUE TITLE
Files placed in CWD instead of application directory

### ISSUE THREAD

**Issue by LostDragonist** [wabbajack-tools/wabbajack#539]
When launching Wabbjack through a file association, i.e., double-clicking on a .wabbajack file, some files are created in the folder containing the .wabbajack file instead of the folder containing Wabbajack.exe (or wherever they're supposed to be).  The known culprits are the logs folder, the nexus_link_cache folder, and settings.json.

Everything seems more or less functional.  The logs being in a different place may be an issue if a user has trouble finding them.  settings.json being in a different place is mostly a minor inconvenience as WJ will remember different things depending on how you launch it.

Last tested on v0.9.19.0.  Logs don't show anything useful.

**Comment by halgari** [comment]
Pretty sure this is fixed, with the path rework.
