### ISSUE TITLE
Simple

### ISSUE THREAD

**Issue by ryzenvideous** [wabbajack-tools/wabbajack#546]
Maybe if you add Skyrim to Vortex's game list. That'd be nice. 
![lumbergh](https://user-images.githubusercontent.com/61168861/74692090-01a2dd00-51e6-11ea-8367-28b6dd5c151b.jpg)

**Comment by erri120** [comment]
Have you read the readme? Especially the [Note about Vortex Support](https://github.com/wabbajack-tools/wabbajack#note-about-vortex-support)?
