### ISSUE TITLE
Separating exe from modlist

### ISSUE THREAD

**Issue by tstavrianos** [wabbajack-tools/wabbajack#56]
Just to centralize and discuss ideas about having the modlist as separate file.
Pros :
- One central binary that everyone can trust and hosted modlists that use that binary
Cons:
- Modlists potentially not compatible across versions of the exe, possibly confusing users

Current proposals:

- Json/XML file with a header field mentioning the version used to create the modlist
- Script file with a list of instructions to run
- Others?

I'll edit this if anyone posts any other proposals.

**Comment by tstavrianos** [comment]
Explanation for script file proposal.

Either in the form of an embedded script language (lua/wren/c# through roslyn/....) or a list of simple lines in the format "<command> <parameter1> ... <parameterN>

Wabbajack will have a list of supported commands (or bindings if using a scripting language) and future versions will not remove existing commands to maintain modlist compatibility.
Sample commands:
Download <url> <filename without path> //download a file to the downloads folder named as in the parameter
ExtractToMods <filename without path> <target folder name> //extract a file to the mods folder
ExtractToTemp <filename without path> <target folder name> //extract a file to the staging folder
CopyFromTemp <filename with relative folder> <target folder and file name> //copy from temp to mods

Sample script:
Download 11563 "moda.zip"
ExtractToTemp "moda.zip" "moda extracted"
CopyFromTemp "moda extracted/fileA.esp" "modA installed/fileA.esp"
CopyFromTemp "moda extracted/fileA.bsa" "modA installed/fileA.bsa"

**Comment by erri120** [comment]
Script parser:
https://www.antlr.org/, https://github.com/antlr/antlr4. I know that there is also a project based on antlr for C# but I misplaced the link. https://github.com/westes/flex is also a possible parser.

**Comment by Cyclonit** [comment]
At least for the beginning, I would suggest not adding a script file. That should be its own feature request as it is unrelated to the mod list itself.

**Comment by tr4wzified** [comment]
This issue should be closed now. Fixed in commit #4597135de54284615e1010b0f974483fc7db67ea
