### ISSUE TITLE
ModList Gallery Not Swapping to InstallView

### ISSUE THREAD

**Issue by Hillgrove** [wabbajack-tools/wabbajack#563]
1. When downloading a modlist there are no indication whether it actually downloaded
2. The app doesn't tell you where the modlist was downloaded to when it succeeds. I was expecting for it to turn up in my regular downloads folder (or documents folder as that's the folder WJ defaults to open when asking it to load a modlist)
3. The app doesn't tell you, you don't have to choose your game installation folder for installation (In fact I think that would be counter productive) but rather a separate folder.
4. This info in the online WJ guide (https://www.wabbajack.org/docs/guide) seems to be outdated:
>6. In the lower left quarter of the window, set the “MO2 Profile” field to your chosen installation folder (it will default to where Wabbajack is located) and the “Download Location” field to your new downloads folder. This will default to “downloadlocation”/MO2/downloads.

**Comment by Noggog** [comment]
Heya!  Thanks for the thoughts and feedback.

1)  Do you mean via the Modlist Gallery?  I believe it is supposed to show a progress bar as it's downloading (in the "tile" of the modlist you selected).   Once it's done downloading (or if it already exists), you should be brought to the installation view, which is the indication that it's done downloading and ready to install.
2)  Sort of.  I'd argue the user doesn't need to necessarily know, as downloading/starting a modlist from the gallery sets the installation config page up for them, so they don't need to know where it is.  Additionally, they can see where it is if they want via the `target modlist` filepath picker in the installation config view once it comes up.
3)  I forget exactly the default behavior, but yes, I don't think WJ has any tooltips/popups of suggestions of where to install the modlist.  Could probably add a little something something.  I've also thought about having WJ explicitly block (not be installable) if the user has the game folder selected, as they never should be doing that.
4)  Yeah, docs are probably outdated.  Things have been moving pretty fast, haha.   I think @erri120 has a new site in the oven anyway, so probably would be updated there and fixed when it rolls out?  He'd know more

**Comment by Hillgrove** [comment]
no worries.. It's an amazing progress you guys (and girls?) have had so far with WJ. Keep it up :)

1. not sure what the window is called, but it's where you can see all the different mod lists features (inside WJ).. In this case I wanted to install F4EE and clicked the little arrow (that downloads the file: fallout_4_enhanced_edition.wabbajack).
For me I was confused as I didn't get an indication (or it was so fast I could have missed it). In any case I had to manually start the F4EE installation by using the "Install Modlist" option (I believe it was called) and point it to the previous mentioned file in the "downloaded_mod_lists" directory.
2. If downloading a modlist from the gallery had automatically switched my view to the installation page, then yes, I wouldn't have needed the information (although as a person that grew up with DOS and managing files/folder I like to know where stuff is :) ).
3. The blocking would be a nice QoL. And I'm sure you get around to the usability of WJ as features and bugs have been squashed.
4.I guess that what happens when the development is fast. No worries though.. so far the install is running smoothly, and I only mentioned these few items as I've been in support for parts of my life, and users in general are stupid and will break stuff if they can.

**Comment by Noggog** [comment]
Huh, that sounds like a bug then.  Clicking download on a modlist should either result in an error icon being shown, or it should bring you to the install view after it's ready.

Maybe do it all again, and have it fail to swap to the install view.. and see what's in the log?  Maybe something is printing there that explains it.  Otherwise, sounds like something to look into.

**Comment by Hillgrove** [comment]
now that F4EE has installed I gave it a second shot. But it still doesn't automatically go to the install window after downloading a ML.

Before starter the WJ app I deleted all logs.

This is the content of the only log file created after trying the above and closing the program.

>0,06 - Wabbajack Build - 6501fe8ce879920e5ca0305980c67c2608addfe2
>8,05 - Loading ModLists from GitHub
