### ISSUE TITLE
Game Folder contents preview

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#566]
**Is your feature request related to a problem? Please describe.**
In the same way that we can print the manifest or the readme without installing a modlist, it would be nice to be able to review the content of the Game Folder, in order to assure the right files are being deployed with the modlist (no ENBs or custom things)

**Describe the solution you'd like**
A button or a CLI option in the UI for creating a modlist.

**Describe alternatives you've considered**
I have no idea

**Additional context**
You guys rock!

**Comment by halgari** [comment]
Not longer required as game folder files are now always explicit
