### ISSUE TITLE
Download speed limiter

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#57]
**Is your feature request related to a problem? Please describe.**
You might throttle others on the same connection if you let Wabbajack run for a while downloading huge modlists. There should be a way to limit the download speed.

**Describe the solution you'd like**
Currently I'm thinking about a checkmark and when checked show a textbox that lets the user enter a maximium speed.

**Comment by erri120** [comment]
https://github.com/halgari/wabbajack/blob/master/Wabbajack/Installer.cs#L531 is the point of interest

**Comment by halgari** [comment]
We can do this now via the resource usage slider, it's not bandwidth based, but it is number of concurrent downloads based.

**Comment by Gvaz** [comment]
I also have this issue, when these modpacks have 700+ to download, I shouldn't have to go into some third party software and cap it manually. Setting concurrent downloads isn't retroactive either so i'd have to close the software down
