### ISSUE TITLE
Add non-Nexus mods to the Slideshow

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#573]

**Comment by erri120** [comment]
Slideshow has the [`TargetMod`](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack/View%20Models/SlideShow.cs#L33) property which is currently only for Nexus Mods [here](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack/View%20Models/ModVM.cs#L14). That VM needs to be changed and [this](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack/View%20Models/SlideShow.cs#L81) selection

**Comment by erri120** [comment]
`public ModVM(NexusDownloader.State m)`, `NexusDownloader.State` should be changed to `AbstractDownloadState` but the problem being that some states are not able to get any useful metadata like `HTTPDownloader.State`, `GameFileSourceDownloader.State`, `GoogleDriveDownloader.State`, ...
I think a new abstract class like `AbstractMetaState` or something like that which has properties for `Author`, `Link`, `ImageLink`, ...

**Comment by erri120** [comment]
Going with a new abstract class for the States with metadata would also help the manifest since that can also be filled with more information

**Comment by Noggog** [comment]
So, some top-down overview of how things are set up now, just for refresher:
- We have a list of mods, we shuffle and then filter out non-nexus ones
- We wrap them in a ModVM class, which wraps the information, but also more importantly exposes  a `IObservable<BitmapImage>`, which powers our caching systems.
- Slideshow systems select the "top" `ModVM` and subscribes to the observable, which does the work to download/convert, and then displays the image
- As the slideshow systems designate a new "top" mod, the old observable is unsubscribed from, and the new one is subbed to.. releasing it to be cleaned up.
- We then subscribe to the "top 3" separately alongside, to "prep" the next few slides so they're ready to go when they actually are "top"

What i think we'd need to do to get other non-nexus mods into the system:
- Add an abstract base class or interface that Nexus states would implement, as well as other sources that want to be exposed to the slideshow.
- Refactor `ModVM` to be a bit more agnostic, and be able to wrap other things and still expose the Bitmap observable.  This would likely just be refactoring it to take the new base class/interface
- Change the filtering so it filters on the interface, not on nexus state type
