### ISSUE TITLE
Vortex Modlist does not output to the Correct Location

### ISSUE THREAD

**Issue by LadyZeefa** [wabbajack-tools/wabbajack#580]
**Describe the bug**
I have a specific Output folder that I point Wabbajack to when compiling modlists on my modding drive. Mo2 modlists go to the location with no issue. When compiling a Vortex Modlist for Stardew Valley, the output Location was ignored and the wabbajack file was placed in the 0.22.0 folder instead. It also did not use the modlist name that is used in configuring.
![explorer_Gxrdm3fhOS_LI](https://user-images.githubusercontent.com/57296851/75296613-a67f7480-57fb-11ea-88d3-c43783c7d192.jpg)

**Additional context**
Windows 10, Stardew Valley
**Logs**
[Wabbajack 2020-02-25 18_13_49.log](https://github.com/wabbajack-tools/wabbajack/files/4252620/Wabbajack.2020-02-25.18_13_49.log)
**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by tr4wzified** [comment]
Should be closed now that Vortex support has been dropped
