### ISSUE TITLE
Add option to not overwrite existing installation

### ISSUE THREAD

**Issue by pgdeaner** [wabbajack-tools/wabbajack#582]
It would be great if you could add an option on an overwrite install for leaving mods that are not part of the modlist in the mods directory and just deactivating them in MO2. This would help with the end user customization of Wabbajack installs. Thanks for your consideration. I love the Wabbajack tool.

**Comment by t3h0th3rLL** [comment]
This would be a very useful feature when updating (and it would also give purpose to the currently existing but defunct checkbox "Overwrite Installation" :D) .

**Comment by t3h0th3rLL** [comment]
Alright, thanks for the quick reply.

**Comment by halgari** [comment]
in master
