### ISSUE TITLE
Store settings.json in local appdata

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#587]
`settings.json` is currently stored in the same folder as the Wabbajack executable. Since we now have an auto-updater and use `%localappata%/Wabbajack` for other stuff, the `settings.json` file should also go in there. Currently whenever WJ updates you get a clean settings file.

**Comment by Noggog** [comment]
I'm on board.  Upsides outweigh the downsides, i think?

Downsides would be that it wouldn't work well to run two WJ's at once (last one to close gets its setup saved), and if we update the settings structure heavily in non-backwards compatible ways it'll break older build's settings.

Alternatively we could have the autoinstaller copy the settings file to the new folder when downloading?  Just another alternative with the same end result.
