### ISSUE TITLE
Move Logs to Common Area

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#591]
I noticed the `!wjlog` bot saying:

`You can find the relevant file (Wabbajack.current.log) in the /logs/ folder within the latest version folder i.e. 0.9.19.0`

Might be nice to move the logs to either %temp% somewhere, and/or have them write to alongside the top level bootstrap app

**Comment by erri120** [comment]
Should be closed now that we have logs in the `%version/logs` folder
