### ISSUE TITLE
Automate the Process of Clicking "Manual Download" > "Slow Download" for Non-Premium Users.

### ISSUE THREAD

**Issue by Kristijan1001** [wabbajack-tools/wabbajack#597]
**Is your feature request related to a problem? Please describe.**
It would make things faster and easier for people who don't have a premium and overall improve the usability of the application.

**Describe the solution you'd like**
Auto Macro implemented in Wabbajack that Automates the Process of Clicking "Manual Download" > "Slow Download" for Non-Premium Users.

Note: Sometimes it says that you are missing some Mods too, so there is an extra "Download" Button Click that needs to be done.

**Describe alternatives you've considered**
Alternative would be a External Macro running and doing it for you. 

**Additional context**
I think opening the site every time for thousands of Mods and loading the ads in the process will generate more revenue for Nexus, rather than getting premium. It's a win win situation for both sides.

**Comment by halgari** [comment]
No, the automated API exists on the Nexus for a reason. The price users pay for not paying for their bandwidth is ads and slower download. It's very possible to automate these steps, but we will not do so. If users want a better experience in this area they can spend $4 for Nexus premium

**Comment by Kristijan1001** [comment]
Like i mentioned my reason was not to avoid the ads and make the link direct and automated. But instead automate the mod downloading from the website. So it will still load all the ADS in the site every time each mod is opened it will just click on the buttons automatically. But fair enough i guess. Thank you.
