### ISSUE TITLE
Able to Navigate Back During Installation

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#598]
Seen on a few occasions users reporting they were able to navigate back to the main view while an install was occurring.  This shouldn't be possible, but after having seen it reported a few times I think somehow it is.

Need to investigate what edge cases this could be happening.

My initial thought is perhaps one half of the command may not be getting an initial value going into the combine latest in this statement:
https://github.com/wabbajack-tools/wabbajack/blob/5afb667fcaf4f2f7f8e33d9552481a8891eb53b8/Wabbajack/View%20Models/Installers/InstallerVM.cs#L226-L231
If no value comes out of the combine latest, then perhaps the ReactiveCommand's default initial state is enabled?  So then the user can click the go back button?

Quick fix might be to just add some `StartWith` calls, but would be curious to know if/what would be blocking and not supplying a value

**Comment by EzioTheDeadPoet** [comment]
wasn't this fixed a while ago ?

**Comment by halgari** [comment]
fixed in master
