### ISSUE TITLE
Cleanup Utils.cs

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#604]
`Wabbajack.Common.Utils` is sitting at >1300 lines. We should prob work with [`#region`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region) for better organization.

**Comment by Noggog** [comment]
Yeah, part of the problem I think is it's just doing too much.
It's got:
- Logging mechanics
- Random enums
- Hashing logic
- Random miscellaneous extension methods
- INI and Ceras parsing
- PMap logic
- I just stopped scrolling

I think first we need to see if/how we can extract some of those concepts to their own dedicated areas.  Then see how the overall length is of the resulting setups?

**Comment by halgari** [comment]
Extension methods can be pulled into their own class easy enough without affecting the app, we can also divide the class into groups of methods and put each group in its own class but combine them via partial classes. I like how easy it is to say Utils.`bleh` to get to any commonly used function, so I'd rather not split the methods into separate classes.

**Comment by halgari** [comment]
Started on this in master, will continue to work on it over time
