### ISSUE TITLE
Fields clear when modlist.txt is selected

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#612]
**Describe the bug**
When creating a modlist, you will first notice the modlist name and such that you can fill out on the left. Until you get to the image part, where you'll first have to select the profile modlist.txt before being able to do this. This isn't really made clear - could perhaps also use some improvement. Main issue though is that these fields that were all filled in are cleared when the modlist is selected, potentially losing someone their description they wrote.

**Comment by Noggog** [comment]
What you're experiencing is WJ's attempt to "save" the current values to the old modlist.txt settings, and load up the new settings.  New settings don't exist and are empty, and the old settings saved to the void of an empty string profile.

I think the solution should be either:
- Disabling all those inputs until modlist.txt is selected
- Adding additional logic to not clear it out if current modlist.txt is empty string.

I think the second solution isn't as viable, as there's a sticky edge case.  What if you enter a bunch of info, then load a modlist.txt that has settings already for it.  Does it delete those settings and apply the current values.. or delete the current values and replace them with what it had in the savefile?  Not clear.

**Comment by tr4wzified** [comment]
Or perhaps first pop up a nice screen to select the profile (or Mod Organizer like issue #608 describes with the dropdown) and then show the current window we use.

**Comment by Noggog** [comment]
I like having the "last used" setup automatically load with no dialog or fuss.  If someone is working on the same modlist repeatedly (which is typical), I like that they just go to the compile area and everything loads up for them immediately.  It's much rarer that they're making a new list.

Also, there's a lot of edge/use cases where "losing your work" problem can occur, not just related to creating a modlist for the first time.  Consider you've been working on a modlist for a while.  Compiled a few times, etc.  You load up WJ, modify some descriptions, and then realize/remember that you moved where the modlist.txt file was on your harddrive.  Shit.  Now you gotta navigate it to where it was moved to, which WJ sees as a new modlist (as it's keyed by path) and nukes your existing work in a similar fashion.

The disable solution would also solve this, as no fields would be modifiable unless the modlist.txt exists.  This solves most of the edge cases I can think of that would lead to lost work problems?

**Comment by halgari** [comment]
Is this still an issue @tr4wzified ?
