### ISSUE TITLE
Could not find Game location

### ISSUE THREAD

**Issue by GumDrops73** [wabbajack-tools/wabbajack#613]
in order to do a proper install Wabbajack needs to know where you Skyrim Special Edition folder resides. We tried looking the game location up in the Windows Registry but were unable to find it, please make sure you launch the game once before running this installer

![12121](https://user-images.githubusercontent.com/59759216/76040530-8e8dba80-5f8a-11ea-9e3a-cdb2e0255b05.png)

**Comment by halgari** [comment]
Pretty simple error, you need to install Skyrim Special Edition via Steam before running Wabbajack

**Comment by GumDrops73** [comment]
oh so a reinstall is needed thanks

**Comment by Evaderik** [comment]
Where is button "_Set path to game directory_"?
PS: Because I do not use 'steam version'. :)

**Comment by EzioTheDeadPoet** [comment]
> Where is button "_Set path to game directory_"? PS: Because I do not use 'steam version'. :)

Don't Pirate the game and Wabbajack finds it.
