### ISSUE TITLE
Something better than Ceras

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#619]
As specified in #595 we use weak typing in several parts of our app. And secondly we've poured concrete on this part of the app by using Ceras: a serialization format designed primarily for short term serialization across network connections. 

## Issues with Ceras
Because ceras was designed for a situation where the data only lives for a single game playthrough or while in transit across a network, simple things like storing type information were elided for more performance. This limitation wasn't initially apparent during our selection process for the library. 

This limitation manifests itself in Ceras's ability to read and write formats as they change over time. Changes such as type changes, name changes, or adding or removing of fields can cause data to no longer be compatible with future versions of the app.

## Requirements of our usage of a serializer

* Support renaming of attributes
* Support type changes of attribute, the in-app's version of an attribute should not be directly tied to the at-rest format of the attribute. We should be able to use a long in-memory (for example) but store it on disk as a string. 
* Support for polymorphic types
* The .NET type name shouldn't be directly linked to the on-disk name for custom classes. In otherwords `Foo.Bar.MyClass` should be allowed to be renamed and/or moved without worry of breaking previously serialized types
* The members in a class should be re-orderable and renamable without worry of breaking the data type
* The serializer should be fast enough to support WJ's rather massive list structures

## Solution
-- more to follow --

**Comment by erri120** [comment]
Closable with Wabbajack 2.0 I think?
