### ISSUE TITLE
"Include Saves" Checkbox

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#627]
**Is your feature request related to a problem? Please describe.**
No problem, just another small quality of life change.

**Describe the solution you'd like**
A checkbox on the Compile Modlist page to either include or ignore the "saves" folder for the profile selected to compile would be ideal.

**Describe alternatives you've considered**
Not forgetting to delete the saves in MO2 or out of the saves folder before compiling.

**Additional context**
None.

**Comment by tr4wzified** [comment]
Pretty sure saves are ignored now? At least they're not removed when updating an existing list

**Comment by halgari** [comment]
Saves are ignored now
