### ISSUE TITLE
Shut down PC when complete

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#629]
(from [`#general`](https://discordapp.com/channels/605449136870916175/605449136883499140/687256205860536355))
> Are there any plans for a 'shut down pc when complete' option in WJ? Assuming it's even possible given Windows access limitations it'd be a nice option for those of us leaving their PC's on overnight to download bigger lists.

I see two solutions: 
1) simply call the shutdown command
2) Using [WMI](https://stackoverflow.com/questions/102567/how-to-shut-down-the-computer-from-c-sharp/102583#102583)

**Comment by halgari** [comment]
I don't think we plan on implementing this, it's a fine enough feature, but I don't really see the point for the limited usage it would get.

**Comment by EzioTheDeadPoet** [comment]
I know you closed this request, but I might eventually will try to implement it. My reason being that I can let a compile/installation run overnight or when going to work, without having my PC draw power and make noise in my room longer than it needs to. (I still consider it low priority but I might want to try it.) If you really wouldn't want it tho I would respect that decision. It is just that as big as lists have become this really is a thing I could imagine more people doing.
