### ISSUE TITLE
Morrowind Modlist Install Failure

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#631]
**Describe the bug**
Attempting to install a Morrowind modlist using the [Morrowind Code Patch](https://www.nexusmods.com/morrowind/mods/19510/) fails due to WJ being unable to locate the game. The Morrowind Code Patch generates a new Morrowind.exe and backs up to original .exe as Morrowind.Original.exe. 

**Additional context**
Windows 10 Version 10.0.18362 Build 18362. Morrowind GOTY Steam edition.

**Logs**
No log is generated when WJ fails to locate a game installation. I have attached the two most recent logs I have and included links to the Readme/.wabbajack

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4322419/Wabbajack.current.log)

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4322421/Wabbajack.current.log)

[MOISE Readme](https://drive.google.com/open?id=18woAAygVC6H75KBvESqhIQn4u3-bDdAb)

[MOISE Wabbajack Files](https://drive.google.com/open?id=1okjwNayqiva6FdFw79jgbM81695PsSSX)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by ForgottenGlory** [comment]
I have tested the install with both the Code Patch modified .exe and the vanilla .exe, both fail.

**Comment by ForgottenGlory** [comment]
A completely fresh, brand new Steam installation failed as well.

**Comment by erri120** [comment]
Simple fix: Update the Morrowind values in the internal game registry (https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Common/GameMetaData.cs#L149)

**Comment by erri120** [comment]
Closed with 3e2b23f07d30f4c22a851d6020b02349c2dd984b
