### ISSUE TITLE
Launcher EXE fails to launch after several days.

### ISSUE THREAD

**Issue by Timboman** [wabbajack-tools/wabbajack#642]
The Auto Updater Wabbajack.exe eventually fails to launch, either after a specific number of launches or after a period of time has passed. The build specific Wabbajack.exe file inside the X.X.X.X build folders work fine and if the exact same launcher EXE is re-downloaded from GitHub it continues to work.

Ethereal issue that needs more investigation, will update if anything can be assertained.

**Comment by halgari** [comment]
@Timboman do we get a screenshot? Does it start to download something? I'll try starting it a bit and see what I can find.

**Comment by Noggog** [comment]
Maybe something to do with the log rollover system?  If the bug is in the old log deletion logic, this would be something that would come up after X tries or days... but never affect new installs

**Comment by Timboman** [comment]
> @Timboman do we get a screenshot? Does it start to download something? I'll try starting it a bunch of times and see what I can find.

Nope, no screenshot. Nothing opens, the process blips up for a second then self terminates (I had task manager open to see what was happening). I can't replicate it right now either, since like I said replacing the exe with another copy of the same one downloaded from Gitub (from the same release) fixed it, so it's currently working for me.

**Comment by Timboman** [comment]
At least Total, Lively & Jdsmith have all encountered the same problem (and fixed it the same way) so it's not isolated to just me.

**Comment by Cheeseburger23** [comment]
This issue is caused by MSI afterburner(or EVGA precision) for some reason. Closing it allowed me to open the EXE

**Comment by Cheeseburger23** [comment]
Installer now works after keeping afterburner closed.

**Comment by Timboman** [comment]
I have MSI Afterburner open and it does still work for me currently, so I'm not sure that is the main issue. See the attached screenshot, MSI Afterburner is open, and I can launch WJ via the Launcher EXE with no issue.
![example](https://user-images.githubusercontent.com/36910038/77366846-4d89fa00-6d2f-11ea-9cf4-b79bd67ce91b.PNG)

**Comment by Cheeseburger23** [comment]
> I have MSI Afterburner open and it does still work for me currently, so I'm not sure that is the main issue. See the attached screenshot, MSI Afterburner is open, and I can launch WJ via the Launcher EXE with no issue.
> ![example](https://user-images.githubusercontent.com/36910038/77366846-4d89fa00-6d2f-11ea-9cf4-b79bd67ce91b.PNG)

Hmm... well i guess i had a different issue then.
