### ISSUE TITLE
"Non-essential" tag for mods so little things don't put your list offline

### ISSUE THREAD

**Issue by PierreDespereaux** [wabbajack-tools/wabbajack#650]
**Is your feature request related to a problem? Please describe.**
Recently Titillating Barrels took down a whole host of modlists when it is not a mod anyone would consider essential. Non-essential mods would likely mainly be non-.esp graphical mods so users don't unknowingly break their save.

**Describe the solution you'd like**
Add a WABBAJACK_NONESSENTIAL tag to be able to be added to mods in your modlist. If Wabbajack cannot find that mod it will skip it. 

**Describe alternatives you've considered**
The self-healing feature is similar to this, but does not cover non-Nexus mods and, in general, the current implementation can make it hard to communicate to the author what is and isn't currently updated. This tag would ensure that the list would remain up if a non-essential mod was taken down.

**Comment by Timboman** [comment]
Conversely you could use the same methodology to make a WABBAJACK_HIGHRES tag to make it skip MO2 mods that specifically are only higher resolution textures for users who have lower end PCs. If the above is possible then this should be too, tho you'd have to create some kind of prompt for the user for the latter.

**Comment by PierreDespereaux** [comment]
That's a really good idea too. I've have a lot of performance users that would appreciate such an option.

**Comment by halgari** [comment]
Fixed as part of the build server updates
