### ISSUE TITLE
Libcef not killing processes

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#651]
**Describe the bug**
```
Not sure if it's known but it seems that Wabbajack doesn't kill the CEF process when the browser window closes: 
```
![Screenshot of Taskmanager](https://puu.sh/FpLMp/51013e096f.png)

**Comment by Unnoen** [comment]
Probably should have created an issue for this, thanks for doing that.

More info if needed:
- Wabbajack version 1.1.3.0, however it's being reported as `Wabbajack v1.1.2.0
a7765311a8cca71f38537d30b89ad104897b10b1` internally.
- Installing Lexy's LOTD with a non-premium account. 

Every time it prompted me to manually download an archive, I noticed the sub-processes increment by one.
