### ISSUE TITLE
Preserve modlist.txt order for disabled mods

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#652]
**Is your feature request related to a problem? Please describe.**
When using multiple profiles for the installation, they have different mods enabled/disabled in the left pane of MO2. And also a specific ordering. But after compiling and installing with WJ, the order is lost for the mods that are disabled in one profile. This also applies when using `WABBAJACK_ALWAYS_ENABLE`

**Describe the solution you'd like**
It seems WJ builds its own modlist.txt after the build. maybe it should preserve the original modlist.txt so the ordering is not lost for the disabled mods.

**Describe alternatives you've considered**
Maybe a way to include the original modlist.txt in some folder in order to overwrite the WJ's one so the ordering is not lost for the disabled mods

**Additional context**
It looks like this in user's end:
![](https://cdn.discordapp.com/attachments/620954238931173378/693830264551374868/unknown.png)

it should look like this:
![](https://cdn.discordapp.com/attachments/620954238931173378/693831269057953882/unknown.png)

**Comment by erri120** [comment]
Quick observations:

Original `modlist.txt`:
```
# This file was automatically generated by Mod Organizer.
+New Merge
+Nether's Follower Framework
+Honed Metal - SSE
+Summermyst - Enchantments of Skyrim
-RaceMenu <- WABBAJACK_ALWAYS_ENABLE
+performance textures 1024x1024
*DLC: Dawnguard
*DLC: Dragonborn
*DLC: HearthFires
```

`modlist.txt` that gets inlined:

```
# This file was automatically generated by Mod Organizer.
+New Merge
+Nether's Follower Framework
+Honed Metal - SSE
+RingOfThePathfinderSE
+Summermyst - Enchantments of Skyrim
+performance textures 1024x1024
*DLC: Dawnguard
*DLC: Dragonborn
*DLC: HearthFires
```

**Comment by erri120** [comment]
https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/CompilationSteps/IncludeThisProfile.cs#L42

All disabled mods are being removed here
