### ISSUE TITLE
Option to manually set game install locaiton.

### ISSUE THREAD

**Issue by Aidiah** [wabbajack-tools/wabbajack#653]
Just a simple option when picking the installation/download location to set the game installation location would be great. 

While you can run the game once to set registry values, not every setup allows it.

Setups being:
 Two install dirs of Skyrim. Why? no idea.
 Wine on Linux, steam instances all games running in proton. Running wabbajack in its own wine prefix doesnt allow it to see skyrim as installed.
 etc

**Comment by erri120** [comment]
We currently have no plans for Linux support. Even if you could manually set the game location WJ, MO2, ENB and SKSE will not work on Linux atm.

**Comment by Aidiah** [comment]
Linux was just an example. I can think of many more use cases for the feature, relying on registry values being present is just a bad idea.

**Comment by tr4wzified** [comment]
While I haven't tried it yet, Wabbajack *should* work on Linux if you run Steam + Skyrim in the same wineprefix. It uses .NET Core, should be available on Linux now.
