### ISSUE TITLE
Add MEGA Login

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#664]
We currently auto login as anonymous when downloading something from MEGA ([reference](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/Downloaders/MEGADownloader.cs#L31)). This is fine for most stuff but the reason mods are being hosted on MEGA is because they are huge. If a modlist only has one or two MEGA links, all is fine but when you have something like [Lotus](https://github.com/wabbajack-tools/opt-out-lists/blob/master/ServerWhitelist.yml#L177) which downloads multiple big mods from MEGA, not only will we get reduced speed but also reach the download limit soon-ish for the user.

If the user has a MEGA account we could add MEGA to the login manager and login using other `MegaClient.Login()` overloads ([ref](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_Login_CG_Web_MegaApiClient_MegaApiClient_AuthInfos_)).

**Comment by erri120** [comment]
MegaApiClient has multiple different ways to login to mega:

- [`Login()`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_Login): this is what we currently use (Anonymously)
- [`Login(MegaApiClient.AuthInfos)`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_Login_CG_Web_MegaApiClient_MegaApiClient_AuthInfos_): login using hashed credentials ([`AuthInfo`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.AuthInfos.html))
- [`Login(String, String)`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_Login_System_String_System_String_): login using email+password

I think [`Login(MegaApiClient.AuthInfos)`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_Login_CG_Web_MegaApiClient_MegaApiClient_AuthInfos_) would be the best which requires [`AuthInfo`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.AuthInfos.html) that can be generated using [`GenerateAuthInfos(String, String)`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_GenerateAuthInfos_System_String_System_String_).

Question is how to add the login to our login manager. Simple popup with email/password text fields or something different?

**Comment by halgari** [comment]
Thanks for adding this, I've punted on this issue for some time. Any storage method we use we can store the data via our normal encryption routines, so security is pretty good there. Is there a way to login via a browser? If so that would save us having to add another UI window. The UI portion of this is likely the part that would take the most time.

**Comment by erri120** [comment]
Doesn't look login via browser is possible. I'm not sure what the capabilities of CefSharp are but if we really wanna use the internal browser, we could maybe create a template HTML file if we don't want another WPF window.

**Comment by erri120** [comment]
Went ahead and added the basic implementation for `INeedsLogin` to the `MegaDownloader`: [PR](https://github.com/wabbajack-tools/wabbajack/pull/669). Since this is in `Wabbajack.Lib` creating a UI is a bit... unclean.
