### ISSUE TITLE
No ModOrganizer2.exe found

### ISSUE THREAD

**Issue by robbyjo** [wabbajack-tools/wabbajack#67]
**Describe the bug**
Mod Organizer 2 is installed in D:\MO2, while its data is installed separately in D:\MO2-Data
When I tried to create modlist from modlist.txt, I got the error of "No ModOrganizer2.exe found in D:\MO2-Data"

**Additional context**
Win 10, Skyrim SE

**Logs**

**Solution**

**Comment by erri120** [comment]
MO2 has to be in portable mode. You can't seperate the MO2 folder when using WJ
