### ISSUE TITLE
Possible issue with MO2 files

### ISSUE THREAD

**Issue by ductiletoaster** [wabbajack-tools/wabbajack#68]
**Describe the bug**
Compiler failed to build with the following error. This is a brand new computer and so I likely have the latest version for M02 etc.

**Additional context**
Windows 10 (brand new install)
Skyrim SE (brand new install)

**Logs**
```
1377.91 - zEdit not detected, disabling zEdit routines
1377.91 - Running Compilation Stack
1377.96 - No match for: unins000.dat
1377.96 - No match for: unins000.exe
1378.6 - Adding 0 that were generated by the stack
1378.61 - No match for 2 files
1378.61 -      unins000.dat
1378.62 -      unins000.exe
1378.62 - Exiting due to no way to compile these files
```
Full file can be found here. https://github.com/ductiletoaster/aetherium/blob/master/Wabbajack.exe

**Solution**
More a work around but I was able to get past this step by simply removing these two files. Likely need to add them to the "whitelist" of M02 files?

**Comment by halgari** [comment]
Those only show up when MO2 was installed via a installer instead of via the portable archive method. Currently only the portable archive method is supported.
