### ISSUE TITLE
Version field for Modlists

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#686]
We already had a talk about this on discord some time ago but while doing #684 I wish we had one.

A version field where you **must** set the version matching this regex:

```regex
^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

(from the [Semantic Versioning document](https://semver.org/), also see [this example](https://regex101.com/r/Ly7O1x/3/))

I honestly think it's better to just force `Major.Minor.Patch.Build` or `Major.Minor.Patch` and **not** go the _you can type whatever the f you want_ route that _some_ popular modding sites (all) take.

**Comment by Noggog** [comment]
Yeah, im down with just using a Version GUI control that takes four bytes as numbers, and binds via the typical C# `Version` class.

**Comment by erri120** [comment]
Also: write information about the modlist to some file in the MO2 directory. eg: `MO2/modlist-info.txt`:
```
Modlist: erri120's Dope Test Modlist
Version: 1.2.3
Installed at: 01.01.1970
Installed with: Wabbajack 2.0.0.0
```

**Comment by erri120** [comment]
Possible regex:
```regex
https://regex101.com/r/Y7dT2N/1
```
