### ISSUE TITLE
Purging of Vortex support

### ISSUE THREAD

**Issue by erri120** [wabbajack-tools/wabbajack#689]
I'm still proud at #142 and it certainly worked for _some_ time, Vortex support turned out to be... useless. I want to use this issue to discuss what exactly we want to remove.

Obviously starting with the UI so that you can't access the Vortex compiler and installer. Then we can remove [`VortexInstaller`](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/VortexInstaller.cs) and [`VortexCompiler`](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/VortexCompiler.cs). We might wanna cleanup the [`GameMetaData`](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Common/GameMetaData.cs) and remove Vortex games.

#142 did more than just add Vortex support, it also introduced more abstraction into the codebase to make it easier when adding more mod manager support. This is perhaps the biggest discussion point: how much of the abstraction do we wanna remove and how easy do we wanna make it to add different Install/Compile options. (#321 also has some info)

I mean, we have MO2 support and it works, it's good, we all love it but it's only for TES/Fallout games. Then we have the hidden Steam Workshop support I implemented ([here](https://github.com/erri120/wabbajack/blob/master/Wabbajack.Lib/CompilationSteps/IncludeSteamWorkshopItems.cs)). Some games like Darkest Dungeon or Divinity Original Sin 2 pretty much only have the Workshop (+ Nexus sometimes).

**Comment by halgari** [comment]
done in master
