### ISSUE TITLE
Implement quad-state list status

### ISSUE THREAD

**Issue by halgari** [wabbajack-tools/wabbajack#708]
Currently lists are either "down" or "up", even though we really have 4 states for a given modlist:

* Available
* Broken
* Broken but being "healed"
* Available but auto-healed

Our reporting code also doesn't notify mod authors of any previously healed items. All this needs to be cleaned up:

1. Track files lists are healed
2. Track files in those lists so authors can be notified
3. Track broken healing attempts
4. Make healing more generic (not just for Nexus mods)
5. Update the UI to show the 4 states of the list
6. Don't allow users to arbitrarily request list healing, this should only be triggered by the server
7. Track modlist files in SQL so we can easily figure out the status of a list in relative real-time

**Comment by erri120** [comment]
should be closed, no?
