### ISSUE TITLE
Absolute Path String Error

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#731]
**Describe the bug**
Attempting to compile on WJ 2.0.0 build results in "Compiler error - Cannot create relative path from absolute path string" error.

**Additional context**
Windows 10 v1909 build 18363.778. SSE

Screenshot just in case I've set up a setting/field incorrectly:
![image](https://user-images.githubusercontent.com/25124348/79918626-ccd81f80-83fa-11ea-9bcc-637e062b4471.png)

I don't know if this is related, but WJ2 also doesn't appear to have LL links whitelisted.

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4512803/Wabbajack.current.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Fixed in master
