### ISSUE TITLE
LL Not Whitelisted

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#732]
**Describe the bug**
LoversLab does not appear to be whitelisted on WJ 2.0.0.

**Additional context**
Windows 10 v1909 build 18363.778. SSE

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4513208/Wabbajack.current.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by erri120** [comment]
Fixed
