### ISSUE TITLE
WABBAJACK_NOMATCH_INCLUDE Not Being Recognized.

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#733]
**Describe the bug**
Merges marked WABBAJACK_NOMATCH_INCLUDE / WABBAJACK_INCLUDE are coming up as "No match found".

**Additional context**
Windows 10 v1909 build 18363.778. SSE

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4513212/Wabbajack.current.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Broken by the path changes, fixed in master.
