### ISSUE TITLE
WJ 2.0 Alpha - Not deleting /tmp_files/ while indexing for VFS Cache

### ISSUE THREAD

**Issue by Timboman** [wabbajack-tools/wabbajack#734]
In my test compile for WJ 2.0 (with Alpha 2) I noticed that while doing my initial hashing and indexing that I was RAPIDLY loosing space on my SSD, after some investigation it would appear that WJ 2.0 is NOT deleting files from the /tmp_files/ directory after they have been indexed.

The bloat grew to over 116GB before I had to pull the plug and stop the modlist scan.

Image of the tmp_files folder contents for context
![image](https://user-images.githubusercontent.com/36910038/79928693-9f4aa080-8411-11ea-862c-690d4c54095d.png)
Size of folder, also for context
![image](https://user-images.githubusercontent.com/36910038/79928771-de78f180-8411-11ea-814d-ae1f226de22d.png)

**Comment by halgari** [comment]
Ended up being that the VFS indexer worked on breadth-first instead of depth-first searching. Fixed in master
