### ISSUE TITLE
MEGA login causes Wabbajack to crash

### ISSUE THREAD

**Issue by sweeper240** [wabbajack-tools/wabbajack#752]
**Describe the bug**
Trying to fill login information and login to MEGA causes Wabbajack to crash

**Additional context**
Win 10 x64

**Logs**
[Wabbajack 2020-04-26 01_54_55.log](https://github.com/wabbajack-tools/wabbajack/files/4534781/Wabbajack.2020-04-26.01_54_55.log)

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by erri120** [comment]
Does this happen while you fill out the two fields or when you click the login button? If it crashes while filling out one of the fields, I need to know which one.

**Comment by sweeper240** [comment]
happens after clicking LOGIN

**Comment by erri120** [comment]
I can reproduce this. This happens when you do not enter a password in the 2nd field. Will be fixed in the next release

**Comment by sweeper240** [comment]
Still occurs with a filled password. From the beginning of this error I was inputting a password

**Comment by sweeper240** [comment]
Bug is still present - not fixed. Here look at the screen shot:

1 - there are multiple entry fields, no labels and it defaults to the password entry rather than user id (which is not labeled)

![SharedScreenshot](https://user-images.githubusercontent.com/62799488/80484181-e6a6c480-891c-11ea-80da-840fb274712a.jpg)

2 - when you enter information you are guessing and no matter if you enter all fields or just the top most fields or the just the top and bottom most fields - nothing works.

![SharedScreenshot2](https://user-images.githubusercontent.com/62799488/80484354-371e2200-891d-11ea-8b31-9aad16245f72.jpg)

once I press LOGIN - Crash
