### ISSUE TITLE
Mega Links Formatting Update

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#767]
**Describe the bug**
Mega seems to have updated the formatting for their links such that a link formatted like this is no longer obtainable:
https://mega.nz/#!RVxiWBYA!Uipp7y8vwpPvyRnNRyHoLVT3wFjIEbIdmouMqfsQm60

The new format is: 
https://mega.nz/file/BIZATIxb#q2XDvIiIkEwNnz-8NdRCCVZ3h31Ft7u-Z6PZQ3UWbWM

This appears to cause link validation to fail during compilation on xLODGen 62.7z even while whitelisted.

**Additional context**
Windows 10 v1909 build 18363.778. SSE

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4541111/Wabbajack.current.log)

Related .meta file:
[xLODGen.62.7z.meta.zip](https://github.com/wabbajack-tools/wabbajack/files/4541117/xLODGen.62.7z.meta.zip)

**Comment by sweeper240** [comment]
Trying to login to Mega in wabbajack still causes the program (Wabbajack) to crash close after clicking "Login"

**Comment by sweeper240** [comment]
This is not fixed yet, is the team aware?
I ask because the issue is listed as closed.

**Comment by LostDragonist** [comment]
Which issue @sweeper240?  If you're having some sort of issue with logging in with Mega, which is completely unrelated to this issue, then you should make an issue about it so it can be tracked.
