### ISSUE TITLE
Manual controls do not work?  Disk measurement has to be override?

### ISSUE THREAD

**Issue by pgdeaner** [wabbajack-tools/wabbajack#777]
**Describe the bug**
It does not matter what I set the manual controls to, they get overridden and I get 2 threads.  It would be really nice if the manual controls worked because the disk measurement does not always seem to be accurate.

Log is from intel 9900K, 32GB, E drive is 2TB Samsung 960 NVME at X4 on an intel premium RST controller.

[Wabbajack 2020-04-28 19_59_51.log](https://github.com/wabbajack-tools/wabbajack/files/4551751/Wabbajack.2020-04-28.19_59_51.log)

**Additional context**
Windows 10 (1909), SSE

**Logs**
Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. Refere to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) page if you do not know how to post the stack trace in a code block.

**Comment by Noggog** [comment]
Hey pg,

Yeah, I understand your confusion looking at it again.  In its current state, the Performance settings area will never exceed the internally calculated recommended WJ number of cores.   Both the performance options of auto or manual are for setting how to lower the # cores even more.   WJ recommends 2?  Do you manually want it to be 1, or automatically 50% of whatever WJ recommends... 1?  Neither will ever go above the recommended 2.  (hence the defaulted manual setting of 255, as that gets combined with the recommended 2 to result in 2 cores)

I do think I can:
1)  Change the manual cores to allow for something above the WJ recommended amount.
2)  Update the tooltips a bit to help clarify intention in the settings panel

I'll have to look around again, there may have been some reason I opted to not allow the user to increase.  If not, I'll see about adding it.

**Comment by tr4wzified** [comment]
This amount of threads is used because you only reach 162MB/s on that drive for some reason. Would be best if there was a warning (or some hidden parameter to launch WJ with), I've seen some people try to up it with a very much below average PC, that could cause issues.

**Comment by Noggog** [comment]
Yeah, I'll add some nice red warnings about janking the cores above recommended.

**Comment by pgdeaner** [comment]
That would be great.  Either suggestion would work for me.  In previous builds of WBJ I have been able to install successfully with a lot more threads.  Some of these really big lists like Elder Souls take forever to install with 2 threads.  I think I'm over 5 hours at this point.

**Comment by tr4wzified** [comment]
I think it's a better idea to improve the disk benchmark. Constantly see people mentioning they're on nvme m2 drives and they get 176MB/s in the benchmark, or less. All of the thread issues I've seen are due to disk speed.

**Comment by pgdeaner** [comment]
I would agree that fixing the disk bench is important.  I'd be glad to help test or provide any data that you need.

**Comment by tr4wzified** [comment]
I've got a feeling it might be because the test is quite short (2 seconds). Maybe certain disks don't really like the sudden need to write and the benchmark might be more accurate if it runs for a little longer. I've simply increased it to 5 seconds in my build, could you please test it @pgdeaner and post your logs from both the normal 2.0.3.0 release and this experimental build?

Can't upload very big files here, so here's a link to the compiled build: 
https://drop.infini.fr/r/BWFhHJsa9t#tHL9S+gaGiFxirXnPnL3WF2yC5YY4ERAkpyiAihiBC4=

**Comment by pgdeaner** [comment]
[wbj2_0_3_0.log](https://github.com/wabbajack-tools/wabbajack/files/4587826/wbj2_0_3_0.log)
[wbj2_0_3_0_test.log](https://github.com/wabbajack-tools/wabbajack/files/4587837/wbj2_0_3_0_test.log)

The new one benches the drive slower.  Is the benchmark pulling random reads?  I can get some pretty low scores with crystal on a 4K random single queue run.

**Comment by tr4wzified** [comment]
Might be within the margin of error. I'll take another look later

**Comment by pgdeaner** [comment]
------------------------------------------------------------------------------
CrystalDiskMark 7.0.0 x64 (C) 2007-2019 hiyohiyo
                                  Crystal Dew World: https://crystalmark.info/
------------------------------------------------------------------------------
* MB/s = 1,000,000 bytes/s [SATA/600 = 600,000,000 bytes/s]
* KB = 1000 bytes, KiB = 1024 bytes

[Read]
Sequential 1MiB (Q=  8, T= 1):  2937.873 MB/s [   2801.8 IOPS] <  2853.53 us>
    Random 4KiB (Q= 32, T=16):  1816.908 MB/s [ 443581.1 IOPS] <  1147.55 us>

[Write]
Sequential 1MiB (Q=  8, T= 1):  1947.804 MB/s [   1857.6 IOPS] <  4283.82 us>
    Random 4KiB (Q= 32, T=16):  1459.838 MB/s [ 356405.8 IOPS] <  1429.74 us>

Profile: Peak
   Test: 16 GiB (x1) [Interval: 5 sec] <DefaultAffinity=DISABLED>
   Date: 2020/05/06 10:07:50
     OS: Windows 10 Professional [10.0 Build 18363] (x64)

**Comment by halgari** [comment]
What's the make/model of the drive this is being run on?

**Comment by pgdeaner** [comment]
Samsung 960 Pro NVME.  PCI v3.

**Comment by pgdeaner** [comment]
2.0.4.3 Seems to be working much better on auto.  Running 14 threads.

Thank you!

**Comment by pgdeaner** [comment]
2.0.5.0 is no longer working.  :(

**Comment by pgdeaner** [comment]
2.0.4.3 and 2.0.4.4 would run 14 threads on my machine.  2.0.5.0 and 2.0.5.1 are back to only able to run 2 threads.  Help me obi wan halgari, you are our only hope.  :)

**Comment by halgari** [comment]
Should be fixed as part of the PR for #857
