### ISSUE TITLE
Corrupted modlist should be tagged as down in the browsing menu

### ISSUE THREAD

**Issue by LordOfRhun** [wabbajack-tools/wabbajack#779]
https://imgur.com/JZJgfxy
Currently when you download a modlist that is down, there is no indication appart from the list being corrupted once it's downloaded. this create a problem as people think the problem is from wabajack and not from the modlist.

a solution would be to implement a simple indicator that the modlist is down in the modlist browser and prevent people from downloading it.

**Comment by halgari** [comment]
Agreed, the final broken list is removed, we'll look into this if we ever decide to break the list format again.
