### ISSUE TITLE
Modlist Failed to Compile

### ISSUE THREAD

**Issue by bbanville** [wabbajack-tools/wabbajack#784]
**Describe the bug**
I am trying to use Wabbajack to make a modlist. I am setting it up identically to how it is described in the for modlist authors faq, but it keep failing to compile. I starting trying to make the modlist after, the F4EE modlist failed to compile as well. I was attempting to use a MO2 profile to create the modlist.

**Additional context**
Win 10, FO4

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4566370/Wabbajack.current.log)

**Comment by halgari** [comment]
You need to add MO2 to your download folder and set it up with a proper .meta file : examples can be seen here: https://github.com/wabbajack-tools/mod-lists/tree/master/custom_mo2_metadata

These lines in the log show that MO2's meta data hasn't been setup correctly
```
13056.78 - No match for 897 files
13056.78 -      boost_python37-vc142-mt-x64-1_71.dll - No Match in Stack
13056.78 -      helper.exe - No Match in Stack
13056.78 -      libcrypto-1_1-x64.dll - No Match in Stack
13056.78 -      libssl-1_1-x64.dll - No Match in Stack
13056.78 -      ModOrganizer.exe - No Match in Stack
13056.78 -      nxmhandler.exe - No Match in Stack
```
