### ISSUE TITLE
Modlists with manual urls from mediafire and moddb have issues in Wabbajack 2.0.3

### ISSUE THREAD

**Issue by LadyZeefa** [wabbajack-tools/wabbajack#787]
**Describe the bug**
While installing vnv with wabbajack 2.0.3 the link for all manual urls pop up with no issue,however, actually downloading the files causes problems. Users have reported wabbajack crashing once they hit the download button or the download will not start at all which causes wabbajack to hang. This only seems to happen with mediafire and moddb links. I have not experienced wabbajack crashing though I have encountered wabbajack hanging on the download page while refusing to download the file. 

**Additional context**
Windows 10, Fallout New Vegas Ultimate Edition

**Logs**
This is a log of a user who had a crash after clicking the download button.
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4569449/Wabbajack.current.log)
Users who experienced wabbajack hang did not have a usable log.
Link to the mods
manualURL=http://download2134.mediafire.com/qd4svkwtzlbg/ln1a2l2th1if8es/Spice+of+Life+Vanilla+v1-5+Release+Candidate.7z
manualURL=https://www.moddb.com/addons/start/171596?referer=https%3A%2F%2Fvivanewvegas.github.io%2Fhuduivui%2B.html

The updated file for vnv
https://wabbajackpush.b-cdn.net/VNV%201.1.5-d0610023-4f8f-4e11-98db-d9fccf390012.wabbajack

**Comment by halgari** [comment]
Reworked this a few weeks back, should be fixed in master
