### ISSUE TITLE
Installation error due to "unknown files"

### ISSUE THREAD

**Issue by LivelyDismay** [wabbajack-tools/wabbajack#800]
**Describe the bug**
Restarting the download/installation process with Wabbajack v2.0.3.0 after they failed for one reason or another seems to cause Wabbajack to fail resuming with the same installation paths. The downloads path specifically will say "Cannot install to this folder as it has unknown files that could be deleted." I imagine that's supposed to say "could not be deleted"?

**Additional context**
Still trying to gather information about it. The issue does still occur even if there is nothing in the installation folder except for the "downloads" folder, which is what we tell people to do. Older versions never had an issue with this and would delete files pretty indiscriminately.

**Logs**
Logs aren't helpful since they can't run the installer. Best I can do is a reference link from Discord:
https://discordapp.com/channels/605449136870916175/704708621732151547/707333745149214740
You can also just run a search for "unknown files" in the server, you'll see a lot of results. This is just the most recent one.

**Comment by tr4wzified** [comment]
It's more of a protective measure taken by Wabbajack, so people don't select System32 and start installing. It's been happening primarily because of Wabbajack crashing at 2.0.0.0 leaving behind other files (I think in the mods directory somewhere, partial installs).

**Comment by LivelyDismay** [comment]
But it happens even if the downloads folder is the only thing that exists in the installation folder. No mods directory at all.

**Comment by tr4wzified** [comment]
Likely some file floating around in there. Say you create an empty directory and a directory inside that called Downloads, if you put a txt file in there Wabbajack will refuse to install to it.

**Comment by LivelyDismay** [comment]
So could we possibly tell WJ to delete anything inside there that doesn't have a specific extension? .7z, .zip, .rar, for example?

**Comment by tr4wzified** [comment]
Possibly a little dangerous, but is very doable yes

**Comment by RARYates** [comment]
Is there a way to override this function? I'm more than willing to mangle my Skyrim directory and work with it, but the error message isn't verbose enough for me to troubleshoot away the issue. I'm a little worried this project will be dead on arrival if people can't click the install button.

**Comment by tr4wzified** [comment]
Not currently. What is your installation location? It should be an empty directory anyway.

**Comment by halgari** [comment]
this has been improved in recent builds
