### ISSUE TITLE
Cannot compile modlist for TTW

### ISSUE THREAD

**Issue by Patchier** [wabbajack-tools/wabbajack#801]
**Describe the bug**
Wabbajack doesn't recognize the TTW install as a game, as it's meant to do. 

**Additional context**
Win 10, TTW

[Wabbajack 2020-05-05 03_58_16.log](https://github.com/wabbajack-tools/wabbajack/files/4584163/Wabbajack.2020-05-05.03_58_16.log)

**Comment by halgari** [comment]
I'm going to close this issue as it's unlikely that we'll implement it any time soon, mostly because it requires two source games, and as it's the only game that would require this feature, the demand just isn't there (yet)

**Comment by erri120** [comment]
Reopen, MO2 sets `gameName=TTW` in its TTW plugin. Since we can now source files from different games we might be able to add TTW as a game in WJ and use the similar values as FNV so the modlist author does not have to swap TTW to FNV in MO2.

**Comment by erri120** [comment]
see https://discord.com/channels/605449136870916175/622649396428931088/817398868509196298

**Comment by TDarkShadow** [comment]
As for demand, users have been requesting a Wabbajack port of [The Best Of Times](https://thebestoftimes.github.io/), which is a TTW-focused variant of the [Viva New Vegas](https://vivanewvegas.github.io/) guide.
