### ISSUE TITLE
Cannot log in to nexus.

### ISSUE THREAD

**Issue by Adun87** [wabbajack-tools/wabbajack#802]
when i attempt to log in to the mod nexus in the program, it goes from the log in page to the main page after a very short amount of time, not leaving enough time for me to type in my user name and password.

I am running windows 10. I was attempting to get the viva new vegas modpack for fallout new vegas.

this did not leave an error message of any kind, as the program likely is unaware that it is working as anything other than intended.

**Comment by Adun87** [comment]
i got help from "uggcaveman" on the wabbajack discord. they gave me the following instructions, which fixed this issue for me. i am closing this issue.


Reset your Wabbajack installation
To completely reset your Wabbajack settings, start off by closing Wabbajack if it is open. Afterwards, press Windows + R on your keyboard and type in %localappdata%. You should see a Windows Explorer window pop up, find and delete the folder called Wabbajack inside.

**Comment by Peaches907** [comment]
This isn't fixing the problem for me. I wonder if updating to windows 11 would help.

**Comment by EzioTheDeadPoet** [comment]
@Peaches907 Please join the official discord for support with this issue.

But you either have a customized windows 10 installation that disables core Microsoft features. Or your WebView2 is broken or not installed.

Refer to Google on how to update/reinstall WebView2.

**Comment by FluidAstronaut** [comment]
I still have the same problem, can you help me?

**Comment by Peaches907** [comment]
I ended up having to update to windows 11 and made Microsoft edge my
default browser.
