### ISSUE TITLE
check downloaded file 

### ISSUE THREAD

**Issue by Langmans** [wabbajack-tools/wabbajack#810]
**Is your feature request related to a problem? Please describe.**
When downloading a mod from vectorplexus.com, I didnt accept their terms of use yet, and the mod high poly head was actually a saved html page renamed to a zip file. The http header was probably "text/html" instead of "application/zip"

After I loggedin through the browser and accepted their terms of use I was able to download after restaring wabbajack.

**Describe the solution you'd like**
Let wabbajack know the user that a file couldnt be downloaded because a user action is required, or at least let the user know that while downloading, a different type was expected.

**Additional context**
This applies to lotus: https://github.com/erri120/lotus/blob/master/README.md

**Comment by halgari** [comment]
Unfortunately we don't have a good way of testing this, if the issue occurs again, we'll take a look
