### ISSUE TITLE
Use relative paths for executables instead of absolute paths, where available

### ISSUE THREAD

**Issue by Umgak** [wabbajack-tools/wabbajack#813]
**Is your feature request related to a problem? Please describe.**
Wabbajack, in its current form, does not _truly_ make portable installations of modlists - sure, the list can be moved and the game will still run, because SKSE is still in the game folder, but all tools - Nemesis, FNIS, xEdit, DynDOLOD, etc. break!

**Describe the solution you'd like**
MO2 supports using relative paths in the same way that the command line or any other program does - appending the tool's relative path to the installation directory is a complete waste of time and only makes things _less_ functional. Instead, Wabbajack could instead scrub the working directory off of executable paths and replace them with a simple dot. This works for tools in the game folder (FNIS/Nemesis) as well as ones in other folders (xEdit, zEdit, DynDOLOD).

The one concern is zMerges - these DO work with a double containing directory (..\\..) in the json, but will automatically be resolved and overwritten at runtime, meaning that opening zMerge, then moving the MO2 installation folder will break things. However, one tool breaking is very preferable to all tools breaking in my opinion.

**Describe alternatives you've considered**
Honestly this is a bit of a niche annoyance so we could very easily just leave it as-is and tell users to reinstall lists via Wabbajack instead of just moving them around, but in my opinion that defeats the purpose of portable mode.

**Comment by jdsmith2816** [comment]
This problem has caused me issues as well when I move around lists from hard drive to hard drive due to needing space...

**Comment by erri120** [comment]
Note to future self: Problem is about the remapping of file paths in [IncludeStubbedConfigfiles](https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/CompilationSteps/IncludeStubbedConfigfiles.cs) https://github.com/wabbajack-tools/wabbajack/blob/803452c13a9a2abda08ae166ed6a4ae62f44572a/Wabbajack.Lib/CompilationSteps/IncludeStubbedConfigfiles.cs#L28-L50
