### ISSUE TITLE
Support for multithreaded downloads on the gallery

### ISSUE THREAD

**Issue by ixanza** [wabbajack-tools/wabbajack#818]
**Is your feature request related to a problem? Please describe.**
Downloading .wabbajack files that are gigabytes in size is really slow on 1 thread. Allow for multithreaded downloads similar to using a download manager.

**Describe the solution you'd like**
Multithreaded downloads similar to a download manager

**Describe alternatives you've considered**
Allowing users to download manually off the CDN, I understand its no longer possible due to the new structure of the build server

**Comment by tr4wzified** [comment]
Added in 2.0.5.0, can be closed now
