### ISSUE TITLE
RxUI Update Breaks Slideshow Text

### ISSUE THREAD

**Issue by Timboman** [wabbajack-tools/wabbajack#823]
What it says on the tin, WJ is not overlaying any text, Modlist Name, Description, Author Name, in the "Slideshow" pane, both before and while installing a list now.

On 2.0.4.3
![image](https://user-images.githubusercontent.com/36910038/81580032-e5dd4c00-937a-11ea-9f0a-c8e9ccd834d8.png)

On 2.0.3.0
![image](https://user-images.githubusercontent.com/36910038/81579930-c3e3c980-937a-11ea-94b7-ac2d6ab2ae91.png)

Same list file, just different WJ versions.

**Comment by Noggog** [comment]
Will take a look when I get home.  In the office this week...

**Comment by erri120** [comment]
With what WJ version was that file compiled?

**Comment by Timboman** [comment]
I used my 1.4.0 version compiled in 2.0.3.0 as an example there because I could get it opened by both versions for the comparison pics, but it holds true for my 1.5.0 build that I made in 2.0.4.3 too, also your latest Lotus version.

**Comment by Noggog** [comment]
Feels like it's a GUI-side issue, rather than a bad modlist file?  The modlist title is displayed in the top bar, but not the overlay.. which means the info exists, it's just not being displayed by the GUI

**Comment by Timboman** [comment]
Ya if you want a quick sanity check, here's my newest modlist file, made in 2.0.4.3 and it has the same issue. I know this one works too because I've already had some successful user installs.

![image](https://user-images.githubusercontent.com/36910038/81581292-87b16880-937c-11ea-873d-8c0ccf33b25a.png)

**Comment by Timboman** [comment]
Looks like 2.0.4.4 fixed it!
![image](https://user-images.githubusercontent.com/36910038/81617990-75ebb780-93b4-11ea-89a5-624dd23f5a2f.png)

**Comment by Noggog** [comment]
Reopened, because we'll want to figure out what about the RxUI upgrade broke the bindings.

Looked into it for a short and distracted moment last night.. and didn't really make sense.  Felt like the a XAML binding (not even a RxUI binding) just stopped doing its job?  Will need to dig in a bit more tonight.

**Comment by Noggog** [comment]
Fixed in #830
