### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BrendanoElTaco** [wabbajack-tools/wabbajack#826]
**Describe the bug**
Program froze after tabbing out accidentally during modlist installation. Could not reopen the program. Tried to end task in task manager, didn't work. Taskkill command wouldn't even close it. Had to restart PC to close. I believe the installer was hashing archives when it got tabbed out.

**Additional context**
Windows 10 Pro. Fallout New Vegas
**Logs**
Didn't create a log

**Comment by tr4wzified** [comment]
Do you have any Windows Event Viewer logs of it? Kinda hard to debug with this amount of information.

**Comment by BrendanoElTaco** [comment]
> Do you have any Windows Event Viewer logs of it? Kinda hard to debug with this amount of information.

No sorry, I recently reinstalled the os so the logs got deleted. But it doesn’t seem to be a problem anymore with the latest version
