### ISSUE TITLE
Wabbajack still attempts automated download when user is non-premium.

### ISSUE THREAD

**Issue by Unnoen** [wabbajack-tools/wabbajack#844]
When using a non-premium Nexus account, Wabbajack will ask you if you want to continue in manual installation mode, however it will still attempt to get the download link from the API before finally opening the embedded browser.

![image](https://user-images.githubusercontent.com/6127568/81916312-03c6dd00-9617-11ea-934a-efc6a4cfef85.png)

It should just default to opening the embedded browser for the user if they confirm manual mode.

**Comment by halgari** [comment]
This is fixed in master we only retry 5xx errors
