### ISSUE TITLE
Mod author name made more prominent 

### ISSUE THREAD

**Issue by JustThatKing** [wabbajack-tools/wabbajack#848]
**Is your feature request related to a problem? Please describe.**

Not so much a problem as a nice thing to have so mod authors are more prominently featured for those manually downloading.

**Describe the solution you'd like**

To make it so the UI for manual downloading shows the mod authors name after "Please download X mod".

**Describe alternatives you've considered**

An additional UI element could be used instead, although my suggestion may be clearer on the UI.

**Additional context**

The autoscroll makes it rather awkward to actually look at who made the mod at a glance. Noticed whilst manually installing a list and trying to check more information on mods I'm interested in.

**Comment by Noggog** [comment]
If it's a quick thing, can you give me a screenshot of the way it exists now?  For some reason I'm having trouble framing the mental context.  Is this the manual download user intervention that shows up at the bottom right of a WJ install in the GUI?

**Comment by JustThatKing** [comment]
Sorry for the delay, I don't check Github much. 
An example of what's currently seen after it automatically scrolls down.
https://drive.google.com/file/d/1vq5kT3KOe2Nd5ziIf_dA0jur4K4CwOc3/view?usp=sharing
My original suggestion was to add the mod authors name to the "Please download" section, however after using manual downloading a bit more, I'm not sure whether this will be viable due to how long some of the archive names can be. My main thought is that manual downloading features mod authors names far less prominently than automatically downloading with Premium.

**Comment by Noggog** [comment]
Gotcha, so related to the browser display during manual downloads.  
Yeah it would likely need to be a more custom view, as putting it all one the one Title line would be unwieldy, as you were saying

Uploading pic again to embed into the issue

**Comment by Noggog** [comment]
![manualinstallmodauthorfeature](https://user-images.githubusercontent.com/24981326/82231001-22b4c000-98f2-11ea-83ff-5f4ed6bc8d1e.PNG)
