### ISSUE TITLE
Wabbajack.exe (update executable) not launching the main program

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#854]
**Describe the bug**
After some time, the normal Wabbajack executable that autoexecutes the update function fails to launch. Launching Wabbajack.exe from inside the version folder works fine.

**Additional context**
Windows 10 Enterprise N LTSC OS Build 17763.316 

**Logs**

Event Viewer
![Event Viewer](https://user-images.githubusercontent.com/55751269/82495505-79d1b500-9aeb-11ea-812f-95455bc9342b.png)

**Comment by joshrooney8** [comment]
**Describe the bug**
Identical issue, but is not resolved by launching from inside the version folder. Resolved by reinstalling and clearing the appdata folder, doing either individually yields no result.

**Additional context**
Both Windows 10 Pro OS Build 18363.900 and Build 10.0.19041.

**Logs**

Event Viewer:
![error](https://user-images.githubusercontent.com/17113597/87245679-3c303f00-c43f-11ea-9233-f9d3e151a370.png)

**Comment by tr4wzified** [comment]
Same issue as https://github.com/wabbajack-tools/wabbajack/issues/965 and https://github.com/wabbajack-tools/wabbajack/issues/642
