### ISSUE TITLE
Wabbajack in-app icon - wrong link

### ISSUE THREAD

**Issue by LivelyDismay** [wabbajack-tools/wabbajack#922]
**Describe the bug**
Bad links in WJ app gallery.

**Additional context**
Open Wabbajack. Browse Modlists. Click a globe icon to open the gallery page on the website. It is blank.
First one I clicked was VNV so I will use that as an example.

App link:
https://www.wabbajack.org/modlist/gallery/vnv

Real link:
https://www.wabbajack.org/modlists/gallery/vnv

Just missing the "s" at the end of "modlists" in the url there.

**Comment by erri120** [comment]
Duplicated of #914
