### ISSUE TITLE
Benchmark download location and install location separately

### ISSUE THREAD

**Issue by ixanza** [wabbajack-tools/wabbajack#948]
**Is your feature request related to a problem? Please describe.**
Currently wabbajack only benchmarks the installation location and sets number of thread count based on it however when storing downloads in another drive or a slower drive it creates a problem as slower drive cannot perform well thread count setup for the installation folder. I’ve tested this in hashing my mod downloads folder of around 6k files and with a thread count of 6 on the slow drive it takes about 5+ hours to hash while it only took 20 minutes to hash on a thread count of 1

**Describe the solution you'd like**
Set different thread counts for downloading/hashing vs actual installation

**Describe alternatives you've considered**
Manually setting the thread account to 1 during hashing/downloading and then setting it back to max on extraction

**Comment by halgari** [comment]
fixed in #1085
