### ISSUE TITLE
2.1.3.0 - Stuck on splash screen

### ISSUE THREAD

**Issue by O0mix0O** [wabbajack-tools/wabbajack#965]
When launching `wabbajack.exe` from the 2.1.3.0 folder (both the one downloaded using the downloader, and the zip posted on the github release) the splash screen remains with the cursor going to the "loading circle" whilst hovering.
Main window never displays.
Have tried running it with all other background programs (steam / afterburner etc.) closed - same result. 

![Wabbajack](https://user-images.githubusercontent.com/9626010/87727066-2791d500-c7b8-11ea-8131-af84f892d703.png)

**Additional context**
Windows 10 Pro - Version 1909 - Build 18363.959

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4934417/Wabbajack.current.log)

------------------------------

[This fixed it](https://github.com/wabbajack-tools/wabbajack/issues/854#issuecomment-657212068)
Unsure if this still needs to be open?

**Comment by Donixs** [comment]
I also have the same issue, and the fix that others have shared does not work for me. Using older versions don't work for me either.

**Comment by erri120** [comment]
Should have been fixed with 2661454fb90b87e6da16b8ec2dbd67c86b0544c8 apparently not the case

**Comment by halgari** [comment]
this is really old and we haven't seen it happen recently, can re-open if needed
