### ISSUE TITLE
Automatically Update Modlists.json inside WJ

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#975]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a quality of life thing.

**Describe the solution you'd like**
I'd like to see a panel in the settings page in WJ for modlist authors where they can copy/paste the download link for their .wabbajack file (once uploaded to the CDN) and also point WJ to the .meta file for the related .wabbajack file. Then, with a button click, Wabbajack could communicate with modlists.json to open a pull request with the necessary changes for the related modlist. May require the modlist author to manually enter their list's machine URL to make sure it updates the correct list entry in modlists.json.

**Describe alternatives you've considered**
Updating modlists.json manually.

**Additional context**
N/A

**Comment by ForgottenGlory** [comment]
To expand on this, you could also have a field during compilation that only appears if the person compiling has an author key that allows them to enter the machine name for the list and then WJ handles opening a pull request for modlists.json automatically based on that.

**Comment by halgari** [comment]
I've wanted this for a long time, I'll start looking into it again.
