### ISSUE TITLE
...has stopped working

### ISSUE THREAD

**Issue by Yippee38** [wabbajack-tools/wabbajack#98]
**Describe the bug**
When I start Wabbajack, and select the modpack to install, it pauses a second, then I get a Windows error saying, "Wabbajack has stopped working"

In the log window, there is the following text:
Wabbajack Build - 78b21550a81850e87c848ad13141b2185a61003e
Uncaught error:
Object reference not set to an instance of an object.
d:\a\1\s\Wabbajack.Common\Utils.cs.ExceptionToString:430.36
CacheImage 0.0
QueueRandomSlide 0.0
PreloadSlideShow 0.0
ConfigureForInstall 0.0
< ctor>b__4.0.0
RunInternal 0.0
Run 0.0
Run 0.0
ThreadStart 0.0

**Additional context**
Windows 7, SP1, 64-bit
I'm trying to install Lexy's Legacy of the Dragonborn into SSE

**Logs**
My Wabbajack.exe.log file only contains the following:
1.58 - Caching slide for The Companions - Don't be a Milk Drinker at https://staticdelivery.nexusmods.com/mods/1704/images/19490 19490-1535055392-370726483.jpeg

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by erri120** [comment]
Url is missing a `/`. But that wouldnt crash wj

**Comment by erri120** [comment]
Log would contain a log Entry with the exception if cacheimage fails. What modlist did you use?

**Comment by Yippee38** [comment]
Yeah.  Sorry.  I copied and pasted that log file.  Not sure what happened to the "/".

**Comment by Noggog** [comment]
May or may not have time to look at it later today, but can you post a link to your modlist?  Easiest way to get a fix sometimes is to just trigger it on our end. 8)

**Comment by Yippee38** [comment]
https://drive.google.com/file/d/1lt3KmwwDBusZ9f9z7crV1qV6fr2nm9Lu/view?usp=sharing

**Comment by Yippee38** [comment]
Any update on this?

**Comment by Noggog** [comment]
Heya @Yippee38 !

Internals have shifted a lot, and some new WJ versions have been released.  I would suggest trying the newer versions (might have to wait for your desired modlist to be updated?) and seeing if the same error pops up.

If so, we'll reopen the issue

**Comment by Yippee38** [comment]
I finally got a chance to test the latest version of Wabbajack.  I got the same crash and a similar, minimal log file.

**Comment by Yippee38** [comment]
Hey.  I just had a thought.  I used to have a game that kept crashing on me and nobody could tell me why.  It turned out that when launching the game it connected to website for some reason (can't remember why) and it was using Internet Explorer in the background to do so.  My security rules for IE (which I don't use) were causing the problem.  Once I added the site as some kind of exception (don't remember the details), it stopped crashing.

Is there any chance this could be a similar situation?  Is Wabberjack downloading via a browser in the background?  Maybe I need to allow an exception for the security rules.

**Comment by Yippee38** [comment]
You said you'd reopen the issue if I was seeing the same problem with the new version.  I am.

Please re-open this issue.

**Comment by Noggog** [comment]
Heya!  Sorry, missed the first two messages somehow.  Not actually too familiar with github notifications yet; flew under the radar.

So are you're running?
Wabbajack Build - 42d8347c76c2332994d2680e3bea1310b17fd576

Because the code related to the original logs you posted in the initial issue I think are completely gone.  Perhaps you're having a different problem, but it's not possible it's related to `QueueRandomSlide` and all that.

Could you perhaps post a fresh log file?

**Comment by Yippee38** [comment]
I just tested the latest version and it works!

Thank you!  You can leave this closed.
