### ISSUE TITLE
Captcha not loading nexus log in

### ISSUE THREAD

**Issue by TontonGak0** [wabbajack-tools/wabbajack#982]
I can't pass the nexus log in screen, because the catpcha never load the challenge, it will turn infinitly

**Comment by vulcandth** [comment]
I am having this same problem!

**Comment by LostDragonist** [comment]
It looks like the Nexus changed from using reCaptcha to hCaptcha and Wabbajack will need to be updated (somehow).  Premium Nexus users can follow these steps to get around the issue:

> Hold Shift and Right click inside the latest version folder of where Wabbajack.exe is in (currently the 2.1.3.3 folder). 
> Click Open PowerShell Window here. 
> In the window that appears, enter .\Wabbajack.exe --apikey="yourapikeyhere" , obviously replacing yourapikeyhere with your api key. 

> Remember not to (accidentally) share your api key in a screenshot or something if you get errors :slight_smile:

**Comment by vulcandth** [comment]
@LostDragonist That didn't seem to do anything. It would just launch the program, showing nexus logged out and it won't download anything without sending you to the login screen with the captcha.

**Comment by vulcandth** [comment]
@LostDragonist Nevermind... I missed the part to look INSIDE the 2.1.3.3 folder. I was in the wrong directory.

**Comment by LostDragonist** [comment]
Looks like Halgari has gotten 2.1.3.4 out which fixes this issue.

**Comment by halgari** [comment]
This is now fixed in master
